### ISSUE TITLE
Connection lost message displayed on web interface

### ISSUE THREAD

**Issue by poldiderjungdrache** [owntone/owntone-server#1070]
Hi,
I have some issue with the web interface always showing connection lost message at the bottom of the screen when browsing my music library. The WebUI still seems to be working fine the message is just a little annoying and I don‘t understand how to get rid of it.
I‘ve attached a screen shot of the error. This was taken in Safari on iPad but I tried Desktop as well and the error always pops up after a few seconds.
<img width="1194" alt="PNG image" src="https://user-images.githubusercontent.com/59320185/89108837-1f829800-d43c-11ea-8a56-e18504a8a549.png">

I am using the latest version 27.1. I just even did a fresh pull and recompiled it but this did not help.
I don’t really see anything in the log file that appears to be related here but I am happy to provide it or any additional information if needed. 
Regards,

Simon

**Comment by chme** [comment]
@poldiderjungdrache on what distribution and what machine are you running forked-daapd? This issue was reported for an older version of Alpine Linux, see #861, but was "fixed" by upgrading to a new Alpine version.

The websocket connection is necessary to get play status, volume, speaker selection updates. (Browsing the library works fine without it.)

**Comment by poldiderjungdrache** [comment]
Hi,
Sure I should have mentioned this earlier I am running it inside a FreeBSD jail. The FreeBSD version corresponds to 11.3 p13.
Regards, Simon

**Comment by asmod3us** [comment]
I had to disable IPv6 to get daapd to listen on IPv4 port 3688. If IPv6 is enabled it was only listening on tcp6/3688 and the UI could not connect.

**Comment by poldiderjungdrache** [comment]
Hi.
Indeed I can confirm. Deactivating IPv6 in the config and restarting resolved the issue for me. Now the UI works without connection issues.
Regards,
Simon

**Comment by ejurgensen** [comment]
Should be fixed now (with commit 1a56255)
