### ISSUE TITLE
Request - Get currently playing queue item details

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1206]
I see that there's been a change to the JSON API that makes it easier to update the currently playing queue item (PUT), but is there an easy way to GET the metadata for the currently playing queue item? My solution is 2 part process where I get the item_id from the /api/player endpoint, then cross-reference that ID against the entire queue (/api/queue) to get the track,album,artist info.

I'm using this in an iOS shortcut where I can ask "What's playing" and get the deets in the form of an alert or notification.

**Comment by ejurgensen** [comment]
Don't think there is a 1-request way of doing that, but should be simple to add, so I will do that.

**Comment by cdlenfert** [comment]
@ejurgensen I've tested this new branch. Works great! Thank you for implementing this.

**Comment by ejurgensen** [comment]
Good to hear, I have merged it now
