### ISSUE TITLE
Add additional field names for smart playlists

### ISSUE THREAD

**Issue by Trudge** [owntone/owntone-server#1213]
Hi,

please think about adding the Comment string field as a supported field for smart playlists.

Thx,

T.

**Comment by jkwim** [comment]
Something that I also wish for. I have many smart playlists in iTunes that I wanted to import. I have been using comment field to tag songs over the years and I cannot think of any other field to use for moving that info.

**Comment by Porco-Rosso** [comment]
I've been using this to export itunes PL into .m3u files
https://github.com/Porco-Rosso/iTunes-m3u8-Playlist-Syncer
it might help you out. Just need to go file>export Library and then point the script at the .xml file, while obviously tweaking the params in the script.

**Comment by jkwim** [comment]
> I've been using this to export itunes PL into .m3u files
> https://github.com/Porco-Rosso/iTunes-m3u8-Playlist-Syncer
> it might help you out. Just need to go file>export Library and then point the script at the .xml file, while obviously tweaking the params in the script.

Thanks. I am about to try this out.

One question:

Can it extract the Smart Playlist Criterea/Rules?

They appear as some form of character encoded string in the XML file

`			<key>Smart Info</key>
			<data>
			AQEAAwAAAAIAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAA==
			</data>
			<key>Smart Criteria</key>
			<data>
			U0xzdAABAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAEAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAAAAAAAB8YAAAAAAAAAAAAAAAAAAAAB
			AAAAAAAAB88AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAQAAAgAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgBFAG4AZwBs
			AGkAcwBoAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAYBTTHN0AAEAAQAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAABAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAAAAAAAAQAAAAAAAAAA
			AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
			ADwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABE
			AAAAAAAAACAAAAAAAAAAAAAAAAAAAAABAAAAAAAAACAAAAAAAAAAAAAAAAAAAAABAAAAAAAA
			AAAAAAAAAAAAAAAAAAA=
			</data>`

**Comment by Porco-Rosso** [comment]
I honestly have no idea, I believe owntone uses its own schema for smart playlists anyway, so they wouldn't be compatible. You can see this useful site to see if any scripts might help you out: https://dougscripts.com/itunes/scripts/scripts06.php

**Comment by chme** [comment]
I opened a PR #1283 that adds the "comment" field to the smartpl expression language
