### ISSUE TITLE
forked-daapd changing name to OwnTone Server

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1215]
As a fyi to anyone interested, forked-daapd will change name to OwnTone Server, and as part of that I have moved the repo to an organisation with that name. Myself and @chme will be the maintainers.

The reason for the name change is mostly that forked-daapd is esoteric and difficult to pronounce. Also, these days it is a lot more than a daap server.

**Comment by Porco-Rosso** [comment]
I fully support changing the name of the project. I was lucky to discover the project, but seeing all the old forks of daapd server was confusing. A name change will likely mean much better discoverability for new users.
Curious, how did you go about selecting the new name? I wonder if there will be some confusion around the resemblance to owncloud and that popular namespace.

**Comment by Porco-Rosso** [comment]
That's a fair set of requirements. I don't have any suggestions myself, and the name does have a certain alliteration to it which is pleasing.
By the namespace I mostly was thinking of [Owncloud](https://owncloud.com) the popular self-hosted dropbox/google drive alternative.
Hometone could be an alternative, but I see a furniture store and some workout product with that name.

**Comment by ejurgensen** [comment]
Thanks for the offer, much appreciated - @chme is head of the frontend department, but is away right now. When he is back he can perhaps get back to you on it.

@Porco-Rosso Hometone is also a good name, but besides the furniture/workout it is taken here on github. That criteria killed quite a number of my ideas too.

**Comment by GerdBlomb** [comment]
Are there any differences at the moment between OwnTone and forked-daapd for the moment (beside name changing)? Will there be a docker image for OwnTone?

I just installed forked-daapd docker image and made it running and i'am unsure if this is the way to go....

Thank you!

**Comment by ejurgensen** [comment]
Right now, forked-daapd 27.4 and OwnTone master branch are close to identical. With regard to the Docker image I think you have to ask over at https://github.com/linuxserver/docker-daapd.

**Comment by thatso** [comment]
FYI: I've made the linuxserver team #[aware](https://github.com/linuxserver/docker-daapd/issues/48) of the name change.

**Comment by chme** [comment]
> I'd gladly work up a new logo if this isn't already in process.

@cdlenfert I am not working on a logo and if you have an idea for a new one, that would be great!

**Comment by cdlenfert** [comment]
@chme I've worked up a new design I'm liking
![image](https://user-images.githubusercontent.com/17277745/115902523-bf93ad80-a41f-11eb-9800-1d1523d5d41d.png)

**Comment by ejurgensen** [comment]
Wow looks really good - I like the "retro" thing it has going

**Comment by chme** [comment]
@cdlenfert I have to agree with @ejurgensen looks great! Will include it in the next web interface update. Thanks a lot!

Do you have the logo also as an svg file? That will probably be better to rescale it to different sizes.

**Comment by chme** [comment]
> @cdlenfert I have to agree with @ejurgensen looks great! Will include it in the next web interface update. Thanks a lot!
> 
> Do you have the logo also as an svg file? That will probably be better to rescale it to different sizes.

Sorry for the noise, just noticed that you already provided the different formats in #1229
