### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by davek00997744** [owntone/owntone-server#1222]
Can forked-daapd/owntone take manually created playlists?

I can see some good info for smart playlists but nothing for standard playlists ??

I don't want to use Itunes front end and want to create my own library etc

**Comment by cdlenfert** [comment]
Yes, you can manually create playlists by building a queue of songs and saving it as a playlist (you first have to enable this option in the config file and establish a location for the playlist file to be saved). You can also build playlists more manually as a list of file paths and save it as a .m3u or .pls file.

**Comment by davek00997744** [comment]
Great, thanks

Is the manual file just the file paths and the file name is the playlist name used ?

**Comment by Porco-Rosso** [comment]
Yes, I just use a text file with .m3u ending and the contents are the song file paths.

**Comment by davek00997744** [comment]
Excellent, many thanks
