### ISSUE TITLE
Log fills with mdns / avahi messages media lib greyed out on Apple Remote (iOS)

### ISSUE THREAD

**Issue by GerdBlomb** [owntone/owntone-server#1223]
Server Version 27.4

The logfile files fills up with the following messags in a 20 sec. schedule:

[2021-04-08 08:52:01] [DEBUG]      web: notify callback reason: 11
[2021-04-08 08:52:01] [  LOG]     mdns: Avahi state change: Client collision
[2021-04-08 08:52:01] [  LOG]     mdns: Avahi state change: Client registering
[2021-04-08 08:52:22] [  LOG]     mdns: Avahi state change: Client collision
[2021-04-08 08:52:22] [  LOG]     mdns: Avahi state change: Client registering

I've also paired my iPad with Apple Remote App to forked-daapd succesfull with the handshake code, but the lib ist grayed out on the iPad in the list of media libaries. I suppose a relation between this two issues.

The messages appears also in the same sequenz if iPad ist not paired. 

avahi service on the host has been disabled (was active, same picture). No difference.

forked-dappd is installed as docker container with host network.

Everything else works fine. I can playback from the webinterface to all my Airplay speakers. All speakers are in place.

Doc G*ggle does not help.

Any hints or tips?

**Comment by ejurgensen** [comment]
This also seems docker-related, so maybe you should add it there too. We can keep it open here for a while as well, perhaps someone has an idea.

**Comment by GerdBlomb** [comment]
Thanks for your information. 

I'am quite unsure if this is a Docker issue. Mainly because the network is host connected. But maybe you're right. Don't know.

But what do the log entries mean anyway? What is the service trying to do? What is the possible reason for a collision?

What do you mean by "add it there to"? I would like to do this, but do not understand where (sorry).

**Comment by ejurgensen** [comment]
> But what do the log entries mean anyway?

They come from the Avahi daemon, I don't know what triggers them. I don't recall seeing them before.

> What is the service trying to do?

It does two things: Asks Avahi to announce its own services (e.g. daap, mpd and dacp), and asks Avahi to notify ("browse") about target services (e.g. Airplay and Chromecast). Since you are seeing it greyed out in Remote, I suppose the former isn't working.

> What do you mean by "add it there too"?

To https://github.com/linuxserver/docker-daapd as I also recommended [here](https://github.com/owntone/owntone-server/issues/1215#issuecomment-815502446).

**Comment by GerdBlomb** [comment]
Thank you for your clarification! I will add it als to the other repo.

**Comment by GerdBlomb** [comment]
I've found out whats wrong here. It may be (is) docker related, but i think a final fix has to be integrated in owntone / daapd. Siehe my post in the other repro.

owntown should give up after a few tries when creating own unique hostnames. But it doesn't.

Anyway. Closed for now, because there is a solution which is also ok.

Keep up this fantatsic work on owntone! Thanks for your assitance.
