### ISSUE TITLE
Question on OwnTone name change

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1227]
I see in the name change branch, it looks like all references to `forked-daapd` are being swapped with `owntone-server`. I was somewhat hoping that a simplified `owntone` text would be the replacement. Going from 12 characters to 14 only to include `-server` seems unnecessary to me. Using the shorter version could make the API commands shorter, make the local URL easier to remember and type, and possibly have other benefits I'm not thinking of.  Of course I'm unaware of the downsides, so I hope I'm not causing any offense in asking the question.

**Comment by ejurgensen** [comment]
Could you add this comment to the PR and close this issue? I am also in doubt whether owntone or owntone-server is best, but let's discuss the pros and cons on the PR.

**Comment by chme** [comment]
For the git project name, I would keep the name `owntone-server`, it makes it clear that this is the project for the server application. If additional projects under the `owntone` origanization are added, it makes it easier to identify what is what. Regarding the name of the binary, probably `owntone` would be enough. Or maybe `owntoned` (d = daemon)? But keeping it the same as the project name is also good (and I am not sure if saving some characters really have a benefit).

**Comment by ejurgensen** [comment]
Yes, I think I will change the PR so that the binary (and config, cname etc.) is just owntone instead of owntone-server

**Comment by cdlenfert** [comment]
@ejurgensen Just getting back from a trip. I'll try adding a comment on the PR. My Git experience is limited, so hopefully I do it correctly.
