### ISSUE TITLE
Question: can I get the last added album (or albums) via a smart playlist?

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1231]
HI, I would like to retrieve only the last album added to the library via either an api call or a smart playlist. I can seem to work out how to do this though I can see the UI has similar capability. Does this functionality exist and if so can you tell how to call it please?

Many thanks

**Comment by chme** [comment]
@aleszczynskig You can use the `search` API endpoint with a smart playlist expression: 

```
GET /api/search?type=album&expression=media_kind%20is%20music%20having%20track_count%20%3E%203%20order%20by%20time_added%20desc&limit=100 
```

(this is the request made by the web ui, change limit to 1 if you only want the last added album. The "having track_count" part is to filter out singles, you can remove it, if this is not what you want)

The API endpoint returns a list of album objects. To retrieve the tracks of this album you will need to make an additional call to the `library/albums/{albumid}/tracks` endpoint (https://github.com/owntone/owntone-server/blob/master/README_JSON_API.md#list-album-tracks).

I cannot think of a way to get this done with a smart playlist.

**Comment by aleszczynskig** [comment]
@chme - many thanks, this will work perfectly for my use-case. I'll give it ago.
