### ISSUE TITLE
Name containing '#' results in a 'Permission Denied' warning in logs

### ISSUE THREAD

**Issue by ddppddpp** [owntone/owntone-server#1232]
A '#'-sign in the name of a file produces an error 'Permission denied' at info log level. This doesn't reflect on the ability to actually play the file, so I'd say it is mostly harmless. Example:
```
[2021-05-05 19:59:34] [ WARN]     scan: Cannot open media file '/mnt/musicshare/Bob Dylan/Modern Times/06 Workingman's Blues #2.m4a': Permission denied
```
- steps to reproduce: just place a file with a '#' sign in the library and trigger a rescan
- version of forked-daapd: 27.4 (and earlier)
- platform: Raspbian buster

**Comment by ejurgensen** [comment]
I tried to reproduce following the steps you outlined, but the issue did not show up. I also can't think of a reason why # would create a problem.

**Comment by ddppddpp** [comment]
Hmm apparently not an owntone issue. My library is sitting on a NAS and I'm mounting it via curlftpfs. Standard CLI file operations like cp give the same error. Closing.
