### ISSUE TITLE
A setup around Airplay, Spotify, local music files and a mobile front-end.

### ISSUE THREAD

**Issue by nadigo** [owntone/owntone-server#1235]
I’m trying to build a setup around Airplay, Spotify, local music files and a mobile front-end.
The elements would be:
 1 - Media server that can combine local files with Spotify (and possibly other streams / services)
 2 - forked-dappd / owntone-server to stream to AirPlay speakers 
3 - A Mobile front end to control media and playing (an MPD client or apple’s remote iTunes app)

One options is to use mopidy + Mopidy-Spotify as an spority + local integrated music server AND slimmed down version of owntone-server - without the iTunes library or mpd server. In this setup we need to stream from mopidy to forked-dappd but I’m not sure the MPD clients or the remote iTunes app could mange changing streams / speakers.

Another option is to build around the full forked-dappd installation as the music server and integrated Spotify somehow (any ideas how to??) and use the remote iTunes app as a client using this script (untested)

Thoughts ??? Happy to work on something like this with you if you like.
Nadav

**Comment by ejurgensen** [comment]
Well the things you mention are exactly what I use owntone (forked-daapd) for :-) Is there anything you're thinking it wouldn't be capable of, and where you would need mopidy?

With regards to installing and configuring, please see the README and maybe the INSTALL file too.

**Comment by nadigo** [comment]
How would you integrate Spotify? 
What would be the best mobile client to manage the media and speakers?

**Comment by ejurgensen** [comment]
Did you [read the README](http://owntone.github.io/owntone-server/)?

I use the Remote app, since I have an iPhone. For Android I think Retune is good.
