### ISSUE TITLE
Add screenshot and logo to README

### ISSUE THREAD

**Issue by Porco-Rosso** [owntone/owntone-server#1244]
Hi again, in the spirit of the new name and logo change, perhaps it is a good idea for us to add the logo and a few screenshots to the README? I see they are already in the WebUI docs.

I think this would bring a lot more visibility to the project, at the expense of maybe attracting more non-technical users who might require more frequent support.

I would think a screenshot or two of the webui, and some screens on how the server appears in some clients (like itunes or MPD clients) would be good.

If this is of interest I can take a swing at it and submit a pull request.

**Comment by Porco-Rosso** [comment]
Also just a note on remote access that can be mentioned in the docs: I am using zerotier and owntown appears on my devices with no extra effort. Much simpler then forwarding a port over SSH. I'm sure wireguard would work as well.

**Comment by ejurgensen** [comment]
Yes, agree with both suggestions. I think @chme is working on improvement of the documentation, incl. screenshots, so not sure if you should make a PR or not. A PR with the zerotier info would great, however.

**Comment by Porco-Rosso** [comment]
I've added a short guide in the wiki: https://github.com/owntone/owntone-server/wiki/Accessing-Owntone-remotely-through-iTunes-Music-with-Zerotier
Feel free to add a link in the main readme https://github.com/owntone/owntone-server#remote-access :)

**Comment by ejurgensen** [comment]
Great guide, I have added a link in the README as you suggested

**Comment by chme** [comment]
I have now merged the updated web site for OwnTone: https://owntone.github.io/owntone-server/
If you find some information missing (there definitively is room for improvement), help on this front is always appreciated :-)

**Comment by ejurgensen** [comment]
The new web site is awesome!

What are the areas you would like improved? Maybe I can look into some of them.
