### ISSUE TITLE
Music controls on home pod unavailable 

### ISSUE THREAD

**Issue by joepool** [owntone/owntone-server#1245]
When playing something to a HomePod (mini), it acts like nothing is playing, music comes out of it, but the display on the top remains dark, volume controls don't work, nor does the play pause button. I have attached a screenshot from the music app when i try to control the homepod, the controls are grayed out, i also cant see what i playing.

In my logs, the following is shown. Could this be related to the issue?
```
Ignoring type AirPlay 2 for device 'Joes Room', will use type AirPlay 1
```
Is there an issue in my config file? Or is this a bug?
I am using owntone version 27.4
Thanks for any help
<img src="https://user-images.githubusercontent.com/65784403/118270027-4edc3000-b4b7-11eb-988c-beb25fb21826.png" height="400" />

**Comment by ejurgensen** [comment]
I'm not sure what is causing this, but you can try setting "raop_disable = true" for the device and see if it is better. That setting will make owntone use Airplay 2 instead of Airplay 1.

**Comment by joepool** [comment]
Thanks for the reply, i did already try this, however, when starting owntone i got this error:
```
[2021-05-14 17:07:48] [  LOG]   config: [root:822] no such option 'raop_disable'
[2021-05-14 17:07:48] [FATAL]   config: Parse error in config file /etc/owntone.conf
[2021-05-14 17:07:48] [FATAL]     main: Config file errors; please fix your config
```
I assumed that this had been deprecated or something but now i guess not...

**Comment by ejurgensen** [comment]
You need to set it like this:

airplay "Joes Room" {
  raop_disable = true
}

**Comment by joepool** [comment]
Ah that makes more sense. 
However unfortunately this hasn't helped and I still have the same issue...

**Comment by ejurgensen** [comment]
Ok. I would be nice to have this working better with owntone, but I don't have the opportunity to do much about it right now, so I will have to close the issue.
