### ISSUE TITLE
Install Issue MacPorts instructions

### ISSUE THREAD

**Issue by 400HPMustang** [owntone/owntone-server#1247]
Downloaded mxml and installed per the mxml instructions 

```
.configure
make
make install
```
result of make install was

```
Mac-mini:mxml-3.2 admin$ make install
Installing libmxml.dylib to /usr/local/lib...
Installing libmxml.a to /usr/local/lib...
Installing documentation in /usr/local/share/doc/mxml...
Installing header files in /usr/local/include...
Installing pkgconfig files in /usr/local/lib/pkgconfig...
Installing man pages in /usr/local/share/man...
```

I get through the rest of the instructions just fine until running sudo make install and get the output below. 

```
checking for mxml... no
configure: error: Package requirements (mxml) were not met:

No package 'mxml' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MINIXML_CFLAGS
and MINIXML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** [config.status] Error 1

```
What should I do to fix this? I don't understand what the message means. Thank you.

**Comment by ejurgensen** [comment]
The error indicates that pkg-config can't find mxml, but I can't give you better advice on why that might be than what the error message says. However, instead of building and installing mxml yourself, you could consider using [the same recipe that the github actions uses, where it is installed via brew](https://github.com/owntone/owntone-server/actions/runs/844338033/workflow).

**Comment by 400HPMustang** [comment]
Thanks for the direction. I tried both ways and got the same result? Is it possible I’m installing it in the wrong location somehow?

Is just launching terminal and running 

`brew install libmxml `

incorrect? Is there something else that has to be done? I think this is my only hangup.
