### ISSUE TITLE
No stream in internetplaylist? 

### ISSUE THREAD

**Issue by HJKLMN** [owntone/owntone-server#1251]
Tried https://playerservices.streamtheworld.com/pls/KINKAAC2.pls 

It plays ok in VLC...
Error
http: Couldn't find stream in internet playlist: https://playerservices.streamtheworld.com/pls/KINKAAC2.pls
Is this the stream? Or am i doing something wrong?

**Comment by ejurgensen** [comment]
You are not doing anything wrong, I see you have stumbled upon some older code which only allowed http, not https (in the streams, not your url above). I have fixed that now.

There should be a fairly easy work-around that you can use with your current version: Just download the pls file (it is actually just a small text file with the actual stream links inside), and then place it in your library. It think it should then work.
