### ISSUE TITLE
Problem playing previously working radio stream

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1254]
Hi, 

I get the following error message when trying to play a radio stream listed in an .m3u playlist.

May 20 12:02:32 music-pi owntone[1441]: [2021-05-20 12:02:32] [  LOG]    xcode: Cannot open 'https://fred.torontocast.com:2515/stream': Protocol not found
May 20 12:02:32 music-pi owntone[1441]: [2021-05-20 12:02:32] [  LOG]   player: Input start was called with an item id that has disappeared (id=16925)
May 20 12:02:32 music-pi owntone[1441]: [2021-05-20 12:02:32] [  LOG]       db: Error fetching queue item by pos relative to item id
May 20 12:02:32 music-pi owntone[1441]: [2021-05-20 12:02:32] [  LOG]   player: Error fetching next item from queue (item-id=16925, repeat=2)
May 20 12:02:32 music-pi owntone[1441]: [2021-05-20 12:02:32] [  LOG]      web: Failed to start playback from position '0'

This was previously working fine and then stopped working. The stream plays correctly in a browser and vlc. Any ideas what is wrong here?

The .m3u file simply lists the url, nothing else. Maybe I need to add something else?

Thanks

**Comment by ejurgensen** [comment]
Just having the url in the m3u is fine. I tried the url both on my Buster RPi and my other machine, and it worked ok. Since when did the problem start appearing?

Btw the error actually comes from ffmpeg, and it seems to be about missing support for https. Maybe you can try 'ffprobe the_url' and see what that says.

**Comment by aleszczynskig** [comment]
I'm not sure actually. It's been a few weeks. I thought the station had gone offline but then realised it was an issue. 

I think the issue is with ffmpeg. This is the output I got from ffprobe.

ffprobe: error while loading shared libraries: libfdk-aac.so.1: cannot open shared object file: No such file or directory

**Comment by ejurgensen** [comment]
Alright... perhaps they changed encoding and that triggered the error?

**Comment by aleszczynskig** [comment]
I've resolved the ffprobe/ffmpeg issue now and get the correct output but I still see can't playback this stream in owntone. I've restarted the service. 

I did compile owntone from master branch last week (but the issue was present before that). Prior to that is was also compiled from source own the master branch. What is the dependency on ffmpeg? Do I need to recompile?

**Comment by aleszczynskig** [comment]
@ejurgensen - thank you for the help.

Yes, this is a raspberry pi so I'll try with your deb to see if that solves the problem to help gather evidence. I need to compile from source as I merge the airplay2_pbevents1 branch as I need the ability to pause on my HomePods. I am also recompiling now with a working version of ffmpeg. The version in my path seems to be broken, I'm not sure why. Maybe this will help. Consider the issue closed as it clearly seems to be something specific to my install which I will investigate.

**Comment by aleszczynskig** [comment]
That's great. I look forward to the formal release when it is ready. 👍
