### ISSUE TITLE
Noob question on upgrade from Forked-Daapd > OwnTone

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1260]
I don't often build and install apps in Linux. And I've never had app I'm using go through a name change. I'm running FD on a Debian Stretch and another Buster machine. I want to make the leap from FD to OwnTone but I'm not sure what exactly I need to do to make that happen. Some questions:

- Is there some process of manually removing FD before I run the OwnTone install? 
- Will the manual Debian install give my a systemctl service for OwnTone, or should I repurpose the one I have from the FD install? 
- If I can simply stop FD, install OwnTone and be done, is there still some way I can clean up and remove FD?

Thanks for any clarifications!

**Comment by ejurgensen** [comment]
Yes, a name change is a bit of a hassle, unfortunately. So I wouldn't consider the question noob! Having up- and downgraded between fd and owntone quite a few times by now, here's my suggestion. Note I assume you are not using /usr/local (though it might actually be a good idea). Altso note I haven't actually executed precisely these steps as in a script.

```
sudo systemctl stop forked-daapd
cd [your github clone of owntone]
autoreconf -fi && ./configure [your configure options]
sudo make install
sudo cp /etc/forked-daapd.conf /etc/owntone.conf
sudo cp -a /var/cache/forked-daapd /var/cache/owntone
sudo install -m 644 owntone.service /lib/systemd/system
sudo systemctl start owntone
```

Now check that everything is working. If it is all good, here's some cleanup (still in your cloned repo dir):

```
make clean
git checkout 27.4 (going back to forked-daapd here)
autoreconf -fi && ./configure [your configure options]
sudo make uninstall
(and then manually remove the service file you manually installed)
```

I have assumed here that you are building yourself. If you are actually using my RPi apt repo, then it should work like this:

```
(edit /etc/apt/sources.list -> change forked-daapd to owntone)
sudo apt update && apt upgrade
sudo systemctl restart owntone
(check that it is working)
sudo apt purge forked-daapd
```
