### ISSUE TITLE
Various Artists are empty on Roku Soundbridge

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1263]
Please try to provide the following:

- steps to reproduce and/or logging of the error
Add an album with Album Artist set to Various Artists. Verify that the web interface shows the album. On the Soundbridge, Browse, Browse Artists, Various Artists. 0 songs are showed.
- version of forked-daapd
27.4
- platform
Debian 10

**Comment by ejurgensen** [comment]
Can you provide the log? Preferably both of when you add the album (so I can see how it is saved) and when the Soundbridge makes the request.

**Comment by frankusb** [comment]
[forked-daapd.log](https://github.com/owntone/owntone-server/files/6602580/forked-daapd.log)
Sure, is this what you need?

**Comment by ejurgensen** [comment]
Yes, that does show what is causing this. Forked-daapd saves the track with album_artist = "Various Artists", and with artist = the actual artist. When the Roku makes the query, it uses an artist = "Various Artists" filter, so the result is empty. Here is the relevant log:

```
[2021-06-05 08:03:55] [DEBUG]      rsp: RSP request: '/rsp/db/0/album?query=artist%3D%22Various%20Artists%22&type=browse'
[2021-06-05 08:03:55] [DEBUG]      rsp: RSP browse query filter: artist="Various Artists"
...
[2021-06-05 08:03:55] [DEBUG]       db: Starting query 'SELECT f.album, f.album_sort FROM files f WHERE f.disabled = 0 AND (f.artist = 'Various Artists') AND f.data_kind = 0 AND f.album != '' GROUP BY f.album_sort, f.album ORDER BY f.album_sort, f.album ;'
```
I think the way to fix this is to interpret "artist" from the Roku as "album_artist". I will make a branch that does this, and then please test - not sure if such a fix would break something else.

**Comment by frankusb** [comment]
Well, somehow Various Artist shows up in the browse menu. Why does Owntone
show that? It seems like Various Artist should be a special case.

**Comment by frankusb** [comment]
Actually thinking about this more, wouldn't the best coverage be to
interpret the query from the Roku as both album artist and artist?

Frank

**Comment by frankusb** [comment]
I guess another alternative would be to add 'Various Artist' as another artist in the id3 tag.

**Comment by ejurgensen** [comment]
I've made a simple fix for this issue, it just interprets "artist" as "album_artist". I hope you can test it and check for any adverse effects.

**Comment by frankusb** [comment]
I've applied the changes to my source tree and Various Artists is now populated seemingly identical to the web interface. I have not noticed any missing media.

**Comment by ejurgensen** [comment]
Ok, I've merged the fix. If you notice any undesirable effects, let me know.
