### ISSUE TITLE
Forked-daapd stops for about 10s after volume change

### ISSUE THREAD

**Issue by Ulrichgau** [owntone/owntone-server#1270]
about every tenth time after adjusting the volume forked-daapd stops playing music for about 10s. 
version 27.4
Raspbian buster on a raspi 3
mpd client is m.a.l.p. on different devices.
It was the case at about 13:49, see attached log file

[forked-daapd_debug.log](https://github.com/owntone/owntone-server/files/6638118/forked-daapd_debug.log)

**Comment by ejurgensen** [comment]
Yes, can see that the volume command to ALSA seems to be hanging:
```
[2021-06-11 13:49:02] [DEBUG]   laudio: Setting ALSA volume to 27
[2021-06-11 13:49:13] [DEBUG]   player: Callback request received, id is 0
```

However, I have no idea why the device is suddenly so slow to process the volume commands? I also don't know what you can do about it, but if you are building yourself you might be able to troubleshoot by looking at volume_normalized_set() in src/outputs/alsa.c. It looks like it is one of the commands in that function that is blocking for 10 seconds.
