### ISSUE TITLE
[spotify] Also scan for podcasts

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1274]
@chme I hope you will finalize your change https://github.com/chme/forked-daapd/commit/6f1010abab8d2305f220b352c25f29130f3c1ed3 that enables Spotify podcast scanning

**Comment by chme** [comment]
The problem with spotify podcasts were that playback failed for these uris: https://github.com/owntone/owntone-server/pull/1230#issuecomment-841764315

Did you manage to get them working? (I did not (yet) look into what caused the error and how it can be fixed)

**Comment by ejurgensen** [comment]
Yes, they should be working now - perhaps you missed my mention of this [here](https://github.com/owntone/owntone-server/pull/1253#issue-648099222)? The fix was to make a different request to the Spotify endpoint when the uri was spotify:episode:xxx instead of spotify:track:xxx.
