### ISSUE TITLE
Two small suggestions

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1275]
* please add libprotobuf-c-dev to the dependencies in the install.md; seems to be mandatory (at least on elementary os, which i dumped, and antix as debian variant)

* in PULSE.MD, user is still "daapd" where it is supposed to be "owntone"
Sorry for not filing a pull request - i have no idea how...

**Comment by ejurgensen** [comment]
Good suggestions, have made them now. Elementary OS looks interesting, looking forward to trying it.
