### ISSUE TITLE
Running the web interface with ssl

### ISSUE THREAD

**Issue by nirnachmani** [owntone/owntone-server#1278]
I installed owntone server on an ubuntu virtual machine and it is working fine. I am now trying to make it work with ssl. The purpose is to enable me to access the web interface via a home assistant lovelace web card and because my HA uses ssl, I can only access websites with ssl from the web card (a limitation of AH). 

I re-built owntone with --with-ssl=openssl and re-installed. Now I can access the web interface on http but when I try to access it via https I get an error that the "Secure Connection Failed" with Error code: SSL_ERROR_RX_RECORD_TOO_LONG. I have been unable to find any solutions and wonder if someone can help me.  Thanks in advance.

**Comment by ejurgensen** [comment]
Sorry, I don't think there is any way you can make owntone listen on https. I don't recall the --with-ssl option, but it is probably just for choosing whether openssl or gcrypt should be used for various crypto operations.

**Comment by chme** [comment]
@nirnachmani I am not running this myself, but I think others managed to use a reverse proxy (e. g. nginx) to only expose the web interface through ssl.

**Comment by nirnachmani** [comment]
Thanks Christian. I managed to do something similar with the Caddy plugin
for Home Assistant which allows me to run HA without ssl internally but
externally adds an ssl layer.
