### ISSUE TITLE
Volume control by metadataPipe (librespot-java)

### ISSUE THREAD

**Issue by snoopbird** [owntone/owntone-server#1281]
Hello everybody,
first of all, thank you very much for the great project!

I am trying to find a way in cooperation with librespot-java (spocon) so that I can get Spotify Connect on the Apple HomePod.

The combination also works almost wonderfully. Unfortunately, the volume control with metadataPipe does not work.

@aleszczynskig gave me the tip (https://github.com/librespot-org/librespot-java/issues/376) that I set the logging to DEBUG. Here I could see the following entry.

> [2021-07-01 21:51:47] [DEBUG] raop: send_progress: Sending SET_PARAMETER to 'Küche'
> [2021-07-01 21:51:56] [DEBUG] player: Read Shairport metadata (type=73736e63, code=70766f6c, len=21)
> [2021-07-01 21:51:56] [DEBUG] player: Not applying Shairport airplay volume while software volume control is enabled (-12,90,0.00,0.00,0.00)
> [2021-07-01 21:51:59] [DEBUG] player: event_read_metadata()
> [2021-07-01 21:51:59] [DEBUG] player: Incomplete read, wanted 1764, got 116 (samples=29/time=657596), deficit 2184
> [2021-07-01 21:52:01] [DEBUG] player: event_play_metadata()

Can someone help me here please?

**Comment by ejurgensen** [comment]
I'm not super into this, but the PR that added volume control via metadata pipe to OwnTone seems to be pr #403, where there also is some explanation of why these volume commands are ignored. I think the basic idea is that if the sender (originally shairport sync) is changing the volume by remixing the pcm then OwnTone should not also change the volume. Going by the code, it looks like a volume string that ends with ",0.00,0.00,0.00" tells OwnTone that the sender is doing its own volume control, and apparantly spocon is also sending that as part of the volume string.

**Comment by snoopbird** [comment]
I reinstalled rasbian yesterday and now it works ?! Does not matter! The main thing is that it works! :-)
