### ISSUE TITLE
hand-migrated playlists deleted

### ISSUE THREAD

**Issue by jimmiedave** [owntone/owntone-server#1287]
Installed OwnTone on a new server. As I have for years, I migrated my collection of (large and detailed) playlists to the new server's songs3.db by reading in exported sql from a file.

I should mention that I first examined the minor schema differences between old and new versions and adjusted the old data for the new schema, and removed 'playlists' table creation statement (so just an INSERT into the existing table).

The result is that the import works without complaint, and I load up the server with Music (nee iTunes) for a client, and the playlists show up in Music. Testing (not exhaustive) shows they work as expected.

But after a reboot of my server, the playlists no longer show up in Music when the library is loaded, and inspection of songs3.db shows that my imported playlists have all been deleted.

Any idea why, and what I can do to fix this? The old songs3.db couldn't be migrated in at install, apparently because the schema was too old.

Deletion appears to be happening here (during startup), and for what reason, I cannot fathom:

```
[2021-07-17 15:35:54] [DEBUG]       db: Running purge query 'DELETE FROM playlists WHERE type <> 0 AND db_timestamp < 1626536060;'
[2021-07-17 15:35:54] [DEBUG]       db: Running query 'DELETE FROM playlists WHERE type <> 0 AND db_timestamp < 1626536060;'
[2021-07-17 15:35:54] [DEBUG]       db: Purged 18 rows
```

Technical details: grabbed the code from this github about 2 days ago, compiled and running on debian buster (actual debian, not raspbian (repo for which doesn't support arm64)) on a raspberry pi 4 4GB. Used pretty vanilla config settings - included --with-libwebsockets, nothing else.

Any ideas appreciated. Rebuilding the playlists one at a time is gonna be way time-consuming.

PS - I've found a temporary workaround by re-datestamping the playlists to a time when I may be 100 years old. But I'd still like to know why I have to do so in order to preserve my data.

**Comment by ejurgensen** [comment]
When the server starts it scans your library for playlists, and any that are not found are deleted, which is what you are seeing in the log. This is implemented by updating timestamps of anything that is found, and then purging the cruft. So your timestamp hack should be ok. 

If you don’t want this there is also a setting called ‘filescan_disable’ which might help you.
