### ISSUE TITLE
Noob Question: service file (Ubuntu)

### ISSUE THREAD

**Issue by Tobentu** [owntone/owntone-server#1292]
This is my first time working with Linux, so sorry for this - I guess dumb - Question. I have built everything like in the documentation but now I dont get what to do at the "Long version - after installation" page. 
I have to create a service file, right? But how does this work? I read, that I can use an existing service file in the "owntone server" directory.

Thank you in advance!

**Comment by ejurgensen** [comment]
After you have run "make install" there should be a .service file in the directory. Installing this service file is only required for making the server start when you boot, so first I would recommend just checking that the server is working. [Here is some information](https://unix.stackexchange.com/questions/224992/where-do-i-put-my-systemd-unit-file) about where to install service files (unit files).
