### ISSUE TITLE
ATV not in sync with other airplay1 devices

### ISSUE THREAD

**Issue by mfauvain** [owntone/owntone-server#1297]
Hi, I've been using owntone (by the way when writing this bug report the template still says forked-daapd) for years with airplay1 on many devices (including some with shairport-sync) and it works perfect, all spkeakers are always in sync (I've tried up to 9 at the same time). Now, I've just included an appleTV to the mix and it works, however there is a slight delay (1s or less I would say), even when using just 2 devices (ATV + another airplay1 device).
Is this something you've experienced?
ATV and all devices are wired ethernet.

owntone version 28.1

**Comment by mfauvain** [comment]
Ah, found the 'sync airplay' in the ATV settings. did that, and sync is now perfect.
Thx again, owntone is absolutely brilliant.

**Comment by ejurgensen** [comment]
Thanks for notifying about the solution, and good to hear that is working well.

What a weird setting for Apple to introduce. I can't think of any reason why someone wouldn't want sync.
