### ISSUE TITLE
Possible incorrect error check in smart_query.c

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1299]
@chme can you check if this should actually be `if (psr == NULL)`:

https://github.com/owntone/owntone-server/blob/e3213066ceb5e9d97c75d5e77f00454aa886d93d/src/smartpl_query.c#L77

Looking at the context it looks that way.

**Comment by chme** [comment]
Yes, it was definitively  a copy paste error. Fixed now with #1305
