### ISSUE TITLE
Could Owntone Be Fighting the API?

### ISSUE THREAD

**Issue by echellst** [owntone/owntone-server#1303]
Hello!

I hope this day finds you well. I have a small issue in which I am hoping the result is just me missing something (which I often do! :) ). 

I wish to have Owntone start to play something, but at a very low volume. Its part of a wake-up automation. However, after my API call, (in which I can see on the web ui that the volume does indeed respond to my call and go to my selected volume level) Owntone seems to be fighting this level and snaps back up to the level in which it was last playing. 

In your documentation you mention that this is a feature of Owntone. Is there anyway to disable this feature? I really need absolute control of the server with no interference from it.

I have checked the config file and nothing is apparent, but like I said I am hoping that I am just missing something!

Thanks!

**Comment by ejurgensen** [comment]
> In your documentation you mention that this is a feature of Owntone

Not sure what you are refering to?

Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the issue occurs. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by echellst** [comment]
[owntone_special.log](https://github.com/owntone/owntone-server/files/7103065/owntone_special.log)
Hi, in the documentation, located here: https://github.com/owntone/owntone-server, there is reference in the "Using iOS Remote" for iTunes area that says.. **" If no output is selected when playback starts, OwnTone will try to autoselect a device. OwnTone remembers your selection and the individual volume for each output device; selected devices will be automatically re-selected, except if they return online during playback."** And although I am not using the remote, Owntone is responding in a similar manner. 

I also discovered that this issue may be associated with the one I recently reported to you (but of course, promptly disappeared...) where after selecting a Spotify playlist, setting the volume, then sending a "play" call via the api, Owntone promptly clears the que, unselects my outputs and will not run again until I restart it. Attached are the logs where the crash occurs. I am pretty darn sure it is because of something that I am doing wrong, but I just can't find it.

The attached log is trimmed to just the error point!  Thank you so much.

**Comment by ejurgensen** [comment]
> "If no output is selected when playback starts, OwnTone will try to autoselect a device"

I should update this part of the docs, nowadays this behaviour is only if you have enable autoselect in the config (by default it is disabled).

> The attached log is trimmed to just the error point!

Doesn't seem like it? It is a whopping 5.3 mb, and it includes all the start-up scan etc. I could only find one volume request, and it seems to be made while the server is still starting (scanning Spotify), which makes it difficult to read. Can try again, and please let the server start completely before trying to trigger the error, because otherwise it gets difficult to read the log.

**Comment by echellst** [comment]
Hi,

I have been trying to get it to fail again, and of course it seems to know that I am looking for it to do so….so its not. I will keep trying and follow your instructions re: the log information.

I do have one bit of information. The error seems to take a few days to so up after a service restart. I know that scheduling a total reboot in crontab is possible, but is it also possible to reschedule a restart of owntone as well? That may just solve my issue.

Thanks!

Eric

**Comment by Porco-Rosso** [comment]
It's still a bandaid, but I don't see why you couldn't just restart the service with crontab if the user permissions are correct.
something like `systemctl restart owntone` depending on your OS.
