### ISSUE TITLE
[request] API parameter for data_kind in Search

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1304]
I'd like to be able to use the Search API specifically for local files or Spotify. This would be functionally similar to the way the toggle works on the search page in the web interface. It would be nice to search specifically on Spotify when things aren't in my local or my Spotify library yet. Or if I have the same album in both, I could search for the specific one I want to play.

![image](https://user-images.githubusercontent.com/17277745/131860781-105e5af8-fad9-495d-aa4a-8542498ff3e4.png)

https://github.com/owntone/owntone-server/blob/master/README_JSON_API.md#search

**Comment by ejurgensen** [comment]
I think you can do this with `expression=data_kind+is+spotify` and `expression=data_kind+is+file`?

**Comment by chme** [comment]
What @ejurgensen suggests will work if you only want to search for Spotify songs that are already in your owntone library. The Spotify search in the web UI does not send search requests to owntone but instead directly uses the Spotify web api (owntone plays no role in it). 

Extending the owntone-server search to also search directly in Spotify (and return tracks/artists/albums that are not in the library) is difficult to integrate well. E. g. the ids to identify an item are different and cannot be easily converted from one to the other. I currently see this out of scope for owntone.

My recommendation is to use the owntone search api to search in your library and use the Spotify web api directly to search in the whole Spotify catalogue. To play results from the Spotify search with owntone, you can then use the owntone api again.

Spotify web api doc: https://developer.spotify.com/documentation/web-api/
JS wrapper library: https://github.com/JMPerez/spotify-web-api-js
