### ISSUE TITLE
[ feature request / query ] add review flag to tracks / files table

### ISSUE THREAD

**Issue by whatdoineed2do** [owntone/owntone-server#1306]
I buy a lot of digital albums for which I don't know the majority of the tracks - I simply throw all of these into the server and play.

However I spend a bit of time manually making notes of the track names and then deleting. 

I would like the owntown to let me "mark" tracks for later deletion with a flag with the flow being:
* listen to track via web front end
* if I dislike the track, mark it (via `/api/library/tracks/1234?review_flag=1` endpoint)
* later, mass extract all track paths (via `search` endpoint) that have been marked and delete

To support this, its relatively simple:
* add integer column, `review_flag`, to `files` and `queue` table
* extend `jasonapi` calls to incl `review_flag` in `track_to_json()` and `queue_item_to_json()`
* update tracks by extending `jsonapi_reply_library_tracks_put_byid()` to take extra param type and corresponding `db` update query.

I thought about doing this with the `rating` item but having a dedicated `review flag` (with an int would carry other meanings to different ppl: 1=delete, 2=reencode, etc..)

Would this be a functionality/PR you'd accept?

**Comment by ejurgensen** [comment]
Sounds fine. I don't think OwnTone should become a music library manager, but this is something that makes sense to do during playback.

Wouldn't you want some sort of UI for it?

With regard to name I would prefer just "flag", and also making it an enum so that the meanings are clear and consistent.

**Comment by whatdoineed2do** [comment]
https://github.com/owntone/owntone-server/wiki/Marking-and-managing-music-tracks-for-review
