### ISSUE TITLE
No more way to disable spotify?

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1308]
Just to clarify this for myself: it is no longer possible to disable spotify in configure? Because --disable-spotify just switches to the new library?
I to not use spotify at all - I's prefer to disable it completely...

**Comment by ejurgensen** [comment]
`--disable-spotify` still disables Spotify completely. It's just that the new library gets compiled (which I suppose is why you ask), but it isn't used or linked to. I didn't get around to making conditional compilation, but I hope to do that later.
