### ISSUE TITLE
Spotify connect feature for forked-daapd not working

### ISSUE THREAD

**Issue by Depechie** [owntone/owntone-server#1313]
Please try to provide the following:

- version of owntone : 28.2
- platform : Raspbian on Raspberry pi 3B+

With version 28.2 we get Spotify capabilities straight out of the box ( no dependency for libspotify ), which is working flawlessly by the way!
My Spotify playlists and music is visible in the OwnTone server and I'm capable to select if to play.

But you also get a Spotify connect device in called forked-daapd in the Spotify app.
Selecting that as play target has no effect! No music is being playout through my selected outputs in the OwnTone server.
Also selecting it is often results in auto unselecting by Spotify, seems the network negotiations are not that reliable?

**Comment by ejurgensen** [comment]
Thanks for the notice, but I can't reproduce this. I don't see anything in the Spotify app.

Owntone doesn't register as a Spotify connect target, and I'm also confident that the name forked-daapd isn't used towards Spotify any more. So I'm thinking you might have librespot running in the background? - maybe you used it previously to pipe audio to forked-daapd?

**Comment by Depechie** [comment]
Maybe some more background... so I have a clean raspbian running docker and I installed https://fleet.linuxserver.io/image?name=linuxserver/daapd for the OwnTone capabilities.
Up until yesterday that incorporated OwnTone version 28.1, I got the message "OwnTone was either built without support for Spotify or libspotify is not installed". Also there was no extra Spotify connect device in the Spotify app at that point.

I did not manually install any libs on the raspbian, but waited for the updated container image of linuxserver. That came available yesterday and we get version 28.2 now of OwnTone.
With that the settings page allowed me to process the Spotify linking flow and with that I got everything of Spotify available. But I also got that extra Spotify Connect device forked-daapd in my Spotify app.

So, you would think their script for build the container contains something specific then? Weird though that I only got the device after following the Spotify flow in OwnTone server website.

**Comment by ejurgensen** [comment]
Ok, I hope you don’t mind bringing the issue to the linuxserver repo? I sounds like the docker-daapd image is needlessly installing librespot (and configuring it with the old name).

Perhaps you can also suggest that they rename docker-daapd.

**Comment by Depechie** [comment]
Yes understood, thx for the details by the way!
