### ISSUE TITLE
Setup webplayer correctly

### ISSUE THREAD

**Issue by martadinata666** [owntone/owntone-server#1314]
I need more info to setup webplayer.

As the [WEB README](https://github.com/owntone/owntone-server/blob/master/README_PLAYER_WEBINTERFACE.md) stated that
`If the server is running at a different location you need to modify the proxyTable configuration in config/index.js`

Where is this `config/index.js` file exactly? do i need create one? or it renamed become other file?

Thanks.

**Comment by whatdoineed2do** [comment]
i think that changed when there was a upgrade to the way vuejs code was built.

in dev, the web i/f comes up on 8080.  Take a look at `web-src/vue.config.js` and the `proxy` object.

**Comment by martadinata666** [comment]
Thank for the clue, there is hidden `env` file but seems the websocket not connecting or hardcoded to localhost.
`.env.development `
```
VUE_APP_JSON_API_SERVER='http://localhost:3689'
VUE_APP_WEBSOCKET_SERVER='ws://localhost:3688'
```
