### ISSUE TITLE
Brew error

### ISSUE THREAD

**Issue by exrector** [owntone/owntone-server#1318]
MacExrector:~ Exrector$ brew install yamllint /Users/exrector/Documents/GitHub/owntone-server/.github/workflows/macos.yml
Updating Homebrew...
Error: macos.yml: /Users/exrector/Documents/GitHub/owntone-server/.github/workflows/macos.yml:1: syntax error, unexpected ':', expecting end-of-input
name: MacOS
    ^
MacExrector:~ Exrector$ 

**_finita la commedia_**

**Comment by ejurgensen** [comment]
Looks like you are giving the yaml file as an argument to brew? You can't do that - if you want to build owntone you have to read the yaml file to see what steps are required.

**Comment by exrector** [comment]
@ejurgensen This is my first time using this method.  Very interesting.  Could you give instructions or a link to learn this method.  Thank you.

**Comment by ejurgensen** [comment]
Well you just have to open the yaml file and then execute the listed commands. That will at least build owntone on your mac.
