### ISSUE TITLE
Is it possible to auto-play tracks when the queue is empty?

### ISSUE THREAD

**Issue by 11ib** [owntone/owntone-server#1319]
I've really been enjoying using Owntone, and am currently just using it to stream Spotify to an AirPlay speaker. However, when I first start Owntone and the queue is empty, if I try to play audio, nothing happens (as expected).

I'd like to have the queue automatically play the tracks from my Spotify library (or from some other playlist) if it's empty, is this possible?

Thanks!

**Comment by ejurgensen** [comment]
Not sure I understand exactly what you mean by "automatic" (triggered by what?), but I think you can make a smart playlist consisting of your library in randomized order. See [README_SMARTPL.md](https://github.com/owntone/owntone-server/blob/master/README_SMARTPL.md). You can also persist the playlist with [the clear_queue_on_stop_disable setting](https://github.com/owntone/owntone-server/blob/master/owntone.conf.in#L401), but I don't remember if it also works across server restarts.

**Comment by 11ib** [comment]
I think to put it more concisely, it would be great to define behavior when Play is pressed and the queue is empty.

For example, if the queue is empty, start playing playlist X (or smart playlist Y). Having to login to the web interface an manually add to the queue works, but automating this process would be a great addition.

**Comment by ejurgensen** [comment]
Ok, I suppose that isn’t supported, but for now you could make your own shortcut for it using the json api.

**Comment by 11ib** [comment]
Hey @ejurgensen sorry to bring this back up, I've looked in README_SMARTPL.md and it references the library folder for the location of the .smartpl file- is this the same location where songs3.db is?
