### ISSUE TITLE
Tag search in web interface - e.g. Composer for classical music

### ISSUE THREAD

**Issue by manderpe** [owntone/owntone-server#1331]
Owntone's web interface has some search options (Artists, Albums, Genres) and the free-form Search (which seems to search by song title).  I have figured out how to search using smart playlist searches and this is excellent but another primary option for Composer would be really helpful for others with extensive classical collections (musician friends who forget syntax).  Meanwhile Owntone is amazing!

**Comment by ejurgensen** [comment]
Closing, is now supported
