### ISSUE TITLE
sent daapd udp packets exceed path mtu

### ISSUE THREAD

**Issue by sozialarbeiter** [owntone/owntone-server#1332]
Hello,

When packets are sent via this socket to an airplay receiver:
#ss -ip | grep owntone -A4 | grep 10.0.0.76 -A4
...
tcp   ESTAB      0      0                                                                               10.0.0.70:54794                           10.0.0.76:commplex-main users:(("owntone",pid=58983,fd=113))
	 cubic rto:566.666 rtt:129.377/109.165 ato:40 mss:910 **pmtu:950** rcvmss:536 advmss:910 cwnd:2 ssthresh:7 bytes_sent:11872 bytes_retrans:290 bytes_acked:11583 bytes_received:3301 segs_out:78 segs_in:67 data_segs_out:39 data_segs_in:38 send 113kbps lastsnd:13774 lastrcv:13547 lastack:13547 pacing_rate 225kbps delivery_rate 1.23Mbps delivered:39 app_limited busy:3442ms retrans:0/1 rcv_space:9100 rcv_ssthresh:64626 minrtt:5.897    

they get fragmented like:
#tcpdump -eni mgmt host 10.0.0.76 -c2
01:07:02.131211 d0:63:b4:00:f3:b2 > e8:68:e7:10:1f:b4, ethertype IPv4 (0x0800), length 962: 10.0.0.70.47423 > 10.0.0.76.58375: UDP, length 1423
01:07:02.131268 d0:63:b4:00:f3:b2 > e8:68:e7:10:1f:b4, ethertype IPv4 (0x0800), length 537: 10.0.0.70 > 10.0.0.76: ip-proto-17

Length is always 1423, shouldn't the application reduce the packet size as it gets EMSGSIZE? Or do I have a misunderstanding?

The consequence of the fragmentation is a cracking sound in my AVR, as it can't properly handle it.

Thanks!

**Comment by ejurgensen** [comment]
The packets are sent here (for Airplay 2): https://github.com/owntone/owntone-server/blob/383146eb35efa20d57cc9c343f676b4d4a427865/src/outputs/airplay.c#L1915
