### ISSUE TITLE
How to build static library?

### ISSUE THREAD

**Issue by sclsj** [owntone/owntone-server#1337]
I wanted to use Github Actions to build binaries (I ran into loads of problems on my machine, and I guess I need a clean environment), but after downloading the results I found that they are linked to other libraries dynamically, which doesn't exist on my machine. How can I build this program statically so that I can use it on other systems? 

I've tried using `LDFLAGS='-static'` and `LDFLAGS='--static'`, but both don't work. I tried passing ` --pkg-config-flags=--static` flag to `./configure`, but it does not recognize this option. (This option builds `ffmpeg` statically)

Is the only way to manually find the commands to build all relevant libraries instead of `homebrew` and pass the `--disable-shared` option to `./configure`? If so, is there an automated way to do this?

Also, I've been specifying the `CFLAGS="-mmacosx-version-min=10.13"` flag in the hope that the resulting binary will be able to run on my old macOS version. The process is `abrt`ed due to missing libraries, so I can't check if it works on my machine. Can anyone confirm this?

**Comment by ejurgensen** [comment]
I don't personally know enough about this to help you, and it probably isn't very likely that anyone else here can. Maybe Google can bring you further - the way OwnTone is built (with automake etc) isn't that special, so maybe someone else out there has made a guide for another binary.
