### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by ashdwells** [owntone/owntone-server#1340]
Hi 

I have come to this stage on the work flow....

chmod +x ./scripts/antlr35_install.sh

and i get this error

chmod: ./scripts/antlr35_install.sh: No such file or directory

All steps previously seemed fine. 

Please advise

**Comment by ashdwells** [comment]
Why closed?! I still have this issue

**Comment by ejurgensen** [comment]
Making chmod work isn't really an owntone issue
