### ISSUE TITLE
iOS speaker selection unavailable when excluding all speakers but one in owntone.conf

### ISSUE THREAD

**Issue by mfauvain** [owntone/owntone-server#1342]
Hi,  I have many owntone servers and I limit some servers to some speakers only, setting (for ex) `airplay "some_speaker" { exclude = true }` for all speakers but one in owntone.conf.
However, when doing so, the iOS app shows no speaker selection at all. Not a big issue, but if for some reason the speaker gets unselected, it is then impossible to reselect it  from the iOS app.
The (lone) speaker is available in the web's speaker selection though.
A quick workaround is to leave at least 2 speakers in the list, in that case they always show up, even when unselected.

**Comment by ejurgensen** [comment]
Have you tried using the `speaker_autoselect` setting? In this case it might be useful.

**Comment by mfauvain** [comment]
Good idea. will try now. thx
