### ISSUE TITLE
Permanently running on 100% CPU (Centos 8 Stream)

### ISSUE THREAD

**Issue by th0u** [owntone/owntone-server#1345]
Please try to provide the following:

- steps to reproduce and/or logging of the error

start owntone and verify cpu load via top/htop

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1833462 daapd     20   0  726160  37444  18932 S  99.7   0.5   4:36.19 /usr/sbin/owntone -f
```

- version of owntone
28.2
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-mpd --without-pulseaudio --disable-spotify 

- platform
Centos 8 Stream 

Enabling debug log does not produce any additional log entries after owntone started and initialised and then sits at 100% load.
htop shows 2 line alternating on top
owntone -f 
owntone | websocket | -f

when configuring with these additional options 
`--without-libwebsockets --disable-webinterface`

then the load is normal.

I don't know if it helps... I ran
`perf record /usr/sbin/owntone -f`
and perf report generated this
`+   56.69%     2.12%  websocket  libc-2.28.so                    [.] __poll                                                                                                   
+   37.84%     2.04%  websocket  [kernel.kallsyms]               [k] entry_SYSCALL_64_after_hwframe                                                                           
+   35.88%    18.32%  websocket  [kernel.kallsyms]               [k] do_syscall_64                                                                                            
+   13.55%     0.91%  websocket  [kernel.kallsyms]               [k] __x64_sys_poll                                                                                           
+   12.37%     4.87%  websocket  [kernel.kallsyms]               [k] do_sys_poll                                                                                              
+    8.14%     8.06%  websocket  [kernel.kallsyms]               [k] syscall_return_via_sysret                                                                                
+    8.04%     7.16%  websocket  [kernel.kallsyms]               [k] entry_SYSCALL_64                                                                                         
+    4.05%     3.87%  websocket  libwebsockets.so.13             [.] _lws_plat_service_tsi                                                                                    
+    3.30%     0.91%  websocket  libwebsockets.so.13             [.] __lws_hrtimer_service                                                                                    
+    2.30%     0.85%  websocket  [kernel.kallsyms]               [k] sock_poll                                                                                                
+    2.18%     2.05%  websocket  [vdso]                          [.] __vdso_gettimeofday            `

if a can submit more info, please let me know.

TIA.

**Comment by Porco-Rosso** [comment]
I faced the same issue https://github.com/owntone/owntone-server/issues/1285, but ultimately could not figure it out. I just wiped my VM and re-installed and it worked.

**Comment by ejurgensen** [comment]
Yes, I think this is the same as #1285. Seems to be some issue with libwebsockets, so I don't think there is much I can do. Which version of libwebsockets is it?

**Comment by th0u** [comment]
thank you both for your information and pointing me to issue #1285. 
I was able to resolve my issue. It was due to an old manually added version of libwebsockets.so hanging around.

Thnx,
