### ISSUE TITLE
28.2 does not build on Fedora 35 from clean tarball -- bogus RSP.u

### ISSUE THREAD

**Issue by derekatkins** [owntone/owntone-server#1350]
I'm trying to build owntone 28.2 from the tarball on a clean Fedora 35 system.  The first thing I noticed is that the tarball does not come pre-autotooled!  That was odd (one usually expects a release tarball to come with 'configure' already created).  Not a big deal, I'm a big boy and can run autoreconf -i.  Then I ran configure and make...

Then it died because the antlr3 dependency files are all bogus:
```
....
Making all in src
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . DAAP.g > DAAP.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' DAAP.u > DAAP.u-t
mv DAAP.u-t DAAP.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . RSP2SQL.g > RSP2SQL.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' RSP2SQL.u > RSP2SQL.u-t
mv RSP2SQL.u-t RSP2SQL.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . DAAP2SQL.g > DAAP2SQL.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' DAAP2SQL.u > DAAP2SQL.u-t
mv DAAP2SQL.u-t DAAP2SQL.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . RSP.g > RSP.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' RSP.u > RSP.u-t
mv RSP.u-t RSP.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . SMARTPL2SQL.g > SMARTPL2SQL.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' SMARTPL2SQL.u > SMARTPL2SQL.u-t
mv SMARTPL2SQL.u-t SMARTPL2SQL.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
/usr/bin/antlr3 -depend -fo . SMARTPL.g > SMARTPL.u
/usr/bin/sed -n -e '/^.*\.g[ ]*:\(.*\)/ { s//\1/;h;d; }' -e '/\.tokens.*:/ { p;d; }' -e '/:/ { G;s/\n/ /;p; }' SMARTPL.u > SMARTPL.u-t
mv SMARTPL.u-t SMARTPL.u
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Entering directory '/builddir/build/BUILD/owntone-server-28.2/src'
make[2]: Leaving directory '/builddir/build/BUILD/owntone-server-28.2/src'
RSP.u:2: *** target pattern contains no '%'.  Stop.
make[1]: *** [Makefile:638: all-recursive] Error 1
make: *** [Makefile:480: all] Error 2
```
Strangely, if I look at RSP.u, it DOES look particularly strange:
```
# cat RSP.u
Java virtual machine used: /usr/lib/jvm/jre-11-openjdk/bin/java 
classpath used: /usr/share/java/stringtemplate4/ST4.jar:/usr/share/java/antlr3.jar:/usr/share/java/antlr3-runtime.jar 
main class used: org.antlr.Tool 
flags used:  
options used:  
arguments used: -depend -fo . RSP.g 
RSPParser.c : RSP.g 
./RSP.tokens : RSP.g
RSPParser.h : RSP.g 
RSPLexer.c : RSP.g 
RSPLexer.h : RSP.g 
```
So yes, those first 6 lines are definitely a problem.  Indeed, all the `.u` files look similarly strange.

This happens with a CLEAN build.  If I go back and run the antlr3 commands by hand at this point it seems to get past the problem, however I am trying to make sure I can do it from a clean build so I can build an RPM.  I have tried several ways to attempt to automate the "correct" building of these .u files but none of them seem to work properly.

**Comment by ejurgensen** [comment]
> The first thing I noticed is that the tarball does not come pre-autotooled!

It sounds like you are using the tar.gz that github generates automatically. This is just a snapshot of the repository. Try using the tar.xz instead, which is the "official" release tarball, and which does indeed have configure. It also means you won't need antlr during building, so the issues you have with that should not be relevant.

**Comment by derekatkins** [comment]
Aha, didn't realize that they were different.  Let me try with the .xz tarball and get back to you shortly.

**Comment by derekatkins** [comment]
Excellent. Thanks. That fixed the error.
I did need to make a small patch to the SPEC file to get the RPM to build.  Care for a PR or is just a .diff okay?

**Comment by ejurgensen** [comment]
A PR would be great. I am not a frequent Fedora user, so great if you can help.

**Comment by derekatkins** [comment]
I'm an "only" Fedora user, so....  :)
I'll close this issue (since it's fixed), and make a PR for the spec file shortly.
Thank you for your rapid and EXCELLENT support.  I only hope this application actually does what I hope it does!!!  :)

**Comment by ejurgensen** [comment]
I have tried building on Fedora 35 straight from master, so with antlr and all, and I couldn't reproduce the issue you had above. I didn't, however, use the script to install antlr, I just installed with `yum install antlr3-c-devel antlr3`. I have updated the Fedora INSTALL instructions so they say to use the package manager.
