### ISSUE TITLE
ArchLinux, error compilation

### ISSUE THREAD

**Issue by JoCarBin** [owntone/owntone-server#1352]
ArchLinux
owntone-server-28.2

library/filescanner_ffmpeg.c:445:37: error: ‘AVStream’ no tiene un miembro llamado ‘codecpar’; ¿quiso decir ‘codec’?
  445 |       codec_type = ctx->streams[i]->codecpar->codec_type;
      |                                     ^~~~~~~~
      |                                     codec
library/filescanner_ffmpeg.c:446:35: error: ‘AVStream’ no tiene un miembro llamado ‘codecpar’; ¿quiso decir ‘codec’?
  446 |       codec_id = ctx->streams[i]->codecpar->codec_id;
      |                                   ^~~~~~~~
      |                                   codec
library/filescanner_ffmpeg.c:447:38: error: ‘AVStream’ no tiene un miembro llamado ‘codecpar’; ¿quiso decir ‘codec’?
  447 |       sample_rate = ctx->streams[i]->codecpar->sample_rate;
      |                                      ^~~~~~~~
      |                                      codec
library/filescanner_ffmpeg.c:448:37: error: ‘AVStream’ no tiene un miembro llamado ‘codecpar’; ¿quiso decir ‘codec’?
  448 |       sample_fmt = ctx->streams[i]->codecpar->format;
      |                                     ^~~~~~~~
      |                                     codec
library/filescanner_ffmpeg.c:449:35: error: ‘AVStream’ no tiene un miembro llamado ‘codecpar’; ¿quiso decir ‘codec’?
  449 |       channels = ctx->streams[i]->codecpar->channels;
      |                                   ^~~~~~~~
      |                                   codec

????
Thanks.

**Comment by ejurgensen** [comment]
What version of ffmpeg is this with?

**Comment by JoCarBin** [comment]
> What version of ffmpeg is this with?

ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

**Comment by ejurgensen** [comment]
I think the issue is that the ffmpeg headers you have installed are not updated, in fact they are very ancient. As you can see the compiler is complaining about no "codecpar" in the AVStream, but this [is](https://ffmpeg.org/doxygen/trunk/structAVStream.html) and has been part of ffmpeg's AVStream for a long time. The compiler suggests using "codec", but that hasn't been in AVStream for [a long time](https://ffmpeg.org/doxygen/0.9/structAVStream.html).
