### ISSUE TITLE
Question: What is the "consume" toggle switch (with the fire icon) for in the web page now playing page?

### ISSUE THREAD

**Issue by manderpe** [owntone/owntone-server#1355]
I have tried looking through the code to figure out what the little fire button is for and figure it is for a "consume" feature in a player but I cannot figure out what that could be.

**Comment by LordMyschkin** [comment]
Thats an easy one: Every played track gets deleted from the playlist.

**Comment by manderpe** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I see!  Good for podcasts I guess but not necessarily for music. Thanks very much.                                                                                                                                              Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: November 24, 2021 2:54 p.m.To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [owntone/owntone-server] Question: What is the "consume" toggle switch (with the fire icon) for in the web page now playing page? (Issue #1355)  
Thats an easy one: Every played track gets deleted from the playlist.

**Comment by LordMyschkin** [comment]
It is a smart way to prevent double play while shuffeling through a larger playlist - I use it regularily with smart playlists.
