### ISSUE TITLE
Volume normalization

### ISSUE THREAD

**Issue by boblund** [owntone/owntone-server#1362]
I've got an iTunes library that I play using Owntone (actually an older forked-daapd release). I'd like to have the playback volume normalized. It appears I can used iTunes sound check to add volume normalization tags to the music files. Will the Owntone player used these tags? Is this the best way to accomplish my goal?

Thanks,
Bob Lund

**Comment by ejurgensen** [comment]
Sorry, but I don't know the answer to this. The files are decoded by ffmpeg's libraries, and I don't know how they deal with such volume tags.

**Comment by boblund** [comment]
ReplayGain looks like it would be a solution; is it supported in Owntone? src/mpc.d says no. But I see in https://github.com/owntone/owntone-server/issues/290 that it mat be. Can you clarify?

Thanks,
Bob Lund

**Comment by ejurgensen** [comment]
Still don't know the answer :-(

**Comment by boblund** [comment]
Thanks.  I tried it with FORKED-DAAPD - VERSION 27.2. Replaygain tags don't have any apparent affect.
