### ISSUE TITLE
Can't install on RPi

### ISSUE THREAD

**Issue by kimme1024** [owntone/owntone-server#1365]
Please try to provide the following:

When trying to follow the guide for installing owntone on raspbian I'm getting the following error:

```
sudo apt install owntone
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owntone : Depends: libantlr3c-3.4-0 but it is not installable or
                    libantlr3c-antlrdbg-3.4-0 but it is not installable
           Depends: libavcodec58 (>= 7:4.2) but it is not installable
           Depends: libavfilter7 (>= 7:4.0) but it is not installable
           Depends: libavformat58 (>= 7:4.2) but it is not installable
           Depends: libavutil56 (>= 7:4.0) but it is not installable
           Depends: libc6 (>= 2.29) but 2.24-11+deb9u4 is to be installed
           Depends: libconfuse2 (>= 3.2.1~) but it is not installable
           Depends: libcurl4 (>= 7.16.2) but it is not installable
           Depends: libevent-2.1-7 (>= 2.1.8-stable) but it is not installable
           Depends: libevent-pthreads-2.1-7 (>= 2.1.8-stable) but it is not installable
           Depends: libgcrypt20 (>= 1.8.0) but 1.7.6-2+deb9u4 is to be installed
           Depends: libgnutls30 (>= 3.7.0) but 3.5.8-5+deb9u6 is to be installed
           Depends: libjson-c5 (>= 0.15) but it is not installable
           Depends: libmxml1 (>= 3.2) but it is not going to be installed
           Depends: libplist3 (>= 2.2.0) but it is not going to be installed
           Depends: libsodium23 (>= 0.6.1) but it is not installable
           Depends: libunistring2 (>= 0.9.7) but it is not installable
           Depends: libwebsockets16 (>= 2.4.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I tried:
https://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies-after-adding-a-ppa

and 

```
sudo apt-get update
sudo apt-get upgrade
```

sadly the issue remains.

**Comment by ejurgensen** [comment]
It looks you are trying to install either the Buster or the Bullseye version on Raspberry OS Stretch. That won't work, and Stretch is also pretty old, so you would need a newer platform (I would recommend a clean install of latest Raspberry Pi OS, which will give you Bullseye).

**Comment by kimme1024** [comment]
> It looks you are trying to install either the Buster or the Bullseye version on Raspberry OS Stretch. That won't work, and Stretch is also pretty old, so you would need a newer platform (I would recommend a clean install of latest Raspberry Pi OS, which will give you Bullseye).

Thanks! As that RPi is constantly running an MQTT service to connect my pellet stove to my home assistant instance a clean install would be a bit too much work. I just tried installing it there as I used to install forked-daapd on it without any issues. As owntone can't be installed on my M1 Mac as originally intended (#1361) I was hoping to (temporarily) fix it this way...
