### ISSUE TITLE
Airplay2 bitrate query

### ISSUE THREAD

**Issue by richjn** [owntone/owntone-server#1369]
Hi, I am new to owntone-server and firstly would like to say thanks for providing this project.

All of my music is stored as flac 44,100 s16 with a bitrate which varies between 850 kbps - 1440 kbps. I have compiled owntone with the option --enable-preferairplay2 and then have no other specific settings for airplay within owntone.conf. I have three airplay2 compatible speakers (Bose, Sonos and Naim) all of which I can connect to and play without issues.

I mainly use owntone via its web interface but occasionally I use ncmpc (ncurses cmd mpd client) and it was whilst using this client I noticed it was reporting a playback bitrate of only 128kbps

> Currently playing song
Position:  1
Artist:    ABBA
Title:     Another Town, Another Train
Album:     Ring Ring
Length:    3:08
Disc:      1
Track:     2
Date:      1973
Genre:     Unknown genre
Path:      file:/home/richard/Music/ABBA/Ring Ring/02 Another Town, Another Train.flac
**Bitrate:   128 kbps**
Format:    44100:16:2<

As best I can see the owntone web interface does not display the playback bitrate ? so I turned on debug for owntone (attached last 300 lines) and as far as I can see this track is being identified correctly but the log doesn't appear to show me what playback rate is being used only that 44100, s16 is being used.

Is this just a nuance of the mpd interface or is something else going on ? Sorry if I'm just making a noob mistake here.

Regards
Richard
[dump.txt](https://github.com/owntone/owntone-server/files/7722379/dump.txt)

**Comment by richjn** [comment]
I have recompiled without --enable-preferairplay2 and confirmed that my speakers are now connected via airplay1 as per default for owntone. No change noted with ncmpc which is still reporting playback at 128 kbps.

I have also pushed audio to all three devices via Roon (uses Airplay1) which plays at the correct kbps rate so it doesn't appear to be hardware related.

**Comment by ejurgensen** [comment]
Not a noob mistake at all. Your issue sounds like it is the same as #959 (changed the title of it just now so it is easier to find). The bitrate is not really 128, so no worries, it is just a hardcoded value that is reported to mpd clients. Of the top of my head I don't remember the reason for that, but it should of course be fixed.

I'll close this issue so that there is only one issue open on it.
