### ISSUE TITLE
Sound source from USB

### ISSUE THREAD

**Issue by orakelet** [owntone/owntone-server#1372]
Not sure if this has been a topic earlier, but I could not find it, so here goes. I want to use my hifi (an old BeoCenter) as a music source for owntone. I have a USB dongle (ezCAP) from line out on BeO and into USB on my RPi, but how do I set the USB dongle as source for the owntone?

**Comment by Porco-Rosso** [comment]
You probably want to take the audio-in from the USB soundcard and write it to a "Pipe"
https://github.com/owntone/owntone-server#pipes-for-eg-multiroom-with-shairport-sync

This guide in the wiki is pretty close to what you are looking to do: 
https://github.com/owntone/owntone-server/wiki/Making-an-Analog-In-to-Airplay-RPi-Transmitter

**Comment by orakelet** [comment]
Thanx, I will try that
