### ISSUE TITLE
multiple airplay 1 devices hosted on same IP not showing in owntone

### ISSUE THREAD

**Issue by Lord-Micro** [owntone/owntone-server#1376]
I have a few airplay 2 devices which appear to be working all ok. So avahi-browser, owntone and the network are at least working and functional.

My issue is I have an old Control4 home automation system (HC800 on OS 2.9) which can provide multiple airport devices for multi-zone audio. They call their implementation Shairbridge. I currently have 6 separates "zones" configured on the same box, all the same IP but different ports. All of which are published and usable from iPad/iPhone/Mac via airplay alongside my official apple airplay devices (HomePod, aTV etc).

These appear to show up through bonjour or mdns (via an iPad add, Discovery) as _raop._tcp devices and all on the same IP but different ports. 

Is this likely an avahi-brower issue? or is it a config within Owntone? Any suggestions, hints, tips or ideas?

examples - 

> Kitchen : 33FA00A66F2E@Kitchen    home-controller-800-000FFF57AC40.local:6731    192.168.1.104
> Downstairs : B905450F09DC@Downstairs    home-controller-800-000FFF57AC40.local:6740    192.168.1.104

More detail of another with more details, Dining : 

> FC7A8A928BE9@Dining._raop._tcp.local.
> Remote Audio Output Protocol (AirTunes)
> 
> home-controller-800-000FFF57AC40.local:6734
> 192.168.1.104:6734
> 
> ch = 2
> cn = 0,1
> da = true
> ek = 1
> et = 0,1
> md = 0,1,2
> pw = false
> sm = false
> sr = 44100
> ss = 16
> tp = UDP
> txtvers = 1
> vn = 3
>

**Comment by ejurgensen** [comment]
What's the output of `avahi-browse -r -k _raop._tcp` on the device that is running OwnTone? + please also include logs as issue template tells you.

**Comment by Lord-Micro** [comment]
Thanks for responding. 
I left it overnight after restarting everything involved. Most are now showing up. Clearly all is ok and issues are on my end. Thanks.
