### ISSUE TITLE
Different album art results in multiple album entries

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1387]
Is it the case that only differing album art should result in multiple album entries with artist/album tags otherwise the same?

For example, Gun's N Roses: Appetite for Destruction has original, MFSL, deluxe, super deluxe releases. If the MFSL tracks have the MFSL album art while the additional tracks from the super deluxe release have album art from that release, when browsing by artist or album, Appetite for Destruction has two separate entries.

**Comment by ejurgensen** [comment]
Album art has no influence on album listing, so the reason for the separate entries must be something else. If you can list all the metadata tags from one track and all from another then perhaps I can see why they are being separated. You can use ffprobe to list the metadata.

**Comment by frankusb** [comment]
Sure, see below.

Input #0, flac, from '01-Welcome to the Jungle.flac':
  Metadata:
    TITLE           : Welcome To The Jungle
    ALBUM           : Appetite For Destruction
    ARTIST          : Guns N' Roses
    GENRE           : Hard Rock
    DATE            : 1987-10-27
    track           : 01
    CATALOGNUMBER   : MFSL UDCD 699
    disc            : 1/4
  Duration: 00:04:31.39, start: 0.000000, bitrate: 958 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1494x1492 [SAR 1:1 DAR 747:746], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

Input #0, flac, from '51-Move To The City (1988 Acoustic Version).flac':
  Metadata:
    ALBUM           : Appetite For Destruction
    ARTIST          : Guns N' Roses
    GENRE           : Hard Rock
    TITLE           : Move To The City (1988 Acoustic Version)
    DATE            : 1987-10-27
    track           : 51
    disc            : 4/4
  Duration: 00:03:26.79, start: 0.000000, bitrate: 991 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 96:96 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

**Comment by ejurgensen** [comment]
Looks like it is the `CATALOGNUMBER : MFSL UDCD 699`. Along with a number of other fields it is used to calculate the album id, and since it is not there for the other track the id would be different. So the solution would be to either add or drop the tag for all the tracks.

**Comment by frankusb** [comment]
What are the "other fields"?

On another album there is no CATALOGNUMBER.

Input #0, flac, from '01-Zoo Station.flac':
  Metadata:
    ALBUM           : Achtung Baby
    MUSICBRAINZ_ARTISTID: a3cb23fc-acd3-4ce0-8f36-1e5aa6a18432
    TITLE           : Zoo Station
    ARTIST          : U2
    MUSICBRAINZ_WORKID: 6f600be9-6746-37cd-84a9-639246f65fbf
    MUSICBRAINZ_TRACKID: 92084e71-26a8-4da4-8242-b707253a3796
    album_artist    : U2
    MUSICBRAINZ_DISCID: C7Nxdg0Z5YpJFZ3B9LVHF.dnPf0-
    DATE            : 1991-11-19
    track           : 1
    MUSICBRAINZ_ALBUMID: bde8784b-ae7e-4553-9dda-1c4a19d3a56f
    MUSICBRAINZ_RELEASEGROUPID: 744c7a1b-ac79-35c4-bd92-7e2c6a24c8d8
    MUSICBRAINZ_ALBUMARTISTID: a3cb23fc-acd3-4ce0-8f36-1e5aa6a18432
    MUSICBRAINZ_RELEASETRACKID: 031d33e3-9b91-33e1-a108-6ba43df0c795
    GENRE           : Rock
    disc            : 1/1
  Duration: 00:04:36.13, start: 0.000000, bitrate: 831 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

Input #0, flac, from '68-'Baby' Tryin' To Throw Your Arms Around The World.flac':
  Metadata:
    ARTIST          : U2
    TITLE           : 'Baby' Tryin' To Throw Your Arms Around The World
    ALBUM           : Achtung Baby
    DATE            : 1991-11-19
    track           : 68
    TOTALTRACKS     : 12
    GENRE           : Rock
    album_artist    : U2
    disc            : 6/6
  Duration: 00:04:12.13, start: 0.000000, bitrate: 803 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

**Comment by ejurgensen** [comment]
Here is the list of fields used: https://github.com/owntone/owntone-server/blob/master/src/library/filescanner_ffmpeg.c#L174

Looks like it is the MUSICBRAINZ_ALBUMID in this latter case.

**Comment by frankusb** [comment]
Thank you, this is perfect.
