### ISSUE TITLE
Lag / jittery performance on Pi Zero

### ISSUE THREAD

**Issue by jonaolden** [owntone/owntone-server#1394]
Hi! First of all thank you for all of your amazing work! Really cool project! 
i was just wondering if the pi zero (1st gen) is sufficient to run owntone server? I’m getting a very laggy performance with connection dropping and would like to know what the bottleneck is. Is it consuming to much of RAM for the PZero to handle? 

Best regards

**Comment by ejurgensen** [comment]
I'm sorry to say I have no experience with the Pi Zero. I recall other people also having issues, but I don't know where the bottleneck lies.
