### ISSUE TITLE
Web interface not connecting to socket `web: LWS Ran out of header data space`

### ISSUE THREAD

**Issue by martadinata666** [owntone/owntone-server#1403]
Please try to provide the following:

- Connect via web http://ip:3689
- 28.3
- docker environment

Reproduce:
1. Build owntone without web
2. Build web separately
3. Access web
4. Web successfully connected to 3689, asking password.
5. Owntone web disconnected after that. (failed connect to socket)

```
owntone-app-1  | [2022-01-30 11:00:54] [  LOG]      web: LWS Ran out of header data space
owntone-app-1  | [2022-01-30 11:01:10] [  LOG]      web: LWS Ran out of header data space
owntone-app-1  | [2022-01-30 11:01:32] [  LOG]      web: LWS Ran out of header data space
owntone-app-1  | [2022-01-30 11:02:02] [  LOG]      web: LWS Ran out of header data space
owntone-app-1  | [2022-01-30 11:02:33] [  LOG]      web: LWS Ran out of header data space

```

This happen inconsistently, sometime the web wil connect to sockets just fine or will show Ran out header space for another time.

**Comment by chme** [comment]
Thanks for the report, but unfortunately I cannot reproduce the error

OwnTone sets the header data size for libwebsockets to 4096 bytes to avoid exactly this error with older versions of libwebsockets (<https://github.com/warmcat/libwebsockets/issues/1270>).

What browser are you using? Can you take a look at the browser debug tools to see what request headers it is sending to the websocket?
Are you using the OwnTone built in web server to serve the web interface? Or are you running a different web server?
Can you share the Dockerfile that you are using to run OwnTone?

**Comment by martadinata666** [comment]
> OwnTone sets the header data size for libwebsockets to 4096 bytes to avoid exactly this error with older versions of libwebsockets ([warmcat/libwebsockets#1270](https://github.com/warmcat/libwebsockets/issues/1270)).
> 
> What browser are you using? Can you take a look at the browser debug tools to see what request headers it is sending to the websocket? Are you using the OwnTone built in web server to serve the web interface? Or are you running a different web server? Can you share the Dockerfile that you are using to run OwnTone?

I tried few browser. My conclusion is the that based on chromium engine like qutebrowser, chromium, edge got not issue. Firefox get this issue, my current firefox version is 96.

I tried the built in and separate web interface, the LWS: ran out seems persistent is firefox. I read the LWS link you given, seems browser cache could be an issue.

So cleared browser cache seems solved, is this something expected that browser cache interfere with websockets? 

On other hands thanks for the link given.

**Comment by martadinata666** [comment]
Just add some note, building on debian sid with newer LWS socket version solve the issues 👍🏼

**Comment by chme** [comment]
Good to know, that it is working with a newer LWS version! (and strange that clearing the browser cache has any effect)
I am always using Firefox and never ran into this issue ... so something else seems to cause this issue. Let's hope it is fixed with the new LWS.

**Comment by martadinata666** [comment]
i also not really sure about it too, i purposely left the firefox im using that got issues with LWS, then i build owntone rebased to debian sid and experimental repo that got newer version LWS `4.1.6`, and deploy it, and it just works. As i checked the latest ubuntu impish got the same version as bullseye at 4.0.20, maybe just some LWS magic playing on me. Thanks for the support btw. 👍🏼

**Comment by pagdot** [comment]
Just stumbled over this issue. Had an issue with a different app that cookies from another app from another app caused a big http header

Maybe this is a similar issue where too much cookie data get sent in the header?
