### ISSUE TITLE
Release 28.3 not available through apt

### ISSUE THREAD

**Issue by trise-ne** [owntone/owntone-server#1404]
Hello everyone,

I tried to update owntone but I'm unable to fetch the _current release 28.3_ through apt on my raspberry pi (configured as shown [here](https://forums.raspberrypi.com/viewtopic.php?t=49928)). The new release is not shown.

This is what I did:

> sudo apt update && sudo apt upgrade
> Hit:1 http://www.gyfgafguf.dk/raspbian/owntone buster InRelease
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Is there anything I could do?

Thanks for your help. :)

**Comment by ejurgensen** [comment]
Great to hear about your interest, but I just haven't published a 28.3 RPi package yet. I generally wait around a week before publishing new packages, just in case.
