### ISSUE TITLE
Build error make[2]: *** Keine Regel vorhanden, um das Ziel „rsp_query.gperf“, benötigt von „rsp_query_hash.h“, zu erstellen.  Schluss.

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1405]
I tried to git pull and make; after updating all dependencies for raspberry pi build (buster), i ran a .configure without 
errors; the following "make" though did not succeed due to the error in the headline (translated "No rule to create target rsp_query_gperf, needed by rsp_query.gperf_hash.h.

anything i missed?

**Comment by ejurgensen** [comment]
I just think you need to clean ("make clean" might be enough) and then rebuild with "autoreconf -vi" before configure. The files mentioned no longer exist, so it must be left over from something earlier.

**Comment by LordMyschkin** [comment]
Yup! Forgot the autoreconf -i after the "make clean". Thx!
