### ISSUE TITLE
Owntone isnt working any more after system restart

### ISSUE THREAD

**Issue by 82timo** [owntone/owntone-server#1407]
Hi,

yesterday, I installed owntone and I got it working. But the installation didn't went smoothly.
I think, that the problem was, that I had a spotify add-on and a spotify integration running.
I disabled them and after a while and some help, I got it working.
Then, I did a restart and I cannot get it running any more.

Another difficulty for me is, that I am grabbing on my system by duckdns. This is a httpS connection and - as far as I understand - it refuses any http connections.
I have difficulties with Spotify's OAuth page. I think, that it is because of the http(s) issue.

I want to play spotify, webradio (I put m3u in my library) and local files (synology NAS).
Webradio is still running, spotify isn`t.

This is the log:

`[2022-01-31 15:34:32] [  LOG]  spotify: Eror opening source: Could not send media request
[2022-01-31 15:34:33] [  LOG]  spotify: Eror opening source: The access point disconnected
[2022-01-31 15:34:33] [  LOG]      web: Error starting playback.
[2022-01-31 15:34:33] [  LOG]      web: JSON api request failed with error code 500 (/api/player/play)
[2022-01-31T14:34:38Z WARN  libmdns::fsm] couldn't parse packet from MyIP:5353: type 47 is invalid`

- version of owntone: Current version: 28.2.20211118
- platform: Home Assistant on Raspberry 4b

Do you need more information?

I like to get some help with the requirements, first.
Is it right/ok, that I have deleted/uninstalled the spotify add-on or do I need it?
What about the spotify integration? It has covered a spotify device.

**Comment by 82timo** [comment]
Hi and thank you for your answer.

1. Spotify-Add-on
Before the installation of owntone, I listend spotify by the spotify add-on. I installed this in the Home Assistant GUI in this way:
Settings/Add-ons, Backup & Supervisor/Add-On Store/ There is "Home Assistant Community Add-on: Spotify Connect".
https://github.com/hassio-addons/addon-spotify-connect

You say, that the spotify installation is integrated in owntown. So I uninstalled "Home Assistant Community Add-on: Spotify Connect". This is what I mean with Spotify Add-On.

Just to be sure: Do I need this? I think no.


2. Duckdns.
I get to my Home Assistant GUI by opening https://mydomain,duckdns.org. This is a httpS (secure) connection with a certificate.
When I run owntone  (Settings/Add-ons, Backup & Supervisor/Owntone server), I have some options and below it says:

Open web user interface (that is my translation). The link is
https://mydomain,duckdns.org/hassio/ingress/1234ab3c_owntone-server  <- I made this anonymous
When I click on this lik, I get a error message:
Connection lost. Reconnecting ... (1)
I think, that this is, because owntown is only accessible from my internal ip.
With "http://192.168.178.3:3689/#/" I can get on the owntown server ("Connection to server established").
With the hamburger menü top right, "settings" and "Online Services", I see

Spotify
You must have a Spotify premium account   <- I have a spotify premium account
Spotify Web API - Grant access to the Spotify Web API
Access granted for shd535e... (28 digits and numbers).
Authorize Web API access <- this doesn't work
Access to the Spotify Web API enables scanning of your Spotify library. Required scopes are playlist-read-private, playlist-read-collaborative, user-library-read, user-read-private, streaming.

When I click on "Authorize Web API accesss", it goes to:
http://owntone.local:3689/oauth/spotify?code=...

This website is unavailable.
I suspect, that this is because of owntone.local....
I tried this:
http://mydomain.duckdns.org:3689/oauth/spotify?code=...   <- unavailable
https://mydomain.duckdns.org:3689/oauth/spotify?code=...   <- unavailable
https://mydomain.duckdns.org/oauth/spotify?code=.. < 404 not found
https//mydomain.duckdns.org/oauth/spotify?code=.. < 404 not found

I think, that the Web API access is not right. But that is only my supposition.
How can I get this working?

3. It has covered a device:
In Home Assistant/Settings/Integration, it says: Spotify: Configure or Ignore.
When I click "Configure", https://account-link.nabucasa.com/authorize_callback?code=... opens:
Done!
Your account is now linked, you can close this window. <- The website is Nabu Casa Account Link
Then next step for spotify is loading and it says cancelled.

So what is the reason, that it is not working?


Question:
What to do with the IDs from:
http://homeassistant.local:3689/api/outputs


Please ask, if there are unclear points from me.
Thank you

**Comment by ejurgensen** [comment]
I can't help you much with Home Assistant, I don't know how that works or if there is some OwnTone integration in it. By your description it seems like it might have its own Spotify integration, and then Owntone would not depend on it. With regard to the web you also need to open port 3688, but in general I wouldn't recommend exposing OwnTone to the internet. For Spotify authentication you must make sure that the server is reachable at owntone.local. You may want to check the README.
