### ISSUE TITLE
Creation of Playlists

### ISSUE THREAD

**Issue by manderpe** [owntone/owntone-server#1408]
Hi, I don't see a way of creating or editting playlists within the Owntone web interface.  Since there are no Windows clients, the web interface seems to be the best way of operating Owntone from Windows and so a method for creating and editting playlists would be really handy.  I know I can do that from a Linux application on the Owntone server but that is harder for my users to do.  I can add songs to the Queue (Now Playing) but don't see a way to save the Now Playing as a new playlist nor to edit it.

**Comment by ejurgensen** [comment]
Yes, you should be able to save queues as playlists from the web ui, but you need to enable the allow_modifying_stored_playlists config setting. Also see the default_playlist_directory setting. I'll update the README now to document this better.

**Comment by manderpe** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Work perfectly!  Thanks so much.                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: January 31, 2022 4:03 p.m.To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [owntone/owntone-server] Creation of Playlists (Issue #1408)  
Yes, you should be able to save queues as playlists from the web ui, but you need to enable the allow_modifying_stored_playlists config setting. Also see the default_playlist_directory setting. I'll update the README now to document this better.
