### ISSUE TITLE
Error installing on Mac OS

### ISSUE THREAD

**Issue by maxymkov** [owntone/owntone-server#1409]
Hi there,
After I'm running command:
autoreconf -i
./configure
make
sudo make install

I'm getting into the error:
In file included from websocket.c:24:
/usr/local/Cellar/libwebsockets/4.3.1/include/libwebsockets.h:301:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [websocket.o] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

I was trying to fix it by installing openssl and modifying .bashrc but got in other types of errors. 

Thank you in advance for any help.

**Comment by ejurgensen** [comment]
Can't help much, I don't have macOS, but it seems the workflow file has a solution for this issue:
https://github.com/owntone/owntone-server/blob/dca85c5a79a16b93ee12bfde64ec1c6e0cd9b543/.github/workflows/macos.yml#L70

**Comment by maxymkov** [comment]
Thanks.
It ends up with error on make
~ % make
make: *** No targets specified and no makefile found.  Stop.

**Comment by maxymkov** [comment]
Find and fixed the mistakes with installation.
BTW to fix them it will require to combine instructions from both installation methods for Mac OS.
However, run command now ends up with errors:

owntone(23343,0x108aa9600) malloc: *** error for object 0x108aa9600: pointer being freed was not allocated
owntone(23343,0x108aa9600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      sudo /usr/local/sbin/owntone
