### ISSUE TITLE
Installation instructions Mac OS

### ISSUE THREAD

**Issue by maxymkov** [owntone/owntone-server#1410]
https://github.com/owntone/owntone-server/blob/dca85c5a79a16b93ee12bfde64ec1c6e0cd9b543/.github/workflows/macos.yml#L44

Before this line there should be .bashrc created and placed in /usr/local/Homebrew/

**Comment by ejurgensen** [comment]
The workflow file is working fine, so I don't see why a .bashrc should be made

**Comment by maxymkov** [comment]
Hmm, I got in error while running:
wget https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
        tar xzf sqlite-autoconf-3310100.tar.gz
        cd sqlite-autoconf-3310100
        export CFLAGS='-DSQLITE_ENABLE_UNLOCK_NOTIFY=1'
        ./configure
        make
        sudo make install
        cd ..

Fixed with placement of .bashrc
