### ISSUE TITLE
Websocket Push Notifications (raspberry pi buster)

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1420]
I am running two instances of owntone 28.3 installed following INSTALL.md for raspberry pi. One instance is on an RPi3b and the other an RPI4. Both are running raspbian OS buster (fully updated). When I use the following curl command from the JSON API for WebSocket push notifications I never get a response like that detailed. Can anyone confirm that this is working on their install before I start attaching logs and using up time?

curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: localhost:3688" \
     --header "Origin: http://localhost:3688" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     --header "Sec-WebSocket-Protocol: notify" \
     http://localhost:3688/ \
     --data "{ \"notify\": [ \"player\" ] }"

**Comment by LLPP65** [comment]
Hi. I'm also looking into websockets push messages (to trigger a sec command to set the receiver input to the daapd host). I've tried perl scripts, node-red and curl and cannot get a push message. Did you ever get this working?

**Comment by jnth** [comment]
You must add the `notify` sub-protocol.

In Python, you can get all messages sent by the server with:

```python
#!/usr/bin/env python

import asyncio
import json
from websockets.sync.client import connect

def main():
    with connect("ws://127.0.0.1:3688/", subprotocols=["notify"]) as websocket:
        websocket.send(json.dumps({"notify": ["player", "volume", "outputs"]}))
        while True:
            try:
                message = websocket.recv()
                print(f"Received: {message}")
            except KeyboardInterrupt:
                break

main()
```
