### ISSUE TITLE
libwebsocket 4.1.6 causes server to take a long time to shutdown

### ISSUE THREAD

**Issue by whatdoineed2do** [owntone/owntone-server#1423]
using master on Fedora 35 / libwebsocket 4.1.6, it takes up to 30secs for the process to terminate.

Traced to the `websocket` waiting for the event loop to timeout and to notice the termiation flag set at line 423
```
[2022-02-22 14:22:56] [ WARN]    httpd: deinit: ws
[2022-02-22 14:23:20] [ WARN]    httpd: deinit: oauth
[2022-02-22 14:23:20] [ WARN]    httpd: deinit: json
```

https://github.com/owntone/owntone-server/blob/e6823199d62a56368ff8bb29631c8e9f172e04c5/src/websocket.c#L420-L430.

apparent simple fix is to have `deinit()` call `lws_service_cancel()` along side the termination flag

```
diff --git a/src/websocket.c b/src/websocket.c
index 6ac4a145..ee25af4e 100644
--- a/src/websocket.c
+++ b/src/websocket.c
@@ -429,7 +429,6 @@ websocket(void *arg)
 #endif
   }
 
-  lws_context_destroy(context);
   pthread_exit(NULL);
 }
 
@@ -540,10 +539,12 @@ websocket_deinit(void)
   if (websocket_port <= 0)
     return;
 
   websocket_exit = true;
+  lws_cancel_service(context);
   ret = pthread_join(tid_websocket, NULL);
   if (ret < 0)
     DPRINTF(E_LOG, L_WEB, "Error joining websocket thread (%d): %s\n", ret, strerror(ret));
 
+  lws_context_destroy(context);
   pthread_mutex_destroy(&websocket_write_event_lock);
 }
```
resulting in no delay.
```
[2022-02-22 14:35:00] [ WARN]    httpd: deinit: ws
[2022-02-22 14:35:00] [ WARN]    httpd: deinit: oauth
[2022-02-22 14:35:00] [ WARN]    httpd: deinit: json
```

Theres a potential race condition on the cancel and the setting of flag and then the context destroy thus move destroy into deinit.

**Comment by chme** [comment]
Sorry for taking so long to respond ... missed this one. Sounds good and the change looks good. Can you create a PR for this?
