### ISSUE TITLE
Potential bug when searching using the json api

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1425]
Hi, 

Owntone 28.3 (installed from repo)
Raspberry Pi 4B+ (Buster)

I am seeing what is a potential bug when searching using the json api. I find that pipes are showing as both pipes with the data_kind set to pipe and files with the data_kind set to file. See my evidence below.

Query 1.
curl -k "http://192.168.1.231:3689/api/search?type=albums&expression=media_kind+is+music+and+data_kind+is+file+or+data_kind+is+spotify+order+by+time_added+jq .&offset=0&limit=16" 

Response 1 includes as the fourth item, note that the data_kind is set to file. 
     
 ```
     {
        "id": "5024056800311776848",
        "name": "Unknown album",
        "name_sort": "Unknown album",
        "artist": "Unknown artist",
        "artist_id": "3032167492714513953",
        "track_count": 1,
        "length_ms": 38761,
        "time_added": "2022-02-24T11:51:20Z",
        "in_progress": false,
        "media_kind": "music",
        "data_kind": "file",
        "year": 0,
        "uri": "library:album:5024056800311776848",
        "artwork_url": "./artwork/group/1"
      }
```

Query 2
curl -k "http://192.168.1.231:3689/api/search?type=albums&expression=media_kind+is+music+and+data_kind+is+pipe+order+by+time_added+desc&offset=0&limit=16"

Response 2, note the data_kind is set to pipe

      {
        "id": "5024056800311776848",
        "name": "Unknown album",
        "name_sort": "Unknown album",
        "artist": "Unknown artist",
        "artist_id": "3032167492714513953",
        "track_count": 4,
        "length_ms": 0,
        "time_added": "2021-10-22T13:57:30Z",
        "in_progress": false,
        "media_kind": "music",
        "data_kind": "pipe",
        "year": 0,
        "uri": "library:album:5024056800311776848",
        "artwork_url": "./artwork/group/1"
      }

In both searches, the id is the same but the data_kind changes. Any ideas or is this a bug. Incidentally I have a metadata pipe set up for this pipe input. Is it possible that it is being detected as a file whilst the audio pipe is being detected as a pipe?

**Comment by ejurgensen** [comment]
I suppose this might happen if the album has both file and pipe tracks? This could well be the case for "Unknown album", since it is sort of an "everything else" album. Maybe you can check via the json api which tracks the album has?

**Comment by aleszczynskig** [comment]
Yes - are correct. The Unknown Album is picking up all of my pipes and radio playlists. I guess I just need to exclude it from my search.

**Comment by aleszczynskig** [comment]
Is there a way I can exclude the Unknown Album from the search if I try to include a clause like 'and album not is Unknown album', owntone either crashes or hangs my pi. I presume because this search is very inefficient. Any suggestions?

**Comment by ejurgensen** [comment]
I can't reproduce any crash or hang. Can you share the exact api call you used?

**Comment by aleszczynskig** [comment]
Sure. 

`curl -k "http://192.168.1.231:3689/api/search?type=albums&expression=media_kind+is+music+and+data_kind+is+file+or+data_kind+is+spotify+album+not+is+Unknown%20album+order+by+time_added+&offset=0&limit=16"`

**Comment by ejurgensen** [comment]
For me, that request returns "Bad request". Not sure why you get crash/hang. Is it owntone from master, og some older build?

The request has a few issues, so "Bad request" would be the correct response. I think the query you want to make is:
`media_kind is music and (data_kind is file or data_kind is spotify) and not album is "Unknown album"`

Url encoded (with + instead of %20):
`media_kind+is+music+and+%28data_kind+is+file+or+data_kind+is+spotify%29+and+not+album+is+%22Unknown+album%22`

**Comment by aleszczynskig** [comment]
It's 28.3 installed from apt using the instructions in INSTALL.md for raspberry pi.

Thank you for the correct query, that does include work. 

Are you interested in a debug or spam log for the query to understand more?

**Comment by ejurgensen** [comment]
> It's 28.3 installed from apt using the instructions in INSTALL.md for raspberry pi

Ok that would explain it. That version is still using the old parser, which had issues that match what you describe.
