### ISSUE TITLE
Spotify config option `album_override` has no effect

### ISSUE THREAD

**Issue by ben-willmore** [owntone/owntone-server#1426]
The spotify config option `album_override` does not work for me -- it doesn't change the album list as far as I can tell.

I looked at the following code in `src/library/spotify_webapi.c` (line 1552 onward):
```
  if (album && album->uri)
    {
      mfi->album_artist = safe_strdup(album->artist);
      mfi->album = safe_strdup(album->name);
      mfi->genre = safe_strdup(album->genre);
      mfi->compilation = album->is_compilation;
      mfi->date_released = album->release_date_time;
      mfi->year = album->release_year;
    }
  else
    {
      mfi->album_artist = safe_strdup(track->album_artist);
      if (cfg_getbool(cfg_getsec(cfg, "spotify"), "album_override") && pl_name)
	mfi->album = safe_strdup(pl_name);
      else
	mfi->album = safe_strdup(track->album);
    ...
    }
```

It looks like the first part should run for tracks from spotify saved albums, and the second part should run for saved playlist tracks. However, for my library, whenever this function is called, `album` always has a value, and `pl_name` is empty (even for saved playlist tracks). As a result, the 'album' code gets run for all tracks, and the "album_override" option never has a chance to take effect.

I changed the calling code to send a `null` album for playlist tracks, which helped (i.e. the correct branch of the `if` statement runs) but resulted in all spotify tracks being assigned to "Unknown album"  (because the playlist name is always blank).  I changed the album name from `pl_name` to "Spotify playlists", which would be OK, but now when I browse albums, the list contains thousands of albums, all called "Spotify playlists" but with different artists. I couldn't find a combination of values that would set all the album artists to "Various artists" (which would result in a single Album called "Spotify playlists" by "Various Artists") without having detrimental effects elsewhere (e.g. when browsing the Artists list).

**Comment by ejurgensen** [comment]
I have tried this now, and observed the same. I suppose something most have broken this. Will have to investigate more to find our what happened, and how to fix.

**Comment by ben-willmore** [comment]
This is a minimal fix to get it to do what the conf file comment says it should do, i.e. "This will use the playlist name as album name for Spotify items". It still doesn't behave as I would expect, because now the "Albums" list (in the web interface) contains many copies of the same playlist name. But perhaps this works as intended when browsing in Remote.

```
diff --git a/src/library/spotify_webapi.c b/src/library/spotify_webapi.c
index 84e80c09..294f39bf 100644
--- a/src/library/spotify_webapi.c
+++ b/src/library/spotify_webapi.c
@@ -1813,6 +1813,7 @@ saved_playlist_tracks_add(json_object *item, int index, int total, enum spotify_
 {
   struct spotify_track track;
   struct spotify_album album;
+  struct playlist_info *pli;
   json_object *jsontrack;
   json_object *jsonalbum;
   int *plid;
@@ -1820,6 +1821,7 @@ saved_playlist_tracks_add(json_object *item, int index, int total, enum spotify_
   int ret;
 
   plid = arg;
+  pli = db_pl_fetch_byid(*plid);
 
   if (!(item && json_object_object_get_ex(item, "track", &jsontrack)))
     {
@@ -1847,7 +1849,7 @@ saved_playlist_tracks_add(json_object *item, int index, int total, enum spotify_
     }
 
   dir_id = prepare_directories(track.album_artist, track.album);
-  ret = track_add(&track, &album, NULL, dir_id, request_type);
+  ret = track_add(&track, NULL, pli->title, dir_id, request_type);
   if (ret == 0)
     db_pl_add_item_bypath(*plid, track.uri);
```

**Comment by ejurgensen** [comment]
Looked a bit into the history, and it looks like the bug appeared  quite a while ago with commit cfc5fef88d34451163365f562b9e209237f19ea4. Since then all calls to track_add() have had pl_name = NULL. Your fix restores the old call, which was `webapi_track_save(&track, NULL, playlist->name, dir_id)`, but like you say it's not a proper fix. By setting album to NULL it also goes against what was intentionally changed  in the opposite direction in commit a28c6ba1d603e89118d3309355f3c6defdcf65c7.

I'm not sure what the right fix for the issue is, I hope @chme will be able to look into this.
