### ISSUE TITLE
Web UI triggers large amount of artwork requests (e.g. to Spotify)

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1427]
Steps to reproduce and/or logging of the error:

1. Login to Spotify for the first time
2. Wait for Spotify library to load
3. Go to albums view and scroll down to the bottom
4. A barrage of artwork requests are sent to Spotify (I guees because all albums above er being loaded)

I think this behavior can bring us in bad standing with Spotify. It would be good if the web UI only loaded albums that were actually in view. Would also make it faster, I guess.

**Comment by chme** [comment]
I agree, that it would be good to only load the items that are in view. 
There is an open issue for this for the library I am using to lazy load images (part of the Vue 3 migration): https://github.com/murongg/vue3-lazyload/issues/19

It is a bit tricky to implement ... 

(I don't think that Spotify will notice the one time load for images. We cache the result, so it only happens once per user.)
