### ISSUE TITLE
Apple Remote Artwork Does Not Update when modifying the now playing artwork url via the API

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1433]
When changing the artwork of the now_playing item via the JSON API, the artwork does not update in Apple Remote. The changes are reflected in the Web UI and the artwork field in the remote app flickers twice before displaying the standard missing artwork image so it does appear that there is an update request made. I appreciate this may be a bug in the remote application. I have attached logs of the change. 

I am using the example call from the JSON API documentation.

curl -X PUT "http://localhost:3689/api/queue/items/now_playing?title=Awesome%20title&artwork_url=http%3A%2F%2Fgyfgafguf.dk%2Fimages%2Fpige3.jpg"

[artwork.log](https://github.com/owntone/owntone-server/files/8306372/artwork.log)

**Comment by ejurgensen** [comment]
I could reproduce. Looks like there are two things to it, one is that the Remote handler (dacp) wasn't listening for queue events, second is that it only has support for live updating of internet and pipe sources. The former seems easy enough to fix, so I did that in the commit above. The latter is a bit more complicated, and maybe not that important?

From the log it looks like you were testing with an internet stream, so in that case this fix should do it. Let me know if it works.

**Comment by aleszczynskig** [comment]
Thanks for the quick response and patch. I have compiled it this morning however it does not seem to work as expected for neither pipe sources or internet sources. 

On the initial api change of artwork, the artwork in Remote does flicker but does not reflect the new image afterwards. On subsequent api calls, there is not flicker (maybe remote things there is nothing to change?).

I have attached debug logs. 

Thanks

[artwork2.log](https://github.com/owntone/owntone-server/files/8309049/artwork2.log)

**Comment by aleszczynskig** [comment]
After further testing, this does appear to work correctly. Apologies for my incorrect feedback earlier today.

**Comment by ejurgensen** [comment]
No problem. Actually your feedback helped me discover that the fix wasn't enough to work for pipe source. I hadn't tested that the first time around. Now I have added a commit to the branch with should address that.

**Comment by aleszczynskig** [comment]
Thanks for the extra work. I did manage to get it to update using a pipe source though initially it didn't work, hence my feedback. Does this make any sense in light of the changes you made?

**Comment by ejurgensen** [comment]
I don't understand how it worked for you with pipe without the extra commit. It don't work for me, at least.

**Comment by aleszczynskig** [comment]
I'm not sure but it is definitely working. I've been using it for several days and it seems to be reliable. Strange.

**Comment by ejurgensen** [comment]
I can add that when you have it working the log should say: `[DEBUG] artwork: Artwork for 'aux' found in source 'stream'`. This means that the artwork was retrieved via the artwork_url.

**Comment by aleszczynskig** [comment]
Right, that makes a lot of sense now. I was not scanning the logs so when it worked 99% of the time I was happy enough. I did note the reference to Spotify in the logs when I did the captures but I didn't really understand what Owntone was doing with Spotify.

The update to the log would be useful. Just for my own understanding then, is the logic as follows:

If a valid artwork_url is specified, it will display this however if no artwork_url is specified, Owntone will do a lookup in Spotify and display that artwork if a match is found. This search would be based upon the other track metadata specified.

**Comment by aleszczynskig** [comment]
I believe this also explains the unknown album - unknown artist head with sunglasses artwork for my pipe sources. I could never work out where this was coming from, but I now believe this must be supplied from Spotify.

**Comment by ejurgensen** [comment]
> The update to the log would be useful

Actually, my remark about the log wasn't about updating it, just what you should expect to see when the artwork is loaded from artwork_url.

> If a valid artwork_url is specified, it will display this however if no artwork_url is specified, Owntone will do a lookup in Spotify and display that artwork if a match is found. This search would be based upon the other track metadata specified.

Yes, that's correct. I've merged both changes just now, so if you make a new build that's what you should be seeing.

**Comment by aleszczynskig** [comment]
Thanks for clarifying. I will update today and give it ago.
