### ISSUE TITLE
Build error on Debian Bullseye

### ISSUE THREAD

**Issue by mapkyca** [owntone/owntone-server#1434]
Please try to provide the following:

- steps to reproduce and/or logging of the error:

```
pair_ap/pair_homekit.c: In function ‘create_and_sign_device_info’:
pair_ap/pair_homekit.c:1109:3: warning: implicit declaration of function ‘crypto_sign_detached’; did you mean ‘crypto_sign_bytes’? [-Wimplicit-function-declaration]
 1109 |   crypto_sign_detached(signature, NULL, device_info, device_info_len, sk);
      |   ^~~~~~~~~~~~~~~~~~~~
      |   crypto_sign_bytes
pair_ap/pair_homekit.c: In function ‘verify_info’:
pair_ap/pair_homekit.c:1162:10: warning: implicit declaration of function ‘crypto_sign_verify_detached’ [-Wimplicit-function-declaration]
 1162 |   return crypto_sign_verify_detached(signature, info, info_len, pk);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pair_ap/pair_homekit.c: In function ‘client_verify_new’:
pair_ap/pair_homekit.c:1696:3: warning: implicit declaration of function ‘crypto_sign_ed25519_sk_to_pk’; did you mean ‘crypto_sign_ed25519_keypair’? [-Wimplicit-function-declaration]
 1696 |   crypto_sign_ed25519_sk_to_pk(vctx->client_public_key, vctx->client_private_key);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   crypto_sign_ed25519_keypair
pair_ap/pair_homekit.c: In function ‘server_keypair’:
pair_ap/pair_homekit.c:1958:16: error: ‘crypto_sign_SEEDBYTES’ undeclared (first use in this function); did you mean ‘crypto_sign_BYTES’?
 1958 |   uint8_t seed[crypto_sign_SEEDBYTES] = { 0 };
      |                ^~~~~~~~~~~~~~~~~~~~~
      |                crypto_sign_BYTES
pair_ap/pair_homekit.c:1958:16: note: each undeclared identifier is reported only once for each function it appears in
pair_ap/pair_homekit.c:1958:11: warning: unused variable ‘seed’ [-Wunused-variable]
 1958 |   uint8_t seed[crypto_sign_SEEDBYTES] = { 0 };
```

- version of owntone: Latest GIT at time of writing
- platform : Debian Bullseye

To reproduce, follow Debian build instructions

**Comment by ejurgensen** [comment]
Thanks for reporting. Peculiar that you are seeing this, that code has been built many times on Debian Bullseye without issues, and Debian doesn't usually change very much. I have also set up github action that builds debs for Debian Bullseye, and [the latest run](https://github.com/owntone/owntone-apt/runs/5498862474) was ok. I will see if I can reproduce in a fresh VM.

The issue looks like it might be a missing include.

**Comment by ejurgensen** [comment]
Can you verify that you have installed `libsodium-dev`? I suspect that package is missing.

**Comment by mapkyca** [comment]
```
libsodium-dev is already the newest version (1.0.18-1).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```
:( 

Additionally, I've checked back at the `./configure` run and libsodium is found...

**Comment by mapkyca** [comment]
If you're able to build, I can only guess that there is something... odd ... about my build environment.

**Comment by ejurgensen** [comment]
I tried with a fresh Bullseye VM, and I couldn't reproduce. I can only guess that an incorrect version of sodium.h for some reason is getting included.

There's a .deb [here ](https://github.com/owntone/owntone-apt/actions/runs/1964187306) for Bulleye amd64, but of course it's not quite the same as building from source.

**Comment by mapkyca** [comment]
That'll do, thanks for the binary! I'll leave the build problems as one of life's little mysteries....
