### ISSUE TITLE
outdated more link on about screen

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1447]
From the about screen:

Web interface built with [Bulma](http://bulma.io/), [Material Design Icons](https://materialdesignicons.com/), [Vue.js](https://vuejs.org/), [axios](https://github.com/mzabriskie/axios) and [more](https://github.com/ejurgensen/OwnTone/network/dependencies).

https://github.com/ejurgensen/OwnTone/network/dependencies returns 404.

**Comment by chme** [comment]
Thank you for the report. It is already fixed for the next release (see commit 282c05f65b9a92932b594393128e92c532f9152c)

**Comment by frankusb** [comment]
I apologize for not checking the latest.
