### ISSUE TITLE
Trouble setting up with SMB Share Music Library and FIFO Pipe (symlink issue?)

### ISSUE THREAD

**Issue by stephenmetzger** [owntone/owntone-server#1448]
Apologies if this has been discussed elsewhere. I couldn't find a solution in my searches. 

I would like to link music from an SMB share to my owntone instance, in addition to having a FIFO pipe linked to shairport-sync. 

I have owntone running in docker on ubuntu server 20.04, and would like to link my music library, which is available as an SMB share from my UnRAID server. 

I have my music library mounted to `/home/<USER>/music` on my Ubuntu Sever. My Music Library is set up to work with iTunes (even though I rarely use iTunes now), so it's set up like:
```- Music
    - Album Artwork
    - Music
       - <ARTIST 1>
       - <ARTIST 2>
       - (etc...)
    - Previous iTunes Libraries
    - (etc....)
```
So, I symlinked `/home/<USER>/music/music` to `/home/<USER>/docker/owntone/music` So that my owntone appdata folder looks like:
```
 - Music
    - <ARTIST 1>
    - <ARTIST 2>
  iPhone (FIFO pipe)
  iPhone.metadata (FIFO pipe)
```
On ubuntu server, my `/home/<USER>/docker/owntone/music/Music` folder shows my music library, but my owntone logs show:
```
[2022-04-11 14:35:31] [  LOG]     scan: Skipping /music/Music, could not dereference symlink: No such file or directory
[2022-04-11 14:35:31] [  LOG]     scan: Skipping /music/Music, read_attributes() failed
[2022-04-11 14:35:31] [  LOG]     scan: Bulk library scan completed in 0 sec
```

and, when I bash into the owntone container and run `cd /music/Music`, i get: `bash: cd: music/Music: No such file or directory`. 

I have : 
```        # Directories to index
        directories = { "/music" }

        # Follow symlinks. Default: true.
        follow_symlinks = true
```
in my owntone.conf file. 

When I symlink my music library directly to `/home/<USER>/docker/owntone`, so that the owntone appdata directory looks like:
``` - owntone
    - config
    - Music
      - <ARTIST 1>
      - <ARTIST 2> 
      - (etc...)
 ```
my library shows up in owntone. But, when I do it this way, I can't add the FIFO pipes (unless maybe I adjust my SMB permissions?) So, thinking that the error with the first symlink approach is something other than a permissions issue, but I cant figure it out. Any

**Comment by chme** [comment]
My guess is, that this is a problem with how the docker container is set up. From what I understood, you are mounting the `/home/<USER>/docker/owntone` folder as a volume into the container. But the container cannot access the files in `/home/<USER>/music` because they are not visible inside the container (maybe this Stackoverflow answer helps: <https://stackoverflow.com/questions/63099376/docker-container-cant-open-symlinked-file-in-volume-mount-during-startup>).

OwnTone supports adding more than one directory, so you can mount an additional folder into the container that contains the pipe.

**Comment by ejurgensen** [comment]
Closing, no feedback
