### ISSUE TITLE
ffmpeg: ignoring 'frma' atom of 'mp4a', stream format is 'drms'

### ISSUE THREAD

**Issue by kiranbhakre** [owntone/owntone-server#1453]
i am seeing below msg in terminal 

scan: Could not create inotify watch for /media/nasmedia/Songs/Apple Music/Siddharth-Suhas: No space left on device
ffmpeg: ignoring 'frma' atom of 'mp4a', stream format is 'drms'
ffmpeg: stream 0, timescale not set

**Comment by ejurgensen** [comment]
> scan: Could not create inotify watch for /media/nasmedia/Songs/Apple Music/Siddharth-Suhas: No space left on device

This error comes from inotify, so you can try googling "No space left on device" + inotify + your platform. The error is not about lack of space, but concerns a limit to how many files can be watched, which is platform dependent.

> ffmpeg: ignoring 'frma' atom of 'mp4a', stream format is 'drms'

Could be some files which have drm?

> ffmpeg: stream 0, timescale not set

Just a warning, I don't think it has any effect
