### ISSUE TITLE
Library Scanned but no music in Web or iTunes (Music.app)

### ISSUE THREAD

**Issue by SteffanCline** [owntone/owntone-server#1462]
On Ubuntu 22, I downloaded the latest version of OwnTone via git pull (28.3 per the log), compiled and installed per the directions exactly with no errors. When I look in the web admin, there is nothing listed under the music tab. Under the files tab, I can see the filesystem just fine. In Apple Music.app (formerly iTunes) I can see my server but there's no music listed under there.

I checked the log file and it shows that it scanned my library without any issues. I can see the client connect and disconnect, just no results.

Suggestions of what to check? 

I have attached a debug log for your review.
[owntone.log](https://github.com/owntone/owntone-server/files/8596526/owntone.log)

**Comment by ejurgensen** [comment]
I had a look at the log, but I can't figure out the cause. As you say, it looks like the files are found alright, but when the clients ask for song lists it is just "Done with song list, 0 songs". Can you send me your `/var/cache/owntone/songs3.db`? Maybe I can then see what the issue is. My email is espenjurgensen@gmail.com.

**Comment by SteffanCline** [comment]
FWIW, I had daapd installed earlier in the day and that worked fine but I removed all the components before building and installing your version. I just sent you the db via gmail.

**Comment by ejurgensen** [comment]
Got the db. The problem is that all your music is registered as audiobooks. You should check how `audiobooks` is set in your config file.

**Comment by SteffanCline** [comment]
I only have the one directory for music. Should I create dummy directories or just set them to ‘’ or null?

**Comment by ejurgensen** [comment]
The default should be fine. Or you can comment out the line.
