### ISSUE TITLE
Spotify integration broken (libspotify sunset)

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1474]
Seems Spotify has [now sunset libspotify](https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/), which has broken both the new and old Spotify integration. With the new integration the error message in the log is: `Error opening source: Premium account required`.

I haven't checked whether librespot works, but if it does I expect the new integration can be made to work again. I'll look into that asap.

**Comment by ejurgensen** [comment]
librespot works, so I could restore the Spotify integration with the above fix

**Comment by chme** [comment]
Awesome, that you found a fix so quickly! I guess the whole libspotify integration can now be removed ...

**Comment by ejurgensen** [comment]
Thanks. It was nice to have the earlier work of removing that dependency pay off. Interesting that librespot seems to be whitelisted. Strength in numbers, I guess. I agree that the libspotify integration can be removed. I'll do that and then I suppose a new release would be good. If there is anything you want in before that let me know.

**Comment by chme** [comment]
Regarding the whitelisting of librespot, I remembered that there were discussions some years ago and that librespot did have contact with Spotify and got some informal approval. Here is the link to the PR with a bit of info about this: https://github.com/plietar/librespot/pull/218

**Comment by ejurgensen** [comment]
Great find! I'll adjust the fix so that the info string follows that format.

**Comment by alex-voigt** [comment]
could you please provide a new release for that?

**Comment by shanedabes** [comment]
I'm a little bit confused on what needs to be done now? Will owntone have spotify support again in the next release or will we have to pair it wit something like spocon?

**Comment by ejurgensen** [comment]
Yes, it will be in the next release, which is coming very shortly. You don't need anything else. It's already available if you use my RPi debian package.

**Comment by ejurgensen** [comment]
It's released now (28.4)
