### ISSUE TITLE
Unexpected behaviour when "consume" and "repeat" are both enabled

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1478]
I was quite confused for a while when "owntoning"on my main music driver buster raspberry:

I start a new smart playlist; Queue gets filled, all seems great.
Playing starts. After the track, log says 
"raop: could not fetch item
airplay: could not fetch item"
Playing the first song repeats, but the "now playing"-page of the Webui gets not updated.
the played song disappears from the queue, although it is still played. After that, play pauses, but can get restartet for the next item - and so on.

Would'nt it be great if "consume" disables "repeat" autmagically and vice versa? I was not aware of my enabling "repeat" - and was very confused!!

**Comment by chme** [comment]
Thanks for reporting this bug! It should now be fixed.
