### ISSUE TITLE
how to work with bluez-alsa?

### ISSUE THREAD

**Issue by VergilGao** [owntone/owntone-server#1480]
I have successfully connected to the bluetooth speaker with bluez-alsa, but I don't know what to do next to make owntone and bluez-alsa work together.

**Comment by ejurgensen** [comment]
Have you seen [this](https://owntone.github.io/owntone-server/advanced/outputs-pulse/)? Not sure I can add much to that, since I don't use Bluetooth myself. So will close the issue.

**Comment by VergilGao** [comment]
As bluez-alsa is integrated in more linux distributions, I think it is necessary to provide a documentation for configuring bluetooth speakers using bluez-alsa.

im running owntone server with the docker container that building by myself. i think i can make it working with bluez-alsa with a little help.
after a series tests, i got this log output:
```
[2022-05-24 21:57:57] [  LOG]   laudio: Couldn't get BlueALSA PCM list: Rejected send message, 1 matched rules; type="method_call", sender=":1.88" (uid=99 pid=25144 comm="/usr/sbin/owntone -f -P /owntone-pidfolder/owntone") interface="org.bluealsa.Manager1" member="GetPCMs" error name="(unset)" requested_reply="0" destination="org.bluealsa" (uid=0 pid=3543 comm="/usr/bin/bluealsa ")[2022-05-24 21:57:57] [  LOG]   laudio: Failed to attach mixer 'bluealsa': No such device
[2022-05-24 21:57:57] [  LOG]   laudio: Could not open mixer 'bluealsa' ('小爱音箱-8317 - A2DP')
```
I searched the source code of `alsa.c`, but did not find the method call that returns the first log
But I found the method calls for the second log and the third log in `alsa.c` line 1169 ~ 1174
```
ret = mixer_open(&as->mixer, as->mixer_device_name, as->mixer_name);
if (ret < 0)
{
  DPRINTF(E_LOG, L_LAUDIO, "Could not open mixer '%s' ('%s')\n", as->mixer_device_name, as->mixer_name);
  goto error_free_session;
}
```
After checking the instructions of alsa-lib, I think I should be able to solve the problems listed in the last two logs
Do you have any idea about the first log? For example, which line of source code is this log returned? It seems that the content of this log output should be the return value of `snd_strerror` call.

Once I locate all the calls that return errors, I can set up a small test environment myself to test according to the instructions of alsa-lib.

**Comment by ejurgensen** [comment]
Some log messages are passed through directly from ALSA, I think the first is such an error. So you can try googling it. I would think that the call that triggers it is `snd_mixer_attach`.

**Comment by VergilGao** [comment]
got it!
i wrote a minimized test program:
```
#include <alsa/asoundlib.h>

int main(int argc, char **argv)
{
    if(argc <= 1)
    {
        printf("need an argument");
        return -1;
    }

    snd_mixer_t *mixer_hdl;
    char* mixer_device_name = argv[1];

    int ret;

    ret = snd_mixer_open(&mixer_hdl, 0);

    if(ret < 0)
    {
        printf("Failed to open mixer: %s\n", snd_strerror(ret));
        return -1;
    }

    ret = snd_mixer_attach(mixer_hdl, mixer_device_name);

    if (ret < 0)
    {
        printf("Failed to attach mixer '%s': %s\n", mixer_device_name, snd_strerror(ret));
        goto out_close;
    }

    return 0;

out_close:
    snd_mixer_close(mixer_hdl);

    return -1;
}
```
it doesn't throw errors when I run it as root
```
/ # gosu owntone ./bluealsa-test bluealsa:3C:CD:57:38:87:2C
ALSA lib ../../../src/asound/bluealsa-ctl.c:972:(_snd_ctl_bluealsa_open) Couldn't get BlueALSA PCM list: Rejected send message, 1 matched rules; type="method_call", sender=":1.156" (uid=99 pid=11414 comm="./bluealsa-test bluealsa:3C:CD:57:38:87:2C ") interface="org.bluealsa.Manager1" member="GetPCMs" error name="(unset)" requested_reply="0" destination="org.bluealsa" (uid=0 pid=3543 comm="/usr/bin/bluealsa ")
Failed to attach mixer 'bluealsa:3C:CD:57:38:87:2C': No such device
```
So it should be a permissions issue
Let me see what permissions are missing

**Comment by VergilGao** [comment]
everything works fine！
I will continue to observe of half a month to a month, and if everything is ok, I will write a document using bluez-alsa based on my experience

**Comment by ejurgensen** [comment]
Thanks a lot for adding information about your findings!
