### ISSUE TITLE
No Apple Music Playlists at all

### ISSUE THREAD

**Issue by braunsch** [owntone/owntone-server#1482]
Just getting started and already getting a bit desperate.

I managed to set up OwnTone (version 28.3) using the linuxserver.io compilation in a Docker container on my Synology NAS (DSM 7.1).
All seems to work fine except for two things: 
(1) no gapless playback - I think this is a known missing feature, and 
(2) None of my playlists from Apple Music is coming over. 

On my Mac (MacOS 10.15.7 "Catalina", Apple Music version 1.0.6.10), there is no XML file with metadata anymore - all I have is my /iTunes Media folder and the "Music Library.musiclibrary" file (package) - both of which I just copied from my Mac to my NAS.  

Apparently, I was able to build my OwnTone library correctly - it will show up as an option in Apple Music and I an connect my iOS Remote app to it and use it - but none of my playlists is showing up. I see every music file - but in the Playlists tab, the count is 0 (even an "Update Library" from the web interface does not help). 

There is not even a single mention of playlists in my log file. 

What has gone wrong, or is that a known bug so that I just have to be patient? 

[owntone.log.txt](https://github.com/owntone/owntone-server/files/8790223/owntone.log.txt)
[owntone.conf.txt](https://github.com/owntone/owntone-server/files/8790224/owntone.conf.txt)

**Comment by ejurgensen** [comment]
> there is no XML file with metadata anymore

Yes, then there would be no source for importing playlists. Not sure how Apple Music stores playlists, but probably not a format OwnTone can read. I wouldn't call it a bug, it's more a feature that has never been added. Someone with a Mac would have to do that, I suppose.

If Apple Music supports exporting to m3u then that might be an option.

**Comment by Porco-Rosso** [comment]
@braunsch 
Have you tried on Music.app `File->Export->Export Library...' That seems to give me an xml. I use it to generate .m3u files for my playlists. 
https://github.com/Porco-Rosso/iTunes-m3u8-Playlist-Syncer
Unfortunately it means that I need to do this manually every time I add new content to my music library. I also don't use any apple music cloud features, it's all mp3 files.

**Comment by braunsch** [comment]
Thank you guys - 

> Have you tried on Music.app `File->Export->Export Library...' That seems to give me an xml.

I tried this - and placed the resulting XML file on my NAS drive, right next to the Apple Music library - and indeed, a re-scan of the library now got me all my playlists. Thank you for the hint!

I guess I will have to do this every time when I make significant changes to my library - a manual process :-( 

On the other hand, I find it hard to believe that OwnTone cannot read the standard Apple Music library file: After all, it has been four years now that Apple switched from the XML format to the .musiclibrary database (which contains the playlists) - and anyone who started collecting music on the Mac in the past four years will never even had an XML file. 

Now - how to put this in as a feature request? 

Thanks guys!
