### ISSUE TITLE
OwnTone prevents server from going to sleep

### ISSUE THREAD

**Issue by braunsch** [owntone/owntone-server#1486]
Running OwnTone in a Docker container on a Synology NAS. 

When running the system with Docker, and with all my docker containers stopped, the system will go to sleep after the designated time. 

The moment I start the container with OwnTone, the system will not go to sleep anymore

This is unexpected behavior because there is no need to read or write anything to any disk when nobody wants to play any iTunes media.

**Comment by ejurgensen** [comment]
Unless you have podcasts (which are refreshed periodically) or have logging set to a high level, then I don't see what would make OwnTone read/write while idle. I agree it shouldn't.

To find the culprit, first check that it isn't the logging itself. If you can rule that out, set the logging to "debug", or maybe even to "spam", and then let OwnTone idle. Then check the log to see what OwnTone has been doing. I think all reads/writes to the db will be logged, as well as any filesystem inotify events.

Btw a work-around might be to create a RAM-disk (if the system doesn't have one already) and store the database there.
