### ISSUE TITLE
Link to README_JSON_API.md is broken

### ISSUE THREAD

**Issue by mfauvain** [owntone/owntone-server#1505]
Cannot acces this part of the documention. Can you help pls?

**Comment by ejurgensen** [comment]
Which link?

**Comment by mfauvain** [comment]
The one on the git.io site. and I couldn't find it anywhere else...

![220627-145849](https://user-images.githubusercontent.com/14844435/176025238-5d9cecac-2ee2-48c0-99d9-1330938e6778.jpg)

![220627-150008](https://user-images.githubusercontent.com/14844435/176025413-dd6b9f73-b3c6-4514-996e-29125ffd70c1.jpg)

**Comment by ejurgensen** [comment]
Thanks, I have fixed the link now (+ a few more that didn't seem to work)

**Comment by mfauvain** [comment]
Thank you

**Comment by ejurgensen** [comment]
Indeed, didn't get the link right. Will try again :-)

**Comment by mfauvain** [comment]
thx!
