### ISSUE TITLE
Crash when active endpoint is lost

### ISSUE THREAD

**Issue by jshep321** [owntone/owntone-server#1509]
Sometimes a crash occurs by rebooting the (shairport-sync/rpizero) endpoint while it is an active client.  

Might be an avahi bug, but likely an unhandled exception from avahi by owntone(speculation)?

-pi4 raspberry pi OS v11/bullseye
-owntone 28.4

Log:
`Jul  2 16:29:19 pi4-1 owntone[1641]: [2022-07-02 16:29:19] [  LOG]     raop: Device 'Garage' closed RTSP connection
Jul  2 16:29:20 pi4-1 avahi-daemon[1761]: Missed message org.freedesktop.Avahi.ServiceResolver::Free()
Jul  2 16:29:20 pi4-1 systemd[1]: owntone.service: Main process exited, code=killed, status=11/SEGV
Jul  2 16:29:20 pi4-1 systemd[1]: owntone.service: Failed with result 'signal'.
Jul  2 16:29:20 pi4-1 systemd[1]: owntone.service: Consumed 3min 55.624s CPU time.
Jul  2 16:29:25 pi4-1 systemd[1]: owntone.service: Scheduled restart job, restart counter is at 3.
Jul  2 16:29:25 pi4-1 systemd[1]: Stopped DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote.
Jul  2 16:29:25 pi4-1 systemd[1]: owntone.service: Consumed 3min 55.624s CPU time.
Jul  2 16:29:25 pi4-1 systemd[1]: Started DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote.
`

**Comment by ejurgensen** [comment]
Thanks for the notice, can you try to reproduce it with gdb? With gdb installed you can start owntone with something like `sudo gdb --args /usr/sbin/owntone -f`.

**Comment by jshep321** [comment]
Doesn't start.  I assume I need to install a non-standard version or compile from scratch, or...?

Reading symbols from /usr/sbin/owntone...
(No debugging symbols found in /usr/sbin/owntone)
(gdb) q

**Comment by ejurgensen** [comment]
Try installing the package owntone-dbgsym

**Comment by jshep321** [comment]
Got it! 
It is related to me manually performing a restart of avahi prior to the endpoint being lost.  This does not crash unless I restart avahi (sudo systemctl restart avahi-daemon).  I do this sometimes after a network issue and I don't see some mDNS airplay clients.

example 1 (note the top 2 disconnects before avahi restart = no crash):
![image](https://user-images.githubusercontent.com/12618683/177185105-5dbc2bae-6f2c-4d1c-9a07-e805715ff310.png)

example 2:
![image](https://user-images.githubusercontent.com/12618683/177185935-469203d9-f051-4fff-a0c4-c8c8099d9d9e.png)

**Comment by ejurgensen** [comment]
Good that you were able to catch it. Could you do it once more and then run `bt` in gdb after the crash? That will show a backtrace, so that I can see where in owntone the invalid call is made.

**Comment by jshep321** [comment]
![image](https://user-images.githubusercontent.com/12618683/177368130-6e2de480-68bf-413a-b09a-bd214707cbb1.png)

**Comment by jshep321** [comment]
Sure thing.

**Comment by ejurgensen** [comment]
I think I found the bug, and I have also tried to fix it, so hope you can test. You can download debs from here: https://github.com/owntone/owntone-apt/actions/runs/2637542509

**Comment by jshep321** [comment]
Finally tested -- confirmed fixed in my environment also.  Thanks!
