### ISSUE TITLE
[web] UI missing hover hints for repeat/shuffle/consume buttons

### ISSUE THREAD

**Issue by clach04** [owntone/owntone-server#1512]
I'm new to OwnTone and DAAP concepts so I have some confusion here, but I think I have an enhancement request.

The web UI in the player:

![image](https://user-images.githubusercontent.com/424032/177050185-c7da1980-0134-4593-8c3a-ada32dec5d49.png)

Has three icons that on first sight I could not identify. I tried hovering a mouse over them and on mobile press-holding finger.

From messing around and looking at source code I think they are in order:

1. repeat options
2. shuffle options
3. favourite/favorite? I'm not sure what "consume" is, I suspect this is something DAAP specific, hence why using that term in the code

I'm not familiar with vue so I can't offer a PR for src/components/NavbarBottom.vue to add the hover support :-(

**Comment by clach04** [comment]
https://owntone.github.io/owntone-server/json-api/#set-consume-mode

**Comment by clach04** [comment]
Is consume/consume-mode an MPD term rather than DAAP? https://www.runeaudio.com/forum/consume-mode-t53.html

>> What is the consume mode in the playback section? I mean the feature with the recycle bin / trash icon.
>
> Consume mode makes MPD remove played songs from the play-queue. It's a built-in MPD feature, and I must admit I was quite confused too about its function at the beginning...

**Comment by clach04** [comment]
https://github.com/owntone/owntone-server/blob/0bde7acce806483de143c7b81affe0d91c426cae/web-src/src/components/NavbarTop.vue#L45 appears to be using a hover class to display the drop down from the burger menu.

Might be able to do the same for repeat, shuffle, consume buttons?

**Comment by hacketiwack** [comment]
@clach04, generally speaking the web UI lacks accessibility features.
What I can do for now is to add a title explaining the button when you hover it.
Would that be enough?

**Comment by clach04** [comment]
> @clach04, generally speaking the web UI lacks accessibility features. What I can do for now is to add a title explaining the button function when you hover it. Would that be enough?

Perfect, it gives a word that someone (me ;-)) can then google to do look it up. Thanks!
