### ISSUE TITLE
files that start with either underscore '_' or dot '.' are ignored by file scanner

### ISSUE THREAD

**Issue by clach04** [owntone/owntone-server#1513]
Please try to provide the following:

- steps to reproduce and/or logging of the error

1. scan media, have a file like `_my song.mp3` and `. also my song.mp3`
2. open web interface
3. search for "hix" - no hits
4. open directory browser and use web browser search for media, e.g.  "song". Will not see the above samples

- version of owntone

    commit 0bde7acce806483de143c7b81affe0d91c426cae (HEAD -> master, origin/master, origin/HEAD)
    Author: ejurgensen <espenjurgensen@gmail.com>
    Date:   Tue Jun 28 20:46:20 2022 +0200

        [smartpl] Fix parsing of CRLF and "NOT (" (closes #1502)

- platform

    Armbian focal (21.08.6) armv7l

Steps to reproduce will greatly improve the chance of getting it fixed. If it is not possible then set the log level to debug (in /etc/owntone.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

Happy to provide any other details.

[Beet ](https://github.com/beetbox/beets/) finds this file fine when it scans.

Appear caused by https://github.com/owntone/owntone-server/blob/master/src/library/filescanner.c#L360.

Short term solution, document this and rename files.

Long term; Ignoring files that start with `._` would make sense, those are almost always MacOS meta data files.

**Comment by clach04** [comment]
In case it's useful:

    (py38venv) :~/music/eyeD3$ eyeD3 /fullpath/_Baby35aa__Praga_Khan_-_Injected_With_A_Poison__Hixxy_Remix_.mp3
    /fullpath/_Baby35aa__Praga_Khan_-_Injected_With_A_Poison__Hixxy_Remix_.mp3                                              [ 6.91 MB ]
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Time: 05:02     MPEG1, Layer III        [ 192 kb/s @ 44100 Hz - Stereo ]
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------
    ID3 v2.3:
    title: Injected With A Poison (Hixxy Remix) [www.muzika.in]
    artist: (Baby35aa) Praga Khan
    album:  muzika.in
    track:          genre: Hardcore (id 129)
    ------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by clach04** [comment]
Possible expected behavior based on https://forums.raspberrypi.com/viewtopic.php?t=49928&start=575#p642275 ?

Also missing other files that start with underscore.

**Comment by clach04** [comment]
Can't confirm this in the docs :-( https://owntone.github.io/owntone-server/library/

**Comment by clach04** [comment]
Confirmed in code; https://github.com/owntone/owntone-server/blob/master/src/library/filescanner.c#L360

files that start with a period/dot/fullstop/full-stop '.' or underscore/under-score/underbar/under-bar '_' are ignored by the scanner with no config option. Files need to be renamed to be picked up by OwnTone.

So looks like a doc issue.

**Comment by clach04** [comment]
possible notes for docs:

    find /musc_dir/ -name \.\*
    find /musc_dir/ -name \_\*

There are some metadata files that it looks like MacOS creates that start with '._'. So possibly a enhancement could be made to code. unclear from original code change https://github.com/owntone/owntone-server/commit/766177bf10a7a603d3cf019043ca549d01014b25 what makes files that start with '_' or '.' hidden (other than Unix file system convention for '.').

**Comment by clach04** [comment]
Recommend ignoring files that that start with '.\_' as those would appear to be mac metadata files. I can't find any real word examples where only starting with a dot and only starting with underscore are not real files.

**Comment by ejurgensen** [comment]
Not sure what the gist of this is? Yes, those files are ignored, and I think they should be.

**Comment by clach04** [comment]
Thanks for taking the time to review @ejurgensen 

1. The behavior is not obvious - I've posted #1514 to try and help with that
2. I don't understand why files that start with an underscore are ignored. Can you help me understand why they are ignored? I'm guessing some platform uses that for hidden files? I've only ever seen files beginning with a dot considered hidden.

Thanks again for this awesome server!

**Comment by ejurgensen** [comment]
No problem, glad to hear you like it. I think you found the explanation for this behavior yourself ref the [link](https://forums.raspberrypi.com/viewtopic.php?t=49928&start=575#p642275) you posted above.

I would consider having actual media files starting with _/. as a bit of an exotic corner case, and I'm not sure I want the docs to cover all those. As I recall, the log does say that the files are not scanned, right?

**Comment by clach04** [comment]
> No problem, glad to hear you like it. I think you found the explanation for this behavior yourself ref the [link](https://forums.raspberrypi.com/viewtopic.php?t=49928&start=575#p642275) you posted above.
> 

I found the code reason ;-)

> I would consider having actual media files starting with _/. as a bit of an exotic corner case, and I'm not sure I want the docs to cover all those. As I recall, the log does say that the files are not scanned, right?

I agree that beginning with a '.' feels like a corner case. \_ was surprising to me (so we may have to agree to disagree), hence suggesting the doc change. I just checked the log file `/var/log/owntone.log` but didn't see any messages about skipped files, extract:

    [2022-07-02 16:29:08] [  LOG]     scan: Scanned 200 files...
    [2022-07-02 16:29:14] [  LOG]     scan: Scanned 400 files...
    [2022-07-02 16:29:17] [  LOG]     scan: Scanned 600 files...
    [2022-07-02 16:29:21] [  LOG]     scan: Scanned 800 files...
    [2022-07-02 16:29:24] [  LOG]     scan: Scanned 1000 files...
    [2022-07-02 16:29:27] [  LOG]     scan: Scanned 1200 files...
    [2022-07-02 16:29:31] [  LOG]     scan: Scanned 1400 files...
    [2022-07-02 16:29:35] [  LOG]     scan: Scanned 1600 files...
    [2022-07-02 16:29:38] [  LOG]     scan: Scanned 1800 files...
    [2022-07-02 16:29:41] [  LOG]     scan: Scanned 2000 files...
    [2022-07-02 16:29:46] [  LOG]     scan: Scanned 2200 files...
    [2022-07-02 16:29:48] [  LOG]     scan: Scanned 2400 files...
    [2022-07-02 16:29:51] [  LOG]     scan: Scanned 2600 files...
    [2022-07-02 16:29:54] [  LOG]     scan: Scanned 2800 files...
    [2022-07-02 16:29:58] [  LOG]     scan: Scanned 3000 files...
    [2022-07-02 16:30:02] [  LOG]     scan: Scanned 3200 files...
    [2022-07-02 16:30:17] [  LOG]     scan: Scanned 3400 files...
    [2022-07-02 16:30:23] [  LOG]     scan: Scanned 3600 files...
    [2022-07-02 16:30:27] [  LOG]     scan: Scanned 3800 files...
    [2022-07-02 16:30:30] [  LOG]     scan: Scanned 4000 files...
    [2022-07-02 16:30:34] [  LOG]     scan: Scanned 4200 files...
    [2022-07-02 16:30:40] [  LOG]     scan: Scanned 4400 files...
    [2022-07-02 16:30:45] [  LOG]     scan: Scanned 4600 files...

there were some sanity check messages relating to play list entries that folloe, but that was the only output for audio file scanning.

I'm not sure if I'd want to see file skipped messages in the log. I didn't think of checking until you suggested it.

**Comment by ejurgensen** [comment]
Ok, I have added info to the docs about . and _ being ignored, but kept it short.
