### ISSUE TITLE
Airplay device on different network / owntone listening on single IP

### ISSUE THREAD

**Issue by spbkaizo** [owntone/owntone-server#1519]
**_(I could well be doing it wrong, so please let me know if so and I'll apologise!)_**

When owntone is running on a machine which has two interfaces, connected to two different networks, and is configured to listen on only one of them, remote devices on the network without the listener fail to connect.

E.g.
10.0.0.0/24
10.10.10.0/24

Host with owntone has an IP in both networks.
Owntone is configured to listen on only 10.0.0.xx

Devices on the 10.10.10.0/24 network will attempt to connect back to the server on it's 10.10.10.xx address.

There is an avahi/mdns repeater running to the 10.10.10.0 network.  

Suggest OwnTone should only be sending messages regarding it's configured listen address to multicast.

**Comment by ejurgensen** [comment]
Yes, currently (for Avahi) OwnTone publishes services with AVAHI_IF_UNSPEC even if a bind_address has been configured. Looks like it would be a small change [here](https://github.com/owntone/owntone-server/blob/master/src/mdns_avahi.c#L849) to change that. If I make a branch with such a change, can you then test it?

**Comment by ejurgensen** [comment]
Sounds good. You can try the above if you switch to the branch called `avahi_use_bind_address`. You can verify that you running this modified version by looking for a message in the log that says "Using network interface [name] (index [number])". The message will only appear with debug log level, and only if you have set a valid bind_address in the config.

**Comment by spbkaizo** [comment]
Can confirm with this change that the MDNS messages appear correctly on the network.  Strangely though, I was struggling to connect back from one other network (there are actually 3 networks in the real implementation).  I suspect this is due to firewall issues on that network rather than owntone itself, but figured I should declare it.

In summary I'm confident it works, but for certainty there's some more debugging to be done on my side.

**Comment by ejurgensen** [comment]
Thanks for testing, I have added the change to master now
