### ISSUE TITLE
Smart Playlist parse error

### ISSUE THREAD

**Issue by jptrsn** [owntone/owntone-server#1521]
I'm currently running owntone 28.4 in docker, and have run into an odd bug with a smart playlist that I cannot understand. It's not related to the other bug I filed (which turned out to be line ending related).

Steps to reproduce:
Create a smart playlist file with the following contents:
```
"Smart Shuffle" {
  data_kind is file
  and media_kind is music
  and not genre is "Folk" 
  and not genre is "World" 
  and not genre includes "Holiday" 
  and not genre is "Children" 
  and not genre is "Speech" 
  and not genre is "Humor" 
  and not genre is "Jazz" 
  and not genre is "Classical"
  and (
        (rating > 90 and
          (
            (play_count = 0)
            or (play_count < 10 and time_played before 3 days ago and time_skipped before 5 days ago)
            or (play_count > 9 and play_count < 20 and time_played before 13 days ago and time_skipped before 15 days ago)
            or (play_count > 19 and play_count < 30 and time_played before 18 days ago and time_skipped before 20 days ago)
            or (play_count > 29 and time_played before 20 days ago and time_skipped before 25 days ago)
          )
        )
      or
      (rating <= 90 and rating > 80 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 8 days ago and time_skipped before 10 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 15 days ago and time_skipped before 17 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 21 days ago and time_skipped before 23 days ago)
          or (play_count > 29 and time_played before 30 days ago and time_skipped before 35 days ago)
        )
      )
    or
      (rating <= 80 and rating > 70 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 13 days ago and time_skipped before 15 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 18 days ago and time_skipped before 20 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 23 days ago and time_skipped before 25 days ago)
          or (play_count > 29 and time_played before 45 days ago and time_skipped before 50 days ago)
        )
      )
    or
      (rating <= 70 and rating > 60 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 15 days ago and time_skipped before 17 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 21 days ago and time_skipped before 23 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 25 days ago and time_skipped before 27 days ago)
          or (play_count > 29 and time_played before 60 days ago and time_skipped before 65 days ago)
        )
      )
    or 
      (rating <= 60 and rating > 50 and 
        (play_count = 0)
        or (play_count < 10 and time_played before 21 days ago and time_skipped before 25 days ago)
        or (play_count > 9 and play_count < 20 and time_played before 28 days ago)
      )  
    )
}
```
In logs, after saving it, I can see that the playlist has been parsed and added to owntone. However, if I modify the final logic line exclude by `time_skipped` as well, the parsing then fails.

Add the following to the final line: ` and time_skipped before 32 days` so that it looks like this:
```
"Smart Shuffle" {
  data_kind is file
  and media_kind is music
  and not genre is "Folk" 
  and not genre is "World" 
  and not genre includes "Holiday" 
  and not genre is "Children" 
  and not genre is "Speech" 
  and not genre is "Humor" 
  and not genre is "Jazz" 
  and not genre is "Classical"
  and (
        (rating > 90 and
          (
            (play_count = 0)
            or (play_count < 10 and time_played before 3 days ago and time_skipped before 5 days ago)
            or (play_count > 9 and play_count < 20 and time_played before 13 days ago and time_skipped before 15 days ago)
            or (play_count > 19 and play_count < 30 and time_played before 18 days ago and time_skipped before 20 days ago)
            or (play_count > 29 and time_played before 20 days ago and time_skipped before 25 days ago)
          )
        )
      or
      (rating <= 90 and rating > 80 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 8 days ago and time_skipped before 10 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 15 days ago and time_skipped before 17 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 21 days ago and time_skipped before 23 days ago)
          or (play_count > 29 and time_played before 30 days ago and time_skipped before 35 days ago)
        )
      )
    or
      (rating <= 80 and rating > 70 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 13 days ago and time_skipped before 15 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 18 days ago and time_skipped before 20 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 23 days ago and time_skipped before 25 days ago)
          or (play_count > 29 and time_played before 45 days ago and time_skipped before 50 days ago)
        )
      )
    or
      (rating <= 70 and rating > 60 and
        (
          (play_count = 0)
          or (play_count < 10 and time_played before 15 days ago and time_skipped before 17 days ago)
          or (play_count > 9 and play_count < 20 and time_played before 21 days ago and time_skipped before 23 days ago)
          or (play_count > 19 and play_count < 30 and time_played before 25 days ago and time_skipped before 27 days ago)
          or (play_count > 29 and time_played before 60 days ago and time_skipped before 65 days ago)
        )
      )
    or 
      (rating <= 60 and rating > 50 and 
        (play_count = 0)
        or (play_count < 10 and time_played before 21 days ago and time_skipped before 25 days ago)
        or (play_count > 9 and play_count < 20 and time_played before 28 days ago and time_skipped before 32 days ago)
      )  
    )
}
```

Parsing then fails.

**Comment by ejurgensen** [comment]
Thanks for reporting. I got around to testing this, and it looks like the parsing fails because of the smart playlist size. Not sure if it is something I should change tbh.

**Comment by jptrsn** [comment]
I'm really disappointed to hear that, as I've been using some form of this algorithm to shuffle my music since 2004. However, when I first created it using the iTunes smart playlist interface, with one smart playlist for each rating, then made a superset by including all songs on each of the rating playlists via the folder structure. Is there a technical reason for the length limit, and is it character based or line based? For example, is it because the playlist needs to fit within a buffer of a given size?

Here's what it looks like in the iTunes UI:

I created one main playlist that excludes any music genres I'm not interested in. That correlates to the section of my smart playlist that excludes by file type, media kind, and genre.

Each individual playlist queries the main playlist, but considers rating, play count, last played and last skipped like this:
![image](https://user-images.githubusercontent.com/5185267/183125900-983209b0-65a1-4621-b888-8d5e12a4ec80.png)

Then the shuffle just selects everything from the folder containing all the feeder playlists:
![image](https://user-images.githubusercontent.com/5185267/183125956-16796661-88a4-4866-a831-e2b5fc504400.png)

Any suggestions for how to solve for my needs? Unfortunately, importing smart playlists from iTunes is less than ideal, since it's not performant at scale, and I'd like to be able to do it via query.

Essentially, I need to be able to set up logic where it filters based on the song rating, how many times I've listened to it, when I last heard it, and when I last skipped it. This makes sure that I can iterate through my whole collection. I'm not sure how else I could implement this logic without a large smart playlist file that includes all the logic I need. It would actually be much cleaner to create the conditions using a loop, kind of like this pseudo-code:
```
for (let rateIterator = 100, rating < 0, rating -= 10) {
  const playedDaysAgo = 100 - rateIterator;
  const skippedDaysAgo = 115 - rateIterator;
  include where rating <= rateIterator and rating > rateIterator and last_played before playedDaysAgo days ago and last_skipped before skippedDaysAgo days ago
}
```

**Comment by ejurgensen** [comment]
> Is there a technical reason for the length limit, and is it character based or line based? For example, is it because the playlist needs to fit within a buffer of a given size?

The parsing result is written to a buffer that has a fixed size of 4096 bytes. It is defined [here](https://github.com/owntone/owntone-server/blob/master/src/parsers/smartpl_parser.y#L203), so you can change it if you want to make your own build. The reason it's a fixed size buffer is that it is easier to work with in C, and the reason it isn't higher is that I didn't want to have issues on platforms with limited stack memory. After googling the subject I think I have been a bit too careful. so I think I will raise it to 16k.

**Comment by ejurgensen** [comment]
I have increased the size limit now. Just to 8k, however.

**Comment by jptrsn** [comment]
Thanks, that should be more than enough space!
