### ISSUE TITLE
Cannot build on Ubuntu 20.04 LTS -  Unable to link function av_init_packet

### ISSUE THREAD

**Issue by edd07** [owntone/owntone-server#1522]
Please try to provide the following:

- steps to reproduce and/or logging of the error

Running the following command (after installing all dependencies as shown in the Installation documentation)

```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user
```

Results in:

```
checking for av_init_packet... no
configure: error: Unable to link function av_init_packet
```

- version of owntone: 28.4

- platform: Ubuntu 20.04 LTS (ffmpeg version: 7:4.2.7-0ubuntu0.1)

**Comment by ejurgensen** [comment]
Looks like you are missing libavutil-dev. Check the docs for a complete list of the dependencies.

**Comment by edd07** [comment]
No, I have installed it, the version installed is the one specified in the issue body

```
sudo apt install libavutil-dev
...
libavutil-dev is already the newest version (7:4.2.7-0ubuntu0.1).
```

**Comment by ejurgensen** [comment]
Ok, not sure what the issue then is. It doesn't look like a general issue, OwnTone builds have been tested many times on that platform.
