### ISSUE TITLE
[Container] Official docker image

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1524]
Dear All,
There are several existing docker images existing for OwnTone.
I was, however, wondering if it wouldn't be an idea to have an official docker image.
Reason behind would be to propose an official version to the end users.
Is that a silly and useless initiative?

**Comment by ejurgensen** [comment]
Sounds fine to me, but it requires an active maintainer. Would you be up for that? I'm not sure if some of the earlier contributors on this are still around.

**Comment by hacketiwack** [comment]
Thanks for the speedy reply. I could do that for sure.
1. You mention there were contributors already. Does it mean that there is already something that's been done?
2. Moreover, do you think it would be worth having a separate repository for that?

**Comment by ejurgensen** [comment]
> You mention there were contributors already. Does it mean that there is already something that's been done?

No, I was just referring to the people who have made Docker images previously.

> Moreover, do you think it would be worth having a separate repository for that?

Sure, we could add that. I suppose it would be parallel to https://github.com/owntone/owntone-apt which is for Debian packages.

**Comment by ejurgensen** [comment]
Closing this, I suppose you decided not to proceed with this
