### ISSUE TITLE
spew of "No spotify refresh token found" when not using Spotify

### ISSUE THREAD

**Issue by ohmantics** [owntone/owntone-server#1526]
If I've never configured Spotify, I get a constant spew of "No spotify refresh token found" in the log. Seems like there's too much going on when no authorization has been setup. Ideally, it would never hit their server in this case, which gives them telemetry of owntone installs.

Yes, I get that I can disable it at configure time. I'd rather leave it enabled in case some day I decided to try Spotify.

**Comment by ejurgensen** [comment]
> Ideally, it would never hit their server in this case, which gives them telemetry of owntone installs.

Their servers are not being hit, the message just means that no token was found in OwnTone's own db. Of course, the log shouldn't be full of these messages, not sure why that might be. Can you share an outtake of the log?

**Comment by ejurgensen** [comment]
Closing, no feedback
