### ISSUE TITLE
FreeBSD install script now working

### ISSUE THREAD

**Issue by GHTho** [owntone/owntone-server#1528]
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
Should the script create /root/owntone_build and use it for building? [Y/n] y
Should the script build owntone? [y/N] y
fatal: destination path 'owntone-server' already exists and is not an empty directory.
gmake: *** No rule to make target 'clean'.  Stop.
autoreconf2.71: export WARNINGS=
autoreconf2.71: Entering directory '.'
autoreconf2.71: configure.ac: not using Gettext
autoreconf2.71: running: aclocal -I m4
ld-elf.so.1: /usr/local/lib/perl5/5.32/mach/CORE/libperl.so.5.32: Undefined symbol "strerror_l@FBSD_1.6"
aclocal: error: /usr/local/bin/autom4te2.71 failed with exit status: 1
autoreconf2.71: error: aclocal failed with exit status: 1
ld-elf.so.1: /usr/local/lib/perl5/5.32/mach/CORE/libperl.so.5.32: Undefined symbol "strerror_l@FBSD_1.6"
./freebsd_install.sh: ./configure: not found

Installing this in TrueNAS 12.0 iocage

**Comment by ejurgensen** [comment]
This error looks to me like there is something wrong on the target system which isn't related to OwnTone. Your system doesn't seem to be able to execute `aclocal` which is part of the build preparation. I can't say why that might be.

**Comment by GHTho** [comment]
Sounds right; I was just letting the person that wrote the FreeBSD install script that it's not working.  I installed the GNU autotools pkg to see if that would help, but no joy.  I'm not a programmer; wish I could help

**Comment by ejurgensen** [comment]
My feedback was that the reason for the failure was something local on your machine. I think the script is working, in fact I just tested it in a TrueNAS jail, and it worked fine. 

You mention you installed autotools manually, perhaps that created a conflict. I didn't do that. I suggest you try creating a new jail and then just run the script, saying yes to the various questions.

**Comment by GHTho** [comment]
Found the problem!  I was on TrueNAS Stable 12.x; moved to 13.x & that fixed it
