### ISSUE TITLE
Does not support the "Music" app on iPad?

### ISSUE THREAD

**Issue by HubKing** [owntone/owntone-server#1530]
This is confusing. Isn't the "Music" app a DAAP client? [Wikipedia says so](https://en.wikipedia.org/wiki/Digital_Audio_Access_Protocol#DAAP_clients). But the OwnTone server does not appear on the Music app. If I run iTunes and share a library (the Music app and the iTunes both asked for my Apple ID), it appears on the Music App. The OwnTone server seems to be working, because in the iTunes, I can click the "Music" drop-down box and choose the OwnTone server and play a song on the server.

Do I need to configure something, or is the Music app not supported? If it is the later case, is it temporary (work in progress), or is it not possible for ever because maybe Apple blocked it (refused to connect unless it is the genuine iTunes app)?

If the Music app is not supported, is there any other option to play the music on an iPad? I have searched the App Store for daap, and there was only one app named "Simple Daap Client", but it seemed an old, abandoned app that could not connect to the OwnTone server (it discovered the server, but showed empty list).

**Comment by ejurgensen** [comment]
To my knowledge, the Music app on iOS is not a DAAP client. It uses Apple Home Sharing, which hasn't been cracked. So the only way to listen on iOS is via MP3 streaming, which can be done via the web UI, via an app like VLC or possibly via some MPD clients. See [this info](https://owntone.github.io/owntone-server/outputs/streaming/).

**Comment by Porco-Rosso** [comment]
@HubKing You might want to try [https://www.rigelian.net](Rigelian) as an iOS client. I can't vouch for it since I don't have an iOS client at the moment, but it looks like a well polished MPD client.
