### ISSUE TITLE
Owntone is not able to load it's SQLite extension.

### ISSUE THREAD

**Issue by utoni** [owntone/owntone-server#1532]
```shell
[2022-08-24 12:17:53] [  LOG]       db: Configured to use database file '/tmp/songs3.db'
[2022-08-24 12:17:53] [  LOG]       db: Could not load SQLite extension: /usr/local/lib/owntone/owntone-sqlext.so.so: cannot open shared object file: No such file or directory
[2022-08-24 12:17:53] [FATAL]       db: Could not open database
[2022-08-24 12:17:53] [FATAL]     main: Database init failed
```

Using the master branch on Debian-11.4-amd64 and configured with: `./configure --enable-chromecast --enable-preferairplay2 --with-pulseaudio --with-libwebsockets --with-avahi`

I was reading the documentation of `sqlite3_load_extension()` and it states that will only search for other library suffixes iff the given path does not lead to a zFile;
```doc
If the file cannot be loaded directly,
attempts are made to load with various operating-system specific extensions added.
So for example, if "samplelib" cannot be loaded,
then names like "samplelib.so" or "samplelib.dylib" or "samplelib.dll" might be tried also.
```
Strange, but at least changing
`ret = sqlite3_load_extension(hdl, PKGLIBDIR "/" PACKAGE_NAME "-sqlext.so", NULL, &errmsg)`
to
`ret = sqlite3_load_extension(hdl, PKGLIBDIR "/" PACKAGE_NAME "-sqlext", NULL, &errmsg)`
in
`db.c` fixed it for me.

**Comment by ejurgensen** [comment]
Thanks for an excellent report. I have tried to reproduce the error in a brand new instance of Debian 11.4, but it did not appear. You are the first user to report this error, and this part of owntone is quite old, so I'm thinking there must be a special circumstance triggering this. I can't figure out what it might be.

**Comment by utoni** [comment]
I will do further investigation on this issue asap.

**Comment by ejurgensen** [comment]
Closing this, can't be reproduced
