### ISSUE TITLE
Question: Setting ratings via iTunes or WebUI?

### ISSUE THREAD

**Issue by mknet** [owntone/owntone-server#1533]
Hello everbody,

is it possible to modify the rating of a song or an album via ITunes (using the lib) or via the WebUI?

Thanks and regards
Marcel

**Comment by mknet** [comment]
I just noticed the ratings can be updated via the JSON/REST-API. Unfortunately, the ratings are not shown in the Music app on the Mac.

**Comment by ejurgensen** [comment]
I think this might simply be because the Music app doesn't support reading/updating ratings via DAAP. It also looks like the web UI doesn't support updating ratings, but I'm unsure about that. If someone else knows better please add a note.
