### ISSUE TITLE
Maximum volume limits

### ISSUE THREAD

**Issue by andyg1001** [owntone/owntone-server#1535]
It would be very beneficial to have a tuning setting where it is possible to set the maximum volume for a particular airplay speaker.

Problem I have is that for one of my speakers 100% is deafening!  Even 50% is too loud.  It is very easy to set the volume too high, especially when the children are using it.  Therefore being able to set a scale factor - e.g. that 40% to be the maximum for the volume scale, so that moving the slider to 100% actually produces a volume of 40% on the speaker - that would be wonderful.

Many thanks!

**Comment by ejurgensen** [comment]
Guess you must have missed it, there is such a setting. My Airplay receiver is also insane at 100%. Look for max_volume in the config file. You set it something like this:

```
airplay "speakername" {
  max_volume = 3
}
```
