### ISSUE TITLE
Documentation on development setup/getting started

### ISSUE THREAD

**Issue by kunom** [owntone/owntone-server#1542]
Not being familiar with autoconf/automake and Linux development environments, I am having a hard time figuring out how get owntone-server to run in Visual Studio Code debugger.

Would it be possible to add a document `docs/development.md` that at least explains on how to configure your checkout to be able to run/debug locally and in isolation without to much runtime references to system-level places like `/usr/bin` and `/var/log`?

**Comment by ejurgensen** [comment]
I've added a draft description of how to do an isolated installation in installation.md, see the above commit/branch. I haven't tested it too much yet. Is that the sort info you were looking for?

**Comment by kunom** [comment]
That works pretty well. I didn't dare to run `make install`, that is maybe why I had some more issues with all of that.

I found two issues:
- The location of the deployed binary is wrong: ` /home/mrdev/**owntone_data**/usr/sbin/`
- In `owntone.conf`, the `directories` property is actually an array

Then some less important things, more into the direction of polishing:
- I probably would apply backtick formatting for file system paths and other identifiers.
- You could make it a bit more friendly for copy/paste by using e.g. `$HOME/owntone_data` and/or by using an intermediate environment variable for the data directory.
