### ISSUE TITLE
Raspberry pi 4 -> open media vault -> OwnTone no Sound from 3.5mm

### ISSUE THREAD

**Issue by simtcrom** [owntone/owntone-server#1550]
Hello, 

I am running OMV (6.0.44-1 (Shaitan)) on raspberry pi 4.
I installed openmediavault-owntone 6.0.5-1 and enabled it.
Went to http://IP:3689/ and played a song there. But no sound is coming via head phone connected via 3.5mm jack of Raspberry Pi 4

I confirmed that 3.5mm jack works by playing a song directly on putty session to pi by using mplayer.

Any thoughts?

**Comment by ejurgensen** [comment]
Not a lot to go on here. Don't know much about OMV, but have you checked the log? It can usually be found at `/var/log/owntone.log`
