### ISSUE TITLE
[web] List all albums/tracks by artist on search page

### ISSUE THREAD

**Issue by catsimple** [owntone/owntone-server#1551]
Is it possible to list all the albums and tracks by the artist I search on search page? It can only list the albums and tracks by the keywords in filename for now.
By the way, it seems that owntone sort the featured artist and primary artist as a single artist, which makes problem like a primary artist's album not contains any featuring tracks.

**Comment by ejurgensen** [comment]
The web UI is @chme's, but I think he is occupied with other stuff these days, so for the time being I guess the answer is no.

**Comment by hacketiwack** [comment]
@catsimple, what is your search query?
If you search with this query syntax: `query: artist is "Michel Sardou`, I think it will do what you're looking for.

**Comment by catsimple** [comment]
@hacketiwack seems that they have achieved this feature.
