### ISSUE TITLE
Added podcasts in VM instance does not persist through TrueNAS restarts

### ISSUE THREAD

**Issue by TX9G9qBxid** [owntone/owntone-server#1554]
Hej! 
As pointed out in title, podcast data does not persist when restarting TrueNAS. 

Platform: 
Version 28.5 running on VM Ubuntu Server 22.04.01 LTS. 
Server running TrueNAS Scale, latest
SMB drive mounted with audio files (incl an empty /Podcast folder) loading into Owntone. Setup via owntone.conf.

Reproduction: 
1. Adding [random] podcast (through Apple Podcast service).
2. Restart OwnTone VM = no issues (podcast data persists)
3. Restart TrueNAS; wait for OwnTone VM to boot
4. Podcast data (added, listened, new etc.) completely gone after TrueNAS restart. 
5. Audiofiles in Music persists through TrueNAS restarts

Unsure where podcast data is stored. If stored on mounted SMB - could issue be due to SMB loading later in sequence? 
I have not yet tried shutting down OwnTone VM manually before TrueNAS restart, then only booting OwnTone AFTER TrueNAS is up'n'running properly.

**Comment by ejurgensen** [comment]
The standard storage is /var/cache/owntone/songs3.db. The audio files are also persisted there, as well as speaker selections and some other stuff. So I think it is possible audio files are also lost during reboot, but since they are rescanned on restart you don't notice. You might notice that e.g. ratings are lost.

I can't say what you can do to fix it, since the issue seems bound to TrueNAS.

**Comment by TX9G9qBxid** [comment]
In case someone finds this post in the future, searching for a solution to the same problem as I had: 
My solution (or rather error) was to not edit the /[user]/owntone-server/owntone.conf file, but rather /etc/owntone.conf. (I know install-instructions correctly instructs to edit the /etc/owntone.conf-file. 
I mistakenly started editing the wrong .conf file leaving it not-original. That file *needs* to be original. 

Simply to a reinstall of owntone in case you cannot revert edits of the /[user]owntone-server/owntone.conf. 

Hope this helps!

**Comment by TX9G9qBxid** [comment]
Hej igen, @ejurgensen, 

Felt I wanted to open this issue again. Perhaps you'd be able to put in a bit more time to solve this - I just recently migrated from TrueNAS and installed Proxmox instead: The issue described above persists with Owntone on a Proxmox VM running Ubuntu Server 22.04 so perhaps this is due to something with regards to VMs in general? 

I'm able to consistently reproduce the issue; usually when performing a reboot/shutdown on the hypervisor itself rather than a VM reboot. 

Please do let me know if you need logs, configs etc. 
I'll be more than happy to provide! 

Thanks :)

**Comment by beaudett** [comment]
Hi @ejurgensen and @TX9G9qBxid, 
the loss of podcast subscriptions also sometimes happens on my raspbian(buster) setup after a reboot.
The audio files are located in a usb-mounted harddrive. During the boot, it can happen that the external disk is
not mounted at the time when owntone starts. In that case, it seems that the /var/cache/owntone/songs3.db file (which is on the SD-card) is largelly flushed and the podcasts are lost. 
In that case, I restore /var/cache/owntone/songs3.db from a backup by hand and the podcast are recovered. 
It seems to me that this situation has similarities with that described by @TX9G9qBxid. I feel that it is my setup which should be blamed: I should make sure the disk is mounted before starting owntone. That said, it could be useful to have the possibility to import/export opml files. 
It take this opportunity to congratulate and thank @ejurgensen for this absolutely marvelous software, which I use smoothly several hours a day.

**Comment by TX9G9qBxid** [comment]
@beaudett - what an excellent observation. At some point, while checking systemctl status, I did come across a log entry stating that my mount point was unavailable. I didn't piece that together with this until now. 

I should be possible to delay the owntone.service a minute or two, working around the issue, dont you think?!

Oh, I'll chime in on the virtual high-fives. I use Owntone all the time, both through the webinterface and through Home Assistant for waking me in the morning playing.

**Comment by TX9G9qBxid** [comment]
Hi again @ejurgensen, 
I'll add that, test and report back. 

I'm no programmer at all, but according to my personal logic, would it not make sense to figure out why the songs3.db - apparently - flushes contents? Adding an argument to the "After" section makes sense, but what happens if the (in my case) SMB is down on owntone.service startup? (I should probably test that as well, btw ... )

Stay tuned :)

**Comment by ejurgensen** [comment]
> would it not make sense to figure out why the songs3.db - apparently - flushes contents?

The reason for that would be that songs3.db is missing when Owntone starts, since the drive isn't mounted yet. So Owntone thinks it is a new install and recreates songs3.db.

> happens if the (in my case) SMB is down on owntone.service startup?

There is already a remote-fs.target dependency, so I expect OwnTone wouldn't be started.

**Comment by TX9G9qBxid** [comment]
> The reason for that would be that songs3.db is missing when Owntone starts, since the drive isn't mounted yet. So Owntone thinks it is a new install and recreates songs3.db.

Perhaps I don't fully understand, but is the file songs3.db not located on the drive on which Owntone is installed? Or is the behavoir due to the SMB drive missing, and then "forcing" Owntone to recreate the file? 

On a related note. 
I did some testing:
With the local-fs.target I was not able to provoke the flushing of the db (i.e. the podcasts data did not disappear). However denying Owntone access to the SMB (/Music-files only) the podcasts data disappeared after VM-restart. Giving Owntone access to the SMB again did not make the podcasts data reappear. 

Again, please do let me know if you want logs etc. I'll be happy to provide! 

Thanks!

**Comment by ejurgensen** [comment]
Good to hear that local-fs seems to fix the problem. Let me know if it turns up again.

> Perhaps I don't fully understand, but is the file songs3.db not located on the drive on which Owntone is installed?

I think you are the only one who can answer this - it would depend on your setup

> However denying Owntone access to the SMB (/Music-files only) the podcasts data disappeared after VM-restart

Did you add the podcasts by adding a file in the library (e.g. a file in the /Podcasts subdir?). Then it would not be there when OwnTone starts, and thus it would be removed.

**Comment by TX9G9qBxid** [comment]
> I think you are the only one who can answer this - it would depend on your setup
I have not moved the .db from its original location in /var/cache/[...] ... so by that logic it should not be able to be missing when owntone starts; since it is located on the same logical drive as owntone itself. Right? 

My /Podcasts is empty. I'm exclusively adding URL's via the webinterface. From my understanding this way of adding should not be affected even if the SMB is unavailable, correct?

**Comment by ejurgensen** [comment]
I can't really help you much more, I'm down to guessing what is going on with your setup, which isn't so fruitful
