### ISSUE TITLE
Date seems off

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1555]
I noticed that on the music tab, some albums added to Owntone had wrong dates. When I examine the files in other tools, the date is correct.

<img width="1097" alt="Screenshot 2022-12-09 at 1 27 43 PM" src="https://user-images.githubusercontent.com/63519142/206782266-ef2764bd-76d9-4188-b2f1-989649c3f722.png">

Input #0, flac, from '01-O Come All Ye Faithful.flac':
  Metadata:
    TITLE           : O Come All Ye Faithful
    ARTIST          : Bobby Darin
    ALBUM           : The 25th Day of December with Bobby Darin
    album_artist    : Bobby Darin
    comment         : Give Darin credit for choosing mostly American spirituals for this release, but he would have fallen flat on his back had he not been backed by the Bobby Scott Chorale on "Go Tell it on the Mountain," "Jehovah Hallelujah," and other rousing numbers. On th
                    : <br />&copy  Dennis MacDonald /TiVo
    GENRE           : Christmas
    COPYRIGHT       : © 1960 Atlantic Recording Corp For the United States and WEA International Inc. for the world outside of the United States. ℗ 1960 Atlantic Recording Corp For the United States and WEA International Inc. for the world outside of the United States.
    track           : 01
    disc            : 1/1
    TRACKTOTAL      : 14
    DISCTOTAL       : 01
    DATE            : 1960-10-01
  Duration: 00:02:22.31, start: 0.000000, bitrate: 580 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 600x600 [SAR 100:100 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

Owntone 28.5, Debian 11.5

I did try a full metadata rescan without change.

**Comment by whatdoineed2do** [comment]
@frankusb - i've seen this before but hadnt time to look.  PR raised that fixes this although theres some internally handling that may need reworking but won't impact your db file.  Please test - rebuild and then full meta rescan your library for server to handle the pre 1970s dates.

**Comment by frankusb** [comment]
Thanks, merged with [PR 1460](https://github.com/owntone/owntone-server/pull/1460), full meta rescan and now the dates before 1970 are working.
