### ISSUE TITLE
Owntone not detecting airplay speaker

### ISSUE THREAD

**Issue by asdkjasdfla** [owntone/owntone-server#1558]
I am using a docker container of owntone. The documentation suggests that owntone will automatically add airplay speakers. However i cannot see my airplay speaker detected. Can you please tell how can i manually enter the airplay speaker?

**Comment by ejurgensen** [comment]
You can't do that. Sounds there is an mdns issue with your Docker, so you would need to fix that.

**Comment by asdkjasdfla** [comment]
> You can't do that. Sounds there is an mdns issue with your Docker, so you would need to fix that.

Many thanks I am a novice. I need to figure out how to do this
