### ISSUE TITLE
Spotify artwork displays low resolution cover art when playback is selected from playlists

### ISSUE THREAD

**Issue by jooosh12** [owntone/owntone-server#1559]
Thanks for the amazing work on Owntone. It's easily the best solution for music playback control on a Home Assistant dashboard. 

The only issue I'm having is, artwork from Spotify will only display a low resolution version when songs/playlists are selected from the Playlists->Spotify tab in the navigation. If I select the playlist from Search->Spotify, the full resolution artwork will then display regardless of whether a single song or whole playlist is selected and played. 

I have adjusted all of the artwork settings with reboots of the system and updating the library, with no luck fixing this issue. I
 have attached screenshots displaying the issue. 

I'm not a programmer of any kind so my understanding of the issue sort of ends here. Hopefully this helps. It's not a deal breaker for me, but it would be really nice to have it fixed. 

Thanks again for the putting this tool together.  

Version 28.5
Raspberry Pi install

<img width="1086" alt="Screenshot 2022-12-21 at 7 33 51 am" src="https://user-images.githubusercontent.com/89721252/208761169-30cf6c69-ee51-4df4-830f-3333b375de17.png">
<img width="1090" alt="Screenshot 2022-12-21 at 7 33 19 am" src="https://user-images.githubusercontent.com/89721252/208761181-2c79040f-daec-4d8f-8371-ae7b0ff8bdca.png">

**Comment by ejurgensen** [comment]
Is it the RPi version of OwnTone from [here](https://forums.raspberrypi.com/viewtopic.php?t=49928) or is it a 28.5 build you made? I am wondering if the build includes [this recent fix](https://github.com/owntone/owntone-server/commit/d468fd358efcb21f9c40e9636b7d423ba31205a1). If it's the version from the RPi forums (28.5.123) it has the fix, and in that case try stopping OwnTone, delete the cache (usually in /var/cache/owntone/cache.db) and check if the issue persists. If it's plain 28.5, then you will need to upgrade to a newer github snapshot e.g., the one I linked to on the RPi forums above, or a build you make.

**Comment by jooosh12** [comment]
Thanks for the quick reply ejurgensen. 

I did follow the forum post's "How to install" section from beginning of the "owntone server (iTunes server) Sun Jul 14, 2013 9:05 pm" thread:

> **How to install**
_Add repository key_
wget -q -O - http://www.gyfgafguf.dk/raspbian/owntone.gpg | sudo gpg --dearmor --output /usr/share/keyrings/owntone-archive-keyring.gpg
_Either add repository for Buster_
sudo wget -q -O /etc/apt/sources.list.d/owntone.list http://www.gyfgafguf.dk/raspbian/owntone-buster.list
_or add repository for Bullseye_
sudo wget -q -O /etc/apt/sources.list.d/owntone.list http://www.gyfgafguf.dk/raspbian/owntone-bullseye.list
Run sudo apt update and then sudo apt install owntone
**Getting started**
_Edit the configuration file (usually /etc/owntone.conf) to suit your needs_
Start or restart the server: sudo service owntone restart
Wait for the library scan to complete. You can follow the progress with tail -f /var/log/owntone.log
If you are going to use a remote app, pair it by going to http://owntone.local:3689/ and find the settings

That is what I have currently running without any deviation. 

I did just stop the service, delete the cache file, and load owntone back up. The issue persists. Is there a way to verify exactly which version I am running? Image below of the about section from dashboard if that helps: 

<img width="1122" alt="Screenshot 2022-12-21 at 9 45 21 am" src="https://user-images.githubusercontent.com/89721252/208781046-0800a854-44ca-428c-8253-0f0d2f6a4828.png">

Apologies for the noob response. Thanks.

**Comment by ejurgensen** [comment]
You can see the exact package version with `apt show owntone`.

**Comment by jooosh12** [comment]
Thanks. Seems it is up to date...

> Version: 28.5.123.gitd468fd3-1+bullseye

**Comment by ejurgensen** [comment]
I was able to reproduce the error and find the bug. Turned out the other fix I linked to above wasn't quite right. Should be fixed now, but you won't have the fix until I have made a new release of the RPi build (and you have upgraded to it).

Thanks for reporting the error, I probably wouldn't have noticed it myself.

**Comment by jooosh12** [comment]
Thanks [ejurgensen](https://github.com/ejurgensen). I'll keep an eye out for the next build release. 
I really appreciate the support on your project here. Keep it up 😁
