### ISSUE TITLE
Installation page should state that you must be logged into github to download debs

### ISSUE THREAD

**Issue by hfuller** [owntone/owntone-server#1560]
Hi,

[This page](https://owntone.github.io/owntone-server/installation/) states "Download .deb as artifact from Github workflow". If you go to this page and you aren't logged into github, for some reason, the list of artifacts is not linked to the actual artifacts. There is no explanation given on the page for why the artifacts aren't downloadable. After a few minutes of troubleshooting with a friend, she finally figured out you have to log into github. Maybe you can add a note on the page to save some other people some time.

Merry Christmas!

**Comment by ejurgensen** [comment]
Thanks for the info, I wasn't aware of that. As you suggested, I have added the info to the installation docs.
