### ISSUE TITLE
Details for /api/library/add

### ISSUE THREAD

**Issue by kallolray** [owntone/owntone-server#1561]
Documentation (http://owntone.github.io/owntone-server/json-api/#add-an-item-to-the-library) does not have details to "Add an item to the library" via /api/library/add
I wanted to add HTTP URLs to Library

**Comment by ejurgensen** [comment]
Thanks for note, I have added to the doc now. I believe the endpoint only works for RSS urls.

**Comment by kallolray** [comment]
Thanks a lot - I can see it now. I have just installed OwnTone in Raspberry Pi 2 and it works list a charm - specially connectivity to AirPlay, Chromecast and local HDMI. Does it send Audio to Bluetooth natively? I could not see that and plan to install BlueALSA.

Have a great New Year.

**Comment by ejurgensen** [comment]
Good to hear! No, OwnTone doesn't do Bluetooth natively. I don't have experience with BlueALSA, I have only tried via Pulseaudio, which I recall was a bit cumbersome. If you didn't already see it, there is some info [on it here](https://owntone.github.io/owntone-server/advanced/outputs-pulse/).
