### ISSUE TITLE
Suggestion: Adding items to the queue

### ISSUE THREAD

**Issue by kallolray** [owntone/owntone-server#1564]
While adding tracks to the queue through "POST /api/queue/items/add", API returns count of tracks added. Will it be possible to return list of "Queue item id" that has been created - it will be helpful to use it in updating or deleting queue items later.

**Comment by kallolray** [comment]
Hello,

I am looking for getting the IDs of the queue (Queue ID) that has been by the call to “/api/queue/items/add” – not the whole Queue. We have a API (/api/queue) for getting the current Queue that already.

Thanks for your kind consideration.

Regards …. KALLOL
Kallol Ray  |  +91 80 4136 2291 | +91-9731022776
Timken India Limited  |  Hosur Road | 39 - 42, Electronics City Phase 1 | Bangalore - 560 100
Stronger. By Design.

From: ejurgensen ***@***.***>
Sent: Monday, January 2, 2023 5:39 PM
To: owntone/owntone-server ***@***.***>
Cc: Ray, Kallol ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [owntone/owntone-server] Suggestion: Adding items to the queue (Issue #1564)


Are you asking about getting just the id's of the items that were added - so not a list of all the id's in the queue (i.e. including items that were in the queue before the add request)?

**Comment by ejurgensen** [comment]
Ok, I'll see if that can be added

**Comment by kallolray** [comment]
Great, Thank

Regards.... Kallol
Send from handheld device.
________________________________
From: ejurgensen ***@***.***>
Sent: Monday, January 2, 2023 8:12:34 PM
To: owntone/owntone-server ***@***.***>
Cc: Ray, Kallol ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [owntone/owntone-server] Suggestion: Adding items to the queue (Issue #1564)


Ok, I'll see if that can be added
