### ISSUE TITLE
Database locking errors when reinstalling Docker container

### ISSUE THREAD

**Issue by leinaht** [owntone/owntone-server#1565]
I have the linuxserver.io image of OwnTone v28.5 running in an unprivileged Turnkey Core Debian container on a Proxmox server, using docker-compose/a Portainer stack. It normally runs flawlessly but I've run into an issue a few times where I've tried adjusting options in the docker-compose file. On the next startup, the container gets stuck in a loop with "DB init error: database is locked" and "Database init failed" errors. This persists even after deleting the config folder so the container recreates it, which I can not understand--is the issue with docker caching something?

[ownlog.txt](https://github.com/owntone/owntone-server/files/10353009/ownlog.txt)

**Comment by ejurgensen** [comment]
Sorry, I can't help with Docker issues. Perhaps the maintainers of the image can help you.
