### ISSUE TITLE
Error in assigning the this.directory.path  in filebrowser-WebUI files section (in File ModalDialogDirectory.vue)

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1567]
today, I notices sth new: 
Everything works when playing smart playlists (my usual usecase) und when using Cantata as remote.
but when i try to add songs via the Web-UI, they won't get added, instead I see above mentioned error code in the log.

All other features work flawlessly (changing volumes, chosing radio stations, playlists and so on)

Im am running Owntone from git master on Debian Bullseye with freshly build web-src.

**Comment by ejurgensen** [comment]
Thanks for the notice, but I couldn't reproduce the issue. Can you provide more detailed instructions on how to trigger it?

**Comment by LordMyschkin** [comment]
Happy new year and thank you for this fast response!
When I select a directory or a file from my selection in the WebUI to play, i trigger an error: 
JSON api request failed with error code 500 (/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start).
selecting the same files via ympd or cantata behaves as expected. 
When selection to "add" or to "add "next", nothing happens.
All other actions in the webui work as expected.... (except a problem with display of acutes on the webradio Café del mar)
Quite sure I am missing something basic again - but get no clue what...

**Comment by LordMyschkin** [comment]
Reproducing is hard:
here is a screenshot trying to explain.
By far not all actions fire the error 500 mentioned above:

![Bildschirm­foto 2023-01-16 um 19 32 54](https://user-images.githubusercontent.com/11705882/212746529-b0dee39c-6c97-4b6c-a5bd-207a83e94e3b.png)

**Comment by LordMyschkin** [comment]
okay, I am sure it is a html/javascript-Problem: i will track that down...

Output from console in devtools in chrome is:

`index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103
:3689/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:41 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$t')
    at index.js:41:11572
index.js:4 TypeError: e.$ is not a function
    at Proxy.eO (index.js:50:92933)
    at rl (index.js:4:4368)
    at Ni.pe [as fn] (index.js:4:38749)
    at Ni.run (index.js:1:6233)
    at z.update (index.js:4:39033)
    at ue (index.js:4:39059)
    at oe (index.js:4:37841)
    at B (index.js:4:37618)
    at g (index.js:4:34211)
    at Ni.pe [as fn] (index.js:4:38312)
B0 @ index.js:4
index.js:50 undefined
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103
:3689/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:41 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$t')
    at index.js:41:11572
index.js:4 TypeError: e.$ is not a function
    at Proxy.eO (index.js:50:92933)
    at rl (index.js:4:4368)
    at Ni.pe [as fn] (index.js:4:38749)
    at Ni.run (index.js:1:6233)
    at z.update (index.js:4:39033)
    at ue (index.js:4:39059)
    at oe (index.js:4:37841)
    at B (index.js:4:37618)
    at g (index.js:4:34211)
    at Ni.pe [as fn] (index.js:4:38312)
B0 @ index.js:4
index.js:50 undefined
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103
index.js:50 Proxy
index.js:50 Proxy
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13476
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13476
:3689/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:41 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$t')
    at index.js:41:11572
index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103
:3689/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:41 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$t')
    at index.js:41:11572
:3689/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
index.js:41 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$t')
    at index.js:41:11572
`

**Comment by ejurgensen** [comment]
Yes, I could also reproduce now. Seems the error is specific to the files listing? It does indeed look like a frontend problem. I'm not so well-acquianted with that, so won't be able to make a quick fix, and @chme isn't currently active.

**Comment by whatdoineed2do** [comment]
i think this is already fixed in c020905f2ea8af84c01b6063fd4fcc8fda66a563.

Running the in tree `web-src` work for me for the condition described - @LordMyschkin are you able to build that locally to verify?  it does mean you need to install nodejs/npm etc on your local machine.  if thats the case, then it just means `htdocs` requires rebuilding

**Comment by LordMyschkin** [comment]
I did build the web-src on my rpi with node myself before reporting.
No; the error stays the same even with your htocs.directory (thank you for providing); but I mixed two errors, I think.
**First one** is a problem in the UI where trying to add a directory by the vertikal-three-dot-menu next to the directory name; 
this does fire an error in the web-console in chrome (index.js:41 Uncaught (in promise) TypeError: this.$t is not a function
    at index.js:41:13103) but does NOT produce an error message in syslog.
**Second one**   is when I try to play this directory via the "play"-menu entry in the same (vertical three dots menu): this does produce the  "web: JSON api request failed with error code 500 (/api/queue/items/add?expression=path+starts+with+%22undefined%22+order+by+path+asc&shuffle=false&clear=true&playback=start)" message, but just because I asked owntone to play an empty playlist.

I did some research, there must be some problem with vue (my very first contact) and the internationalization library not having initialized this.t$() or using it outside its scope. I even tried using a beta-version of i18n-library and switching options in vite.config.js (setting "globalInjection: true" in the  i18n-part in the plugins where mentioned somewhere in the context of this error) - but i have no idea what I am doing there....

Maybe espen should rename this thread to "Error in vue: this.t$ is not a function" to get the knowing reader on the right track?

**Comment by LordMyschkin** [comment]
Did some further research on that one and at least know whats happening:
in ./components/ModalDialogDirectory.vue, there are two errors.

1) "this.directory.path" does not contain the path, which causes "undefined" instead of the path to get passed to the webapi.queue_expression_add_next in ./webapi/index.js . I just cant find where this.directory.path gets it's value from.


2)  webapi.queue_expression_add_next and webapi.queue_expression_add_next should pass the "this" to the webapi call; this is easy to fix, so the "this.$t() is undefined-Error"  disappears.

should be very easy to fix for someone who knows anything about vue.

**Comment by whatdoineed2do** [comment]
Does any of the "Add Next" or "Add" items work now?  i found how to fix the directory dialog but it'll mean nothing as the Add/Add Next leads to the `$t() is not defined` error which was part of the translation work.

The `webapi/index.js` functions use `$t(...)` but for the `queue_add_*` functions this is all undef'd.

@hacketiwack - any thoughts?

**Comment by LordMyschkin** [comment]
That problem was much easier to fix by adding the "this" as context as argument to the function calling $t, and then  calling $t with context.$t instead of this.$t.

eg redefine addqueue_next (path) to addqueue_next (path, context)

then calling addqueue_next as addqueue_next (currdir, this)

and then in the function addqueue_next (dir, context) {
.
.
.
context.$t(_translateme_string)



I have no idea what causes this error, but above fix works for me - maybe you can implement this in the pull request you filed? i am very unsecure in using git and took as long for my first pr as I did for finding the problem....

**Comment by LordMyschkin** [comment]
solved by #1501 by @hacketiwack and and #1572 by @whatdoineed2do
