### ISSUE TITLE
Spotify Connect Issue

### ISSUE THREAD

**Issue by metec22** [owntone/owntone-server#1575]
I have a weird issue where I cannot start playback within the Spotify app. When I select OwnTone as the playback device through Spotify Connect, a song will show playing for a few seconds and then will go on to the next song and so on but never starts playing. 

If I initiate playback from OwnTone, playback works without issue but the Spotify app does not show that anything is playing. I can start playing music from the app and have two streams playing from the same user. 

Logs do not show any errors.

**Comment by ejurgensen** [comment]
OwnTone does not support Spotify Connect, so that's why. As mentioned in the docs you can use something like spocon as a workaround. There is also issue #295 you can follow. Maybe one day I will get it done. 😃

**Comment by metec22** [comment]
Ah well that would do! Thanks for the workaround and other ticket!
