### ISSUE TITLE
Potential memory leak in /src/transcode.c

### ISSUE THREAD

**Issue by icy17** [owntone/owntone-server#1580]
Potential memory leak in [transcode.c](https://github.com/owntone/owntone-server/blob/master/src/transcode.c) line 519, 1014 and 513. Calling av_dict_set() without calling av_dict_free() to free the memory will cause a memory leak. [Doc](https://ffmpeg.org/doxygen/trunk/group__lavu__dict.html#ga1bafd682b1fbb90e48a4cc3814b820f7) says "av_dict_free() Free all the memory allocated for an [AVDictionary](https://ffmpeg.org/doxygen/trunk/structAVDictionary.html) struct and all keys and values."

**Comment by ejurgensen** [comment]
I had a look at this and I don't think there is a memleak.

> Calling av_dict_set() without calling av_dict_free() to free the memory will cause a memory leak

No, that isn't correct. av_dict_set() will add a keyval to a dictionary, whereas av_dict_free() is for freeing the entire dictionary.

In stream_add() the dictionary is freed be avcodec_open2. The only exception is if OwnTone would be giving unknown values in the dictionary to avcodec_open2, but OwnTone isn't doing that. Of course, in the future allowed options might change, so I will add protection against that.
