### ISSUE TITLE
Great project but not working

### ISSUE THREAD

**Issue by fawumann** [owntone/owntone-server#1582]
I did everything in this guide as mentioned. Such a great project. But be warned. It will not work on raspberry pi 3b or 3b+ or 4 with actual pi os images. Wether bullseye or buster. 

Some bugs are:
- Cpiped will not autodetect sound 
- Workaround with startup code will do the trick but not with the hifiberry mentioned in this guide. Not working with hifiberry dac+adc ( plus )
- Working without cpiped and with external usb sound card (uac 222) with rc.local startup config 
- Sound quality is then not as good as easy Bluetooth connection because of this cheap soundcard

So it can work when you won’t use cpiped and another soundcard. But not that fluid. So don’t waste your time. I think it’s because of an older used raspian os. Actual iso is not compatible.

**Comment by ejurgensen** [comment]
I'm thinking this doesn't belong here, you're issues seem to concern cpiped, but cpiped is not part of OwnTone. OwnTone works just fine on RPi.

I'm unsure what you mean by "this guide", but I'm guessing the wiki article. The wiki's are, as it says, just for users to share ways of using OwnTone.

**Comment by fawumann** [comment]
HiFi Berry was not working. If you follow all steps it works well! Thank you. My fault!
