### ISSUE TITLE
Normalize audio

### ISSUE THREAD

**Issue by ski522** [owntone/owntone-server#1583]
So I ripped all my CD's going back to the 80's in FLAC and recently read that CD's recorded in the 80's were recorded with lower volume levels to maintain quality verses more recent CDs where loudness seems to be the norm and I find that to be true.  

When I shuffle all of my ripped CD's I have to constantly adjust my stereo sound up/down due to the latter. FFmpeg has the ability to normalize audio per this link [http://johnriselvato.com/ffmpeg-how-to-normalize-audio/](http://johnriselvato.com/ffmpeg-how-to-normalize-audio/)

Now I know I could manually re-encode all my rips, but rather keep them as original FLAC rips. 

Is there way to add options to ffmpeg or make it a feature request to add extra the options to ffmpeg before playing?

**Comment by frankusb** [comment]
The challenge is what options should you add to normalize an arbitrary track? It's specific to your entire library and the current playing track. In many cases, owntone is not using ffmpeg to play a track.

That being said, if Owntone supported ReplayGain and forced transcoding, it would allow the user to analyze their library and apply appropriate ReplayGain settings for each track.

**Comment by ejurgensen** [comment]
I'm unsure if ReplayGain already works, see #290. Like you say it requires sending through ffmpeg, which for daap can be set with force_decode. We could expand that setting so it also used for RSP?

**Comment by ski522** [comment]
Most of the time I'm casting to a google audio group and a lot of times I'm streaming online stations so noticed Owntone was using ffmpeg when casting from a stream. Wasn't sure if the same was done for casting local ripped files. 

I think the link I sent about normalization is similar to what radio stations use to normalize all the music as they stream which makes sense as the streams always seem to have the same sound levels (outside of stupid commercials which blast you out, LOL). 

Worst case I have a backup copy of my ripped CD's so I can just write a script to go though them all and normalize the rips with ffmpeg since the originals are backed up.

**Comment by frankusb** [comment]
It would be interesting to do for RSP for lossless collections since unless a user has their collection in WAV, ffmpeg has to transcode to WAV (ignoring lossy files that the Soundbridge plays directly).

I doubt @ski522 is asking about RSP though.

**Comment by ejurgensen** [comment]
It looks like RSP uses the same method as DAAP, so the options for transcoding should actually also work there. Could you see if using force_decode has an effect?

**Comment by frankusb** [comment]
If I understand correctly, flac will be transcoded to wav for RSP so that setting would have no effect. I do have mp3s, would force_decode = { "mpeg", "mpeg" } and then looking for ffmpeg processes be the effect?

**Comment by ejurgensen** [comment]
> flac will be transcoded to wav for RSP so that setting would have no effect

Yes that's right. Let's wait with the mp3s and look into the flacs. I would like some sort of reference test with ffmpeg, could you help me with that? I'm not sure I quite understand how normalization is supposed to work e.g. how does ffmpeg know what level to normalize to. Could you share two flac's, one with normal volume and one with low volume, and also the ffmpeg/ffplay command that makes the low volume track played at the desired normalized level? Then I can look into what is needed to make OwnTone do the same.

**Comment by ski522** [comment]
I threw 2 files here [OneDrive](https://1drv.ms/u/s!AlcEDrQPebO_nyyHhPqVEZnm8S3x?e=4uOVVh), original and the other normalized using ffmpeg. 

The command I use is from the recommendation link I have in my OP,
`ffmpeg -i ./02\ -\ Hey_Hey_What_Can_I_Do.flac -af loudnorm=I=-16:LRA=11:TP=-1.5 out.flac`
You can see the difference in waveforms using Audacity ([https://www.audacityteam.org/](https://www.audacityteam.org/))

The purist won't like normalization (which I am and why I ripped in FLAC), but when I'm not in purest mode and just listing to music in the background the normalization helps keep the sound constant with the various Google Chromecast that I have scattered around my house running in Chromecast audio group.

**Comment by frankusb** [comment]
@ski522 that's why I suggested ReplayGain, using -af volume=replaygain=track allows the FLAC to be stored in its original form but adjusted when the user wants to (in theory).

I'm working on a test case for @ejurgensen.

**Comment by frankusb** [comment]
@ejurgensen `metaflac --add-replay-gain` to add the replaygain tags to a flac, edit the file with your favorite tag editor (kid3) and increase `REPLAYGAIN_TRACK_GAIN` by say 20, `ffmpeg -i 01-Pigs\ on\ the\ Wing,\ Part\ 1.flac -af volume=replaygain=track test.flac`. Then pull up each flac in Audacity and see the increased volume.

**Comment by ejurgensen** [comment]
Thanks for excellent hints on how to do this with ffmpeg and how to test. I have made [a branch](https://github.com/owntone/owntone-server/tree/replay_filter1) with some changes that are my first attempt at supporting replay gain. I tested with `curl http://localhost:3689/rsp/stream/161 --output test.wav`, where 161 is the file id of my flac file with `REPLAYGAIN_TRACK_GAIN`, and it seemed to work. Please also try, if you can.

I'm not sure what the best strategy would be for non-transcoded sources. I guess forcing e.g. mp3->mp3 transcoding could mean a quality loss, and in principle the client might support `REPLAYGAIN_TRACK_GAIN`. But if it doesn't, the user might prefer reasonable volume to quality loss?

**Comment by frankusb** [comment]
Forcing WAV with RSP would likely make wireless Soundbridge users stutter and buffer as they only have 802.11b radios. I experienced this when I converted to FLAC and had to install a dedicated access point for my Soundbridge Radio and wire the remaining wireless M1001. Soundbridges do not support ReplayGain to my knowledge so owntone would be their only way to support it. So for Soundbridges, MP3 -> MP3 might not be a bad option although it's not something I would want to  do. FLAC or MP3 to WAV is an excellent option for wired Soundbridges.

**Comment by ejurgensen** [comment]
Yes, a bit tricky. I'm thinking that since the issue with non-decoded sources would only be present for daap and rsp, and it can be solved with `force_decode`, I am now in favour of just using the solution in the branch + some additional info in the config file.

Another issue, maybe a bit related, is how replaygain tags work for non-flac sources. There isn't too much info on the internet about this, but I understand mp3's (id3) should use TXXX:REPLAYGAIN_TRACK_*, or an older RVA2 tag. I could set the latter with kid3 and with a tool called `normalize-audio`, but ffmpeg didn't seem to support it (rare that you can say that). I haven't found a tool that could set TXXX:REPLAYGAIN_TRACK_*, so not sure if ffmpeg supports it. Maybe replaygain for mp3's is very exotic? Do you guys know anything about this?

Would using ffmpeg's `loudnorm` filter, like you suggest @ski522, be less dependent on the source format? I'm not sure I quite understand how that filter works. Is the idea that the user sets the values for the filter globally and then those values are applied to all tracks? If so, I suppose ffmpeg then needs to analyze each track before playback to get the highs and lows. I wonder how that works, since usually ffmpeg doesn't read the entire file first, and I don't think filters can change how ffmpeg reads a source.

**Comment by ski522** [comment]
I don't know how ffmpeg normalizes the sound either as it doesn't seem to read the file first, I know audacity under the effects menu option has a normalize option as well. 

My interest would be having a default set of values that the user could change and are used on the fly while playing the music if possible. And normalizing the sound is degrading the original anyways so I'm okay with loss of quality during normalization of the file.

I don't know how casting works with Owntone, I was hoping it used ffmpeg and that I could just add the "-af loudnorm=I=-16:LRA=11:TP=-1.5" option to ffmpeg (barring that's what casting uses). 

If this turns out to be crazy arse programming work, then I'll probably just copy all my FLAC's to second directory and write a shell script to normalize those tracks in my copy directory...disk space is cheap enough now a days.

**Comment by ejurgensen** [comment]
You can't just add ffmpeg command line arguments since Owntone uses ffmpeg's api/libraries, but I've made another branch to experiment with the loudnorm filter, you can find [it here](https://github.com/owntone/owntone-server/tree/volume_filter2). For now, I have just hardcoded the filter values to those that you wrote. I'm still not sure I understand how this filter works, but I notice it uses much more cpu, so it's definitely doing some work. Audacity and just listening confirm that the audio levels are being modified.

**Comment by frankusb** [comment]
> Another issue, maybe a bit related, is how replaygain tags work for non-flac sources. There isn't too much info on the internet about this, but I understand mp3's (id3) should use TXXX:REPLAYGAIN_TRACK_GAIN, or an older RVA2 tag. I could set the latter with kid3 and with a tool called `normalize-audio`, but ffmpeg didn't seem to support it (rare that you can say that). I haven't found a tool that could set TXXX:REPLAYGAIN_TRACK_GAIN, so not sure if ffmpeg supports it. Maybe replaygain for mp3's is very exotic? Do you guys know anything about this?

I added two tags to an mp3 file, `REPLAYGAIN_TRACK_GAIN +20.79 dB` and `REPLAYGAIN_TRACK_PEAK 0.60256958` using kid3 and ffmpeg performed exactly the same as with a flac file. What is the TXXX: prefix? I did find that just adding REPLAYGAIN_TRACK_GAIN was not enough, REPLAYGAIN_TRACK_PEAK had to be present before ffmpeg would adjust the output.

**Comment by ski522** [comment]
> but I've made another branch to experiment with the loudnorm filter, you can find [it here](https://github.com/owntone/owntone-server/tree/volume_filter2).

I'll give the branch a shot when I have a chance, probably later this week.

**Comment by ejurgensen** [comment]
I've made another attempt at this which is inspired by why what you said @ski522 about "that I could just add the "-af loudnorm=I=-16:LRA=11:TP=-1.5" option". In this version I've added a config option `decode_audio_filters`, where you can indeed do exactly that. Or one can instead set the option to `volume=replaygain=track`, like you suggested, @frankusb.

I generally dislike adding config options to fix issues, but it's the best solution I can think of in this case.

In principle, any other ffmpeg filter, e.g. an equalizer, can also be added like this. Even multiple filters. However, I haven't tested if that will actually work.

Let me know if it works for you. I will delete the other branches, so the one to test now is: https://github.com/owntone/owntone-server/tree/ffmpeg_filter3

**Comment by frankusb** [comment]
This is actually a nice option as it gives the user the ability to select track or album replay gain (as well as built in normalization).

**Comment by ski522** [comment]
I was going to give this branch a try, but I keep getting the message after compiling and running "Will not be able to stream Chromecast, libav does not support Opus encoding" 

I'm using the same machine I currently have owntone running on and casting works fine with the released version. I removed that release version before recompiling and installing this version. 

I have owntone running on a VM on a server that cast  to all my speakers and home amp...it is not attached directly to my home amp, so I can only test by casting. 

Server is latest Ubuntu and up to date with apt. 

Did I miss something on compiling this version?

**Comment by ski522** [comment]
While I didn't have libavcodec-extra installed, didn't help. Seems the issue might be related to ffmpeg

```
[2023-02-23 05:35:14] [ WARN]   ffmpeg: The encoder 'opus' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[2023-02-23 05:35:14] [  LOG]    xcode: Cannot open encoder (opus): Experimental feature
[2023-02-23 05:35:14] [  LOG]     cast: Will not be able to stream Chromecast, libav does not support Opus encoding
```

**Comment by ejurgensen** [comment]
Strange, especially since I understand it worked before, right? You said it was Ubuntu in a VM, so I could try to reproduce in a VM. Which version of Ubuntu is it?

**Comment by ski522** [comment]
I rebuilt a fresh VM and everything is working now with my chromecast group :) so not sure what was going on before. I'm testing this build as I type and will let you know the results...but so far good!!

I do see the higher cpu, but that's not a problem as my VM server has enough CPU power. 

I like the idea of putting various config parameters into the conf file, allows people to customize things further. 

I guess my other recommendation is to maybe put something in the GUI settings that allows a user to toggle the use of this config setting in case they want to just listen to the rips as they were recorded on the CD.

**Comment by frankusb** [comment]
> I guess my other recommendation is to maybe put something in the GUI settings that allows a user to toggle the use of this config setting in case they want to just listen to the rips as they were recorded on the CD.

Yes, ideally this would be a dynamic choice as typically it would only be used when shuffling across albums.

**Comment by ski522** [comment]
Well going on about 5 hours now listening to my ripped CD's on shuffle mode and haven't needed to touch the volume once casting to my Google audio group...I'm liking this implementation! 

Unless I'm imagining it, I would say this has solved the issue I was asking about, good job!

**Comment by ski522** [comment]
That's fine, majority of the time I'm listening to my CD's via google group cast throughout the house as background music. I can just edit the conf file if I want to listen to FLAC unaltered for some reason.

**Comment by ejurgensen** [comment]
I've merged this change now. Thanks for your help.
