### ISSUE TITLE
Adjustable buffer for real-time sources

### ISSUE THREAD

**Issue by hoiz** [owntone/owntone-server#1585]
I have a suggestion that builds on #1577. Short summary: I only use OwnTone with internet radio and Spotify via pipe. In both cases, data cannot be read in advance and unfortunately I keep having dropouts. In the log I see both "Got retransmit request from..." and "Source is not providing sufficient data, temporarily suspending playback" messages.

If these real-time sources would buffer more, then you would have a greater latency, but also more stability. Is it possible to make this buffer adjustable via a config?

Thank you!

**Comment by ejurgensen** [comment]
"Got retransmit request from..." and "Source is not providing sufficient data" are rather different issues. Basically, the former has to do with network packet loss, and that buffer size is set by AirPlay and cannot easily be changed.

The latter could be alliviated with an increased buffer, but that's more of a workaround than a solution, and adding such a buffer doesn't look trivial to me, so it's not something I will spend time on doing. Note that when you get "Source is not providing sufficient data", OwnTone does build a buffer before starting again, precisely to avoid frequent interruptions. So if you still get frequest interruptions I would say you have problem with the source.
