### ISSUE TITLE
How is the id calculated for an album

### ISSUE THREAD

**Issue by aleszczynskig** [owntone/owntone-server#1587]
Hi, 

I have several owntone instances running, each on a raspberry pi and each configured to monitor a cifs share with my music collection. Normally, each instance of owntone assigns a common id to each album, however my newest instance seems to generate a different id from the rest. I've had a quick scan of the issues but couldn't find anything?

Can you explain how the album ID is generated please and if there is any configuration that might influence why I am getting different results on one particular instance?

Many thanks

**Comment by ejurgensen** [comment]
The album ID is a hash that is calculated from the metadata tags. If one of [these tags](https://github.com/owntone/owntone-server/blob/master/src/library/filescanner_ffmpeg.c#L197) are found then they are used, otherwise [the artist + album name](https://github.com/owntone/owntone-server/blob/master/src/db.c#L1138) is used.

**Comment by ejurgensen** [comment]
Forgot to answer the second part of your question: No, I can't think of clear explanation of the issue, especially if the instances are running on the same host. Otherwise it could be differences in ffmpeg versions (leading to differences in which tags are detected) or character encodings.

**Comment by aleszczynskig** [comment]
Thanks for the information @ejurgensen. I will do some investigating.

**Comment by ejurgensen** [comment]
Yes, I think that is the explanation. The hashing function is murmur_hash64, and it has a different implementation for 32 and 64 bit, and it also returns different results.
