### ISSUE TITLE
Spotify Playlists populate as empty in Music and iTunes

### ISSUE THREAD

**Issue by meaneymikesd** [owntone/owntone-server#1590]
Please try to provide the following:

- steps to reproduce and/or logging of the error
-- Enabled the Spotify integration in the OwnTone settings and logged into Spotify.
- version of owntone
- -28.6
- platform
- - Linuxserver.io Docker container

Steps to reproduce
1. Configure Owntone Spotify settings
2. Launch Music or iTunes on a macOS device.
3. Navigate to the shared library created by Owntone
4. Click on a Spotify playlist
5. Observe it's vast emptiness.
Nothing displays in the Owntone logs when this occurs
![Screenshot 2023-03-12 at 11 04 04 AM](https://user-images.githubusercontent.com/52477141/224563617-d6a2ca1e-520e-4841-b919-fc0d49b8bf03.png)

**Comment by ejurgensen** [comment]
Yes, you cannot play Spotify tracks via iTunes/Apple Music. It's noted in the docs here under "Limitations": https://owntone.github.io/owntone-server/integrations/spotify/
