### ISSUE TITLE
Is there a way to add Artwork to a pipe?

### ISSUE THREAD

**Issue by jackklink** [owntone/owntone-server#1591]
Maybe I am doing something wrong, but I have tried everything under the sun to get Artwork to show up for my pipe.

I have a pipe setup for audio input to my RPi just like the wiki shows to do and I have tried so hard to add artwork.jpg or AUX.jpg files next to the pipe or in a subfolder with the pipe or with the folder name that the pipe is in, but no matter what, the pipe does not have artwork.

For example a pipe in `/home/pi/music/AUX` I will create `/home/pi/music/artwork.jpg`
or a pipe in `/home/pi/music/Turntable/AUX` I will create `/home/pi/music/Turntable.jpg` or  `/home/pi/music/Turntable/Turntable.jpg`

So I am guessing this just doesn't work with pipes? Is that what's going on? Is there another way I could give my pipe album art?

**Comment by ejurgensen** [comment]
There doesn't seem to be a way of adding static artwork for a pipe, but looks like the only change required to support it is the one you can see above. If you build yourself you can check if it works. I can also make a test .deb for you if you want.

**Comment by jackklink** [comment]
Great solution! But actually now that I look closer at the code, I do see this section which seems to check for artwork on a pipe via metadata...
https://github.com/owntone/owntone-server/blob/6930fcbfb8b8f43a69ba07e438d17e931bc67547/src/artwork.c#L270-L276

And looking here you can see that it looks for a "metadata pipe." Not sure what that means or how I would create one?
https://github.com/owntone/owntone-server/blob/6930fcbfb8b8f43a69ba07e438d17e931bc67547/src/artwork.c#L1600-L1635

**Comment by jackklink** [comment]
I found my answer!

https://github.com/owntone/owntone-server/blob/6930fcbfb8b8f43a69ba07e438d17e931bc67547/src/inputs/pipe.c#L27-L29

Will close this once I get it working. But thanks for your help @ejurgensen!

**Comment by jackklink** [comment]
Sorry I moved too quickly and realize now that this metadata has to be provided via a pipe and not as static metadata that I could simply create in a file. I will just go with your easier solution, @ejurgensen. Thanks

**Comment by jackklink** [comment]
> There doesn't seem to be a way of adding static artwork for a pipe, but looks like the only change required to support it is the one you can see above. If you build yourself you can check if it works. I can also make a test .deb for you if you want.

**Comment by aleszczynskig** [comment]
I've been wanting this feature for years. I had no idea it was such an easy fix. I've just made the change to my build and it's working as advertised. I no longer get the horrid (in my opinion) unknown artist artwork flash up before my various scripts updated the artwork via the api. A simple fix and a massive quality improvement. Thank you.

**Comment by ejurgensen** [comment]
I've merged it in now. Great to hear that it's also useful for you @aleszczynskig. Not sure why that type of artwork search wasn't enabled for pipes in the first place, I can't see any downsides to it.

**Comment by aleszczynskig** [comment]
@ejurgensen - this is working great for me, thank you. I've noticed that once you have an artwork file specified for a source you cannot override that artwork via the api. I believe this may also be detailed in the documentation somewhere. Is this something that can be easily overridden/disabled in code? It would be great to be able to specify the initial artwork file on opening of a pipe but subsequently update it via the api.

**Comment by ejurgensen** [comment]
Yes, I think if the search order is changed like in the above commit, then "dynamic" artwork e.g. via api will take priority over the permanent image. Give it a try and let me know if it works better like this.

**Comment by ejurgensen** [comment]
I have merged the modified search order into master now
