### ISSUE TITLE
Airplay: device stops playing after some time

### ISSUE THREAD

**Issue by Kwinnieprince** [owntone/owntone-server#1594]
Please try to provide the following:

- start playing music on an airplay device on a different subnet (MDNS is repeated on both vlans)
- music suddenly stops playing

Relevant logs:
`Mar 21 13:11:49 raspberrypi owntone[6443]: [2023-03-21 13:11:49] [  LOG]  airplay: No response to POST /feedback from 'Living Room'
Mar 21 13:11:49 raspberrypi owntone[6443]: [2023-03-21 13:11:49] [  LOG]   player: Attempting reconnection in 5 sec to the AirPlay 2 device 'Living Room'
Mar 21 13:12:04 raspberrypi owntone[6443]: [2023-03-21 13:12:04] [  LOG]  airplay: Response to GET /info from 'Living Room' was negative, aborting (0 (null))
Mar 21 13:12:04 raspberrypi owntone[6443]: [2023-03-21 13:12:04] [  LOG]   player: The AirPlay 2 device 'Living Room' failed to activate`

When enabling that output again in ownTone, the music starts playing again for some time

Steps to reproduce will greatly improve the chance of getting it fixed. If it is not possible then set the log level to debug (in /etc/owntone.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by ejurgensen** [comment]
Not sure I can help much. The log just shows that OwnTone can't connect, but no indication why. I can only guess it's a network issue.
