### ISSUE TITLE
Avahi txt record pw comparison should be case insentive

### ISSUE THREAD

**Issue by iVolt1** [owntone/owntone-server#1596]
First, thanks for the great project.  I use owntone almost every day.

TuneAero on Windows returns an avahi txt record with pw=False which has an upper case F which causes owntone to think it requires a password when it really does not.  Perhaps the upper case F violates a standard. 

I think changing the comparison to a case insensitive comparison in raop.c will fix the issue for TuneAero.

_From the owntone log:_
[2023-03-25 19:01:07] [  LOG]     raop: AirPlay device 'BA790 TA' is password-protected
[2023-03-25 19:01:07] [  LOG]     raop: No password given in config for AirPlay device 'BA790 TA'
[2023-03-25 19:01:07] [  LOG]     raop: AirPlay device 'Basement East' is password-protected
[2023-03-25 19:01:07] [  LOG]     scan: Bulk library scan completed in 0 sec
[2023-03-25 19:01:07] [  LOG]      lib: Library init scan completed in 0 sec (1 changes)

_From avahi-browse:_
=  wlan0 IPv4 DCA632148113@Kodi (LibreELEC)                 AirTunes Remote Audio local
   hostname = [LibreELEC.local]
   address = [192.168.1.253]
   port = [36666]
   txt = ["vs=130.14" "am=Kodi,1" "md=0,1,2" "da=true" "vn=3" "pw=false" "sr=44100" "ss=16" "sm=false" "tp=UDP" "sv=false" "et=0,1" "ek=1" "ch=2" "cn=0,1" "txtvers=1"]
=  wlan0 IPv4 F6234C55C09F@BA790 TA                         AirTunes Remote Audio local
   hostname = [MA790GP-UD4H-2.local]
   address = [192.168.1.123]
   port = [51297]
   txt = ["am=TuneAero" "tp=UDP" "vn=3" "**pw=False**" "ss=16" "sr=44100" "da=true" "sm=false" "sv=false" "et=0,1" "ek=1" "cn=0,1" "md=0,1,2" "ch=2" "txtvers=1"]
=  wlan0 IPv4 B75ACF4F5007@Basement East                    AirTunes Remote Audio local
   hostname = [MA790GP-UD4H-2.local]
   address = [192.168.1.123]
   port = [55172]
   txt = ["am=TuneAero" "tp=UDP" "vn=3" "**pw=False**" "ss=16" "sr=44100" "da=true" "sm=false" "sv=false" "et=0,1" "ek=1" "cn=0,1" "md=0,1,2" "ch=2" "txtvers=1"]
=  wlan0 IPv4 CA681CA80D43@Basement West                    AirTunes Remote Audio local
   hostname = [OpenWrt243.local]
   address = [192.168.1.243]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "ch=2" "cn=0,1" "ek=1" "et=0,1" "sv=false" "da=true" "sr=44100" "ss=16" "md=0,1,2" "vn=65537" "tp=TCP,UDP" "vs=105.1" "am=ShairportSync" "fv=76400.10" "sf=0x4"]
=     lo IPv4 E869071F94E7@Yamaha Analog                    AirTunes Remote Audio local
   hostname = [DietPiWyse.local]
   address = [127.0.0.1]
   port = [5000]
   txt = ["pw=false" "txtvers=1" "ch=2" "cn=0,1" "ek=1" "et=0,1" "sv=false" "da=true" "sr=44100" "ss=16" "md=0,1,2" "vn=65537" "tp=TCP,UDP" "vs=105.1" "am=ShairportSync" "fv=4.1.1" "sf=0x4"]

_From raop.c:_
  // Password protection
  password = NULL;
  p = keyval_get(txt, "pw");
  if (!p)
    {
      rd->has_password = 0;
    }
  else if (*p == '\0')
    {
      DPRINTF(E_LOG, L_RAOP, "AirPlay '%s': pw has no value\n", device_name);

      goto free_rd;
    }
  else
    {
      **rd->has_password = (strcmp(p, "false") != 0);**
    }

  if (rd->has_password)
    {
      DPRINTF(E_LOG, L_RAOP, "AirPlay device '%s' is password-protected\n", device_name);

      if (devcfg)
	password = cfg_getstr(devcfg, "password");

      if (!password)
	DPRINTF(E_LOG, L_RAOP, "No password given in config for AirPlay device '%s'\n", device_name);
    }

  rd->password = password;

**Comment by ejurgensen** [comment]
Thanks for a very good report. I agree the comparison should be case insensitive. It should be fixed now.
