### ISSUE TITLE
Anyone ever got owntone to run on arch-based linux (esp. EndeavourOS)

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1600]
I find that pipewire uses pulseaudio quite differently, and I can't find any source on how to install owntone on endeavourOS, wich seems to be increasingly popular.
Any hints out there on where I can find instructions?

**Comment by LordMyschkin** [comment]
Its included in the AUR-Repositories, building gets automated there  - owntone starts perfectly, but getting local outputs to work (Pipewire) seems to bee really tricky -  Pulseaudio instructions to not apply, ALSA also does not work - I guess I'll have to figure out that one myself.
The network part and the UI work.
Maybe it is just a problem with ALSA on a MacBookAir, although desktop apps do play sound smoothly...

**Comment by LordMyschkin** [comment]
I figured it out myself - to reduce mileage to everyone else,  I wrote a wiki page.

I wonder: pulseaudio requests that owntone starts AFTER user is logged in. 
This makes it quite unhandy, far away from a simple "set it up and have fun" - solution.
Would'nt it be wiser if owntone tried to connect to pulseaudio later (or every other minute) as long as there is no local playback established, at least when compiled --with-pulseaudio?

or is there an elegant solution to start owntone by systemctl after pulseaudio kicks in?

**Comment by ejurgensen** [comment]
> or is there an elegant solution to start owntone by systemctl after pulseaudio kicks in?

OwnTone's [service file](https://github.com/owntone/owntone-server/blob/master/owntone.service.in) does specify that. See the "After" section. But maybe you mean starting owntone after the user is logged in (and running as a user process)? I guess you can also do that, I suppose google has the howto.
