### ISSUE TITLE
mp3 streaming broken with ffmpeg 6

### ISSUE THREAD

**Issue by acronie** [owntone/owntone-server#1601]
Hello to all,

After building and installing owntone on Fedora 38, everything went well except an error I can see in the log file : 

`xcode : error occured while encoding: Invalid argument`

It happens when I open the stream.mp3 url from the web interface.
I wonder if this issue is linked to ffmpeg, so I tried to reinstall an older version of ffmpeg-devel an reinstall owntone, but no luck.

Does anyone have an idea about fixing that ?

Thanks!

**Comment by ejurgensen** [comment]
Yes, it has to do with ffmpeg, but not sure what the exact cause might be. I will see if I can reproduce. In the meantime, if you are building from the master branch you could try building the latest release instead. I guess there is slight change that it works better.

**Comment by acronie** [comment]
Thanks for your feedback! I'll try to use the latest release and will report then.

**Comment by ejurgensen** [comment]
I was able to reproduce this. Seems to be some incompatibility with recent ffmpeg. I will take a look at it.

I also tested the release version, and unfortunately that was worse (spews errors in the log).

**Comment by acronie** [comment]
OK. I tried also with the latest release, and no luck either. I ended up reinstalling Mint on the PC I'm using as a server instead of Fedora. Everything went OK and is working now.
Thank you!

**Comment by ejurgensen** [comment]
Should be fixed now. Thanks for reporting.
