### ISSUE TITLE
Can u please write how to install it on osx with Homebrew?

### ISSUE THREAD

**Issue by Cuddles1233** [owntone/owntone-server#1603]
I Try now 10 Hours and it doesn't work :-(

*** No targets specified and no makefile found.  Stop.

Please thanks

**Comment by hacketiwack** [comment]
@Cuddles1233, can you please elaborate which steps you tried already?
Thanks

**Comment by Cuddles1233** [comment]
I copy the iml in terminal after I installed homebrew.

Then I installed every Brew instance manually. But at the End this 2 Parts dont work.

- name: Configure

      run: |

        autoreconf -fi

        ./configure --enable-chromecast --enable-lastfm --with-pulseaudio



    - name: Build

      run: |

        # Without setting these env vars the build fails with "fatal error: 'openssl/ssl.h' file not found"

        # (Solution taken from https://github.com/libimobiledevice/libimobiledevice/issues/389#issuecomment-289284190)

        export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib

        export CPATH=$(brew --prefix openssl)/include

        export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig

        make



    - name: Install

      run: sudo make install

And how I automatically start the dml I dont figured out.

**Comment by hacketiwack** [comment]
Actually, there is an error already at the first stages.
You can see that when you try to compile the library `libinotify-kqueue` there is already an error.
If you were running a CI/CD pipeline, it would fail in your situation and not even go further down the lane.

On my machine, I get the same error. And I'm pretty sure that its because we have a different version of macOS than the one hosted by Microsoft (GitHub in this case).

I will check where this error comes from.

**Comment by Cuddles1233** [comment]
After restart of Terminal

   - name: Configure
      run: |
        autoreconf -fi
        ./configure --enable-chromecast --enable-lastfm --with-pulseaudio

Works.

But now the last dont work.

make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.

Dont know why

**Comment by hacketiwack** [comment]
This is most probably cause by the previous errors that prevents the `configure` command to work properly, resulting in the impossibility to execute `make`.

If you look at the file `config.log`, you'll see that there is a fatal error:

```
configure:5124: gcc -c -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -I/opt/homebrew/opt/flex/include conftest.c >&5
conftest.c:50:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
```

First things first, you need to be able to compile libinotify-kqueue properly.

**Comment by Cuddles1233** [comment]
Yes I get this error.

controller.c:44:31: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]
static atomic_uint nworkers = ATOMIC_VAR_INIT (0);
                              ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/stdatomic.h:51:41: note: macro marked 'deprecated' here
#pragma clang deprecated(ATOMIC_VAR_INIT)

**Comment by hacketiwack** [comment]
Yep. And I don't know how to solve it either.

**Comment by ejurgensen** [comment]
Try building with the change in the above commit, I think it should suppress the error. Looks like libinotify-kqueue uses a deprecated macro, so it's really just a warning.

I'll make an issue over there, but not sure how active the repo is, the last commit was in 2021.

**Comment by Cuddles1233** [comment]
Witz this change I get this.

/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I. -DNDEBUG -D_THREAD_SAFE -pthread -Wall -Werror -Wno-deprecated-declarations -MT libinotify_la-controller.lo -MD -MP -MF .deps/libinotify_la-controller.Tpo -c -o libinotify_la-controller.lo `test -f 'controller.c' || echo './'`controller.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -DNDEBUG -D_THREAD_SAFE -pthread -Wall -Werror -Wno-deprecated-declarations -MT libinotify_la-controller.lo -MD -MP -MF .deps/libinotify_la-controller.Tpo -c controller.c  -fno-common -DPIC -o .libs/libinotify_la-controller.o
controller.c:44:31: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]
static atomic_uint nworkers = ATOMIC_VAR_INIT (0);
                              ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/stdatomic.h:51:41: note: macro marked 'deprecated' here
#pragma clang deprecated(ATOMIC_VAR_INIT)
                                        ^
1 error generated.
make[1]: *** [libinotify_la-controller.lo] Error 1
make: *** [all] Error 2

**Comment by ejurgensen** [comment]
Ok, try with `export CFLAGS='-Wno-deprecated-pragma'` instead, like above.

**Comment by hacketiwack** [comment]
Thanks @ejurgensen `libinotify-kqueue` could be compiled.

**Comment by hacketiwack** [comment]
By the way, with Homebrew on macOS Ventura, the paths to `bison` and `flex` are the anymore under `/usr/local/opt/bison/bin/bison` and `/usr/local/opt/flex/bin/flex` respectively.
Therefore, this will have to be changed when the `macos-latest` is set to another version macOS.

**Comment by hacketiwack** [comment]
Finally, I got it to build on macOS Ventura with the following commands.
It is not optimised at all.

# Install the toolchain
```zsh
brew install automake autoconf libtool pkg-config gperf
```

# Build libinotify
```zsh
git clone https://github.com/libinotify-kqueue/libinotify-kqueue
cd libinotify-kqueue
export CFLAGS='-Wno-deprecated-pragma'
autoreconf -fvi
./configure
make
sudo make install
cd ..
```

# Build sqlite
```zsh
curl -o sqlite-autoconf-3310100.tar.gz https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
tar xzf sqlite-autoconf-3310100.tar.gz
cd sqlite-autoconf-3310100
export CFLAGS='-DSQLITE_ENABLE_UNLOCK_NOTIFY=1'
./configure
make
sudo make install
cd ..
```

# Install ffmpeg
```zsh
sudo chown -R $(whoami) $(brew --prefix)/*
brew install ffmpeg
```

# Install packages
```zsh
brew install bison flex libunistring libmxml confuse libplist sqlite libwebsockets libevent libgcrypt json-c protobuf-c libsodium gnutls pulseaudio openssl
```

# Symlink bison and flex
```zsh
sudo ln -s /$(brew --prefix bison)/bin/bison /usr/local/bin/bison
sudo ln -s /$(brew --prefix flex)/bin/flex /usr/local/bin/flex
```

# Configure paths for build
```zsh
export LDFLAGS="-L$(brew --prefix libgcrypt)/lib -L$(brew --prefix libgpg-error)/lib -L$(brew --prefix libevent)/lib -L$(brew --prefix flex)/lib -L$(brew --prefix protobuf-c)/lib -L$(brew --prefix json-c)/lib -L$(brew --prefix bison)/lib -L$(brew --prefix llvm)/lib -L$(brew --prefix libunistring)/lib"
export CPPFLAGS="-I$(brew --prefix libgcrypt)/include -I$(brew --prefix libgpg-error)/include -I$(brew --prefix libevent)/include -I/opt/homebrew/opt/llvm/include -I$(brew --prefix json-c)/include  -I$(brew --prefix protobuf-c)/include -I/opt/homebrew/opt/flex/include -I$(brew --prefix libunistring)/include"
export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
export CPATH=$(brew --prefix openssl)/include
export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
```

# Build OwnTone
```zsh
git clone https://github.com/owntone/owntone-server.git
cd owntone-server
autoreconf -fi
./configure --enable-chromecast --enable-lastfm --with-pulseaudio
make
sudo make install
```

**Comment by hacketiwack** [comment]
@Cuddles1233, did you finally manage to make it work on your side?

**Comment by ejurgensen** [comment]
Fyi libinotify-kqueue has fixed the cause of the compile error, so that's great. See https://github.com/libinotify-kqueue/libinotify-kqueue/issues/17. Should mean that `export CFLAGS='-Wno-deprecated-pragma'` is no longer necessary.
