### ISSUE TITLE
Segfault on running query 'UPDATE artwork ...'

### ISSUE THREAD

**Issue by ErrorSource** [owntone/owntone-server#1604]
Hi,

since commit 71d37fc (on Apr 12, 2023) - i where several commits behind, don't know how many, maybe since beginning of April - ownTone stalls here with a segmentation fault, when doing a lib rescan and there always at the following query:

```
[2023-04-30 20:35:25] [  LOG]     scan: Scanned 1600 files...
[2023-04-30 20:35:25] [DEBUG]       db: Running query 'END TRANSACTION;'
[2023-04-30 20:35:25] [DEBUG]    cache: Running query 'UPDATE artwork SET db_timestamp = 1682879725 WHERE filepath = '/media/Music/Linkin Park/Living Things/cover.jpg' AND db_timestamp >= 1549477411;'
Segmentation fault (core dumped)
```
or
```
[2023-04-30 20:44:23] [  LOG]     scan: Scanned 1600 files...
[2023-04-30 20:44:23] [DEBUG]       db: Running query 'END TRANSACTION;'
[2023-04-30 20:44:23] [DEBUG]    cache: Running query 'UPDATE artwork SET db_timestamp = 1682880263 WHERE filepath = '/media/Music/Red Hot Chili Peppers/Californication/cover.jpg' AND db_timestamp >= 1549479510;'
Segmentation fault (core dumped)
```

So ownTone runs here for several hours, then crashes. Or sometimes it stalls at start. Has something changed with dependencies and i missed that? How can i investigate deeper? Maybe it has nothing to do with scanning for artwork? Unfortunately i have no experience with gd or similar procedures.

ownTone runs on Ubuntu 22.04.2 LTS (5.15.0-71-generic). Worked for years now. I would be grateful for any help.

**Comment by ejurgensen** [comment]
Thanks a lot for reporting. Sounds like it is easy for you to reproduce, so it would be great if you could track the bug with gdb. Here's how you can do that:

1. Install gdb (sudo apt install gdb)
2. Stop owntone (sudo systemctl stop owntone)
3. Load owntone in gdb (sudo gdb --args /usr/sbin/owntone -f)
4. Run owntone ('run') and let it run until it crashes
5. Get a backtrace ('bt') and share it here

**Comment by ErrorSource** [comment]
Thank you very much for the fast answer and the howto. Now i have a segfault message. Hope, it's enough!?
```
[2023-05-01 11:43:43] [  LOG]    cache: Beginning DAAP cache update
[2023-05-01 11:43:44] [  LOG]    cache: DAAP cache updated
[Thread 0x7fffb4ff9640 (LWP 710181) exited]
[Thread 0x7fffb57fa640 (LWP 710180) exited]
[Thread 0x7fffb5ffb640 (LWP 710179) exited]
[Thread 0x7fffb67fc640 (LWP 710178) exited]
[2023-05-01 11:59:52] [  LOG]  airplay: AirPlay device 'CFCE764FE564@RPiCar Airplay' is missing a device ID

Thread 1 "owntone" received signal SIGSEGV, Segmentation fault.
0x000055555559228c in browse_resolve_callback (r=0x5555557fe8d0, intf=2, proto=0, event=AVAHI_RESOLVER_FAILURE, name=0x555555800780 "CFCE764FE564@RPiCar Airplay", type=0x555555803000 "_airplay._tcp", domain=0x5555556db070 "local", hostname=0x0, addr=0x0, port=0, txt=0x0, flags=0, userdata=0x55555570e470) at mdns_avahi.c:779
779       family = avahi_proto_to_af(addr->proto);
```

And thanks again for your amazing "project"!

**Comment by ejurgensen** [comment]
Thanks, that's perfect, it shows the cause clearly.

@couteau this seems to come from PR #1599. Looks like addr is NULL when event is AVAHI_RESOLVER_FAILURE. Which makes sense, I guess. Since the PR uses addr->proto instead of proto it causes a null pointer deref. It's probably a common scenario, so I will fix it asap.

**Comment by ejurgensen** [comment]
Should be fixed now, please confirm if you can

**Comment by ErrorSource** [comment]
Yeah, no more segfaults (so far)! Uptime of ownTone now more than a day. Thank you again for your quick solution.
