### ISSUE TITLE
Owntone API - push notifications

### ISSUE THREAD

**Issue by kalle2000** [owntone/owntone-server#1605]
Hi,

I am failing to get the push notifications working for me (e.g. perl, python). Even when using the command from the help I do not get any result, neither can I see anything in the debug log.

`curl --include      --no-buffer      --header "Connection: Upgrade"      --header "Upgrade: websocket"      --header "Host: localhost:3688"      --header "Origin: http://localhost:3688"      --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ=="      --header "Sec-WebSocket-Version: 13"      --header "Sec-WebSocket-Protocol: notify"      http://localhost:3688/      --data "{ \"notify\": [ \"player\" ] }"

HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
Sec-WebSocket-Protocol: notify

?
?frag ctl`

What am I doing wrong here?

**Comment by ejurgensen** [comment]
Hi @kalle2000 I guess there isn't anyone around able to help with this, so I will close the issue. If you find the answer yourself please share it here.

**Comment by aleszczynskig** [comment]
I had similar problems but I got it working with nodeRED. See this post. 

[](https://github.com/owntone/owntone-server/issues/1420)

I can post a working config if that is helpful. Maybe that will shed some light on your problems in python.

**Comment by kalle2000** [comment]
> I had similar problems but I got it working with nodeRED. See this post.
> 
> [(https://github.com/owntone/owntone-server/issues/1420)](https://github.com/owntone/owntone-server/issues/1420)
> 
> I can post a working config if that is helpful. Maybe that will shed some light on your problems in python.

That’s very kind, please do so

**Comment by jnth** [comment]
It's a bit late but for the records, you must use the `notify` sub-protocol like the one declared in the [source code)(https://github.com/owntone/owntone-server/blob/master/web-src/src/App.vue#L183).

In Python, you can get all messages sent by the server with:

```python
#!/usr/bin/env python

import asyncio
import json
from websockets.sync.client import connect

def main():
    with connect("ws://127.0.0.1:3688/", subprotocols=["notify"]) as websocket:
        websocket.send(json.dumps({"notify": ["player", "volume", "outputs"]}))
        while True:
            try:
                message = websocket.recv()
                print(f"Received: {message}")
            except KeyboardInterrupt:
                break

main()
```
