### ISSUE TITLE
[web] Playlist items count missing

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1606]
When browsing playlists, the item count at the top of the page in the webui for the playlist being viewed appears to be broken.
![image](https://github.com/owntone/owntone-server/assets/17277745/ede621fa-486d-44d8-9e90-26dd827936db)

**Comment by hacketiwack** [comment]
This is not fixed with the commit [0d095b3](https://github.com/owntone/owntone-server/commit/0d095b30377ba3bbd0de5d77fbc4506e067206cf).
