### ISSUE TITLE
(Help Request) SomaFM Stations

### ISSUE THREAD

**Issue by wynteryyc** [owntone/owntone-server#1608]
Hi

I'm trying to add SomaFM stations to my OwnTone server.  I can copy/paste the server into the stream URL and it just works but adding them as a playlist has so far not worked.

This is what I have for example (groovesalad.pls)

[playlist]
File1=https://ice4.somafm.com/groovesalad-128-aac
Title1=Groove Salad [SomaFM]
NumberOfEntries=1

I have this file in my _Playlists folder.  There are other local playlists in the same folder that work.  I've restarted the server as well as refreshed it.

TIA

**Comment by ejurgensen** [comment]
Any info in the log?

**Comment by wynteryyc** [comment]
it shows my other playlists and the new one

[2023-05-11 05:53:05] [  LOG]     scan: Unchanged playlist found, not processing '/srv/music/_Playlists/Groovesalad.pls'

**Comment by wynteryyc** [comment]
Ok here is what I did.
I chowned the entire music folder to the owntone user
I restarted the service
The Groovesalad entry doesn't appear in the playlists part of the web UI but if I search for 'groove', I can see the playlist and it plays.

I think my problem was expecting to see the stream with the playlists in the UI.

(oops)  and Thank You!

**Comment by ejurgensen** [comment]
Yes you should see it when you select the Radio tab in the web UI

**Comment by wynteryyc** [comment]
OHHHH!  <my bad>
