### ISSUE TITLE
(Question) Disable Spotify using the config file?

### ISSUE THREAD

**Issue by wynteryyc** [owntone/owntone-server#1609]
Hi

Is it possible to disable Spotify using the config file or do I need to recompile and flag it to exclude Spotify support?

TIA

**Comment by ejurgensen** [comment]
You can just not login to Spotify?

**Comment by wynteryyc** [comment]
yeah  100%.  I'm not logged in.
I'm being picky about logfile errors.

no big deal.

thanks!
