### ISSUE TITLE
Question: OwnTone and Podcasts / Airplay

### ISSUE THREAD

**Issue by dev1981** [owntone/owntone-server#1614]
Hello, 

i have an issue that i can not see subscribed Podcasts in my Itunes software running on Win10.
I have added the podcast using the webinterface to the DAAP server (using URL) but it does not show up on my client in Itunes.
Interestingly is when i check the remote app on my iphone the podcasts are listed. Only Itunes wont show them.
As i understood the podcasts i added in the web interface arent stored somwehre locally (just links in the WEB?!) Maybe thats the issue?

Removing the added podcasts within the web interface does not work as well. I klick the remove button but nothing happens.

The 2nd thing is related to Airplay configuration. I have 1 Airport Express running.
Here is the Airplay related section in my .conf file:

# airplay "Airport Express" {
        # OwnTone's volume goes to 11! If that's more than you can handle
        # you can set a lower value here
        #max_volume = 11

        # Enable this option to exclude a particular AirPlay device from the
        # speaker list
        # exclude = false

        # Enable this option to keep a particular AirPlay device in the speaker
        # list and thus ignore mdns notifications about it no longer being
        # present. The speaker will remain until restart of OwnTone.
        # permanent = false

        # Some devices spuriously disconnect during playback, and based on the
        # device type OwnTone may attempt to reconnect. Setting this option
        # overrides this so reconnecting is either always enabled or disabled.
        # reconnect = false

        # AirPlay password
        password = "SuperSafePW"

        # Disable AirPlay 1 (RAOP)
        # raop_disable = false

        # Name used in the speaker list, overrides name from the device
        # nickname = "My speaker name"
# }

here are the entries from the log when i start the server:
[2023-06-01 06:00:41] [  LOG]     raop: AirPlay device 'AirPort Express' is password-protected
[2023-06-01 06:00:41] [  LOG]     raop: No password given in config for AirPlay device 'AirPort Express'
[2023-06-01 06:00:41] [  LOG]     raop: AirPlay device 'AirPort Express' is password-protected
[2023-06-01 06:00:41] [  LOG]     raop: No password given in config for AirPlay device 'AirPort Express'

What i am doing wrong? Hopefully anybody can help me with the two issues i have.

greetings

Adrian

**Comment by ejurgensen** [comment]
> Only Itunes wont show them.

For iTunes (daap), OwnTone is basically a file server, and only local files are served. So for podcasts you have to let OwnTone do the playback, e.g. via the web interface or a dacp/mpd controller.

> No password given in config for AirPlay device 'AirPort Express'

Notice that the P is capitalized, but it doesn't seem to be in your config.

**Comment by dev1981** [comment]
> > Only Itunes wont show them.
> 
> For iTunes (daap), OwnTone is basically a file server, and only local files are served. So for podcasts you have to let OwnTone do the playback, e.g. via the web interface or a dacp/mpd controller.
> 
> > No password given in config for AirPlay device 'AirPort Express'
> 
> Notice that the P is capitalized, but it doesn't seem to be in your config.

i had tried using capital P before but heres the log output when ich change it from passoword to Password:

[2023-06-01 08:20:11] [  LOG]   config: [airplay:854] no such option 'Password'
[2023-06-01 08:20:11] [FATAL]   config: Parse error in config file /etc/owntone.conf
[2023-06-01 08:20:11] [FATAL]     main: Config file errors; please fix your config

**Comment by ejurgensen** [comment]
It's the P in "AirPort Express"

**Comment by dev1981** [comment]
> It's the P in "AirPort Express"

:D i got it a second ago that u meant the name of the device :) sry 
its working now. At least the Airport thingy.
