### ISSUE TITLE
[web] Slider bars on the output control screen are too thin

### ISSUE THREAD

**Issue by iVolt1** [owntone/owntone-server#1620]
I find that the slider bars on the output control screen are vertically too slim to easily land the mouse pointer on in order to change the volume in on one click.  I usually end up hunting the mouse pointer up and down until it falls on just the right pixel(s) or give up go grab the slider circle on the slider.

When using that web page on my iphone,  I also find the sliders to be a little thin for landing the finger on for volume change.

I looked through the code and it looks like https://github.com/chme/slider/blob/main/src/Slider.vue is the slider code that is used and I don't see anywhere in that code or owntone code that allow adjustment of the thickness of the slider so I hope a way can be found.

As always, owntone is a great product I use daily and appreciate all the work that goes into it!

![image](https://github.com/owntone/owntone-server/assets/71899823/52e5cdc2-3fa4-4c72-8a31-66ebf231a4a3)

**Comment by hacketiwack** [comment]
@iVolt1, I can understand what you explain here.
I'm not sure that it can be improved with the current slider library.
How selectable is the slider of this other library [here](https://wikiki.github.io/form/slider/)?

**Comment by hacketiwack** [comment]
I've looked at the source code and actually, it is possible to change the thickness of the slider.
The `--slider-height` in [mystyles.scss](https://github.com/owntone/owntone-server/blob/master/web-src/src/mystyles.scss) is responsible for this behaviour.
Question is now: what would a reasonable size be?

**Comment by iVolt1** [comment]
I tried the library you linked to and either of these, the third and fourth choices down, are a definite improvement.  

<input class="slider is-fullwidth" step="1" min="0" max="100" value="50" type="range">

<input class="slider is-fullwidth is-medium" step="1" min="0" max="100" value="50" type="range">

Thanks for finding the place in the source. I tried recompiling - changing --slider-height to 8px and all the way up to 32px and could see no difference.  Maybe there is something else involved?

**Comment by ejurgensen** [comment]
I also sometimes stuggle with these controls, so would be great if there is something that can be done

**Comment by iVolt1** [comment]
I am not a html or css expert so I took a broad approach and changed every occurrence of --slider-height in htdocs/assets/index.css from 4px to16px and did get thicker slider bars that work better.  This change did cause the slider bar to drop a few pixels below the icons on the left so some adjustment probably needs to be done there too.

One other thing I noticed is that the finger pointer when hovering on the slider bar only appears to the left of circle slider and on the right it stays as the normal arrow pointer when landing on the slider bar.  It seems more logical to have the hand finger pointer appear on either side of the circle, but then I am not a ui expert either.


![Screenshot 2023-06-13 053935](https://github.com/owntone/owntone-server/assets/71899823/46332c7f-0604-443d-a12e-5457d64bbeb9)

**Comment by hacketiwack** [comment]
Thanks @iVolt1 for your input. I take your proposal into consideration.
I'm no UI expert either, but there's room for improvement.

**Comment by iVolt1** [comment]
I will give it a try later today and get back.  Thanks.

**Comment by iVolt1** [comment]
This is better.  The bars are not as thick as my hack.  Landing on the bars is easier than the original but with my 3440 x 1440 screen and a kind of sensitive mouse and I still don't always land on the first try.  Thanks for working on this.

**Comment by iVolt1** [comment]
This is perfect on IOS.

**Comment by hacketiwack** [comment]
Thanks for your input @iVolt1. I will try to improve it.

BTW, I also have a 3440x1440 screen on which I test. I guess my mouse is less sensitive 😬.

As it seems you're using a machine with Windows 10/11, I'll setup a virtual machine to test the new UI there as well.

**Comment by iVolt1** [comment]
That change does make the volume bar easier to land on and control using the bar and the circle.  On IOS it is harder to land on the circle and slide from there but landing on the bar is easy.  Perhaps the circle could be a little larger?

One other observation is that it might be better to have the on-off icon that is on on the left be lined up with the bottom of the slider or centered centered with the slider which would keep the on-off and slider actions on the same horizontal plane and maybe save some vertical space in the device list if the name was brought down a little too.

Thanks again for improving the usability.

**Comment by hacketiwack** [comment]
@iVolt1, yes, I agree with your points, which I can summarise this way (and add one more point related to the main volume button)

1. On mobile, the circle should be bigger the be more accessible.
2. The on-off icons should be, indeed, aligned with the slider. They are currently aligned in the middle of the zone. But overall this part needs to be remodelled and the spacing also removed.
3. There is a wish to get the main volume control on the main page (more information [here](#1442)). I think this should be indeed something accessible on the main page.

I will make another round to address these points.

**Comment by hacketiwack** [comment]
@iVolt1, I solved point 1 and corrected a few other flaws regarding the spacing.

I will address point 2 and 3 at another time if you don't mind.

**Comment by iVolt1** [comment]
Cool.  No hurry.  Thanks for getting it this far.

**Comment by hacketiwack** [comment]
I made some other improvements, but did not yet tackle the point 2 and 3 as said earlier.
My suggestion is that if ok for you @iVolt1 and @ejurgensen, I will merge these changes into the master branch.
Of course, I won't forget the 2 other points, but I'll do it at another time, because I would like to simplify the code related to the volume controls.
Thanks again for the suggestions.

**Comment by ejurgensen** [comment]
Nice that you were able to make the controls easier to use, however in my view the look suffered a bit. The new look is sort of "heavy".

It's up to you whether you want to merge, since you know the available options better - and of course taste is subjective anyway.

**Comment by hacketiwack** [comment]
I agree with your comment about heaviness. I need to make a bit lighter before merging.

**Comment by hacketiwack** [comment]
Latest change includes a lighter slider, which keeps its ability to be reached easily.
Thanks in advance for your feedback.

**Comment by hacketiwack** [comment]
They are now at the same size than before. Thanks for the feedback @ejurgensen.

**Comment by hacketiwack** [comment]
@iVolt1, thanks for your comment. I don't see any red line anywhere 😅. At least, it's not a wanted effect.
Can you please make a screenshot and tell me which browser your using?
Thanks

Regarding the second point, I agree with you. I think it could be done. I need to check though.

**Comment by hacketiwack** [comment]
I see now where the comment of the red icon comes from. It is actually the default icon on Windows when an operation is not allowed. In the current version this icon is the same.

But, if we implement the possibility to change the volume when the source is not active, then this icon should disappear.
Another possibility would be to change the cursor icon with a custom one.

**Comment by hacketiwack** [comment]
@iVolt1, I changed the cursor icon, so it won't be a big red sign anymore. ☺️

**Comment by ejurgensen** [comment]
Looks great now!

**Comment by hacketiwack** [comment]
Thanks.
I will then proceed with the merging of the branch in the coming days. ☺️

**Comment by iVolt1** [comment]
Looks good for sure, however the big red sign is now grey but really no sign should be needed since everything else for that device is greyed out.  Thanks for all of the hard work.
