### ISSUE TITLE
how to change radio station name?

### ISSUE THREAD

**Issue by Yumega** [owntone/owntone-server#1625]
I edit a radio m3u like this 
![image](https://github.com/owntone/owntone-server/assets/61570667/6eb576b9-377f-4caf-a035-44423872dc37)

but on web side, the radio station name is wrong
![image](https://github.com/owntone/owntone-server/assets/61570667/8f9b47f8-e1a2-4065-a151-921de4c83acc)

how to change them into a right name ? and how to delete one station?

**Comment by ejurgensen** [comment]
The format of EXTINF is:
```
#EXTINF:-1, Sample artist name - Sample track title
C:\Music\SampleMusic.mp3
```

And you delete by removing the line from the m3u file.

**Comment by Yumega** [comment]
not mp3, what I add a radio station, and change the radio station name displays on the web
