### ISSUE TITLE
How to enable speaker Computer by default?

### ISSUE THREAD

**Issue by nook24** [owntone/owntone-server#1628]
Hi,
sorry for creating an issue for this but I'm wondering how I could enable the `Computer` speaker by default? I'm running owntone within a Docker container but whenever the container restarts, I have to manually enable the `Computer` speaker in the Webinterface again.

I'm using ALSA just in case this matters.

<img width="1170" alt="Bildschirmfoto 2023-07-04 um 22 01 47" src="https://github.com/owntone/owntone-server/assets/9019992/ab4ac8b2-9486-4076-a4dd-3aa103ad8a66">

Many thanks.

**Comment by ejurgensen** [comment]
Speaker selection should be saved to owntone's database, so I'm thinking that perhaps the database isn't persisted in your Docker setup? It's normally located in /var/cache/owntone/songs3.db.

**Comment by nook24** [comment]
Good call. I think i found the issue. The database is located on a persistent storage and also writable from the container. I noticed that OwnTone was able to store other settings such as the top navigation bar menu items without any issues.
So I checked the SQL Light database itself, and for me the record of the Computer Speaker looks sus due to `id=0`

I manually set the value of selected to 1 and now the `Computer` speaker is selected when the container starts.
![speaker_sqllight](https://github.com/owntone/owntone-server/assets/9019992/a61ee327-737b-474b-bbb9-a2bea9b03d11)


I'm using the docker image from linuxserver.io
https://docs.linuxserver.io/images/docker-daapd

**Comment by ejurgensen** [comment]
id=0 is correct for Computer.

I think speaker selection is saved to the database when OwnTone shuts down, so another possible reason for this is that it isn't shutting down properly. Perhaps it is crashing? Or Docker just kills it?

**Comment by nook24** [comment]
A safe button would be good^^
I'm fine with this workaround. I will probably never touch the Speaker settings again anyway.

> so another possible reason for this is that it isn't shutting down properly

Perhaps. The Docker image has an init system so it should stop all processes gracefully. I'm closing this as I thing the issue that the database is not saved properly is related to the Docker container instead of OwnTone itself.

Many thanks for your time and help :)
