### ISSUE TITLE
[web] Chinese translation

### ISSUE THREAD

**Issue by Yumega** [owntone/owntone-server#1630]
I can help translate the web ui into Chinese, where to start

**Comment by Yumega** [comment]
> Great! Thanks a lot. The best is to create a pull request with your translation.
> 
> You'll have to create a new file called `zh.locale` and placed [here](https://github.com/owntone/owntone-server/tree/master/web-src/src/locales).
> 
> To start, the best is to base your translation on the `en.locale` [file](https://github.com/owntone/owntone-server/blob/master/web-src/src/locales/en.json).

I have finished the translation here https://raw.githubusercontent.com/Yumega/max/master/windows/zh.json
but I don't know how to pull request, you can use zh.json as your own work, Thank you

**Comment by hacketiwack** [comment]
@Yumega, Chinese has been included in this [commit](https://github.com/owntone/owntone-server/tree/6c3e74d159a92c4d69ef18a9a04f90fcfff7504a).
