### ISSUE TITLE
Need help setting up OwnTune in a TrueNAS Jail

### ISSUE THREAD

**Issue by lachydavies25** [owntone/owntone-server#1632]
Hey, I'm in trying to get the script to work with no luck, it's telling me "command not found" when trying to run the script. Is anyone able to help?

**Comment by hacketiwack** [comment]
@lachydavies25 what are you trying to achieve? Could you please be more specific? Thanks

**Comment by lachydavies25** [comment]
Don’t worry about it you can close the ticket I gave up on trying to do it
through a jail and did it through a dock in a VM instead
