### ISSUE TITLE
how to choose language in web-interface - owntone V28.6

### ISSUE THREAD

**Issue by ffatgit** [owntone/owntone-server#1633]
Hello Folks,

first of all: BIG thank you for the whole project (and the time and sweat you all putting into it)!

Now to my question:
I'm not sure if it is an issue or if the problem is located between the shoulders of earth-people (=me):
Id liked to use one of the implemented language in the web-interface.
But of the settings page there only the headline "Language".
I didn't find a section in the owntone.conf file.

After check of the documentation and even the entries here in the github repository I didn't find an entry point / idea for a solution.
So I'm really happy, if someone could give me a hint.

The system I using (testing, playing around) the owntone server on, is an Raspberry Pi 3B+.
Software wise it is the docker container of linuxserver.io *1 on top of a "Raspberry Pi OS Lite" image with Openmediavault 6.
But i guess "only" docker container could be "different" or the "problem" compared to a installation on a host.
(Raspberry Pi OS and Openmediavault are not the issuer!?)

*1 link: https://fleet.linuxserver.io/image?name=linuxserver/daapd 

I checked also the forums and repositories of linuxserver.io and openmediavault.

Thank you in forward!
Frank

![owntone_language resized](https://github.com/owntone/owntone-server/assets/21111020/f9b9633f-83c3-4615-925f-d580f3c5d17d)

**Comment by hacketiwack** [comment]
Hi @ffatgit,
Thanks for the thank you ☺️ It's really appreciated.

Regarding the configuration of the language, there is no parameter in `owntone.conf`. At least for now.
The only way to configure it is under the `Settings` page (the screenshot you made).
The language that's chosen by the Web interface is selected according to your browser preferences. For example, if you have French first, then it will by default use French.

However, in your screenshot, there should be a dropdown menu showing the languages.
As depicted below.
<img width="764" alt="owntone-language-settings" src="https://github.com/owntone/owntone-server/assets/13329768/746ee862-9e21-4e75-8829-0b44efc50b8a">

What is the Web browser and operating system you're using to display the Web interface?

Thanks in advance.

**Comment by ffatgit** [comment]
Hello hacketiwack,

thank you for the quick response.

Yes you a right, there is no drop down field.
The OS I'm calling the web interface is a Ubuntu derivate with the Firefox ESR browser.
I'll will check it with other devices (OS and browser combination) later and give a feedback.

Best regards!

**Comment by ffatgit** [comment]
Hello again!

So i tested the web-interface with different (real) machines and different browsers (list as follows).
On all machines the "preferred" language is set to the "goal" language (in my case = German).
In the browser and although in the OS settings.
But in no constellation there was the drop down box.

- macOS Monterey (Version 12) with Safari 
- Ubuntu 23.04 with Chromium
- Android 13 (=LineageOS 20) with Chrome based browser.

I checked the language settings in  Raspberry Pi OS (where the owntone-sever is running on):
- German
- de_DE.UTF-8 UTF-8
- even keyboard and WiFI setting = de / 

Any further tip or point to check?

Thank you in forward!

**Comment by ejurgensen** [comment]
I also don't have a dropdown (Safari):

![image](https://github.com/owntone/owntone-server/assets/1156686/4645e29e-13d9-4333-8ebf-26a1149abfd3)

**Comment by hacketiwack** [comment]
Thanks both.
That's absolutely insane!

I also use the following [container image](https://hub.docker.com/r/linuxserver/daapd) inside podman.
I'm not running it under a Raspberry PI however, but a standard Intel machine.

I've tested the web UI successfully on the following platforms:
- Ubuntu 22.10, Chromium (115.0.5790.110 official build snap 64-bit) and Firefox (111.0.1 64-bit)
- Windows 10, Firefox (114.0.2 64-bit), Edge (115.0.1901.188 64-bit)
- macos Ventura 13.5, Safari (16.6 (18615.3.12.11.2)), Firefox (116.0.1)
- iOS 16.6, Safari

That said, it won't help you much to make it work on your side.
Cloud you please more precise on which versions of OwnTone you are using. I guess it's the latest release 28.6.

Moreover, do you receive any error message in the console? And if yes, what are they?

And just out of curiosity, when you go to Music > Artists and open the options, do you see the dropdown menu?
<img width="276" alt="dropdown-menu" src="https://github.com/owntone/owntone-server/assets/13329768/8e19aa8a-cc5c-405d-830f-3b3324d94f72">

And finally, could you try clearing your cache and retry?

I know it's a lot of things to try, but I'm really clueless at the moment.
Thanks

**Comment by ejurgensen** [comment]
I think the reason might be that my browser language is neither en/de/fr/ch. If I set my browser to English then the dropdown does appear. So @hacketiwack you might be able to reproduce by setting your browser language to for instance Spanish (in Chrome it's Settings > Language).

**Comment by hacketiwack** [comment]
I could reproduce the issue. Indeed, it appears when the user has a language that is not in the languages supported by OwnTone.

**Comment by hacketiwack** [comment]
Thanks for having discovered and identified this bug @ffatgit and @ejurgensen.
It is now corrected with the commit [dcbdee6](https://github.com/owntone/owntone-server/commit/dcbdee659861c93af953083c7eb74605f560eaa2).

<off-topic>
@ejurgensen, when do we plan to have a new release of OwnTone?
</off-topic>

**Comment by ffatgit** [comment]
Hello Folks,

sorry, I'm late :grin:!
I checked the given informations on my side with the following steps / result:
- added the language French :fr: in the Firefox ESR (by the way is 102.10.0esr (64-Bit))
- after that the switching the language to French :fr:
- opened the owntone-server web-interface again.
- result 1: no changes and no dropdown field
- I remember the hint to clear the cache
- so I reset / delete the cache with the function of Firefox:
-  "Settings" / "Privacy & Security" / "Cookies and Site Data" / Button "Clear Data"
- close the browser = Firefox and reopen it and the owntone-server page
- result 2: the dropdown field is there :heavy_check_mark: 

But let me ask:
- is it possible, that "only" French :fr: and English :us: is "included"?
- Why? Because, I had only these two in the dropdown field. And in minimum, I would expect "German" :de: although (because it is added in the Firefox settings. (refer to the attached screenshot.

Thank you in forward!

 
![owntone-language-fr](https://github.com/owntone/owntone-server/assets/21111020/08935022-3958-4981-b045-9d891fa14500)

**Comment by hacketiwack** [comment]
@ffatgit you're right. German has been included. However, it is still not yet released in an official version.
This is why you can't see it yet.

It would be actually great to have an official Docker image that is based on the latest sources: some kind of nightly build.

**Comment by ffatgit** [comment]
@hacketiwack okay thank you for clarify this.
It would be more than great, if there is an "offical" docker (compose) or / and a "partner-ship" between e.g. Linuxserver.io and  owntone.
But I know this is work, that "someone" has to do.

For me personal it sadly out of scope.

Thank you, have a nice (rest) weekend!

**Comment by hacketiwack** [comment]
Actually, I have got the build of a Docker image on my todo list since quite a few months now.
Certainly, it's the right time to automate these builds. ☺️

**Comment by ejurgensen** [comment]
Nice with the quick fix @hacketiwack. Looks like you didn't push the rebuilt web interface with the fix? I only see the source file fix.

I'll make a new release to RPi soon, and then a version 28.7 in perhaps a week or two.

**Comment by hacketiwack** [comment]
I will push the rebuilt web interface as well.

**Comment by hacketiwack** [comment]
Done.

**Comment by ejurgensen** [comment]
Excellent, works for me now
