### ISSUE TITLE
iphone remote not working any more

### ISSUE THREAD

**Issue by tropas2001** [owntone/owntone-server#1634]
Recently I had to restart my RPI4 with owntone (28.1) on it (before this it was running very successfully). On reboot i couldn't access my library via the remote app. I've since upgraded the phone to the latest IOS and built owntone (28.6) but this still hasn't fixed the problem. I've also deleted the cache and rebuilt the database but still no luck. I can play music though the webui successfully just not use iOS remote app. Both the RPI and the phone are on the same subnet. I have approx 6500 songs in my library. 

I can pair the library, owntone reports successful but the remote app shows a greyed out library with no name against it...which means i can't click on it. 

shairport works fine.

any ideas?

**Comment by ejurgensen** [comment]
I tried now with a fresh Remote instance and it worked, so doesn't seem to be a general issue. If it appears greyed out it could be because Remote isn't getting the mdns announcement. So maybe check that avahi and dbus are running on the RPi?
