### ISSUE TITLE
No Sound in Web Browser Player

### ISSUE THREAD

**Issue by kulak** [owntone/owntone-server#1636]
Hi, 

I am a bit confused of what to expect from the web browser player.

I was able to get the server to play to Apple HomePod, but I can't get music to play in web browser.

**Comment by hacketiwack** [comment]
Hi @kulak, under the chevron in the right lower corner, you have a menu where you can activate the HTTP stream.

<img width="342" alt="HTTP Stream" src="https://github.com/owntone/owntone-server/assets/13329768/8d8ee906-540b-4768-9943-e38e9acb3f39">

Just click on the icon next to the volume bar.

**Comment by kulak** [comment]
It simply spins:

![image](https://github.com/owntone/owntone-server/assets/853478/df6b7127-8fb4-457e-9a9a-8bd33fa1a5f0)

**Comment by kulak** [comment]
I documented configuration steps I took here: https://wiki.archlinux.org/title/OwnTone

**Comment by hacketiwack** [comment]
It spins until you hit the play button.
This web audio player is not super responsive and the volume doesn't work in Safari. But otherwise it works.
