### ISSUE TITLE
Airplay 2/ALAC encoding not working with ffmpeg 6

### ISSUE THREAD

**Issue by GHTho** [owntone/owntone-server#1640]
I used OwnTone a couple of years ago and it worked fine.  Running 28.5 with pkg add on TrueNAS-13.0-U5.3 in a jail; the UI shows the playlist and the songs look like they're playing (pause, play, next & previous all work); however I don't get any sound from any of my AirPlay devices; the log shows millions of entries while the songs are playing, otherwise the log looks fine; I must be missing something simple because the web has nothing on the error

[2023-08-13 17:03:51] [  LOG]    xcode: Error occurred while encoding: Invalid argument
[2023-08-13 17:03:51] [  LOG]  airplay: Could not ALAC encode frame

Meant to mention dbus & avahi are running

**Comment by GHTho** [comment]
Sure, I will have to figure out the syntax for ffmpeg, never used it

**Comment by ejurgensen** [comment]
`ffmpeg -i track.flac -acodec alac track.m4a`

**Comment by ejurgensen** [comment]
I'll see if I can reproduce. Might be a bug that's was fixed after 28.5, not sure.

**Comment by ejurgensen** [comment]
I was able to reproduce, unfortunately the bug is still there. I will fix it asap.

In the meantime, if you can downgrade ffmpeg to a lower version than 6 it should work.

**Comment by GHTho** [comment]
Thank you! I’ll see about the downgrade 

Mkt

**Comment by GHTho** [comment]
Hate to bother you, but I have a question.  I planned on using this at a big party in 2 weeks.  Trying to see which route to take.  I installed ffmpeg 4.4.3.6, but when I install owntone again, the pkg manager wants to install ffmpeg 6 again; so I locked ffmpeg and then reinstalled owntone, problem is that (I guess the maintainer of the port has a reference to "ld-elf.so.1: Shared object "libavformat.so.60" not found, required by “owntone”.

Trying to figure out if I need to ask the maintainer about the dependency or just have him wait until you fix it and then see if he can upgrade to your new version

Or last resort try to find another solution.

Thank you for your time,
Keith

**Comment by GHTho** [comment]
Finding a work around.  The port maintainer has a May pkg 25.5_1 and try to use libmap

/usr/local/etc/libmap.conf
[/usr/local/sbin/owntone]	# owntone
ibavformat.so.60	libavformat.so.58
libavcodec.so.60	libavcodec.so.58
libavutil.so.58		libavutil.so.56


I made progress; no lib errors anymore, used your May pkg w/libmap; however, my db had been upgraded by the newer version and failed, no big deal, just delete/recreate; except owntone will not recreate my db; Database Init failed

owntone is owner & group with 664 perms


[2023-08-17 08:10:59] [  LOG]       db: Configured to use database file '/usr/local/var/cache/owntone/songs3.db'
[2023-08-17 08:10:59] [  LOG]       db: Could not open '/usr/local/var/cache/owntone/songs3.db': unable to open database file
[2023-08-17 08:10:59] [FATAL]       db: Could not open database
[2023-08-17 08:10:59] [FATAL]     main: Database init failed
[2023-08-17 08:10:59] [  LOG]     main: mDNS deinit
[2023-08-17 08:10:59] [  LOG]     main: Exiting.

drw-rw-r--  2 owntone  owntone  2 Aug 17 08:10 owntone/

Ideas?

**Comment by ejurgensen** [comment]
Not really. Must be a permission problem of some sorts, but you checked that. I notice owntone is trying to use /usr/local/var/cache/owntone, packaged versions should be using /var/cache/owntone, but maybe that is just odd packaging and has nothing to do with the permission issue.

But 25.5 is pretty old anyway, probably from before OwnTone even supported Airplay 2, which your speaker seems to require. So I don't think going back to that will help you.

I have found an (ugly) fix for the issue, which I will post soon, so maybe the best solution is to go back to your original freenas with ffmpeg 6, and try to build Owntone with the fix. Either build yourself or maybe you can get the port maintainer to do it (not sure how that works).

**Comment by GHTho** [comment]
Got it working; multiple problems
I was using the owntone user for perms not daapd
For some reason can't use /usr/local/var/cache/owntone even with the correct permissions had to change to /var/cache/owntone

Thank you for your help, saved the day

Keith
