### ISSUE TITLE
Multiple instance (same pc) and different Spotify account for each instances

### ISSUE THREAD

**Issue by mfauvain** [owntone/owntone-server#1641]
Hi,
I am having issues when trying to authorize Spotify on different owntone instances (different ports). It seems the process only works for owntone.local:3689 and I can't get the process to work when using another port (eg: 36891)
Response is `INVALID_CLIENT: Invalid redirect URI`
Any ideas?

Thx

**Comment by ejurgensen** [comment]
You can't change the callback url, but since the authorization is one-off you can simply stop all the instances, configure all their ports to 3689, then start one, authorize, stop it again, then the same with next. When you are done you can set the ports back to where they were.

**Comment by mfauvain** [comment]
Thx. However when I do so and try to login to a different Spotify account for each owntone instance, it automatically logs to the same Spotify account (even if I do logoff first)

**Comment by ejurgensen** [comment]
I assumed you had configured your instances with different databases? (the credentials are saved in songs3.db, as are the libraries).

If you have done that, then there is no way the Owntone instances would know about eachother's account. Then it might be a browser cookie, then just use private mode.

**Comment by mfauvain** [comment]
I did use different databases. It was the browser cookies... 
Thx. all working now.
