### ISSUE TITLE
Required library permissions?

### ISSUE THREAD

**Issue by xioren** [owntone/owntone-server#1642]
I have this running in docker on my unraid server but it is unable to scan my files. The log is filled with ```unraid lstat() failed: Permission denied``` for all the directories. I have tried changing folder permissions and still get this result. Oddly my jellyfin media server (also a docker container) can scan these files no issue (maybe its not using lstat?). Any ideas?

**Comment by ejurgensen** [comment]
Sorry, no idea what might be going on here. Hope you found a solution.
