### ISSUE TITLE
Using Owntone with authentication directly on the internet

### ISSUE THREAD

**Issue by X-Ryl669** [owntone/owntone-server#1647]
Not an issue per se, but I think it's worth sharing.

I've managed to run Owntone behind NGINX with Authelia to protect against unauthorized users.
Typically, the setup is like this:
```
[      NGINX          ]
[   HTTPS proxy       ] => [ Owntone ]
[   with auth_request ] => [ Authelia ] 
```

I've written a [blog post](https://blog.cyril.by/en/software/example-sso-with-authelia-and-owntone) about how to set it up. There is no change required to Owntone (except in the configuration file for NGINX proxying), so it's relatively easy to implement.

My blog is using markdown, so I guess it should be easy to share the markdown content with you so you can add a wiki page for this setup.

**Comment by ejurgensen** [comment]
Thanks for sharing, that's really great. Very nice praise too. Yes, it would be nice to include, but not sure which way would be the best. You could add a wiki entry with a link to your blog post? Or maybe add it here: https://owntone.github.io/owntone-server/advanced/remote-access/

**Comment by X-Ryl669** [comment]
There are 2 parts: installing Authelia (which, IMHO, shouldn't be in a Owntone wiki) and using Authelia with Owntone. I can send you the markdown of the blog post by email if you want to integrate it in the wiki or in the documentation. Is it possible to make a PR for the documentation (if so, how)?

**Comment by ejurgensen** [comment]
On second thought, I think the best would be link to your blog from https://owntone.github.io/owntone-server/advanced/remote-access/. If the content is included directly in the docs then there is a maintenance issue. If you could share a few lines of description, incl. the link, it would be great. Then I can add it to the docs.

**Comment by X-Ryl669** [comment]
Maybe adding something in the line of
```markdown
## Accessing from Internet for authenticated users

If you intend to access Owntone directly from Internet, it's a good idea to protect it against unauthenticated users. 

[This guide](https://blog.cyril.by/en/software/example-sso-with-authelia-and-owntone) shows a detailed setup tutorial to achieve this securely.
```

**Comment by ejurgensen** [comment]
Thanks a million, it's now added to the docs
