### ISSUE TITLE
arm32v7-latest docker posted 5 days ago is not downloading! 

### ISSUE THREAD

**Issue by stephane77777** [owntone/owntone-server#1649]
Hi,

Is is possible to get owntone 28.7 on a docker with arm32v7 (using raspberry pi 3 with 32 bit debian)?

docker pull linuxserver/daapd or docker pull linuxserver/daapd:arm32v7-latest doesn't give me 28.7.

Regards,
Stephane

**Comment by ejurgensen** [comment]
I don\t know, you will have to ask over at those repositories

**Comment by stephane77777** [comment]
Hi, can you tell me where I ask?
