### ISSUE TITLE
same album name and same album artist, but mess display

### ISSUE THREAD

**Issue by Yumega** [owntone/owntone-server#1653]
**As the subject, the name of the album and artist all the same, in navidrome the display has no problem like this**

![IMG_9799](https://github.com/owntone/owntone-server/assets/61570667/b1147baf-c1e4-474d-8d8a-26becce90d89)

but in owntone, the display like this

![IMG_9800](https://github.com/owntone/owntone-server/assets/61570667/11e7256d-cb96-47e4-b694-c732ea69378b)

**Comment by ejurgensen** [comment]
There isn’t really enough info here to say why this is happening. As you can see from issue template, you should look into the log, possibly use debug level (but please don’t post an entire debug log here).

**Comment by ejurgensen** [comment]
Can you please add line breaks
