### ISSUE TITLE
Spotify Connect volume jumps to 100%

### ISSUE THREAD

**Issue by floodwayprintco** [owntone/owntone-server#1657]
- steps to reproduce and/or logging of the error

In past versions, we always kept Spotify at 100% because the volumes were not in sync. 

Now I can adjust Spotify volume, and it will be instantly reflected in Owntone. This is great but it doesn't work in reverse, though. 

Sometimes the Spotify volume will get set to 100%, and then Owntone will take a song or two before it syncs then BLASTS the music. I can't reproduce this but it seems to be a Spotify issue where volume defaults to 100%.

It seems like the Master Volume in Owntone should be the source of truth, adjusting my Spotify volume down from 100% instead of Owntone UP. 

If I start with both volume at 10%, I can only raise both volumes via Spotify. Then whenever there is a Spotify glitch it cranks the volume to 100%. Shouldn't it check my Connect Speaker (owntone) first and set the volume from there?

- version of owntone
Version 28.6

Compiled with support for ffmpeg, Spotify, librespot-c, LastFM, Without Chromecast, MPD, Websockets, ALSA, Pulseaudio, Webinterface, Regex.

- platform
Raspberry Pi

**Comment by ejurgensen** [comment]
OwnTone doesn't have support for Spotify Connect, so you must be using some in-between software - maybe spocon? This would also be the software that channels the volume changes to OwnTone. So the first thing to do would be to check if it is forwarding those changes correctly. If not, you have to raise the issue with that project. You can probably see in OwTone's log what it is receiving.

**Comment by floodwayprintco** [comment]
Thank you! Yes, it is Spocon in between, which has had some issues in the past. 

Could it be a feature idea for Owntone? It seems like it could prevent big jumps in volume from Pipes. 

I don't have much experience in the logs but if I keep having issues I will have to look deeper. Thanks again

**Comment by ejurgensen** [comment]
> Could it be a feature idea for Owntone? It seems like it could prevent big jumps in volume from Pipes.

Yes, I actually did start the work, using libspotify as reference. However, I understood Spotify was changing protocol, and libspotify wasn't ready with the new one, and I didn't want to spend time implementing a protocol that is being deprecated. So I put it on hold.

**Comment by floodwayprintco** [comment]
This is still happening. It connects to my Owntone server and ignores the current volume. It sets it to 100% the default of the web app. It's making my Owntone setup unusable along with the Spocon issue.
