### ISSUE TITLE
Can't save playlists - "not a virtual path for configured library directory"?

### ISSUE THREAD

**Issue by otokuma** [owntone/owntone-server#1658]
Hi, I'm trying to create playlists from the web interface but getting this error in the log:

> [2023-09-26 23:25:11] [  LOG]     scan: Path '/mnt/mediastorage/iTunes/Playlists/test.m3u' is not a virtual path for a configured (local) library directory.
> [2023-09-26 23:25:11] [  LOG]      web: JSON api request failed with error code 500 (/api/queue/save?name=test)

I'm unsure what this means specifically. My library directory exists in

>  Directories to index
>         directories = { "/home/leo/Desktop/mediastorage/iTunes" }

and the playlists are configured to be saved in

>  A directory in one of the library directories that will be used as th>
>         # playlist directory. OwnTone creates new playlists in this directory i>
>         # a playlist name is provided (requires "allow_modify_stored_playlists">
>         default_playlist_directory = "/home/leo/Desktop/mediastorage/iTunes/Playlists>

where "mediastorage" is an external drive that I have mounted to a directory as written in this article:

https://pimylifeup.com/raspberry-pi-mount-usb-drive/

which I suspect is the core of the problem, as the error code gives the /mnt/ path, but I don't know why or how to fix it. I have tried with both the /mnt/ path and the /home/ path, and neither work.

I have also tried setting a directory outside of the external drive entirely, but that also gives back the same error.

Thank you in advance!

**Comment by ejurgensen** [comment]
Just checked the code, looks to me like changing the "directories" setting to "/mnt/mediastorage/iTunes" should solve the issue (even though OwnTone should ideally also work with the other path). You say that you have tried this without success, so not sure why that might be.

**Comment by otokuma** [comment]
Hi, that fixed it! I had only tried both directories as the playlist directory, not the library directory. Changing 

> Directories to index
> directories = { "/home/leo/Desktop/mediastorage/iTunes" }

to

> Directories to index
> directories = { "/mnt/mediastorage/iTunes" }

solved it.

Not sure why OwnTone will use the Desktop shortcut for the library but not the playlists, but it's all good now. Thank you so much!
