### ISSUE TITLE
Integration into Apple Music / Where and how to select server

### ISSUE THREAD

**Issue by ulfw** [owntone/owntone-server#1664]
Hi, I have just found owntone and want to use it to share my local music.
The docker instance ins running on an synology.

But I can not select the library in apple music on osx sonoma. Where can I find the "select dropdown"?

How can I debug, why my server is not been found by Apple Music?

Thanks

**Comment by hacketiwack** [comment]
Hi @ulfw, you can find your OwnTone library when clicking the chevron down icon next to the library item in the menu on the left in Apple Music (formerly iTunes). See below.

<img width="212" alt="Change Music Library" src="https://github.com/owntone/owntone-server/assets/13329768/ce48ee7e-16b0-412e-838d-f24400572767">

**Comment by ulfw** [comment]
And if I cant see (dont have) this chevron down icon? I cant select anything. Which port does daapd use?

**Comment by hacketiwack** [comment]
Default port number is 3689.

**Comment by ulfw** [comment]
Is it possible that I have to unblock a port or enable a special feature?

**Comment by ejurgensen** [comment]
It's more likely to be an mdns issue. If it doesn't show the announcement isn't making it to your mac.

**Comment by ulfw** [comment]
I had to modify the config value for "trusted_networks", its set to "any" now. And it works.
