### ISSUE TITLE
Systemd service should have a User and Group rule and/or avoid starting as root.

### ISSUE THREAD

**Issue by X-Ryl669** [owntone/owntone-server#1666]
Usual POSIX user management policy is to use groups to "mark" files that can be accessed by multiple users.
Typically, let's say you have 4 users in your music collection. Your users will all be in the `music` group, so they can access the music from each other.

Owntone, when started via systemd, should run with this group.

Right now, Owntone is behaving unconventionally: it starts as root and will downgrade to the user specified in its configuration file. Yet, if run with the final user directly, it's working perfectly, so I wonder if we shouldn't drop this completely, since it doesn't seem it's required, or it should also downgrade to the specified group in the configuration file too. By doing only half of the work, it's clunky and doesn't work the way POSIX intended to be used.

**Comment by ejurgensen** [comment]
How would this work for systems that don't have systemd?

**Comment by X-Ryl669** [comment]
I don't know. 

I'm not sure whose responsibility it is to run a software with the right credentials. Is is the software responsibility to start at root and downgrade to whatever is its configuration file, or for the init system to trigger with the right credentials at first?

I think from a security point of view, the latter is better since the init system is usually well audited for security and the less software you have that requires root, the better.

Anyway, either way, the current situation isn't working, since it's not doing the setguid stuff by itself and the systemd isn't doing it either.

**Comment by ejurgensen** [comment]
I agree that in principle it's better that the OS starts of the daemon with the end user/group, but I also see there is a bunch of stuff being done before the priviliges are dropped, and I don't think it's worth taking risks by removing that.

Aside from the principle of it, I  don't quite agree there is an issue with groups. At least I haven't seen any issues with the current implementation, and I can see it's been around for 12 years. It does include group handling with setegid, and also seems to match what the start-stop-daemon does.
