### ISSUE TITLE
Indentation in C source code

### ISSUE THREAD

**Issue by X-Ryl669** [owntone/owntone-server#1667]
I have trouble with the indentation rules in the C code. I can't set my editor to fit the rules, there are too "alien" so such logic isn't implemented and prone to error.

Would you accept to change to a space only based indentation, which is much better supported in code editors?

I've written a tool that's implementing the current (mixed space & tabs) indentation rules here:
```python
#!/bin/python3
import sys


def replaceTab(line):
    spaceLine = line.rstrip().replace('\t', '        ')
    meat = spaceLine.lstrip()
    # Then convert left spaces to tab following the rules:
    indentation = len(spaceLine) - len(meat)
    tabCount = int(indentation / 8)
    return '\t' * tabCount + ' ' * int(indentation % 8) + meat

def main():
    dryRun = False
    if len(sys.argv) < 2:
        print("Usage is {} [-n] fileToFix".format(sys.argv[0]))
        return 0

    file = sys.argv[1]
    if (file == '-n'):
        dryRun = True
        file = sys.argv[2]

    print("Processing: {} {}".format(file, "dry run" if dryRun else ""))
    outLines = []
    with open(file, 'r') as f:
        lines = f.read().split('\n')
        for line in lines:
            outLines.append(replaceTab(line))

    if dryRun:
        for line in outLines:
            print(line)
    else:
        with open(file, 'w') as f:
            f.write('\n'.join(outLines))
    
if __name__ == '__main__':
    main()
```

But running on all C files modifies them, some lines are offset by one additional (or -1) space than expected, likely because the indentation is wrong initially.

**Comment by ejurgensen** [comment]
Sorry, forgot to answer this when you asked about it in the PR, but I'm not going to change the indentation, even though it's weird.

**Comment by X-Ryl669** [comment]
Ok, so would you accept a PR that's running this script on each file so it follow the same rules everywhere (and maybe add it to the tool folder so it can be run as a git pre-commit hook?)
