### ISSUE TITLE
Parsing m3u with BOM skips first line

### ISSUE THREAD

**Issue by gitteric** [owntone/owntone-server#1674]
Issue:
When a playlists contains a valid path at the very first line, and has a BOM, the first entry is ignored.

Example m3u file, utf8 with BOM, containing following two lines:
`..\Mp3_Tagged\Soundtracks\Chinatown\01 - Jerry Goldsmith - Love Theme From Chinatown.mp3`
`..\Mp3_Tagged\Other\Chet Baker\One Night in Tokyo\06 - Chet Baker - Almost Blue.mp3`
Results in only the second line beeing recognized

No big deal, since there is no problem when a playlist starts with some meta info (#...), but  a fix in a future release would be great :)

**Comment by ejurgensen** [comment]
Thanks for reporting. Should be fixed now.
