### ISSUE TITLE
AppleTV 4K Audio Playback is silent

### ISSUE THREAD

**Issue by Traace** [owntone/owntone-server#1675]
Description:
When playing music via AirPlay to a AppleTV 4k, the audio stays silent.

Steps to reproduce:
1. Get a AppleTV 4K running tvOS 17.1 and two Homepods 2 running audioOS 17.1.
2. Create a Stereo Pair and setup a fixed direct connect with AppleTV. They are now appear as only one AirPlay Device in the network: "Traace aTV"
3. Install owntone from .deb Packages or via Docker to a Debian Bookworm Server
4. Import Music Library to owntone
5. Pair owntone with AppleTV 4-Digit Pin
6. Start to play some music via AirPlay to AppleTV from Webinterface
7. Notice that AppleTV doesn't output any audio. Notice that the Homepods light up for a breef moment. Notice that meanhile owntone repots a happy playback.

All Devices are in the same subnet. There is no firewall between them.

Logs:
[owntone.log](https://github.com/owntone/owntone-server/files/13183074/owntone.log)

What I already tried to fix the issue:
- Disable IPV6
- Moved from .deb installation to docker
- Switch between AirPlay Version 1 & 2
- Home Settings: Allow Playback from anywhere, without password
- Restarted Homepods
- Restarted AppleTV
- Verified that playback works fine from MacOS 14.1 and iOS 17.1

Version of owntone: 
28.8

Platform: 
Debian Bookworm X86_64

**Comment by ejurgensen** [comment]
Thanks for a good report.

Playing to my ATV4 with tvOS 17.1 works ok, both with Airplay 1 and 2, but mine isn't in a group. So I think that is likely the reason the results are different. There is some talk about this in issue #1413 where it looks like people have varying luck with playback. Unfortunately, there hasn't been a breakthrough in finding a solution.

I'll close this issue so as to keep the discussion on making grouping work on the other issue.
