### ISSUE TITLE
Ideas on Apple Music library sync

### ISSUE THREAD

**Issue by xavier7179** [owntone/owntone-server#1680]
I searched all over the internet, and I am trying to figure out if a solution exists, so I am trying here. 

I wanted to move my library remote, and OwnTone is perfect. With my "local" library, I could also sync music on iPhone(s) to access them offline, e.g., using CarPlay. This is not possible for shared libraries such as OwnTone. Is it correct?

**Comment by Porco-Rosso** [comment]
Just some ideas for you, as this is what I currently do.

My main music library lives inside apple's Music app.

1. I use this to export the playlists as .m3u files with relative paths to the music files (so the library is portable) https://github.com/Porco-Rosso/iTunes-m3u8-Playlist-Syncer

2. I sync the library to my NAS/home server using whatever you like (rsync, [resilio sync](https://www.resilio.com/individuals/) or [syncthing](https://syncthing.net/))

3. On the NAS I have owntone pointed to the library. It automatically picks up the library files and playlists. I use this to play music around the house.

4. On the NAS I have [Navidrome](https://github.com/navidrome/navidrome/) pointed to the library. This allows me to listen to the library over the web, or on the go with [substreamer](https://substreamerapp.com). 

The only drawback is that you need to update the playlists every time you make any changes, so the sync is not automatic (at least for playlists). Hope that helps.

**Comment by Porco-Rosso** [comment]
re-reading your comment, I think Navidrome+Substreamer could be a good fit for you. Substreamer allows you to download the files for offline listening.

**Comment by ejurgensen** [comment]
Yes, OwnTone doesn't support Apple's Home Sharing, which I think is (or was) the name of the system that allows you to share media between Apple Music on various devices. I don't think there are any open source solutions that have support for it.

@Porco-Rosso's alternative sounds like a good alternative method, so I will close the issue.
