### ISSUE TITLE
[web] Review the "Browse" page

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1685]
**Context**
Currently, under the Music page, there is a tab called "Browse".
It can mislead users to think that they can browse the music.
However, under this tab, they would only be able to see the last added albums and the previously played tracks.

**Suggestion**
There are two possibilities in my opinion to make things clearer:

A. Change the name of the tab from "Browse" to "History"
B. Split the playback history and the new additions into two separate tabs

What is your idea on that matter?

**Comment by ejurgensen** [comment]
I never noticed this, but yes, you are right. I would say just changing the caption to "History" would be the best.
