### ISSUE TITLE
Unrecognized JSON API request: '/api/library/tracks/undefined'

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1688]
I've recently migrated my music (and many other things) from a 2TB drive to a new 6TB drive. I'm not sure if it's relevant, or it's more specific to the latest Owntone updates that include lyrics in the web player. My point being there are several factors in play here, but I do know that when my library was offline, and I was using Owntone only with Spotify, I still had this error repeating.

The error in the subject of this issues keeps repeating and showing in the web interface. With the log at debug level, I'm only getting this info:

```
[2023-11-23 12:30:57] [DEBUG]      web: JSON API request: '/api/library/tracks/undefined'
[2023-11-23 12:30:57] [  LOG]      web: Unrecognized JSON API request: '/api/library/tracks/undefined'
```
![image](https://github.com/owntone/owntone-server/assets/17277745/8432023d-de38-4580-8119-6f048b8779d8)

Chrome inspector tools is pointing to index.js and the only thing I can find in there specific to `api/library/tracks/` is this:
```
    library_track(e) {
        return pe.get("./api/library/tracks/" + e)
    },
    library_track_playlists(e) {
        return pe.get("./api/library/tracks/" + e + "/playlists")
    },
    library_track_update(e, t={}) {
        return pe.put("./api/library/tracks/" + e, void 0, {
            params: t
        })
```
Other than these errors, everything seems to be working great at least in terms of my regular usage.

Thanks for looking. What can I do to provide more info?

**Comment by hacketiwack** [comment]
Thanks for reporting this. If I remember well, I also came across this error, but I thought it was due to my setup.
I will have check that out.

**Comment by cdlenfert** [comment]
Thank you for the quick reply. When I first noticed this error, I restarted Owntone multiple times, I did a `git pull` and rebuilt Owntone to get the latest changes. The issue was still present through all of that. And that's when I captured and shared the issue above. 

However, I just changed my debug log back to "log" level, and restarted Owntone, and now the `Unrecognized JSON API request` is not occurring anymore. It was before with the log on "log" level, and on "debug" and now that I'm back at "log" level, it's just not happening anymore...

**Comment by hacketiwack** [comment]
Thanks for the info. Well, even if I set to the log level `info` I still get the error messages...

**Comment by hacketiwack** [comment]
I pushed a temporary fix that avoids this error. I will investigate further tomorrow.
But as you say, it seems to be a problem caused by the introduction of lyrics.
Thanks again for reporting.

**Comment by hacketiwack** [comment]
@cdlenfert I would really appreciate if you could test and give your feedback. Thanks

**Comment by cdlenfert** [comment]
The errors did come back before trying the new fix. I've updated to the new fix and so far no errors. I'll report back if they return. Thanks again!

**Comment by hacketiwack** [comment]
Thanks for the feedback. I'll keep you posted.

**Comment by cdlenfert** [comment]
I spoke too soon. Still getting the unrecognized API error:
```
2023-11-23 19:51:59] [  LOG]      web: Unrecognized JSON API request: '/api/library/tracks/undefined'
[2023-11-23 19:51:59] [  LOG]      web: Unrecognized JSON API request: '/api/library/tracks/undefined'
[2023-11-23 19:56:53] [  LOG]      web: Unrecognized JSON API request: '/api/library/tracks/undefined'
```

**Comment by hacketiwack** [comment]
It should be properly corrected now. It was indeed introduced by the lyrics features, which was considering Spotify songs as tracks of the library.

@cdlenfert can you please test again on your side? Thanks in advance.

**Comment by cdlenfert** [comment]
Updated this morning. I’m not seeing any errors at this point. Thank you!

**Comment by hacketiwack** [comment]
Amazing! Thank a lot.
