### ISSUE TITLE
how to restart stream automatically after each service (or host) restart?

### ISSUE THREAD

**Issue by alirezadigi** [owntone/owntone-server#1691]
Hi, thanks for your great project.

I use a VM to run the Owntone server, and sometimes I may need to reboot the VM, the VM's host, or the `Owntone service` itself. I'm building a local internet radio.

After each restart, I should log in to the HTTP interface to restart the stream, select the "playlist," and enable the *repeat all* option, among other things.

Additionally, I want to utilize the `stream.mp3` file to have an internet radio.

I'm looking for a way to ensure that the music continues playing after each restart, even if it's another track, rather than simply stopping the music and requiring me to manually play it.

**Comment by frankusb** [comment]
That seems doable from the [command line](https://owntone.github.io/owntone-server/json-api/).

**Comment by alirezadigi** [comment]
@frankusb, thanks a lot.

So, should I use crontab, right?
And is there any more automated way?

**Comment by alirezadigi** [comment]
Also, I don't know when the service restarts, and I don't think it can be done with crontab.

**Comment by frankusb** [comment]
I'm not a Linux expert but I would think you could make a service that is dependent on the owntone service. Or worst case you could use the [/api/player](https://owntone.github.io/owntone-server/json-api/#get-player-status) to poll.

**Comment by alirezadigi** [comment]
thanks , i'll try creating service

**Comment by alirezadigi** [comment]
but i think this issue can be open , because of kind of feature request...

**Comment by ejurgensen** [comment]
Like @frankusb suggests, you can do this with command line, so by making a startup script (a service file) that depends on owntone and runs e.g. mpc commands to start playback. You can google the details on how to do that. It's not a feature that will be integrated into the server.

**Comment by alirezadigi** [comment]
@ejurgensen thanks a lot
