### ISSUE TITLE
[outputs] master volume not independant when updating for remote device (ie Soundbridge) 

### ISSUE THREAD

**Issue by whatdoineed2do** [owntone/owntone-server#1697]
My main PRI system has the following known outputs as seen by the server:

* a onboard DAC
* a headphone port
* a Roku Soundbridge (remote)

Using the web UI to change the volume, we get some odd behaviour:
* When all outputs are active, we can independantly change the volume of the _Soundbridge_ (to 75%) and _master_ volume remains untouched  (@ 99%) - similarly the other outputs
* When the _DAC_ and _headphone_ outputs are **individually muted** (`selected = false` with _Soundbridge_ and _master_ being the only active speaker), repeating above volume change to _Soundbridge_  (say to 50%)  results in the the **_master_ volume being matched** (now at 50%)

This can be verified using the REST api too, `curl -XPUT "http://ownetone.local:3689/api/player/volume?output_id=....&volume=50"`

I would expect that _remote_ outputs/speakers to be treated indeoendantly.  Any pointers for where I can investigate this?  Or is this expected behaviour.

I can't test with a Chromecast at this time but it may have similar results.  I do have a [Soundbridge test harness](https://github.com/whatdoineed2do/forked-daapd/blob/master/tests/rcproku.c) that we can see this issue.

**Comment by hacketiwack** [comment]
If I understand properly, it happens only with the web UI.
I would then have a look at these two files mentioned below. This is where the volume is set.

- [NavbarItemOutput.vue](https://github.com/owntone/owntone-server/blob/master/web-src/src/components/NavbarItemOutput.vue)
- [NavbarBottom.vue](https://github.com/owntone/owntone-server/blob/master/web-src/src/components/NavbarBottom.vue)

**Comment by whatdoineed2do** [comment]
Sorry, to clarify - this happens with both the web ui AND the REST api

**Comment by whatdoineed2do** [comment]
A bit more testing .. and amybe its not as problematic as it seems.

Let say the situation is this:

* Initial state:

|output|state|vol|
|-|-|-|
|**master**|--|100|
|DAC|enabled|100|
|Headphone|enabled|85|
|Soundbridge|enabled|60|

* Update Soundbridge to 42

|output|state|vol|
|-|-|-|
|**master**|--|100|
|DAC|enabled|100|
|Headphone|enabled|85|
|Soundbridge|enabled|**42**|

* Update DAC to 90

|output|state|vol|
|-|-|-|
|**master**|--|**90**|
|DAC|enabled|**90**|
|Headphone|enabled|85|
|Soundbridge|enabled|42|

* Disable DAC and headphones, master matches soundbridge

|output|state|vol|
|-|-|-|
|**master**|--|42|
|DAC|disabled|90|
|Headphone|disabled|85|
|Soundbridge|enabled|42|

Any changes to sounbrige are now matched to master

* change Soundbrige

|output|state|vol|
|-|-|-|
|**master**|--|72|
|DAC|disabled|90|
|Headphone|disabled|85|
|Soundbridge|enabled|72|

* enable DAC (which has louder volume), master matches loudest.  this is consistent if sounbridge was higher, its the loudest volume that becomes master vol setting

|output|state|vol|
|-|-|-|
|**master**|--|90|
|DAC|enabled|90|
|Headphone|disabled|85|
|Soundbridge|enabled|72|


Given this, I think this is appropriate behaviour - its was just not quite what i expected when i saw it in the UI
