### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by electrickite** [owntone/owntone-server#1700]
Any chance a new release could be created? I'm hoping we can get the FreeBSD crash fix from October into the ports tree.

**Comment by ejurgensen** [comment]
Sure, maybe in about 3 weeks time. There have been some recent changes that need a bit more testing.

**Comment by electrickite** [comment]
That would be great, thanks for all your work on this project!

**Comment by ejurgensen** [comment]
I've published a new release now
