### ISSUE TITLE
Spotify refresh token messages in log

### ISSUE THREAD

**Issue by electrickite** [owntone/owntone-server#1701]
When viewing the owntone log, I see many repeated log entries regarding Spotify tokens:

    [2023-12-22 10:44:26] [  LOG]  spotify: No spotify refresh token found

These seem to be added when the web UI is being used. I don't have Spotify configured, so I don';t believe there is any way to remove these messages other than changing the log level to exclude "log" messages. 

Could these Spotify token log entries be changed to "info" or "debug" to remove clutter from the logs?

owntone version: 28.8

**Comment by ejurgensen** [comment]
Yes, you right, there is no reason for that logging. The above commit should removed it going forward.
