### ISSUE TITLE
Owntone server does not start (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by badewanne1234** [owntone/owntone-server#1704]
Hi 

I had a owntone server installed previously and it was running nicely. I now moved it to a new VM on Ubuntu 20.4 but I cant get it running.

After the normal/standard installation procedure (https://owntone.github.io/owntone-server/building/) for Ubuntu, I also added avahi-daemon via `sudo apt install avahi-daemon`

Starting the owntone server does not work and I cant work it out whats wrong, here is whats displayed after trying to start the server with `sudo systemctl start owntone`, followed by `sudo systemctl status owntone`:

```
* owntone.service - DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote
     Loaded: loaded (/etc/systemd/system/owntone.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2023-12-30 23:07:43 UTC; 2s ago
       Docs: man:owntone(8)
    Process: 348 ExecStart=/usr/sbin/owntone -f (code=exited, status=1/FAILURE)
   Main PID: 348 (code=exited, status=1/FAILURE)

Dec 30 23:07:43 owntone systemd[1]: owntone.service: Main process exited, code=exited, status=1/FAILURE
Dec 30 23:07:43 owntone systemd[1]: owntone.service: Failed with result 'exit-code'.
```
What am I missing? Any help is highly appreciated, thank you so much! :)

**Comment by ejurgensen** [comment]
What does the log say?

**Comment by badewanne1234** [comment]
/var/log/owntone.log is even empty, I have set the logging level to debug but its empty. looks like its crashing even before?

**Comment by badewanne1234** [comment]
One more thing which might be related but I'm not sure, I have followed the installation script (standard...) but there is an issue with this too: 
`/etc/init.d/owntone restart` throws just this: `-bash: /etc/init.d/owntone: No such file or directory`

**Comment by ejurgensen** [comment]
What's the output of:
'sudo /usr/sbin/owntone -f'? If nothing then what about '/usr/sbin/owntone --help'?

**Comment by badewanne1234** [comment]
2023-12-30 23:54:39] [FATAL]   config: Could not lookup user myusername: Success
[2023-12-30 23:54:39] [FATAL]     main: Config file errors; please fix your config

I changed the username from "owntone" to the user that I have setup for the symlink user to my NAS server with the PW in fstab, looks like this is not correct? Is the user in the config a user that has been created by the script initially and must remain "owntone"?

**Comment by ejurgensen** [comment]
You can set the user to another user, but it looks like your "myusername" isn't working correctly.

**Comment by badewanne1234** [comment]
Is is a requirement that the user that is used for the NAS connection is the same as the owntone user?

**Comment by badewanne1234** [comment]
For reference. it can be entirely different - worked it out finally, it was a problem of the LXC container of Proxmox: it was not a priviliged, but an unprivileged container, thus it could not establish the SMB connection to the NAS share.
