### ISSUE TITLE
[spotify] spotify_login never used

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1705]
The following [method](https://github.com/owntone/owntone-server/blame/d6f6508638e191ca7d81076293570d0db2a69e37/src/inputs/spotify.c#L75) `spotify_login()` seems to be unused.
Should it be considered for removal?

```c
int
spotify_login(const char *username, const char *password, const char **errmsg)
{
  struct spotify_backend *backend = backend_set();

  if (!backend || !backend->login)
    return -1;

  return backend->login(username, password, errmsg);
}
```

**Comment by ejurgensen** [comment]
Indeed, I have removed it now (also one other unused function).
