### ISSUE TITLE
Feature: Disable web interface in config

### ISSUE THREAD

**Issue by davidandreoletti** [owntone/owntone-server#1708]
Hi,

The setup is:
- owntone gets its music stream from a shairport-sync named pipe
- owntone outputs music to some default output

In this setup, there is no need to run a web interface to control playback.

https://github.com/owntone/owntone-server/blob/b6ad73e1fa57a47907d1e84067116025dadf0f22/owntone.conf.in#L35 Conf file does not indicate it is supported.

Do you consider adding support for disabling (a) the web interface ?

**Comment by ejurgensen** [comment]
I don't think such an option would be of much value. The http server consumes very little resources when not used. It is also used for much more than the web, so disabling it would disable many parts of OwnTone.
