### ISSUE TITLE
Excluding AirPlay devices that contain a single quote in the name

### ISSUE THREAD

**Issue by jeakob** [owntone/owntone-server#1710]
Is it possible to exclude AirPlay devices that contain an apostrophe? For example Tom's HomePod

**Comment by ejurgensen** [comment]
Yes, like this:

```
airplay "Tom's HomePod" {
        exclude = true
}

```

**Comment by jeakob** [comment]
This doesn't appear to work in my config:

```
airplay "Tom's ATV" {
        exclude = true
}
```


![image](https://github.com/owntone/owntone-server/assets/39410668/86413f20-704e-42c2-b679-1e017e9119bd)

The device name in OwnTone is uppercase, which doesn't match the actual name in the home app.

**Comment by ejurgensen** [comment]
If you go to http://[owntones ip]:3689/api/outputs you can see the exact name and copy/paste it

**Comment by hacketiwack** [comment]
@jeakob, another way to know the real name from the web interface by selecting the name of your device and inspect the HTML element. It will show you the real device name.
Technically, the capitalisation is done by a style on the web interface.
