### ISSUE TITLE
Spotify Connect keeps pausing.

### ISSUE THREAD

**Issue by floodwayprintco** [owntone/owntone-server#1711]
Please try to provide the following:

- steps to reproduce and/or logging of the error:

I'm having trouble with my Owntone server. I only use it with Spotify connect. 

The issue I have is that it will randomly pause. After a while of playing, maybe an hour sometimes, it will pause. Hitting play on Owntone doesn't bring it back. It sometimes needs a full restart or to disconnect Spotify, reconnect and start a new track.|

I ran a log and these errors stood out to me:

```
Jan 12 12:07:51 pi-music-server owntone[553]: [2024-01-12 12:07:51] [  LOG]   laudio: Failed to attach mixer 'default': No such file or directory
Jan 12 12:07:51 pi-music-server owntone[553]: [2024-01-12 12:07:51] [  LOG]   laudio: Could not open mixer 'default' ('(null)')
Jan 12 12:07:53 pi-music-server owntone[553]: [2024-01-12 12:07:53] [  LOG]  artwork: Source 'stream' returned an error for 'spotify'
Jan 12 12:07:55 pi-music-server owntone[553]: [2024-01-12 12:07:55] [  LOG]  artwork: Request to 'file:/tmp/owntone.IN8X3u.jpg' failed with code 0
Jan 12 12:07:55 pi-music-server owntone[553]: [2024-01-12 12:07:55] [  LOG]  artwork: Request to 'file:/tmp/owntone.IN8X3u.jpg' failed with code 0
Jan 12 12:07:55 pi-music-server owntone[553]: [2024-01-12 12:07:55] [  LOG]  artwork: Source 'stream' returned an error for 'spotify'
```

- version of owntone: Version 28.6

- platform Rasperry Pi 4B+. It was on an older 3 before with SD card and I thought it might be that. The issue persists after my SSD and Pi upgrade.

**Comment by floodwayprintco** [comment]
I have posted the issue to Spocon as well: https://github.com/spocon/spocon/issues/62

There is a log there as well. Maybe that will help too.

**Comment by hacketiwack** [comment]
@floodwayprintco looking at the error messages you have posted here and on the spocon repository, it seems the problem is not related with OwnTone.
You may be lucky to try with the latest version of OwnTone first.

**Comment by floodwayprintco** [comment]
> @floodwayprintco looking at the error messages you have posted here and on the spocon repository, it seems the problem is not related with OwnTone. You may be lucky to try with the latest version of OwnTone first.

Thank you. Did the logs make you think it was most likely Spocon, or not that either?

You're right, I just updated Spocon so I should update Owntone too.

**Comment by ejurgensen** [comment]
The errors in OwnTone's log just mean that local audio won't work, but I assume you aren't using that anyway, and that there was a problem fetching artwork. The latter might be a bug, it wouldn't be the cause of the playback problem you have.

**Comment by floodwayprintco** [comment]
> Member
> ###

Thanks for confirming. Can you look at my Spocon issue and give your opinon? Do you think it is Spocon?

I updated Owntone though, so I will keep testing!

**Comment by floodwayprintco** [comment]
There is no end in sight to this issue. It still happens all day long. 

I have an issue on Spocon and it's not getting any attention.

Is there any other way to send my Spotify Connect to Owntone for whole-house audio?

**Comment by ejurgensen** [comment]
Not sure. Maybe use librespot + cpiped to make it write to a pipe? But then you probably won't have volume control via Spotify Connect, so perhaps not really a solution.

I did start work on integrating Spotify Connect into OwnTone, but I had to abandon it. At the time, they were changing to a new protocol, and since librespot hadn't implemented it yet I had no reference to use. And I didn't want to spend time on a protocol that might become deprecated.

**Comment by floodwayprintco** [comment]
> Not sure. Maybe use librespot + cpiped to make it write to a pipe? But then you probably won't have volume control via Spotify Connect, so perhaps not really a solution.
> 
> I did start work on integrating Spotify Connect into OwnTone, but I had to abandon it. At the time, they were changing to a new protocol, and since librespot hadn't implemented it yet I had no reference to use. And I didn't want to spend time on the old protocol since it might become deprecated.

Thank you. From my understanding Spocon writes to a pipe and Owntone plays it. The problem is that Spocon is not working anymore. I'm not savvy enough to build anything custom myself.

I definitely need the volume control but thank you for the tip. 

There is another user with the same Spocon issue but it seems like we are the only two using it this way.
