### ISSUE TITLE
Easiest way to remove Chromecast?

### ISSUE THREAD

**Issue by floodwayprintco** [owntone/owntone-server#1714]
I recently updated my Owntone server as part of a troubleshooting process - but I forgot to disable Chromecast. I don't want my Google Speakers showing up in this Airplay list.

Can someone please advise the simplest way to remove Chromecast? Do I need to fully remove Owntone and start over?

**Comment by Porco-Rosso** [comment]
You should be able to exclude them with a simple line in the config.
See here: https://github.com/owntone/owntone-server/blob/9eb391be8b8e064785fe41482eb2d5b1799ca036/owntone.conf.in#L365

**Comment by floodwayprintco** [comment]
Thank you, but is there any way to remove it completely? I want to avoid
manually excluding speakers especially if we decide to add new ones. I only
use them for TTS never for Owntone.

--

Cory Beal



*He/HimProduction Manager @ Floodway Print Company LTD.*

https://floodwayprintco.com/

**Comment by ejurgensen** [comment]
Then you would have to make a build yourself and use `./configure --disable-chromecast`
