### ISSUE TITLE
audioversatz / audio offset / delay

### ISSUE THREAD

**Issue by pisabird** [owntone/owntone-server#1716]
Hello, 

First of all, thank you so much for this very great work!

I have different devices. One of them has a delay of approx. 1 second.
It would be great to implement  "audioversatz / audi offset / delay" so that all speakers have the same timeline.
Thank you
Rolf

**Comment by ejurgensen** [comment]
You didn't specify device types, but I will assume they are Airplay? If so you cannot specify a delay because it shouldn't be necessary. OwnTone communicates timing to them, and if that doesn't result in them being in sync I'm tempted to say one of them isn't working as it should.

**Comment by pisabird** [comment]
I am using AirPlay and Chromecast. AirPlay has a delay of more than one second.

**Comment by ejurgensen** [comment]
You can adjust Chromecast in the config file like this:

```
chromecast "YourSpeakerName"
{
  offset_ms = 1000
}
```

Note there is still a risk of drift.

**Comment by pisabird** [comment]
is this also working for Version 28.6?

**Comment by ejurgensen** [comment]
Yes

**Comment by pisabird** [comment]
Hello Sir,
The offset for Chromecast is not working for me.

Can you please have a look into it?

chromecast "SHIELD" {
        # OwnTone's volume goes to 11! If that's more than you can handle
        # you can set a lower value here
#       max_volume = 11

offset_ms = 12000


        # Enable this option to exclude a particular device from the speaker
        # list
#       exclude = false

        # Name used in the speaker list, overrides name from the device
#       nickname = "My speaker name"
}


Thank you!
