### ISSUE TITLE
delete log file. not will be create again

### ISSUE THREAD

**Issue by Jumbo125** [owntone/owntone-server#1717]
Hy guys

Thank you for this great project.

I had some problems with the airplay function. So i read the log file, which was fully of text. So i deleted it. It will be not create automatically. when i create the log file by msyself, owntone will be write in it....

Has anybody a soultion?
Thank you

**Comment by ejurgensen** [comment]
You need to restart OwnTone for the log to be recreated. If you did that, and it didn't happen, then the user Owntone is configured to use doesn't have write permission in the directory.

**Comment by Jumbo125** [comment]
thank you!
it didn't work, cause i enabled "password" and left it empty
