### ISSUE TITLE
No sound on macOS AirPlay2 receiver

### ISSUE THREAD

**Issue by bugprogrammer** [owntone/owntone-server#1720]
I am using Owntone 28.9，macOS Sonoma 14.3，and I have a music library set up under debian 12，I have disabled IPv6, as well as raop for this device。No exceptions seen in the logs。

**Comment by clumsyCoder00** [comment]
I just ran into this issue tonight. shairport-sync destinations work correctly.

**Comment by bugprogrammer** [comment]
> I just ran into this issue tonight. shairport-sync destinations work correctly.

My English is not good, so I use translation software. This problem has been around for a long time, and I have been studying it on and off for a while. I am currently also using hairport-sync installed by brew. Now a major pattern has been discovered. This is what happens if the Mac has dual network cards. First turn off a network card, start owntone, and then start the network card, it will be normal. In other words, every time you restart owntone, you must first turn off a network card.
------------------------------------------------------------------------------------------------------------------------
我的英文不好，用的翻译软件。这个问题很久了，我断断续续的研究了一段时间。我目前也在用brew安装的shairport-sync。现在发现了一个重大规律。如果Mac具有双网卡，就会这样。先关闭一张网卡，启动owntone，再启动网卡，就是正常的。也就是说，每一次重启owntone都要先关闭一张网卡。

**Comment by ejurgensen** [comment]
I can't do much about this, since I wouldn't be able to reproduce it.

**Comment by bugprogrammer** [comment]
> > I can't do much about this, since I wouldn't be able to reproduce it.
> 
> Understood. Thanks anyway!
> 
> Edit: I've found the cause for this issue, unrelated to owntone.

May I ask what is the reason？
----------------------------
请问是什么原因？

**Comment by clumsyCoder00** [comment]
> ## May I ask what is the reason？

It was very much my own doing. I inadvertently configured a home assistant automation to immediately turn off the stream when it started. SMH

**Comment by bugprogrammer** [comment]
> > ## May I ask what is the reason？
> 
> It was very much my own doing. I inadvertently configured a home assistant automation to immediately turn off the stream when it started. SMH
Is there any way to remove the pop-up window that allows mac to receive airplay2?
-----------------------------------------------------------------------------------
mac接收airplay2的那个允许弹窗您有办法去掉吗

**Comment by bugprogrammer** [comment]
> > ## May I ask what is the reason？
> 
> It was very much my own doing. I inadvertently configured a home assistant automation to immediately turn off the stream when it started. SMH

Is there any way to remove the pop-up window that allows mac to receive airplay2?
-----------------------------------------------------------------------------------
mac接收airplay2的那个允许弹窗您有办法去掉吗
