### ISSUE TITLE
add a internet raodio stream to radio list

### ISSUE THREAD

**Issue by Jumbo125** [owntone/owntone-server#1721]
hy everyone
is it possible to add a interet radio stream like: https://streams.antennemv.de/amv-love/mp3-128/radiode/?

thank you very much

**Comment by hacketiwack** [comment]
Yes. You have two ways to do it:

- From the web UI by adding it directly with the button "Add stream" (see images below)
<img width="1116" alt="Add stream" src="https://github.com/owntone/owntone-server/assets/13329768/ac5562e7-bb53-4146-a2d8-2866f1411177">
<img width="689" alt="Add stream" src="https://github.com/owntone/owntone-server/assets/13329768/117a2a78-5ab2-4277-b3aa-f3ed0c30535a">

- By creating a .m3u8 / .m3u file in your library with the link you mentioned.

**Comment by hacketiwack** [comment]
More information [here](https://owntone.github.io/owntone-server/advanced/radio-streams/)

**Comment by Jumbo125** [comment]
> Yes. You have two ways to do it:
> 
> * From the web UI by adding it directly with the button "Add stream" (see images below)
> 
> <img alt="Add stream" width="1116" src="https://private-user-images.githubusercontent.com/13329768/307599394-ac5562e7-bb53-4146-a2d8-2866f1411177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzI0OTcsIm5iZiI6MTcwODg3MjE5NywicGF0aCI6Ii8xMzMyOTc2OC8zMDc1OTkzOTQtYWM1NTYyZTctYmI1My00MTQ2LWEyZDgtMjg2NmYxNDExMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzEzNDE5YTFlZDE0ZjA0MGZjMjdmY2EzMzk3NjQ1NDU3YzA1OTMwMTVkZDdiNWQ0YjkzZGVhMTUwYWQyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.opxGmNBT_iA_pD1rqlW1NQdsCxB0QkHMX2qY3GpBXEo"> <img alt="Add stream" width="689" src="https://private-user-images.githubusercontent.com/13329768/307599395-117a2a78-5ab2-4277-b3aa-f3ed0c30535a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzI0OTcsIm5iZiI6MTcwODg3MjE5NywicGF0aCI6Ii8xMzMyOTc2OC8zMDc1OTkzOTUtMTE3YTJhNzgtNWFiMi00Mjc3LWIzYWEtZjNlZDBjMzA1MzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE0NDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYzY0Mjg3YmNlMDU1MmQ3NDY1MmQyNjAyMWY3ZDUyNGNmZDNiYmM0MTVjNDdlN2I3MTM5YzhlMTY4N2Y3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0U3RtRp6eZysogrHlENupdjuuDh_OvtAAhP1zeTd6v0">
> * By creating a .m3u8 / .m3u file in your library with the link you mentioned.

oh. where did you find this in the webgui? i don't have a "add stream" button. i searched it in the "playlist", "radio","music" tab

**Comment by hacketiwack** [comment]
You can access this feature from the queue page by clicking the queue button (button in the bottom left).
![Queue Button](https://github.com/owntone/owntone-server/assets/13329768/5ab7f8fe-a966-434c-98fd-96d9dde420c2)

**Comment by Jumbo125** [comment]
Thank you!

**Comment by Jumbo125** [comment]
last question by the way, cause it works know, but i would change some layout options.... do you know where the files from the server are located? i would like to change the css file.
![image](https://github.com/owntone/owntone-server/assets/61667987/4874a7b3-99d4-4d06-a5ec-f68788324f16)
