### ISSUE TITLE
run it locally, change css settings?

### ISSUE THREAD

**Issue by Jumbo125** [owntone/owntone-server#1724]
Hello 
is it possible to run it locally and use all files from a local copy from this project?
i need to conifg the webplayer with some css style formatings and more

thank you!

**Comment by hacketiwack** [comment]
If your objective is to fiddle around with the web UI, you can do the following:
1. Check out the Git repository
2. To to the folder web-src folder and change what you need/want
3. Install `npm` and run the following command:

```bash
npm install 
```

5. Run a local copy of the web UI with the following command (bash or zsh)
Note that `owntone.local` must be replaced with your own OwnTone server address.

```bash
export VITE_OWNTONE_URL=http://owntone.local:3689; npm run serve
```

4. Then access your local version through: `http://localhost:3000`

Some more information can be found [here](https://owntone.github.io/owntone-server/clients/web-interface/).

**Comment by Jumbo125** [comment]
@hacketiwack 
okay. i hope i understand it correctly...

1. i downlaod the Git resp. and save it locally
2. i install the project with npm install owntone-server-28.9.tar.gz 
3. it will be install it locally
4. now i can view it on port 3000
5. where is it installed to change the css files?

**Comment by hacketiwack** [comment]
Not exactly. The instructions I gave only allow to run the web UI locally.

If you want to run the OwnTone server locally on your computer, you have to follow the installation instructions presented in this [document](https://owntone.github.io/owntone-server/installation/).

Note that by default, the web UI is located under `/usr/share/owntone/htdocs`.

**Comment by Jumbo125** [comment]
> Not exactly. The instructions I gave only allow to run the web UI locally.
> 
> If you want to run the OwnTone server locally on your computer, you have to follow the installation instructions presented in this [document](https://owntone.github.io/owntone-server/installation/).
> 
> Note that by default, the web UI is located under `/usr/share/owntone/htdocs`.

okay i see. i used the raspberry install. i think that was a fail.
i should use the debian config tutorial.... is it correct?

do you know how i can uninstall the "old owntone-rasperry installation"?
thank you

**Comment by hacketiwack** [comment]
It depends on which OS you want to install OwnTone.
What is your OS?

And maybe a question I should have asked at the beginning: what do you want to adapt in OwnTone?

**Comment by hacketiwack** [comment]
Actually, if you install OwnTone locally with the procedure described for the Raspberry Pi OS, then you don't have to worry about having access to Internet.
The web UI doesn't rely at all on any internet connectivity. All the resources are installed locally on your device.

I enjoin you to follow the instructions [here](https://owntone.github.io/owntone-server/installation/) and more specifically [here](https://forums.raspberrypi.com/viewtopic.php?t=49928).

**Comment by Jumbo125** [comment]
okay...
do you know where the style files (http://localhost:3689/assets/index.css) is located, when i do the raspi tutorial???
where is thefolder assests? where is the root directory?

thank you

**Comment by hacketiwack** [comment]
As I wrote earlier, the files are under `/usr/share/owntone/htdocs`.
These files are rather difficult to read because they are minified (with the command npm run build).
But, my question remains: what do you want to change in the OwnTone UI?

**Comment by Jumbo125** [comment]
you are great. there is the css file. i will test it
Thank you very much!!!!
i only want to change some css styles, like font-size and more
