### ISSUE TITLE
does not build without sys/queue.h

### ISSUE THREAD

**Issue by neheb** [owntone/owntone-server#1726]
musl libc does not include sys/queue.h, making compilation fail:

```
httpd_libevhttp.c:26:10: fatal error: sys/queue.h: No such file or directory
   26 | #include <sys/queue.h> // TAILQ_FOREACH
      |          ^~~~~~~~~~~~~
compilation terminated.
```

libbsd can be added as a dependency to work around.

**Comment by hacketiwack** [comment]
@neheb, which procedure of [this documentation](https://owntone.github.io/owntone-server/building/) did you follow?

**Comment by ejurgensen** [comment]
@neheb is openwrt maintainer so I'm guessing he noticed the error from one of the buildbots. I will make a fix for it.

**Comment by ejurgensen** [comment]
Thanks for reporting @neheb, I think it should be fixed with the above patch. I haven't gotten around to updating the openwrt/packages version to 28.9, but when I do I guess I can either include this patch or add the libbsd dependency you mention.

**Comment by neheb** [comment]
Musl in OpenWrt is patched to include a sys/queue.h . Should be eliminated honestly to reduce the amount of patching, which is what I’ve done locally.

Don’t remember if this is the only usage in the code base.
