### ISSUE TITLE
automatic pairing to some devices?

### ISSUE THREAD

**Issue by Jumbo125** [owntone/owntone-server#1732]
Hy
i love your project. is it possible to force a automatic pairing to some devices via airplay? It would be really great, when i can force owntone to connect to some airplay devices automatically, when they are online. for example:
if my speaker is online, owntone sould pairing to it. if i turn off the speaker and restart it again, owntone should paring it again.

is this possible? i didn't found any config for that.

thank you

**Comment by ejurgensen** [comment]
I'm not sure what you mean by "automatic pairing"? Usually pairing involves entering a PIN or a password from the Airplay device.

Do you just mean selecting the speaker?

**Comment by LordMyschkin** [comment]
Could be meant the same enhancement as #518.
I'd still love to see an auto activation of activated speakers.
