### ISSUE TITLE
[search] Wrong results when using the "query:" mode in the library search

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1733]
**Current situation**
A search on the library (not Spotify) from the web UI, when using the "query" syntax, doesn't take into account the `media_kind` properly. This leads to have potentially too many results in other categories: e.g., Podcasts and Audiobooks.

**Steps to reproduce the problem**
Given a library with albums of `{artist name}`, but no podcasts, no audiobooks, nor playlists from this artist, do the following search:
1. On the library search page, search for the artist with a query similar to this one: `query: artist is "{artist name}"`
2. The search results gives works of this artist in the cateogries:
    - Albums, which is correct ✅
    - Podcasts, which is _incorrect_ ❌
    - Audiobooks, which is also _incorrect_ ❌

**Expected situation**
The search takes care of the `media_kind` search parameter and only provides results in the expected categories.

**Comment by hacketiwack** [comment]
To simplify the test, the two queries below, give the same results:

```
/api/search?type=album&media_kind=podcast&expression=artist+is+%22Michael+Jackson%22
```

```
 /api/search?type=album&media_kind=music&expression=artist+is+%22Michael+Jackson%22
```

**Comment by ejurgensen** [comment]
Since it's a criteria you have to put the media_kind in the expression, so:
`/api/search?type=album&expression=artist+is+%22Michael+Jackson%22+and+media_kind+is+music`
