### ISSUE TITLE
[api] Allow filtering the genre by media kind

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1735]
**Current situation**
In the current implementation of the `genre` API, it is not possible to filter by `media_kind`.
The following query, will always return the genre of the `music` media kind.

```
/api/library/genres/jazz/?media_kind=audiobook
```

Result example

```json
{
  "name": "Jazz",
  "name_sort": "Jazz",
  "track_count": 4318,
  "album_count": 374,
  "artist_count": 132,
  "length_ms": 1193109978,
  "time_played": "2024-03-26T09:17:51Z",
  "time_added": "2023-12-18T09:03:59Z",
  "in_progress": false,
  "media_kind": "music",
  "data_kind": "file",
  "date_released": "2023-06-23",
  "year": 2023
}
```

**Suggested situation**
The `media_kind` parameter is used and thus the result is affected accordingly.

**Comment by ejurgensen** [comment]
I think for these kind of searches you need to use the search endpoint

**Comment by hacketiwack** [comment]
The only problem with the search endpoint of the API is that it doesn't retrieve genres.

I was interested in getting genre objects because there are two interesting fields `track_count` and `album_count`
I will find another way to get the information.

By the way, I'm wondering why the genre object has some of its fields, like: year, date_released, in_progress, time_added, time_played. These fields don't make sense to me for this object.

**Comment by ejurgensen** [comment]
Ok let me know if you would like me to add genre objects to the search endpoint, I expect that's not too difficult

**Comment by hacketiwack** [comment]
Thank you for the proposition.
However, I would prefer to have the `media_kind` working on the `/api/library/genres/{genre}` endpoint.
And without these useless elements: `name_sort` (is there really a name sort on the genre?), `time_added`, `in_progress`, `data_kind`, `date_released`, and `year`

Calling the endpoint `/api/library/genres/Jazz?media_kind=music` should give the following result:

```json
{
  "name": "Jazz",
  "track_count": 4318,
  "album_count": 374,
  "artist_count": 132,
  "length_ms": 1193109978,
  "media_kind": "music",
}

This would probably also require to correct the endpoint `/api/library/genres?media_kind={media_kind}`, which is also returning the same useless fields at the moment.

IMHO, this would make the API a wee bit cleaner.

**Comment by hacketiwack** [comment]
Actually, the so-called [`browse-info`](https://owntone.github.io/owntone-server/json-api/#browse-info-object) object has a weird content in my opinion.
It seems, looking at the source code that it's used for `composer` and `genre`. Hence, the `name_sort` field.

**Comment by ejurgensen** [comment]
Ok I will check why media_kind is behaving like this. I think the other fields are there for a reason (I'm guessing some sort of overview) so I don't think they should be touched.

**Comment by hacketiwack** [comment]
Amazing! Thanks a lot.

**Comment by ejurgensen** [comment]
I had a look at it this, and I have added the above change that means the search endpoint can return genres. I don't think adding media_kind filtering to /api/library/genres/[genre] is the right way to go, because it seems a bit random that filtering on media_kind is supported, but not on any other attribute. That /api/library/genres?media_kind=xxx exists is in my opinion also a bit of an eye sore (also when you look at the code), but I guess it has to stay now that it's there.

**Comment by hacketiwack** [comment]
Thanks a lot for the change. I made a change that get rid of the use of the Genre API endpoint (`/api/library/genres`) and corrects the count of albums and tracks by genre and media kind.

IMHO, it would be great to remove this endpoint as it is not used anymore by the web UI and it is providing unexpected results anyway.
