### ISSUE TITLE
Unexpected result when starting album playback via JSON API

### ISSUE THREAD

**Issue by cdlenfert** [owntone/owntone-server#1737]
I have an iOS shortcut that allows me to search for albums by name, lists any matches found, and starts playback of my chosen album. The final command in that shortcut builds the following path for my API request:

http://owntone.local:3689/api/queue/items/add?uris=library:album:8106933743823879888&clear=true&shuffle=false&playback=start

This works to start playback of the album I've asked for ("Daniel" in this case). However, in my library, this album is listed as having only one track.
![image](https://github.com/owntone/owntone-server/assets/17277745/b5717ae3-37bf-4b89-aa5d-66fc35450ca8)

I have the full album in the my local files AND in my Spotify library.
- local URL http://owntone.local:3689/#/music/albums/8106933743823879888
- spotify URL http://owntone.local:3689/#/music/spotify/albums/6hklBSOyHrnC42LQksxrzd

All of the local files have metadata for the album title (as seen via the VLC player):
![image](https://github.com/owntone/owntone-server/assets/17277745/d3bc56f7-9196-4271-ad15-9dfaae65ba6c)

But when I look at the track info modal in Owntone for the 1 track that appears in the album, it references the Spotify path:
![image](https://github.com/owntone/owntone-server/assets/17277745/b3e10ec1-5905-4d52-87a9-babf192e904a)

I'm not sure why the local library path doesn't show all of the tracks. For similar albums that I have both locally and in my Spotify library, the album shows up twice in the Artist page that list all albums in Owntone, and tracks locally are "type-file", not "type-spotify" unlike the single track I'm seeing in the Daniel "local" album.

**Comment by hacketiwack** [comment]
It is weird indeed that you're seeing only one track for the album in your library.
So basically:
1. The album in your local library should be present in the list of albums (it's probably **not** this identifier: `8106933743823879888`, see point 3).
2. The link `http://owntone.local:3689/#/music/spotify/albums/6hklBSOyHrnC42LQksxrzd` should give you all the tracks of your album located in the Spotify library.
3. However, if you have one or more songs of this Spotify album in one of your Spotify playlists, the Spotify album will appear in the list of albums even though it is not a file from the local library. So, check if your track "Market Street" by "Real Estate" is in one of your Spotify playlists. And I think this is what's happening in your situation. The link `http://owntone.local:3689/#/music/albums/8106933743823879888` **is** this particular case.

I hope I made myself as clear as possible.

Side note: It might be confusing to have Spotify items appearing in the pages where you expect only local library files. This is why there is an option to hide Spotify items (except on the search page).

**Comment by cdlenfert** [comment]
Thank you for the detailed reply. I believe I have a better understanding overall now. Some additional observations/questions:
1. My local files for the "Daniel" album are on my server, but not in an indexed directory, so they should not appear in my library/database. I just incorrectly assumed they were supposed to be.
2. The Spotify URL `http://owntone.local:3689/#/music/spotify/albums/6hklBSOyHrnC42LQksxrzd` indeed gives me all of the tracks in the album.
3. The only efficient way I've found to check if a track is in one of my Spotify playlists (I have 77) is to use the mobile app, start to add that track to a playlist, look at the playlists available to add to, and if it's in one already, there is a green check mark. I did this, and the song doesn't appear to be in any of my Spotify playlists. I also went through playlists I suspect the song may be in and searched for it using the browser and command F and didn't find it. (if there's another way to double check this, please let me know)
4. When I set the owntone.conf option `album_override = true` in the Spotify settings (and restart Owntone), I still see the Daniel album on the artist page (even though it is not in the local library). Do I have to rescan my library (or additionally rescan metadata) for this to take effect? I can manually toggle the display of Spotify albums in the web interface and the album disappears, but shouldn't the config setting do the same?

And the final question, which I'm still trying to answer in my testing is will changing this setting change the behavior of the API request to start an album? I would expect that it would but I'm not sure if the request data is going to be different, or these settings only hide the partial local album from the web interface, but the actual data available to the API will remain the same as before.

**Comment by cdlenfert** [comment]
update: Rescanning the library has caused the "Daniel" album to be removed by default form the Artists page in the web interface. I also did not have this album saved in my Spotify library. This makes me even more confused as to how it appeared in the first place (since local files were not indexed and Spotify album was not favorited/saved, and I cannot find it in any of my playlists). So bizarre.

Either way, doing a rescan, adding the album only to my Spotify library has solved my issues of being able to make an API request to start playback of the full album. And changing the config setting to now show albums that are part of a spotify playlist (and rescanning) fixed that weird straggler track.

**Comment by hacketiwack** [comment]
@cdlenfert thanks for the heads-up. Shall we close this ticket then?

**Comment by cdlenfert** [comment]
Yes, I think we should close it. I still don't know why the song/album appeared in my Library when I couldn't find it in any Spotify playlists, but I'm not overly concerned with that since rescanning seemed to fix the problem.
