### ISSUE TITLE
local network AirPlay1 speakers can be fond，but can't support Airplay2 and multiplay yet. how to solve?please share your opinion ,Thx!

### ISSUE THREAD

**Issue by eleven520** [owntone/owntone-server#1738]
I burst into tears of joy upon seeing this project. Install and test immediately. However, speakers that originally support AirPlay1 in the local area network still cannot support AirPlay2. Is it because I misunderstood the project？ and can not support to multiplay yet。

**Comment by eleven520** [comment]
![截屏2024-03-28 下午9 13 31](https://github.com/owntone/owntone-server/assets/51551815/d8eed975-e41c-4690-b0b4-6af074f9c7c4)

**Comment by eleven520** [comment]
![截屏2024-03-28 下午9 13 31](https://github.com/owntone/owntone-server/assets/51551815/d8eed975-e41c-4690-b0b4-6af074f9c7c4)

**Comment by eleven520** [comment]
![截屏2024-03-28 下午9 13 03](https://github.com/owntone/owntone-server/assets/51551815/840ff7f6-bd0a-4d44-a35a-e795b7cf061e)

**Comment by ejurgensen** [comment]
OwnTone does support both Airplay 1 and 2. Not sure I understand the issue, can you give some more info about what you want to achieve?

**Comment by eleven520** [comment]
> OwnTone does support both Airplay 1 and 2. Not sure I understand the issue, can you give some more info about what you want to achieve?

Through this project, how can I get my LAN smart speaker to be recognized by HomeKit and use them as an audio output device for Apple TV. That be best to compose a stereo device. 👍

**Comment by ejurgensen** [comment]
OwnTone is an AirPlay *sender* but it seems you are looking for a *receiver*? I don't know of anything that can add AirPlay 2 receiving capability to an existing speaker, but maybe shairport-sync would be interesting for you?

**Comment by eleven520** [comment]
> shairport-sync

thank you
