### ISSUE TITLE
Potential memory leak when calling sqlite3_open

### ISSUE THREAD

**Issue by icy17** [owntone/owntone-server#1741]
Version: master
Bug description:
Calling [sqlite3_open](https://github.com/owntone/owntone-server/blob/master/src/db.c#L7128) in src/db.c:7128 without releasing parameter 2 when no longer needed cause memleak.

**Comment by ejurgensen** [comment]
Looks like param 2 is released on line 7144, so there is only a memleak if sqlite3_backup_init fails. Do you agree?

**Comment by icy17** [comment]
> Looks like param 2 is released on line 7144, so there is only a memleak if sqlite3_backup_init fails. Do you agree?

Yes, you're right
