### ISSUE TITLE
transcode.c build error with FFmpeg 7.0

### ISSUE THREAD

**Issue by freultwah** [owntone/owntone-server#1743]
Having upgraded to FFmpeg 7.0, owntone no longer builds. The error message is as follows:

```
transcode.c:960:71: error: incompatible function pointer types passing 'int (void *, uint8_t *, int)' (aka 'int (void *, unsigned char *, int)') to parameter of type 'int (*)(void *, const uint8_t *, int)' (aka 'int (*)(void *, const unsigned char *, int)') [-Wincompatible-function-pointer-types]
    s = avio_alloc_context(ae->buffer, AVIO_BUFFER_SIZE, 1, ae, NULL, avio_evbuffer_write, NULL);
                                                                      ^~~~~~~~~~~~~~~~~~~
/usr/local/include/libavformat/avio.h:404:25: note: passing argument to parameter 'write_packet' here
                  int (*write_packet)(void *opaque, const uint8_t *buf, int buf_size),
                        ^
1 error generated.
```

Apparently, `uint8_t *` and `const uint8_t *` do not mix.

This is caused by the following commit to ffmpeg which constifies data pointees of write callbacks:

https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/2a68d945cd74265bb71c3d38b7a2e7f7d7e87be5

I tried fixing it by doing the following, but that seems to have broken something else, as even though the build error disappears and build is apparently successful, I cannot play anything back, the daemon dies immediately.

```
--- src/transcode.c.orig        2024-01-18 13:46:52.000000000 +0200
+++ src/transcode.c     2024-04-05 14:32:49.298894000 +0300
@@ -888,7 +900,7 @@
 }
 
 static int
-avio_evbuffer_write(void *opaque, uint8_t *buf, int size)
+avio_evbuffer_write(void *opaque, const uint8_t *buf, int size)
 {
   struct avio_evbuffer *ae = (struct avio_evbuffer *)opaque;
   int ret;

```

**Comment by ejurgensen** [comment]
Thanks for notifying about this, I'll look into it.

**Comment by ejurgensen** [comment]
> I tried fixing it by doing the following, but that seems to have broken something else, as even though the build error disappears and build is apparently successful, I cannot play anything back, the daemon dies immediately.

Your fix is correct, so I've added that now. The crash must be something else, but I'm not able to reproduce that. I played a few tracks and that worked ok. Would you be able to try with gdb and make a new issue if it reports a crash?

Make sure that you clean out any old version of ffmpeg, otherwise that might cause trouble.
