### ISSUE TITLE
M3U Radio playlist returns '500 Internal Server Error'

### ISSUE THREAD

**Issue by ellesurg** [owntone/owntone-server#1744]
Hello, many thanks for this software - I absolutely love it and use it all the time.

Since a few days I have the following problem and I am unable to solve it. I run owntone version 28.9 as docker container on a QNAP NAS. When playing any M3U playlist, owntone now returns:
> Request failed (status: 500 Internal Server Error http://192.168.0.10:3689/api/queue/items/add?clear=true&playback=start&shuffle=false&uris=library:track:8392)

The log shows:
> [2024-04-06 20:49:00] [  LOG]    xcode: Cannot open 'http://stream-uk1.radioparadise.com/aac-320': I/O error
> [2024-04-06 20:49:00] [  LOG]      web: JSON api request failed with error code 500 (/api/queue/items/add?clear=true&playback=start&shuffle=false&uris=library:track:8384)

Example of a playlist:
```
#EXTM3U
http://stream-uk1.radioparadise.com/aac-320
```

I tried with multiple M3U radio playlists, recreating the container, deleting the config and database. Same problem.

Any help is greatly appreciated.
Thanks again!

**Comment by ejurgensen** [comment]
The error seems to come from the ffmpeg libraries that OwnTone uses to open the http stream. Do you think you might have upgraded ffmpeg before the errors began appearing?

**Comment by ellesurg** [comment]
Thanks for the swift response! If ffmpeg upgraded, it was not intentionally done... I will search in that direction.
For info, here is the ffmpeg version:

> ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
> built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014
> configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto=auto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
