### ISSUE TITLE
Fix MacOS workflow

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1751]
@hacketiwack as you can see the MacOS workflow is currently failing. It's because Homebrew's mxml is now version 4, but the new version of mxml is apparently quite different from version 3, so can't directly be used. As you can see from recent commits I tried various things to make Homebrew install version 3 instead (version 3.3.1), but I couldn't make it work. Do you happen to know how that can be done?

**Comment by hacketiwack** [comment]
I will check it out to see how we can fix this.

**Comment by hacketiwack** [comment]
I tried a few things regarding the issue with Mini-XML.
I changed the file `configure.ac` to use `mxml4`, because the version 3 is not available anymore in Homebrew:

```conf
OWNTONE_MODULES_CHECK([OWNTONE], [MINIXML], [mxml4],
```

It passes all the `configure` steps, but fails when it comes to the `make` command:

```log
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       misc_xml.o
misc_xml.c:220:35: error: use of undeclared identifier 'MXML_NO_CALLBACK'
  return mxmlSaveAllocString(top, MXML_NO_CALLBACK);
                                  ^
misc_xml.c:235:38: error: use of undeclared identifier 'MXML_OPAQUE_CALLBACK'
  node = mxmlLoadString(top, string, MXML_OPAQUE_CALLBACK);
                                     ^
misc_xml.c:258:32: error: use of undeclared identifier 'MXML_OPAQUE_CALLBACK'
  node = mxmlLoadFile(top, fp, MXML_OPAQUE_CALLBACK);
                               ^
misc_xml.c:292:15: error: use of undeclared identifier 'MXML_ELEMENT'
  if (type == MXML_ELEMENT)
              ^
misc_xml.c:340:19: error: use of undeclared identifier 'MXML_OPAQUE'
      if (type == MXML_OPAQUE)
                  ^
misc_xml.c:342:24: error: use of undeclared identifier 'MXML_ELEMENT'
      else if (type == MXML_ELEMENT)
                       ^
misc_xml.c:364:14: error: use of undeclared identifier 'MXML_NO_PARENT'
    parent = MXML_NO_PARENT;
             ^
7 errors generated.
make[3]: *** [misc_xml.o] Error 1
```

Then I tried to reinstall the older version of the library in a brutal way:

Retrieving first the Homebrew formula of the version 3.3.1:

```bash
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/71bfcd3624ee88eee1e2ea6653753dafd48e7fcf/Formula/lib/libmxml.rb > libmxml.rb
```

And then installing the version 3.3.1:

```bash
brew install --build-from-source libmxml.rb
```

And finally, I get these warnings:

```log
  CC       parsers/daap_parser.o
parsers/daap_parser.c:1563:9: warning: variable 'daap_nerrs' set but not used [-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
parsers/daap_parser.c:92:25: note: expanded from macro 'yynerrs'
#define yynerrs         daap_nerrs
                        ^
1 warning generated.
  CC       parsers/smartpl_parser.o
parsers/smartpl_parser.c:1885:9: warning: variable 'smartpl_nerrs' set but not used [-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
parsers/smartpl_parser.c:98:25: note: expanded from macro 'yynerrs'
#define yynerrs         smartpl_nerrs
                        ^
1 warning generated.
  CC       parsers/rsp_parser.o
parsers/rsp_parser.c:1527:9: warning: variable 'rsp_nerrs' set but not used [-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
parsers/rsp_parser.c:94:25: note: expanded from macro 'yynerrs'
#define yynerrs         rsp_nerrs
                        ^
1 warning generated.
```

Even though using the older version 3.3.1 might work, it seems a bit odd to go to these extents to make the build work.
I don't know. I would be more inclined to adapt for version 4.

**Comment by ejurgensen** [comment]
Thanks for looking into this. Those parser warnings don't have anything to do with mxml, so it seems you got 3.3.1 to work. I will try to update the workflow with your method.

Switching to mxml 4 is some work, especially because compability with 3 would still be needed. It's not going to be very pretty. Even now, misc_xml.c has a bunch of wrappers and compability stuff. Given the track history with mxml, I think it might be better to switch to a more standard xml parser - i.e. one that's already available on most distros. Hopefully that would also have a more stable API.

**Comment by ejurgensen** [comment]
I added your method with commit f00aae6 and the workflow is now back on track :-)
