### ISSUE TITLE
Owntone only plays to homepod mini if "ipv6 = no"

### ISSUE THREAD

**Issue by marioscube** [owntone/owntone-server#1752]
Please try to provide the following:

in owntone.conf:
ipv6 = yes
=> no playable output to homepod mini speaker

ipv6 = no
=> music tart playing right away

- version of owntone = 26.5
- platform = debian bullseye

**Comment by ejurgensen** [comment]
Yes, there is some problem with the ipv6 implementation and Apple devices (maybe also others). I was never able to find the reason, so I'll consider just changing the default ipv6 setting to disabled.

**Comment by marioscube** [comment]
I don't like it, but I can appreciate an honest answer.

Thank you for owntone (forked-daapd).
