### ISSUE TITLE
fix delay in pipe

### ISSUE THREAD

**Issue by fethom** [owntone/owntone-server#1755]
Hej, I use on a raspberry 3b+ ( Operating System: Raspbian GNU/Linux 11 (bullseye) Kernel: Linux 5.15.36-rt41-v7+) the media center Kodi. Audio goes via a  virtual sound card to the pipe from owntone  and sends it to my HomePods (stereo). When I watch a TV-Livestream the sound reachs the HomePods between 4,1s , 4,6s or 5,1s later. In Kodi I can tune  a fix delay between -10s to 10s.  Is there an easy way to get a fix delay in onwtone that, lets say is 5,1seconds? The virtual sound card  transcodes the input audio with ffmpeg. This is the command: 

`ffmpeg -f s16le -channels 2 -channel_layout stereo -thread_queue_size 8 -i pipe:0  -use_wallclock_as_timestamps 1 -force_key_frames 00:00:01.000 -channels 2 -acodec pcm_s16le -bufsize 200k -f s16le  -ar 44100  pipe:1 >/media/ramdisk/AUX`

Or are there other options to get a fix audio delay, when using pipe as input?

**Comment by ejurgensen** [comment]
The short answer is no.

Is it the sync with source or playback start that has variable delay? Airplay should offer multiroom sync, so say you have the Homepods and a third Airplay speaker, then they should all be playing in sync even though the third speaker might start before the Homepods. OwnTone sends timing info to the speakers to make sure they stay in sync.

**Comment by fethom** [comment]
That´s not the problem, the HomePods are in sync and a third or fourth one too. I think the time owntone starts the playback from the pipe differs. Is there a possibility to get there a fix value or do I have to change  something in that ffmpeg command above?

**Comment by ejurgensen** [comment]
> I think the time owntone starts the playback from the pipe differs

Why do you think that?

> do I have to change something in that ffmpeg command above

I can't help much with ffmpeg, but I'm not stuff like keyframe and wallclock do much when the output is PCM? In any case, if I understand your setup correctly, ffmpeg transcodes from some source to PCM, which is written to a pipe. Depending on the source, I suppose this transcoding could have some variable time before the first samples are written. I would think it is insignificant, but I can't say for sure.

**Comment by fethom** [comment]
I think that because I suppose that owntone checks if there´s input in the pipe in short intervals. But when the stream starts just in the time between two intervals , then there is the different delay, which is not bigger than this interval. may be I think wrong. But probably it is everything together, the tanscoding, the pipe write/read and the network latency. I thought it were possible to set or get for every new input the same values. How long does that takes when owntone detects input in the pipe to react and send it further? Are there other input possibilities planed eg. alsa?

**Comment by ejurgensen** [comment]
OwnTone doesn't check the pipe at intervals, it is notified by the kernel that there is data to read

**Comment by fethom** [comment]
Could realtime-privileges be useful to speed up the machine? But I didn’t add a owntone-user and group to the system to give the realtime rights in /etc/security/limits.conf. Still is that possible to do that now?

**Comment by ejurgensen** [comment]
I don't think that will make a difference. Delays usually means that either something is buffering or something is turning on.

To identify whether the delay is on the input side or output side, you could try with some time measurements without Airplay. If they are the same then you have an indication that the delay is on the network/Airplay side. Precise timing isn't simple though, and a bit too complex for me to offer guidance on.

**Comment by fethom** [comment]
OK, Thanks! And one last question is, if it is possible to use a sound card directly as input source or to implement it!

**Comment by ejurgensen** [comment]
No that's not currently supported, and also not high on my todo-list, since arecord should do the job.

**Comment by fethom** [comment]
I didn´t know that arecord is able to stream to airplay devices...

Ok, thank you very much for your support!

**Comment by ejurgensen** [comment]
> arecord is able to stream to airplay devices

That's not what I meant. arecord can read from sound card and write to the pipe, so basically adds the sound card capability to owntone that you asked for.

**Comment by fethom** [comment]
ok!

**Comment by fethom** [comment]
Is there a way for realtime playing for pipe input, or speed up the process from reading the datas until the playing in the HomePods?

**Comment by ejurgensen** [comment]
The delay comes from the output side (starting the speaker), so there isn't anything to do about it on the input side. However, the delay shouldn't be variabel, so if that's the case then I don't know what is going on.

**Comment by fethom** [comment]
Thx for the fast answer! It’s an other constellation now, I tried to send audio from the tv -headphones -line-out to the HomePods with a rpi zero 2w with owntone. It’s working but this takes around 5 s. For audio only, no problem but not with video. I thought I could use this constellation but it will not be that fast, to get in synchrony. that’s why I ask for speeding up with realtime or is there  an other idea?
the other first issue with the different delay is working now, after I didn´t transcode the stream with ffmpeg anymore in /etc/asound.conf. Now the audio in HomePods  starts in every case 4.8 seconds after starting the TVstream in KODI. I could set the fix delay in Kodi and every stream is in sync.
