### ISSUE TITLE
Cannot save queue to playlist: Status 500 'Internal Server Error'

### ISSUE THREAD

**Issue by bitevader** [owntone/owntone-server#1756]
Please try to provide the following:

- steps to reproduce and/or logging of the error
- version of owntone
- platform

Steps to reproduce will greatly improve the chance of getting it fixed. If it is not possible then set the log level to debug (in /etc/owntone.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by bitevader** [comment]
Hi everybody, On the web IF, I couldn't save my queue 'mystream' as a playlist named 'MyPL'.
This is what the log says:

[  LOG]   player: Could not open pipe for reading '/home/pi/Music/mystream.metadata': No such file or directory
[  LOG]     scan: Path '/home/pi/Radio/Rip/MyPL.m3u' is not a virtual path for a configured (local) library directory.
[  LOG]      web: JSON api request failed with error code 500 (/api/queue/save?name=MyPL)

Glad for any help in this jungle!

**Comment by hacketiwack** [comment]
In your configuration (owntone.conf), you need to configure two parameters:

- [allow_modifying_stored_playlists](https://owntone.github.io/owntone-server/configuration/#allow_modifying_stored_playlists), and
- [default_playlist_directory](https://owntone.github.io/owntone-server/configuration/#default_playlist_directory)

Make sure that you provide the correct permissions to the directory you specified under default_playlist_directory.

Hope this helps.

**Comment by bitevader** [comment]
Thanks for the answer.
I have owntone installed on a Rapberry PI 3 B. When I use the 'Save'-buttom on the Web-IF to save my stream as playlist, what more permissions should be required concerning to what my config already contains?
A pullout of (what I think are) the relevant settings I changed or left I have posted below.
What do you think?
[owntone.conf.txt](https://github.com/owntone/owntone-server/files/15204722/owntone.conf.txt)
I don't know why the attachement comes within here?!

**Comment by hacketiwack** [comment]
The two parameters seem to be configured correctly. I would add the directory `/home/pi/Radio` in the directory list as well.

```conf
library {
    allow_modifying_stored_playlists = true
    default_playlist_directory = "/home/pi/Radio/Rip"
    directories = { "/home/pi/Music/", "/home/pi/Radio" }
}
```

Make sure that permissions on `/home/pi/Radio/Rip` is set to be writable by the user starting OwnTone.
Just to test, you can give 777 permission on it like this:
(777 is too permissive, but is OK for temporarily testing)

```bash
sudo chmod 777 -R /home/pi/Radio/Rip
```

**Comment by bitevader** [comment]
Well, the playlist was saved but when I wanted to play it, this:
[owntone.log.txt](https://github.com/owntone/owntone-server/files/15205832/owntone.log.txt)
When I checked the playlist file it had .m3u but the properties were: plain text document, 0 bytes.
??

**Comment by hacketiwack** [comment]
What kind of file is `/file:/home/pi/Radio/Rip/Chue am Waldrand`?

The message in the logs is telling you that the file type is unsupported in the playlist.

```log
Unsupported data kind for playlist file '/file:/home/pi/Radio/Rip/Chue am Waldrand' ignoring item '/home/pi/Music/mystream'
```

**Comment by bitevader** [comment]
Chue am Waldrand - in english: Cow on the edge of the forest - is the name
of the playlist. I also tried the name without spaces with the same result.
As I mentioned, the file extension .m3u was added, but in properties I saw
that the type was plain text and it contained 0 bytes.
I don‘t know either why it is not supported. Once again I am at the limits
and I hope somebody may help. Thanks.

LargePrefPlaceholder-XKUz1MEJBwkOM


Alain Nussbaumer ***@***.***> schrieb am Sa. 4. Mai 2024 um
07:26:

**Comment by hacketiwack** [comment]
I was not being judgmental about what you’re listening. 😅
I should have asked, what is the type of data you have in the mystream file?
Is it a regular file?

**Comment by bitevader** [comment]
Sorry, mystream I generated with mkfifo -m666 /home/pi/Music/mystream and
arecord -D hw:CARD=CODEC,DEV=0 -f raw > /home/pi/Music/mystream
It is from a USB input (ALSA I think) and it shows up on the Web-IF where I
can play the music it contains. To store the playlist I chose a subfolder
to Radio because  owntone suggests it for playlists containing an url. I am
not 100% shure if this is correct though.

LargePrefPlaceholder-XKUz1MEJBwkOM


Alain Nussbaumer ***@***.***> schrieb am Sa. 4. Mai 2024 um
16:06:

**Comment by bitevader** [comment]
Problems and problems. When you try a new feature it won't work. It seems impossible to set it up without investigating, guessing and finally having to ask somebody with lots of experience. Latest case in place is playing an .mp3 file which won't work. The log:
[owntone.log.txt](https://github.com/owntone/owntone-server/files/15210768/owntone.log.txt)

**Comment by hacketiwack** [comment]
Sorry, I can't help you with the arecord command. Never used it myself.

I also don't know from what comes the error below:

```log
[2024-05-04 21:18:04] [  LOG]    xcode: Error while feeding the filtergraph: Invalid argument
[2024-05-04 21:18:05] [  LOG]   player: Error reading source '/home/pi/Music/Ascenseur.mp3' (id=4)
[2024-05-04 21:18:05] [  LOG]   player: Error reading from source
```

I never saw that before.

My recommendation to troubleshoot would be to test bit by bit.
First make a default installation of OwnTone with one directory containing one audio file.
And then ramp up in complication.

**Comment by bitevader** [comment]
Oh Jesus, thanks anyway.

LargePrefPlaceholder-XKUz1MEJBwkOM


Alain Nussbaumer ***@***.***> schrieb am Sa. 4. Mai 2024 um
21:44:

**Comment by bitevader** [comment]
hacketiwack, you gave me a clue with mentioning 'arecord'-command. So I changed the type from 'raw' to 'wav' in the call and bingo, mp3 playing worked. But making a similar change for 'mystream' still didn't solve 'the save playlist - problem'. It remains the same, it won't play! Maybe I have to raise a price for solving it?
