### ISSUE TITLE
Why is it not possible to use ALSA input fo owntone fifo stream and Audacity at the same time?

### ISSUE THREAD

**Issue by bitevader** [owntone/owntone-server#1759]
Just the title. Glad for any info.

**Comment by ejurgensen** [comment]
You mean using the same fifo? If so it would be because data is transfered/removed when read

**Comment by bitevader** [comment]
No, Fifo stream starts running by arecord-command. Audacity starts recording. Doing this works only for a party, if the other hadn't been started. Not what I want. I would like to hear what I am recording simultaneously. Because both reside in Raspberry, where I have no sound output available, I hoped to use the FIFO stream for listening to know when to stop recording.

**Comment by bitevader** [comment]
Why is the status closed?
