### ISSUE TITLE
Which protocolls are avaible?

### ISSUE THREAD

**Issue by Jumbo125** [owntone/owntone-server#1762]
Hello
First of all, a big thank you for this great work!!!
the project is really great.

I just wanted to ask whether it also supports protocols other than Airplay, which are included with many WiFi speakers.

I would like to buy a new wifi speaker and then use it with owntone. Only very few wifi speakers have airplay (in the low price segment)
Of course I could hang another rapsi on the speakers and use it as an airplay client. But if there is a ready solution, that would of course be better. 

Thanks

**Comment by Porco-Rosso** [comment]
I think the docs might have the info you are looking for:
https://owntone.github.io/owntone-server/clients/supported-clients/

> OwnTone supports these kinds of clients:
> 
> - DAAP clients, like iTunes or Rhythmbox
> - Remote clients, like Apple Remote or compatibles for Android/Windows Phone
> - AirPlay devices, like AirPort Express, Shairport and various AirPlay speakers
> - Chromecast devices
> - MPD clients, like mpc
> - MP3 network stream clients, like VLC and almost any other music player
> - RSP clients, like Roku Soundbridge

**Comment by Jumbo125** [comment]
yeah, i found this too.
do you know if any of this protocolls are in the mostly wlan speakers?

**Comment by ejurgensen** [comment]
There are probably many protocols out there, so it would be easier if you could say which one you are interested in. I think the most common ones are Airplay, Chromecast and Spotify Connect, where OwnTone supports the first two. Sonos has its own protocol, but I think they also support Airplay.

**Comment by Jumbo125** [comment]
okay, i will have a look again.
Thank you for the tipps
