### ISSUE TITLE
Building OwnTone on Mac OS 14 Sonoma

### ISSUE THREAD

**Issue by ejurgensen** [owntone/owntone-server#1764]
The Github action Mac OS workflow fails after macos-latest became Mac OS 14. The issue occurs at the configure stage when checking for libraries that were installed with Homebrew e.g. libunistring. Homebrew installs them in /opt/homebrew/opt/[libraryname], and configure can't find them there. It would probably be possible to fix by exporting a whole bunch of CFLAGS/LDFLAGS, but it becomes quite ugly.

@hacketiwack do you have any experience with building on Mac OS 14? I can only troubleshoot via Github actions, so it's quite cumbersome (I never got the VM to work).

**Comment by hacketiwack** [comment]
@ejurgensen I will check that out. On Azure DevOps, I can compile without any issue (with macOS 14). Need to look into the current CI on GitHub.

**Comment by ejurgensen** [comment]
A bit of progress - I found out that setting CFLAGS="-I/opt/homebrew/include" and LDFLAGS="-L/opt/homebrew/lib" fixes the library problems I had. But next issue is that "make" isn't using the Homebrew bison/flex versions, even if I modify PATH.

**Comment by hacketiwack** [comment]
Actually, yesterday night I could compile on my macOS machine.
You're right with the flags. But there are more to include to make the build work.

**Comment by ejurgensen** [comment]
Got it to work now, but it only by force-symlinking the Homebrew versions of bison/flex, which maybe isn't great. If you see a better way then let me know.
