### ISSUE TITLE
Prevent icy streams from adding garbage metadata

### ISSUE THREAD

**Issue by barolo** [owntone/owntone-server#1765]
During scan, meta from icy streams gets added to db, unfortunately it's often trash, resulting in something like this `   icy-name        : Fluid: Drown in the electronic sound of instrumental hiphop, future soul and chilled trap. [SomaFM]` being added as an artist.
As per  #891 it's supposed to be possible to be overridden, yet it doesn't seem to be working.
Am I doing something wrong?
[I'm running git-master]

```lua
#EXTM3U
#EXTALB:Online Radio
#EXTART:SomaFM
#EXTINF:-1, SomaFM - Fluid
http://ice6.somafm.com/fluid-128-aac
```

**Comment by ejurgensen** [comment]
Yes its on purpose, otherwise the radio list becomes less useful with some clients, eg Apple Remote
