### ISSUE TITLE
[Apple Music Application] Incorrect cover artwork displayed

### ISSUE THREAD

**Issue by hacketiwack** [owntone/owntone-server#1768]
**Current situation**
When using the OwnTone music library in the Apple Music Application on macOS, I get incorrect cover artwork for certain albums.
For the same albums, in the web user interface, these cover artworks are correctly displayed.

**Expected situation**
The correct cover artworks are displayed in the Apple Music Application.

**Context**
The error appears with all versions of OwnTone I've tested so far.
There are no specific error messages in the logs only warnings that are not related in my opinion.

```log
[ WARN]     daap: Could not find requested meta field 'all'
[ WARN]     daap: Could not find requested meta field 'dmap.downloadstatus'
[ WARN]     daap: Parser will ignore duplicate occurrence of meta field 'daap.songtime'
[ WARN]     daap: Could not find requested meta field 'com.apple.itunes.cloud-id'
[ WARN]     daap: Could not find requested meta field 'dmap.objectextradata'
[ WARN]     daap: Could not find requested meta field 'com.apple.itunes.saved-genius'
[ WARN]     daap: Could not find requested meta field 'dmap.haschildcontainers'
[DEBUG]  artwork: Artwork request for item 365170 (max_w=0, max_h=0)
[DEBUG]     daap: Request for artwork without mw or mh parameter
```

**Comment by ejurgensen** [comment]
Yes, I wonder how we can debug this. In principle this should be pretty simple. The Music app initially gets track IDs and then should just make artwork requests using those IDs. In your example 365170. I assume this is not the correct ID for the track you selected in the Music app? It might be useful if you could add details about the expected track (it's id, album_id and album_artist_id) and about the track displayed (you can check with http://localhost:3689/api/library/tracks/365170).

Perhaps you can also see id's in the Music app if you look at the track properties?

**Comment by ejurgensen** [comment]
@hacketiwack do you think we will be able to debug this or should we close the issue?

**Comment by hacketiwack** [comment]
Let's close this issue for now. I didn't have time to check that.
