### ISSUE TITLE
Compiling under Arch fails complaining about not defined stdlib.h in misc_xml.c

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1772]
today I ran into the problem that the latest update of endeavorous deletes dependencies of owntone (ffmpeg, I think);
when trying to reproduce that at home, I chose to install ot from scratch - but the first compile fails:

`
misc_xml.c: In Funktion »xml_get_node«:
misc_xml.c:164:3: Fehler: Implizite Deklaration der Funktion »free« [-Wimplicit-function-declaration]
  164 |   free(path_cpy);
      |   ^~~~
misc_xml.c:31:1: Anmerkung: binden Sie »<stdlib.h>« ein oder stellen Sie eine Deklaration von »free« bereit
   30 | #include <libxml/tree.h>
  +++ |+#include <stdlib.h>
   31 |
misc_xml.c:164:3: Warnung: Unverträgliche implizite Deklaration der eingebauten Funktion »free« [-Wbuiltin-declaration-mismatch]
  164 |   free(path_cpy);
      |   ^~~~
misc_xml.c:164:3: Anmerkung: binden Sie »<stdlib.h>« ein oder stellen Sie eine Deklaration von »free« bereit
misc_xml.c: In Funktion »xml_new_node_textf«:
misc_xml.c:259:3: Warnung: Unverträgliche implizite Deklaration der eingebauten Funktion »free« [-Wbuiltin-declaration-mismatch]
  259 |   free(s);
      |   ^~~~
`

So after defining stdlib.h in misc_xml.c, compile ran without problems. (and i was not able to reproduce the other bug - will check for that tomorrow...)

**Comment by ejurgensen** [comment]
Thanks for reporting! Should be fixed now
