### ISSUE TITLE
No Chromecast Speaker at Bump version to 28.9

### ISSUE THREAD

**Issue by pisabird** [owntone/owntone-server#1776]
I compiled the [Bump version to 28.9](https://github.com/owntone/owntone-server/commit/fbc556ed6749e724e5a9bfe2968ef0a69c2de25f) for my Debian 12 and copied the owntone.conf from my old system 28.6.

Database and Owntone ist working, but I don't have my Chromecast Speaker. 

There is also no error in the logs.

**Comment by pisabird** [comment]
I used the same owntone.conf from my old system, where it worked. Where should I set --enable-chromecast?

**Comment by frankusb** [comment]
The setting is not in owntone.conf, it is set when you run configure during the build process.

**Comment by pisabird** [comment]
got it. thank you!
