### ISSUE TITLE
Password Authentication Issue with Apple Music After Setting Library Password

### ISSUE THREAD

**Issue by HJH0924** [owntone/owntone-server#1778]
Hello OwnTone Team,

I have encountered an issue with the OwnTone server where the password authentication is not functioning as expected, particularly with Apple Music.

**Environment:**
- Host OS: Ubuntu 23.10, Ubuntu22.04
- Client OS: macOS Sonoma 14.4.1

**Steps to Reproduce:**

1. I compiled the OwnTone server from source with the following steps:
   ```shell
   sudo apt-get update
   sudo apt-get install \
    build-essential git autotools-dev autoconf automake libtool gettext gawk \
    gperf bison flex libconfuse-dev libunistring-dev libsqlite3-dev \
    libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
    libasound2-dev libxml2-dev libgcrypt20-dev libavahi-client-dev zlib1g-dev \
    libevent-dev libplist-dev libsodium-dev libjson-c-dev libwebsockets-dev \
    libcurl4-openssl-dev libprotobuf-c-dev -y
   git clone https://github.com/owntone/owntone-server.git 
   cd owntone-server
   autoreconf -i
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user
   make
   sudo make install
   ```
   And then set a password in `/etc/owntone.conf` under the library section and started the OwnTone service:
   ```shell
   systemctl start owntone.service
   ```

2. iTunes and Apple Music clients were able to connect to my OwnTone server without entering a password, even though a password was set.

3. I also compiled the OwnTone server from a release package with the following steps:
   ```shell
   sudo apt-get update
   sudo apt-get install \
    build-essential git autotools-dev autoconf automake libtool gettext gawk \
    gperf bison flex libconfuse-dev libunistring-dev libsqlite3-dev \
    libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev \
    libasound2-dev libxml2-dev libgcrypt20-dev libavahi-client-dev zlib1g-dev \
    libevent-dev libplist-dev libsodium-dev libjson-c-dev libwebsockets-dev \
    libcurl4-openssl-dev libprotobuf-c-dev -y
   wget https://github.com/owntone/owntone-server/releases/download/28.9/owntone-28.9.tar.xz 
   tar -xvf owntone-28.9.tar.xz
   cd owntone-28.9
   autoreconf -i
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-install-user
   make
   sudo make install
   ```
   And then set a password in `/etc/owntone.conf` under the library section and started the OwnTone service.

**Results:**
- After setting a password, the iTunes client prompts for the password and connects normally.
- However, when using Apple Music, it prompts for a password but then displays an error message indicating the password is incorrect, even though the correct password was entered. Apple Music can connect without issues when no password is set.

**Expected Behavior:**
- Both iTunes and Apple Music clients should be able to connect to the OwnTone server after entering the correct password.

**Observed Behavior:**
- The Apple Music client fails to connect after entering the correct password, indicating a potential issue with password handling or authentication.

**Additional Information:**
- I have ensured that the password is set correctly in the configuration file.
- The issue does not occur with the iTunes client, suggesting it may be specific to Apple Music's implementation.

I would appreciate any guidance or assistance in resolving this issue. Thank you for your time and support.

Best regards!

**Comment by hacketiwack** [comment]
I will check that in a few days as I don't have access to my setup right now.

**Comment by hacketiwack** [comment]
I've just tested this and I can reproduce the problem.
In the logs, I get this information:

```log
[2024-07-18 19:34:52] [DEBUG]     daap: DAAP request '/login' in worker thread 280
[2024-07-18 19:34:52] [DEBUG]     daap: Checking authentication for library
[2024-07-18 19:34:52] [DEBUG]    httpd: No Authorization header
[2024-07-18 19:34:52] [  LOG]     daap: Unsuccessful library authorization attempt from '192.168.0.20'
[2024-07-18 19:34:57] [DEBUG]     daap: DAAP request '/login' in worker thread 280
[2024-07-18 19:34:57] [DEBUG]     daap: Checking authentication for library
[2024-07-18 19:34:57] [  LOG]    httpd: Bad password
[2024-07-18 19:34:57] [  LOG]     daap: Unsuccessful library authorization attempt from '192.168.0.20'
```

There are no other useful messages.

**Comment by ejurgensen** [comment]
Thanks for checking. Can you modify the "Bad password" log message to print authpwd? It is in the httpd_basic_auth function in httpd.c. It seems like authpwd doesn't match the expected value.

**Comment by hacketiwack** [comment]
I added a line as suggested to debug.
To test, my password was `password`.

In the method `httpd_basic_auth`, the `authpwd` and `passwd` are respectively `1):password` and `password`

The variable `authuser` contains the following value in my case:

`iTunes_Music/1.4.5 (Macintosh; OS X 14.5) AppleWebKit/618.2.12.11.6 build/36 (dt:1):password`

**Comment by ejurgensen** [comment]
Excellent, that reveals the problem, I think. For whatever reason, Apple Music is using "(dt:1)" as username, and that creates a problem since it contains a colon, which is also the delimiter between username and password. It also seems to be me that it is not in line with rfc 7617 which says the username must not include a colon.

@hacketiwack can you test again with the above small change (the strchr -> strrchr)? This isn't a very clean solution, since it creates a problem if the password has a colon, so it is mostly just to check that I am on the right track.

**Comment by hacketiwack** [comment]
I've just tested with the latest version, and it doesn't work.
I need to check what's in this string and I'll keep you posted.

**Comment by hacketiwack** [comment]
This indeed work. But as you say, now it is now possible to have a colon ":" in the password.

Would it be possible to search for the strings username and password with a regular expression, like this:

```regex
/(?<username>\(.*?\)|[^:]*):(?<password>.*)/g
```

With this you accept only a username with a colon when it is enclosed with parentheses.
What do you think?

**Comment by ejurgensen** [comment]
Yes, I think that would be a good solution. Thanks for the regex, I will try with that.
