### ISSUE TITLE
How to turn off library advertisement?

### ISSUE THREAD

**Issue by gearhead** [owntone/owntone-server#1781]
I am sharing my library via samba and would like to turn off the library advertisement via avahi on 3689.

I tried commenting out the full Library {} section of the config and the owntone service would not start. 

Could this be added as a setting in the config? If it has to be a patch to the source, could I ask for help developing that patch?

Gearhead

**Comment by gearhead** [comment]
@ejurgensen I was able to find the flags in 'man owntone' and get this silenced, thanks. I was not able to find them anywhere else in the docs, though. Not in the wiki on github, nor with 'owntone -h'.

**Comment by ejurgensen** [comment]
Yes they seem to be missing from 'owntone -h', I will get that fixed
