### ISSUE TITLE
Soundbridge Reboots After A Few Minutes Playing

### ISSUE THREAD

**Issue by minofso** [owntone/owntone-server#1783]
Hi, Since upgrading to to v28.9.129, when playing an album on the Roku Soundbridge, the Soundbridge will reboot near the end of the second track.
If I start playback from track 3, the Soundbridge will reboot during track 4. This is with any album playing and there is nothing in the log.
This happens with either Bookworm or Bullseye. The Soundbridge plays perfectly up to v28.8.128.
Before typing this issue, I tried v28.9.130 and the problem is still there.
I could just stay with v28.8.128 as there is probably no benefit upgrading if only using the Soundbridge (apart from the web interface if on a pc) but it would be good to solve this for when upgrading to the next Pi os release.
If you require any futher information then please let me know.
Thanks

**Comment by frankusb** [comment]
If you have an M1001, this is fixed [here](https://github.com/owntone/owntone-server/commit/5542492d332719fb77765e7b97d4dc3cc07de765). If you can build from source, that is an option. Or you could set to transcode to MP3 instead of WAV.

**Comment by ejurgensen** [comment]
Yes, the next RPi release I make will include the fix
