### ISSUE TITLE
Recent docker update issues

### ISSUE THREAD

**Issue by joeqaz** [owntone/owntone-server#1784]
After the most recent update to the docker image, I am no longer able to log into a bash shell. I receive the following error:

"OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown"

I am pulling from docker.io/owntone/owntone:latest

I am running Docker on TrueNAS Scale Dragonfish-24.04.2, and using Dockge for my compose file handling.

Thanks for any help you can provide

**Comment by hacketiwack** [comment]
I will have a look at it in a few days.
In the future, please open such work items [here](https://github.com/owntone/owntone-container)

**Comment by hacketiwack** [comment]
I actually re-read your message more thoroughly. You have to run the following command to enter into the container.

```shell
docker exec -it <container-name> sh
```

**Note:** Replace <container-name> with the name of your container instance.

There is no Bash interpreter within this container. The interpreter is [BusyBox](https://busybox.net), provided by Alpine Linux.

**Comment by joeqaz** [comment]
Thank you for the help!
