### ISSUE TITLE
iOS stream stops when screen locks

### ISSUE THREAD

**Issue by jshep321** [owntone/owntone-server#1785]
This is a universal problem that only occurs when listening via the "http stream" mechanism.  Sometimes this is useful when away from home and connected via VPN.

There are ways to get around this as noted in this thread below, but not sure these would work in this architecture?

https://stackoverflow.com/questions/9709891/prevent-ios-mobile-safari-from-going-idle-auto-locking-sleeping

**Comment by hacketiwack** [comment]
@jshep321 I unfortunately, can't reproduce the problem with my iOS device. The latest version of iOS is installed on it.
Can you clarify which version of iOS you have and the steps to reproduce the issue?

Moreover, I'm not sure to understand the relationship with the VPN.

**Comment by jshep321** [comment]
(VPN is how I access my home network, so ignore that unintentional red herring.)

@hacketiwack You can't reproduce this?  Hmmm.  You have something magical that no one in that stackoverflow post has. 

Just open the http stream of owntone in a (iOS safari) browser and either click the power button or wait until the iphone sleeps.  The stream stops.  iPhone 15 Pro, latest iOS (17.5.1).

My hope from looking at the first post in the stackoverflow link is that we can add something on the server side to keep the iphone from sleeping.

Photos attached.
![IMG_4311](https://github.com/user-attachments/assets/a76c2fad-0d5e-4a0c-8e89-440725eb3eee)
![IMG_4312](https://github.com/user-attachments/assets/ee979cc9-f541-4714-83f6-459e9287d534)

**Comment by jshep321** [comment]
@hacketiwack Ok I solved this.  It is a silly simple thing.  

Private browsing mode vs non-private.  Works fine in non-private mode.  

Perhaps a note in the guide to point this out will help others.  I am going to the stackoverflow site and providing a note now...

**Comment by hacketiwack** [comment]
Yep, we could mention that aspect in the documentation, indeed.

**Comment by hacketiwack** [comment]
A note has been added in the documentation [here](https://owntone.github.io/owntone-server/outputs/streaming/).
