### ISSUE TITLE
can't install on ArchLinux (build error)

### ISSUE THREAD

**Issue by wynteryyc** [owntone/owntone-server#1788]
I'm on the latest ArchLinux.  I have an AUR package that I used to install OwnTone.  The server fails to start

[zzzz@zzzzBox ~]$ systemctl status owntone
● owntone.service - DAAP/DACP (iTunes), RSP and MPD server, supports AirPlay and Remote
     Loaded: loaded (/etc/systemd/system/owntone.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/owntone.service.d
             └─override.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-07-31 10:12:39 MDT; 794ms ago
 Invocation: 1bc89fbb84bf4364bc529da6d201e310
       Docs: man:owntone(8)
    Process: 42784 ExecStart=/usr/bin/owntone -f (code=exited, status=127)
   Main PID: 42784 (code=exited, status=127)

When I try to build OwnTone, I get the following.

transcode.c: In function ‘avio_evbuffer_open’:
transcode.c:948:71: error: passing argument 6 of ‘avio_alloc_context’ from incompatible pointer type [-Wincompatible-pointer-types]
 948 |     s = avio_alloc_context(ae->buffer, AVIO_BUFFER_SIZE, 1, ae, NULL, avio_evbuffer_write, NULL);
|                                                                       ^~~~~~~~~~~~~~~~~~~
|                                                                       |
|                                                                       int (*)(void *, uint8_t *, int) {aka int (*)(void *, uns
igned char *, int)}
In file included from /usr/include/libavformat/avformat.h:319,
from transcode.c:29:
/usr/include/libavformat/avio.h:404:25: note: expected ‘int (*)(void *, const uint8_t *, int)’ {aka ‘int (*)(void *, const unsigned ch
ar *, int)’} but argument is of type ‘int (*)(void *, uint8_t *, int)’ {aka ‘int (*)(void *, unsigned char *, int)’}
 404 |                   int (*write_packet)(void *opaque, const uint8_t *buf, int buf_size),
|                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:944: transcode.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/dale/Applications/owntone-server/src/owntone-server-28.9/src'
make[2]: *** [Makefile:641: all] Error 2

**Comment by ejurgensen** [comment]
> The server fails to start

Run `sudo /usr/bin/owntone -f` to see why. It could be an invalid config file.

**Comment by wynteryyc** [comment]
/usr/bin/owntone: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory

ffmpeg 2:7.0.1-2

**Comment by ejurgensen** [comment]
> /usr/bin/owntone: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory

This means your AUR package isn't compatible with your system (maybe it's for another version).

> ffmpeg 2:7.0.1-2

Compability with ffmpeg 7 was fixed in April with commit a8342dc. So that it fix is not in a release yet. You will need to build from git master.

**Comment by wynteryyc** [comment]
ok thanks!
