### ISSUE TITLE
[m3u] songs whose file path begin with non-latin character don't load

### ISSUE THREAD

**Issue by tsuyo-o** [owntone/owntone-server#1795]
- steps to reproduce and/or logging of the error
put a m3u file(see bellow section for detail) in playlist directory
- version of owntone
28.9
- platform
Docker

For following m3u file,  only "05.アイデンティティ.flac" is visible on owntone webUI.
```
サカナクション-834.194_Disc1/5.新宝島.flac
サカナクション-834.194_Disc2/3.ユリイカ.flac
サカナクション-834.194_Disc2/9.セプテンバー_-札幌_version-.flac
Sakanaction-魚図鑑__浅瀬/05.アイデンティティ.flac
```
This is the screen shot of the webUI.
<img width="595" alt="Screenshot 2024-08-17 at 22 55 32" src="https://github.com/user-attachments/assets/8f5be618-8a3b-410b-afc0-26bfece307a0">

**Comment by ejurgensen** [comment]
Thanks for notifying, I think the issue should be fixed now.

**Comment by tsuyo-o** [comment]
It works now. Thank you.
<img width="595" alt="Screenshot 2024-08-21 at 15 19 02" src="https://github.com/user-attachments/assets/f7824a28-c3ad-42b6-848c-ce529f8dc94a">
(I had to copy the m3u file to confirm this, as library scan didn't work with playlist directory.)
