### ISSUE TITLE
Soundbridge title is blank if song title has "&" in it

### ISSUE THREAD

**Issue by frankusb** [owntone/owntone-server#1798]
I have a song with the title "Sweet & Low" and noticed that on the Roku Soundbridge the song name is blank. I used Kid3 to rename the song title to "Sweet And Low" and then the Soundbridge displays the title correctly. I changed it back to "Sweet & Low" and then the Soundbridge displayed a blank title again. In all cases, the song plays correctly.

The owntone version displays as 28.9 but I am building from source. The platform is Debian 12.

**Comment by ejurgensen** [comment]
Thanks for reporting. Looks I wasn't using the correct libxml2 function for the xml generation. I think it should be fixed now.

**Comment by frankusb** [comment]
That does fix it. Thanks!
