### ISSUE TITLE
Owntone crashes with no error message in log

### ISSUE THREAD

**Issue by GHTho** [owntone/owntone-server#1800]
FreeBSD 13.2-p6 on TrueNAS 13.1
Owntone 28.9_2
Name           : owntone
Version        : 28.9_2
Installed on   : Thu Aug 15 13:19:52 2024 CDT
Origin         : audio/owntone
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : audio
Licenses       : GPLv2
Maintainer     : dinoex@FreeBSD.org
WWW            : https://github.com/owntone/owntone-server
Comment        : DAAP (iTunes), MPD (Music Player Daemon) and RSP (Roku) media server
Options        :
        AIRPLAY2       : on
        ALSA           : on
        CHROMECAST     : on
        DOCS           : on
        ITUNES         : on
        MPD            : on
        NLS            : on
        PULSEAUDIO     : off
        WEBINTERFACE   : on
Shared Libs required:
        libwebsockets.so.19
        libuuid.so.1
        libunistring.so.5
        libsqlite3.so.0
        libsodium.so.26
        libprotobuf-c.so.1
        libplist-2.0.so.4
        libmxml.so.1
        libjson-c.so.5
        libintl.so.8/
        libinotify.so.0
        libgpg-error.so.0
        libgnutls.so.30
        libgcrypt.so.20
        libevent_pthreads-2.1.so.7
        libevent-2.1.so.7
        libcurl.so.4
        libconfuse.so.2
        libavutil.so.58
        libavformat.so.60
        libavfilter.so.9
        libavcodec.so.60
        libavahi-common.so.3
        libavahi-client.so.3
        libasound.so.2
Annotations    :
        FreeBSD_version: 1303001
        build_timestamp: 2024-08-14T09:26:40+0000
        built_by       : poudriere-git-3.4.1-30-g79e3edcd
        port_checkout_unclean: no
        port_git_hash  : 41f806cbbc2
        ports_top_checkout_unclean: no
        ports_top_git_hash: ff9b1b7bdb1
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 2.39MiB

stays running until I try to play a file or change/add an AirPlay speaker

owntone.log
[2024-08-28 18:07:06] [DEBUG]   player: Speaker enable: 'MBR' (id=171791497016898)
[2024-08-28 18:07:06] [DEBUG]   player: Registered callback to device_activate_cb with id 0 (device 0xf7f4a90, MBR)
[2024-08-28 18:07:06] [DEBUG]   player: Number of active callbacks: 1
[2024-08-28 18:07:06] [DEBUG]   player: Subscription request for quality 44100/16/2 (now 1 subscribers)

valgrind output:
root@Utils:/usr/local/etc # ==50968== Thread 16:
==50968== Invalid write of size 4
==50968==    at 0x2B226D: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2B046A: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2D1246: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2CC04A: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2C3334: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2BB178: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2F24CE: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x7988000: ??? (in /usr/local/lib/libevent-2.1.so.7.0.1)
==50968==    by 0x798415B: event_base_loop (in /usr/local/lib/libevent-2.1.so.7.0.1)
==50968==    by 0x2BD377: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x8305A79: ??? (in /lib/libthr.so.3)
==50968==  Address 0x16c is not stack'd, malloc'd or (recently) free'd
==50968== 
==50968== 
==50968== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==50968==  Access not within mapped region at address 0x16C
==50968==    at 0x2B226D: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2B046A: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2D1246: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2CC04A: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2C3334: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2BB178: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x2F24CE: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x7988000: ??? (in /usr/local/lib/libevent-2.1.so.7.0.1)
==50968==    by 0x798415B: event_base_loop (in /usr/local/lib/libevent-2.1.so.7.0.1)
==50968==    by 0x2BD377: ??? (in /usr/local/sbin/owntone)
==50968==    by 0x8305A79: ??? (in /lib/libthr.so.3)
==50968==  If you believe this happened as a result of a stack
==50968==  overflow in your program's main thread (unlikely but
==50968==  possible), you can try to increase the size of the
==50968==  main thread stack using the --main-stacksize= flag.
==50968==  The main thread stack size used in this run was 16777216.
==50968== 
==50968== HEAP SUMMARY:
==50968==     in use at exit: 21,018,165 bytes in 22,621 blocks
==50968==   total heap usage: 531,910 allocs, 509,289 frees, 812,201,853 bytes allocated
==50968== 
==50968== LEAK SUMMARY:
==50968==    definitely lost: 0 bytes in 0 blocks
==50968==    indirectly lost: 0 bytes in 0 blocks
==50968==      possibly lost: 2,141,088 bytes in 579 blocks
==50968==    still reachable: 18,705,791 bytes in 21,959 blocks
==50968==         suppressed: 171,286 bytes in 83 blocks
==50968== Reachable blocks (those to which a pointer was found) are not shown.
==50968== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==50968== 
==50968== For lists of detected and suppressed errors, rerun with: -s
==50968== ERROR SUMMARY: 16 errors from 14 contexts (suppressed: 0 from 0)
==50968== could not unlink /tmp/vgdb-pipe-from-vgdb-to-50968-by-root-on-Utils
==50968== could not unlink /tmp/vgdb-pipe-to-vgdb-from-50968-by-root-on-Utils
==50968== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-50968-by-root-on-Utils

**Comment by ejurgensen** [comment]
Thanks for trying with Valgrind, but as you can see your owntone binary doesn't have debug symbols, so it doesn't give much info. Would it be possible for you to complile yourself and try with that? Otherwise please submit the bug to FreeBSD packages (I assume they have some sort of bug reporting site?).

**Comment by ejurgensen** [comment]
Closing, no feedback
