### ISSUE TITLE
May I suggest elaborating homebrew install

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/owntone-server#1805]
Someone should please guide users through the process of Installing on homebrew.
Even after lots of googling and creating a whole bunch of access tokens, I am not able to run the workflow. 
I am sure this is very smart - if you know how to do it. But I (more an experienced user than a developer) am struggling using this tool - and just find now clue...

**Comment by ejurgensen** [comment]
Hi @LordMyschkin, I'm not sure what you mean by "installing on homebrew"? Do you mean installing on Mac OS using Homebrew (the package manager)?

If so, it's more simple than what you might have been trying to do. You don't need to run the workflow yourself, you just read it as a recipe. Or consider each "run" as commands for a script, so the install process becomes this (note the below is non-root, so everything is installed in $HOME):

```
brew install automake autoconf libtool pkg-config
brew install gperf bison flex
sudo ln -s "$(brew --prefix)/opt/bison/bin/bison" /usr/local/bin/bison
sudo ln -s "$(brew --prefix)/opt/flex/bin/flex" /usr/local/bin/flex
git clone https://github.com/libinotify-kqueue/libinotify-kqueue
cd libinotify-kqueue
autoreconf -fvi
./configure
make
sudo make install
cd ..
brew install libunistring confuse libplist libwebsockets libevent libgcrypt json-c protobuf-c libsodium gnutls pulseaudio openssl ffmpeg sqlite
export CFLAGS="-I$(brew --prefix)/include -I$(brew --prefix sqlite)/include"
export LDFLAGS="-L$(brew --prefix)/lib -L$(brew --prefix sqlite)/lib"
autoreconf -fi
./configure --prefix=$HOME/owntone_data/usr --sysconfdir=$HOME/owntone_data/etc --localstatedir=$HOME/owntone_data/var --enable-chromecast --with-pulseaudio
make
make install
```

**Comment by LordMyschkin** [comment]
that indeed is easy. 
since in the documentation, it says "This workflow file used for building OwnTone via Github actions includes all the steps that you need to execute: [.github/workflows/macos.yml](https://github.com/owntone/owntone-server/blob/master/.github/workflows/macos.yml)" - so i was thinking of this workflow as some kind of automatic install script with special github magic :-)
Obviously, there was just a knot in my very own thinking - I am glad noone knows how may hours I spent trying to install it to my MacBook by running this workflow without any change happening on my side....
Thanks for the quick support!

**Comment by ejurgensen** [comment]
Glad to hear it worked. Let me know if you have a suggestion for a wording that is more clear.

**Comment by LordMyschkin** [comment]
Although I hate some extra steps.
my brand new installation of sonoma wanted mit to instal libavcodecs and some other stuff, so I installed ffmpeg via bew first.
And - just in case someone else struggles here - make could not find m4, only the installation of the command line xtools from https://developer.apple.com/download/all/?q=command%20line%20tools solved that (neither installing it autmatically nor by homebrew).

**Comment by LordMyschkin** [comment]
I wrote a Wiki Page - basically repeating the steps from above and explaining why it failed and where I found problems.
https://github.com/owntone/owntone-server/wiki/Installing-on-MacOS-(14.7)
