### ISSUE TITLE
Artist album list Sort by "Release date" does nothing

### ISSUE THREAD

**Issue by obriencj** [owntone/owntone-server#1808]
Please try to provide the following:

- steps to reproduce and/or logging of the error
  - select the music icon at top left of page
  - click "Artists"
  - select an artist with multiple albums
  - albums are sorted by name
  - click the tiny arrow at top of page to display the filter and sort options
  - change Sort to "Release date"
  - nothing happens
  - the Filter heading is also entirely blank, no input box or anything else
  - can see the Year value on all of the albums, which does not correspond to the order they are displayed
- version of owntone
  -  28.9
- platform
  - owntone running via container, docker.io/owntone/owntone:latest
  - accessed via Firefox ESR 115 on linux, windows, and macos with same results
  - also gave Edge a try, same results

The media is all copied over from my iTunes library which I'm migrating away from, so it's m4a files. I've enabled the `itunes_overrides = true` but that doesn't appear to have changed anything.

It seems like Owntone is able to interpret what exiftool is calling the "Content Create Date" in order to display as the "Year" field in album and song properties, but it isn't sorting by that value.

**Comment by hacketiwack** [comment]
@obriencj This has been corrected a long time ago in the master branch.

@ejurgensen when do you plan to release a new version?

**Comment by ejurgensen** [comment]
@hacketiwack (and @dwong33), yes, I will make a new version soon. I'm a bit unsure if I should include my coming mpd refactor PR in it or not. I also have to test that 28.10 will work as version number (will package managers recognize it as > 28.9).

**Comment by hacketiwack** [comment]
Package managers would normally consider 28.10 newer than 28.9. But I'm struggling to find good information to support my saying.

**Comment by hacketiwack** [comment]
I will check that more in details.

**Comment by obriencj** [comment]
okay, sorry for the noise on that. Please let me know if you need screen-shots or exiftool dumps on anything.

**Comment by hacketiwack** [comment]
No worries at all. Everyone does their best. 
I would be interested in one of the audio file you have. 
Question is mainly, what software do you use to tag?
I’m using MusicBrainz Picard.

**Comment by obriencj** [comment]
I'm migrating away from iTunes into Owntone, so these are m4a files and they've got the tags as provided by apple originally (either as purchased or as ripped). I can see via exiftool a values named "Content Create Date" which seems to be the only value correlating to the "Year" value that Owntone displays.

**Comment by hacketiwack** [comment]
@obriencj, can you please run this command on some of your files?

```shell
ffprobe -hide_banner <filename>
```

It should give you something like this:

```shell
Input #0, mp3, from '9aa46052-c0ee-3b42-a0c6-a40e5d06e9c0.mp3':
  Metadata:
    title           : Should I Stay or Should I Go
    artist          : The Clash
    track           : 19/20
    album           : The Essential Clash
    disc            : 2/2
    genre           : Rock
    TMED            : CD
    MusicBrainz Release Group Id: 41b94ac5-cddc-4f26-80f8-6fe445bbf0cf
    TORY            : 2003
    publisher       : Epic
    MusicBrainz Release Track Id: 9aa46052-c0ee-3b42-a0c6-a40e5d06e9c0
    album_artist    : The Clash
    TSO2            : Clash, The
    artist-sort     : Clash, The
    SCRIPT          : Latn
    ASIN            : B00008H2K0
    ARTISTS         : The Clash
    originalyear    : 2003
    BARCODE         : 696998905627
    CATALOGNUMBER   : E2K 89056
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: US
    TSRC            : GBARL1200670/GBBBN8200005/GBBBN9902467
    MusicBrainz Album Type: album/compilation
    Acoustid Id     : 2330cb3d-dd1a-4790-93ff-2144ab675ab8
    MusicBrainz Album Id: 7adf8b40-8622-43ba-8eb2-c5fec39fb263
    MusicBrainz Artist Id: 8f92558c-2baa-4758-8c38-615519e9deda
    MusicBrainz Album Artist Id: 8f92558c-2baa-4758-8c38-615519e9deda
    date            : 2003-03-11
  Duration: 00:03:08.47, start: 0.000000, bitrate: 195 kb/s
  Stream #0:0: Audio: mp3 (mp3float), 44100 Hz, stereo, fltp, 192 kb/s
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
```

**Comment by hacketiwack** [comment]
The `date` metadata is what you are looking for.

Example:

```shell
  date            : 2003-03-11
```

If this one is missing, you will not be able to sort by release date.

**Comment by obriencj** [comment]
Checking in, I did indeed see a date value in the relevant files, eg:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Music/Caravan Palace/Caravan Palace/01 Dragons.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2026-06-12T06:21:01.000000Z
    iTunSMPB        :  00000000 00000840 00000364 0000000000A5345C 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    iTunNORM        :  00001AB4 00001576 00007C31 0000644E 0000741A 0000C55F 00007E87 00007E87 00009FA3 00023BCB
    title           : Dragons
    artist          : Caravan Palace
    album_artist    : Caravan Palace
    composer        : Vial, Payen, Delaporte & Tilleke
    album           : Caravan Palace
    genre           : Electronic
    track           : 1/15
    disc            : 1/1
    compilation     : 0
    gapless_playback: 1
    date            : 2008-10-20T12:00:00Z
    media_type      : 1
    purchase_date   : 2017-08-15 16:11:42
    sort_name       : Dragons
    sort_album      : Caravan Palace
    sort_artist     : Caravan Palace
  Duration: 00:04:05.57, start: 0.047889, bitrate: 287 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 267 kb/s (default)
    Metadata:
      creation_time   : 2026-06-12T06:21:01.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x0]: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 599x600 [SAR 300:300 DAR 599:600], 90k tbr, 90k tbn (attached pic)
```

and saw a "Year" value in the info, but no sorting.

Then I did a full re-scan, and suddenly new values appeared and sorting worked! So with the new update it simply was still using the old cached data, which apparently didn't include those date values.

Now I can indeed see proper date sorting (in addition to the release date actually being visible in the album listing without going into album details).

About the only thing that's still odd here is that if I have the list of albums sorted by Release Date, and then hit `...` at the top and select `Play` it'll still queue the albums in title order.
