### ISSUE TITLE
Enable/Disable output not working correct vi MPD client

### ISSUE THREAD

**Issue by oliver-koch** [owntone/owntone-server#1814]
### Enable/Disable output not working correct vi MPD client.

With owntone 28.10 the numbering schema of outputs has changed. When i try to enable/disable those, it will only work for output id 0. Other output ids cannot be controlled anymore.

i use the follwing setup:
 - all outouts are of type airplay_1
 - fhem mpd [plugin ](https://wiki.fhem.de/wiki/MPD)
 - Android M.A.L.P. app

Owntone log (level debug) shows only the following:
```
[2024-09-25 10:29:27] [DEBUG]      mpd: MPD message: disableoutput 2
[2024-09-25 10:29:27] [DEBUG]      mpd: MPD message: close
```

Until 29.9 everything worked fine.

**Info:** via Apple Remote App, it works with 28.10, but i think it conrolles the outputs directly via airplay.

**Comment by ejurgensen** [comment]
I can reproduce this. @grobian it seems to be regression from PR #1779, specifically the change of the condition in output_get_cb().

I will make a fix.

**Comment by ejurgensen** [comment]
Should be fixed now. I hope you can verify that it works now, but you will need to build owntone from the master branch. I can also make a .deb for you, if you want.

**Comment by oliver-koch** [comment]
A .deb would be nice. I run it in a docker Container. Hope i can update i directly inside the Container. 
Otherwise i will set up a testenv for retest. 
Thanks you very much in advance!

**Comment by hacketiwack** [comment]
@oliver-koch depends on which container image you are using. But most of the container images are based on Alpine Linux.
You can otherwise use the staging tag of this [container image](https://hub.docker.com/r/owntone/owntone).
It is based on the latest master branch of OwnTone.

**Comment by oliver-koch** [comment]
Sounds good. I will try tomorrow. 

I use currently this image: linuxserver/daapd. 
Didnt Check that there is an official Container too.
Good chance to change it. 
Thanks !

**Comment by oliver-koch** [comment]
i tried to get the container running, but unfortunately without success. 
i tried the label staging and latest. in both cases webif is not reachable from browser. 
ports are open and owntone seems to run (see attached log):
```
/var/cache/owntone # netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:44839        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:6600            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3688            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3689            0.0.0.0:*               LISTEN      -
udp        0      0 0.0.0.0:47170           0.0.0.0:*                           -
udp        0      0 127.0.0.11:34866        0.0.0.0:*                           -
udp        0      0 0.0.0.0:36005           0.0.0.0:*                           -
udp        0      0 0.0.0.0:54012           0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
udp        0      0 0.0.0.0:38247           0.0.0.0:*                           -
udp        0      0 0.0.0.0:42027           0.0.0.0:*                           -
udp        0      0 :::52349                :::*                                -
udp        0      0 :::5353                 :::*                                -
```
i need to get deeper in. i will come back soon.

maybe someone can see the problem directly
[owntone.log](https://github.com/user-attachments/files/17144518/owntone.log)
[owntone.conf.txt](https://github.com/user-attachments/files/17144579/owntone.conf.txt)

**Comment by oliver-koch** [comment]
Retest OK! Works for me.
Thanky you very much for the quick solution!
I love your proejct. :)

**Comment by ejurgensen** [comment]
Excellent, thanks!
