### ISSUE TITLE
[Enhancement] AudiobookShelf

### ISSUE THREAD

**Issue by Thomas-O** [owntone/owntone-server#1815]
Do you know what would be really cool?

If it was possible to integrate [AudioBookShelf](https://github.com/advplyr/audiobookshelf) in to Owntone.

Either connecting to an AudioBookShelf server or embedded within Owntone. Or Maybe both.

**Comment by ejurgensen** [comment]
Can you elaborate on what sort of integration you are thinking of? And how would it work for seen from a user perspective?

**Comment by Thomas-O** [comment]
To be perfectly honest, I really haven’t given it much thought. It’s largely pipe-dream thinking.

As much as I like and use AudioBookShelf, I just wish there was some way to play the files without sitting in front of a PC or depending upon clunky bluetooth. Something with dlna/upnp and the proprietary stuff like chromecast and the like.

One of my idle daydreams is the hope that someone will create an audio streamer operating system / server designed specifically for active (networked) speakers. Which I am convinced will be the dominant hi-fi choice for most people in the coming years. From high-end stuff like Bang and Olufsen and KEF, to Lithe ceiling speakers, to cheap and cheerful boxes from mass-market manufacturers.

This audio OS / streamer would be somewhat like PiCore Player + Squeezebox server. Though far more user-friendly and 21st century.

It would have plugins for every audio and music service. It could also host, organise and serve your own audio collection. And it would have optional integrations with every home automation system from Google to Home Assistant.

Everything in one place. No need to flit from one mobile app to another. Nor to use a speaker manufacturer’s often half-baked and spottily maintained mobile app. One server / client to rule them all.

The development would be open-source and created in partnership with and funded by a consortium of hi-fi companies. From the big bucks outfits to boutique brands. They can concentrate on what they do best - making the hardware – while the server developers would create a universal network audio server & client.

3rd parties would be actively encouraged to create and sell plug-and-play boxes (with and without storage) using the operating system. Or to add the server software to NAS, routers or whatever. Or create 3rd party clients of all types: mobile, desktop, wall mounted.

I mean, it’s not much to ask, is it?

**Comment by ejurgensen** [comment]
Sorry guys, but you have to be a bit more specific
