### ISSUE TITLE
do you still use rigelian as owntone controller?

### ISSUE THREAD

**Issue by Yumega** [owntone/owntone-server#1820]
ios rigelian was good, from2024 the new versions have a lot of problems for owntone, so I go back using old version.

if someone can develop an ios APP better than rigelian and charge onetime money, I will buy.

Now the old version rigelian is my only choice🙁

**Comment by ejurgensen** [comment]
Of the iOS mpd apps I have tried with OwnTone, I liked MPD Pilot the most.

I only tried the free version of Rigelian, and I noticed that on start-up it makes a requests for all changed albums during the last 3 months. For a small library that's no problem, but for the larger library that I actually use, that yields a 400 line request. That seemed to break something. I think its bad practice to make that large of a request at startup. I doubt the app actually needed details about all those 400 albums.

Note that this is tested with the master version of OwnTone. The last release probably has issues with all the apps.
