### ISSUE TITLE
Owntone not starting after upgrade from Fedora 40 to 41

### ISSUE THREAD

**Issue by queequed** [owntone/owntone-server#1825]
hi, 

after upgrading to fedora 41, my owntone service does not start anymore, libavformat.so.60 is missing (only libavformat.so.61 is installed after upgrade), not sure if I should downgrade and how or wait for owntone update ? 

regards
````
 23 11:17:52 nuc owntone[68267]: /usr/sbin/owntone: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file>

Nov 23 11:17:52 nuc systemd[1]: owntone.service: Main process exited, code=exited, status=127/n/a
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit owntone.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 127.
Nov 23 11:17:52 nuc systemd[1]: owntone.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit owntone.service has entered the 'failed' state with result 'exit-code'.
````

**Comment by ejurgensen** [comment]
How did you install owntone?

**Comment by queequed** [comment]
I followed instructions for fedora Quick version for  [Fedora](https://owntone.github.io/owntone-server/building/#quick-version-for-fedora)

After upgrading to fedora 41,as the service was not starting anymore, I tried to rebuild owntone with the same procedure but I get an error about libavformat too

````
checking for libavformat libavcodec libavutil libavfilter... no
configure: error: Package requirements (libavformat libavcodec libavutil libavfilter) were not met:

Package 'libavfilter' not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBAV_CFLAGS
and LIBAV_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
````

**Comment by ejurgensen** [comment]
Yes, you probably need to recompile since your old version linked with some shared library files that aren't there anymore (e.g. libavformat.so.60).

libavfilter should be included when you install ffmpeg-devel, so I'm not sure why it's not being found. What does `pkg-config --path libavfilter` return?

**Comment by queequed** [comment]
it returns... nothing
:~$ sudo pkg-config --path libavfilter
and for libaformat
:~$ sudo pkg-config --path libavformat
/usr/lib64/pkgconfig/libavformat.pc

**Comment by ejurgensen** [comment]
Strange. If you list the ffmpeg-devel files with `dnf repoquery -l ffmpeg-devel` do you not see libavfilter files?

**Comment by ejurgensen** [comment]
I just tried installing on a fresh Fedora 41 vm, and it worked fine. No problem finding libavfilter:

```
ej@fedora:~$ pkg-config --path libavfilter
/usr/lib64/pkgconfig/libavfilter.pc
```

I don't know why it's not being found on your computer, I can only suggest reinstalling ffmpeg-devel. Since I don't think there is an issue with OwnTone here I will close the issue.
