### ISSUE TITLE
ReplayGain

### ISSUE THREAD

**Issue by drcryogen** [owntone/owntone-server#290]
Just a remark since it seems to be unstated in the documentation except for issue https://github.com/ejurgensen/forked-daapd/issues/216 .

ReplayGain _does_ indeed work with forked-daapd. I applied the replaygain tags to the music library with the scripts from the rgain package and forked-daapd honored them without any trouble. The tags made a huge difference in playback experience.

**Comment by drcryogen** [comment]
I used the replaygain package from the repositories. The replaygain and collectiongain commands do the heavy lifting. If you're using the replaygain script from the repositories beware that it seems to fail for ALAC encoded files (aka Apple lossless).

FYI, forked-daapd doesn't like the files being replaygain'ed inside the library. I just process new files outside and move them into place when they're finished being processed. One could also shut down forked-daapd while doing the initial run with collectiongain. 

---------------------------
Message created using 100% recycled electrons

**Comment by cdlenfert** [comment]
Thank you for the response. I did `sudo apt-get install replaygain` on my Stretch Pi Zero and it says the package is not available. I've tried Google but can't find anything that makes it clear if this is available in Raspbian, and how to get it set up even if I do get it installed.

**Comment by drcryogen** [comment]
Try the python-rgain package. That installs the replaygain and collectiongain scripts.

**Comment by cdlenfert** [comment]
Ok, got the package installed and am able to run `replaygain` and `collectiongain`. I have my library split into artist/album folders. Should `collectiongain` work on the entire library if I run it on the outer /music directory? Will this only do leveling on an album level, or track level? For example if I shuffle my entire library (I often do) will audio between tracks be leveled? Or do I need to dump all songs into a single directory and run `replaygain`. Thanks for your help and any clarification

**Comment by kkfh** [comment]
@drcryogen - could you clarify which version of forked-daapd you got replaygain to work?  In particular, did you have to apply the patch from #216? Or did it work right off of master?
