### ISSUE TITLE
It would be nice to support Spotify using a free OSS client

### ISSUE THREAD

**Issue by rbalint** [owntone/owntone-server#34]
There is despotify which I have not tried myself and may or may not work:
http://despotify.sourceforge.net/

Using a GPL-compatible client would allow packaging Forked-daapd in Debian with Spotify support.

**Comment by ejurgensen** [comment]
There's a special satisfaction in fixing ancient issues, so even though you probably aren't interested any more, I'm pleased to announce that commit a1f9e10f9cf0b74f9194bfc82588a999063528c0 finally provides fully open source Spotify integration - no more libspotify required.
