### ISSUE TITLE
Support for OpenELEC

### ISSUE THREAD

**Issue by jkiddo** [owntone/owntone-server#35]
Could forked-daapd be disted for the OpenElec platform? It dpes not seem too hard and I would gladly help out where I could.

See more at http://wiki.openelec.tv/index.php/How_to_make_OpenELEC_addon_-_on_MuMuDVB_sample

**Comment by jkiddo** [comment]
Pretty pretty please - I hope someone would have a look at http://kodi.wiki/view/Add-on_development - I would just love to see this happen.

**Comment by jkiddo** [comment]
See http://openelec.tv/forum/90-miscellaneous/76276-daap-server-on-openelec-itunes-airplay-daapd#140969

**Comment by TomAlperin** [comment]
Don't hold your breath on this. The whole concept of OpenELEC is it's simplicity. When it XBMC first started running on the Raspberry Pi, there was a definite performance advantage. Now there's no noticeable difference between even just installing Kodi directly into Raspbian. If you really want that functionality, do what I did and switch to Raspbian with Kodi installed in it and you can add whatever else you want. Make it a print server and a web server as well. If you can get through the more complex install, the user experience is identical. I have my local music directory set to Kodi's music playlist folder so when I create a playlist (something forked-daapd can't do) it just shows up in forked-daapd.

**Comment by jkiddo** [comment]
That is of course a way to do it - I've considered it multiple times and you might got a point

**Comment by ejurgensen** [comment]
Thanks for the notification, let's see what kind of reaction it gets. In general I don't want to build packages for platforms I don't use myself, but if I can help someone else doing this it would be my pleasure.

**Comment by hacketiwack** [comment]
As OpenELEC does not exist anymore, shouldn't we close this ticket?

**Comment by ejurgensen** [comment]
Yes, let's. Thanks for checking into these old issues.

**Comment by jkiddo** [comment]
Good thing I didnt held my breath on this one 😬
