### ISSUE TITLE
Question: Successful compilation under FreeNAS 9.2?

### ISSUE THREAD

**Issue by janw** [owntone/owntone-server#56]
Hi! 

I've been trying to figure out, how to compile forked-daapd on FreeNAS 9.2 for a few days now, without any success. Are there any reports or even a tiny tutorial on how to do that? In the README it says, that compilation on FreeBSD is possible. So it can't be to hard to do it on FreeNAS as well, right?

Best regards!

**Comment by Tom14-** [comment]
Hi @Janwillhaus,

I'm trying to install on FreeNAS 9.3, would you mind sharing your build configuration? Right now I'm using:

    CFLAGS="$CFLAGS -I/usr/local/include -L/usr/local/lib -I$WORKDIR/avl-0.3.5 -L$WORKDIR/avl-0.3.5 -I$WORKDIR/libantlr3c-3.4/include -I$WORKDIR/libantlr3c-3.4 -L$WORKDIR/libantlr3c-3.4/.libs" ZLIB_LIBS="-L/lib -lz" ZLIB_LIBS="-L/lib -lz" ZLIB_CFLAGS="-I/usr/include" ./configure --localstatedir=/var --prefix=/usr --sysconfdir=/etc

This compiles but gmake fails:

```
RSPParser.c: In function 'strop':
RSPParser.c:1716: error: 'FOLLOW_set_in_strop184' undeclared (first use in this function)
RSPParser.c:1716: error: (Each undeclared identifier is reported only once
RSPParser.c:1716: error: for each function it appears in.)
RSPParser.c: In function 'intop':
RSPParser.c:2124: error: 'FOLLOW_set_in_intop261' undeclared (first use in this function)
RSPParser.c: In function 'dateop':
RSPParser.c:2359: error: 'FOLLOW_set_in_dateop315' undeclared (first use in this function)
RSPParser.c: In function 'dateref':
RSPParser.c:2680: error: 'FOLLOW_set_in_dateref362' undeclared (first use in this function)
RSPParser.c: In function 'dateintval':
RSPParser.c:2765: error: 'FOLLOW_set_in_dateintval378' undeclared (first use in this function)
Makefile:1269: recipe for target 'forked_daapd-RSPParser.o' failed
gmake[3]: *** [forked_daapd-RSPParser.o] Error 1
gmake[3]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd/src'
Makefile:505: recipe for target 'all' failed
gmake[2]: *** [all] Error 2
gmake[2]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd/src'
Makefile:532: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/usr/local/src/forked-daapd/forked-daapd'
Makefile:399: recipe for target 'all' failed
gmake: *** [all] Error 2
```

Thanks,

Tom

**Comment by ejurgensen** [comment]
See also issue #92 (looks antlr related)
