### ISSUE TITLE
[bug] antlr / smart query api server lockup

### ISSUE THREAD

**Issue by whatdoineed2do** [owntone/owntone-server#570]
Using `curl "http://localhost:3689/api/search?type=album&expression=genre+is+\"Pop\"" | jq` can pull back values.

However, using single quotes or no quotes around `Pop` in above causes the server to lockup.

Will try look at this as I look at the search-genre functionality.

**Comment by ejurgensen** [comment]
@chme can you look at this?

**Comment by whatdoineed2do** [comment]
It looks like the antlr is expecting In `jasonapi_reply_search()`
```
  memset(&smartpl_expression, 0, sizeof(struct smartpl));

  if (param_expression)
    {
      expression = safe_asprintf("\"query\" { %s }", param_expression);
      ret = smartpl_query_parse_string(&smartpl_expression, expression);
      free(expression);

      if (ret < 0)
	return HTTP_BADREQUEST;
    }
```

* [GOOD] hitting endpoint with `api/search?type=albums&media_type=music&expression=genre+is+%22Pop%22`, `expression` is `"query" { genre is "Pop" }`
* [BAD] hitting endpoint (as it would arrive from webui with uriencoded/escaped string) with `api/search?type=albums&media_type=music&expression=genre%2Bis%2B%22Pop%22`, `expression` is `"query" { genre+is+"Pop" }`

It then gets stuck in `smartpl_query_parse_string() -> smartpl_query.c:parse_input() -> psr->playlist(psr)`

**Comment by chme** [comment]
Somehow antlr3 does not always recognize invalid input strings. For your example `"query" { genre+is+"Pop" }` it hangs in `SMARTPLParser.c` directly at reading the first token (`retval.start = LT(1)`). 
Probably the grammar in SMARTPL.g is not entirely correct and results in the parser not being able to recognize all cases of invalid input. This error is also triggered for smart playlist files and is not specific to the JSON API. 
This is really hard to fix ... I'll try to find a solution, but this might take a while ...  

If you pass a valid query expression like `"query" { genre is "Pop" }` (the url encoded version is `expression=genre+is+%22Pop%22` or `expression=genre%20is%20%22Pop%22`) , you will get the correct result.

**Comment by ejurgensen** [comment]
Fixed with switch to bison/flex
