### ISSUE TITLE
web player does not make good use of screen space

### ISSUE THREAD

**Issue by snizzleorg** [owntone/owntone-server#643]
I think the web interface for the player is a great addition to an already awesome player. I have however some minor issues or suggestions. The web interface is fine when used on a portrait mode device. However in landscape mode it does not make good use of the screen real-estate.

For example I have a rpi working as a controller (and server). And it looks like this:

![img_3101](https://user-images.githubusercontent.com/1573482/50394632-1d842d80-075f-11e9-9de0-77d530e35e2a.jpg)

I think the title and play buttons could be closer to each other. Also the control buttons could be way bigger. 

The cherry on the top would be a dark theme...

**Comment by ejurgensen** [comment]
I suppose this can be closed
