### ISSUE TITLE
Support for Google Music

### ISSUE THREAD

**Issue by jkiddo** [owntone/owntone-server#81]
I've written a DAAP/DMAP Server myself in Java (its called Jolivia) and I've builtin support for Google Music using another library that I've written in Java called gmusic (https://github.com/jkiddo/gmusic.api). I would love to see the same feature in forked-daapd as I find the feature quite useful.

**Comment by slucky31** [comment]
I agree ! It would be great !

**Comment by ejurgensen** [comment]
Thank you for these suggestions, they are good motifivation to do this. I don't know when/if I can do it, but if anyone else wants to work on it please let me know.

**Comment by jkiddo** [comment]
Regarding library dependencies all it needs is a http client and a json parser. I can provide guidance but I'm pretty rusty in C/C++

**Comment by theroboticsheep** [comment]
Any updates on this? I found working Google Music plugins for [mopidy](https://github.com/mopidy/mopidy-gmusic) and [kodi](https://github.com/vially/googlemusic-xbmc), both of which use the [gmusicapi](https://github.com/simon-weber/gmusicapi) project.  I also found a [gmusic-daap](https://github.com/dpogue/gmusic-daap) project, but they are all in python, and your project has by far the best support for airplay speakers on Raspberry Pi.

**Comment by ejurgensen** [comment]
No updates on this, but your request definitely pushes it up my todo-list. Like you and @jkidde pointed out, all the building blocks are there, so it shouldn't be too much work putting it together. Can't give you any promises, though.

**Comment by theroboticsheep** [comment]
Creating a C API port looks like a lot of work and the python api seems mature and well maintained, do you think calling into the python library from C as described here [here](https://docs.python.org/2/extending/embedding.html) would work?  Also, is the functionality going to largely be a clone of your spotify plugin?

**Comment by ejurgensen** [comment]
Depends what you mean by clone? Yes, it would follow some of the same principles, but the actual code would probably be quite different. Libspotify and the gmusic api are rather different. Embedding gmusicapi is an interesting idea. How would that work when distributing forked-daapd? Like e.g. for Debian?

**Comment by theroboticsheep** [comment]
I'm actually not familiar with the practice, it was just an idea.  I guess there are two options, either package gmusicapi ourselves as a [deb](https://wiki.debian.org/Python/LibraryStyleGuide?action=show&redirect=Python%2FPackaging) and set it as a dependency, or require "[pip install gmusicapi](http://unofficial-google-music-api.readthedocs.io/en/latest/usage.html)" for Google Music support in the install instructions.  Then just call into it from gmusic.c.

**Comment by theroboticsheep** [comment]
https://www.bountysource.com/issues/7446199-support-for-google-music

I think this feature would be very desirable to a lot of people so I just put a $50 bounty on it.  I know that's not a meaningful amount of money to a developer, but it's a start.  If anyone else comes here looking for an elegant solution for streaming your Google Play Music through a Raspberry Pi to Airplay Speakers, I urge you to go to Bountysource and throw down a couple bucks to help incentivize this solution.

To any developer looking to take on this challenge, I'm happy to help with code reviews and testing.

**Comment by ejurgensen** [comment]
Thanks for pushing the issue, that’s really awesome. I think your suggestion about embedding gmusicapi will be the best way to do it, especially if I will be the one doing it. I don’t use Google Music myself, so maintenance would be a problem if I ported it to C. I also think you are right that for distributions it will be ok to ask the user to “pip install” to get this support. That is the same as libspotify.

**Comment by hacketiwack** [comment]
Dear All, I think we can close this issue as Google Music is no longer with us.
